### PR TITLE
respawn - Replace unique acre radios with their baseclass

### LINKED ISSUE #4441: conflict between ace respawn with same gear and unique item mods
conflict between ace respawn with same gear and unique item mods

Here so I don't forget.

Basic summary;
- when a mod usch as acre2 replies on unique items and ace respawn with same gear is enabled, it could potentialy result in a duplicate item (when items are unique due to their classname). We should look at supporting unique items by adding their base class / parent instead of the unique id item.

### PR DESCRIPTION
**Pull request by PabstMirror**
Fix #4441

- Should fix ACRE error
```
ACRE WARNING: Id object relation created independently of unique ID creation process (acre_prc343_id_2)
```
- Also fix `ace_killedByFriendly` global event inside global event

### CODE REVIEW

**Comment by jonpas** [comment]
TFAR does it on the same principle, but not sure if it handles those things itself.

**Comment by commy2** [comment]
INFO_2 needs new CBA

**Comment by 654wak654** [comment]
For TFAR radio classes go like `{classname}_{number}`.

https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/master/arma3/%40task_force_radio/addons/task_force_radio_items/radio_ids.hpp

**Comment by PabstMirror** [comment]
Need to test with TFAR but it looks like their configs are similar.

**Comment by commy2** [comment]
Wouldn't this mean that you have to readjust your radio every time you respawn?

**Comment by jonpas** [comment]
@commy2 Yes, but it is the only way to handle it, as the old radio is already registered and then you get 2 of them, because cleanup of old IDs doesn't kick in that fast.

**Comment by commy2** [comment]
Some people might feel like this is a regression though. Just saying.

**Comment by jonpas** [comment]
But it's not, both TFAR and ACRE error out on duplicate IDs as far as I know (not 100% on TFAR) and may introduce undefined behaviour.

**Comment by bux578** [comment]
Make it an option with default off. So that it behaves like now. If people want/need that, they could opt-in.

**Comment by CorruptedHeart** [comment]
Just chiming in from the TFAR side, I seem to recall adding functionality that will handle duplicate IDs and copy the settings from the old radio to the new radio or something similar. Unfortunately I'm at work and can't search the repo to find exactly where that is happening on the TFAR side.

**Comment by commy2** [comment]
Something like this ^ is needed.

**Comment by dedmen** [comment]
I think this is the code @CorruptedHeart meant https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/1.0/addons/core/functions/fnc_radioReplaceProcess.sqf

also on respawn we are calling
https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/1.0/addons/core/functions/fnc_requestRadios.sqf
With a call in line 50 passing its undocumented parameter (true) to https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/1.0/addons/core/functions/fnc_radioToRequestCount.sqf
tells radioToRequestCount to replace all Radios. So in turn on respawn all radios should get replaced by new ID's with the same old settings.

As i just got woken up, I'm gonna go back to sleep now.

**Comment by dedmen** [comment]
I'd prefer that you would just call 
```true call TFAR_fnc_requestRadios;```
which will take care of handling duplicate ID's.

If your script executes before TFAR's respawn handler (As it is now. Not copying settings), TFAR will not be able to copy settings from the old radios to the new ones.
If your Respawn Loadout script runs after TFAR's handler though you would have to take care of duplicate ID's.

**Comment by bux578** [comment]
@dedmen The only problem I ever had with duplicate IDs was loading a profile from Virtual Arsenal

**Comment by CorruptedHeart** [comment]
And we have a PR and issue to fix the arsenal: https://github.com/michail-nikolaev/task-force-arma-3-radio/issues/1123

So it might not be an issue after all for the TFAR side if that is the case and no handling will be required on your side.

**Comment by bux578** [comment]
@dedmen feel free to join our chat http://slackin.ace3mod.com/

**Comment by Dorbedo** [comment]
Shouldn't that be fix on TFAR/ACRE side, since it is restricting the usage of arsenal an the `getUnitLoadout` command? In my opinion, you could add a possibility to modify the loadout before spawning. The modification should be done by the mod, which is using unique items.

**Comment by Glowbal** [comment]
I feel this solution may be to specific towards acre. I'd like to generalize it so it can be used by other systems as well. Ig our planned bft components

**Comment by jonpas** [comment]
@Sniperhid will look into it for ACRE2, to try to sort it on that side as it should be.

**Comment by PabstMirror** [comment]
Looks like TFAR and ACRE will both be handling the problem on their own

**Pull request closed without merging**
