### PR TITLE
ACE_Finger cleanup

### LINKED ISSUE #1917: Finish Enhanchments to pointing
Finger is functional, but I didn't finish all the notes from @esteldunedain 
See #1548

### PR DESCRIPTION
**Pull request by esteldunedain**
**When merged this pull request will:**
- Add privates
- Replace ad-hoc function with EFUNC(common,getZoom)
- Make pointing error proportional to the distance to the target
- Close #1917
- Allow pointing to nearby positions:

"Soldier, pick that weapon up"
image

### CODE REVIEW

**Comment by PabstMirror** [comment]
This is fantastic; I think it also matches how the 1.62 pointing will work 
(except that is global which we don't want)

**Comment by esteldunedain** [comment]
>  I think it also matches how the 1.62 pointing will work 

Ouch, I didn't know they were planning such a thing. Is there any info about it?

**Comment by bux578** [comment]
@esteldunedain https://www.youtube.com/watch?v=Jy68aqB2-l4

**Comment by esteldunedain** [comment]
Aha, yes; this PR works exactly like that, except it's:
1- Only shown to nearby units
2- Fades after a sec
3- It has a hand animation

BIS keeps ripping out mods :grin:

**Comment by jonpas** [comment]
> BIS keeps ripping out mods :grin:

Sadly making it worse in those 2 cases (pointing and squad radar).

**Pull request closed without merging**
