### PR TITLE
ACE2 ball tracers port.

### PR DESCRIPTION
**Pull request by jaynus**
This merges in all the ACE2 ball tracers models.

### CODE REVIEW

**Comment by esteldunedain** [comment]
Pushing for later, cause apparently we won't be using them right now

**Comment by cych** [comment]
ACE had very good tracer effect, the basic Arma 3 tracer lacks of consistency, too small compared to real life tracer effect.

**Comment by jaynus** [comment]
There was some arguments back and forth about the laser beams so these weren't implemented.

**Comment by cych** [comment]
I got a solid 1080p argument for more visible bullet tracers

https://www.youtube.com/watch?v=V8766Nh-oGE

**Comment by ulteq** [comment]
Is this ready for merge?

**Comment by esteldunedain** [comment]
@ulteq, this PR only contains the ball tracers models from ACE2, but they are not used for any ammo yet. The actual usage should probably be an optional pbo, cause not everyone likes them

@cych, tracer looks shouldn't be evaluated from video footage. Bright lights have much more persistence in the human retina than on video. I've heard people with real military experience say tracers-as-lines are much closer to rl than tracers-as-balls.

**Comment by jaynus** [comment]
>  tracer looks shouldn't be evaluated from video footage

This is why blastcore and JSRS have always been incorrect. What they sound and look like on footage is *completely wrong*

**Comment by ulteq** [comment]
@jaynus @esteldunedain Thanks for the clarification.

**Comment by ulteq** [comment]
Ready for testing.

And what do we do with the new classes that did not exist before (e.g. the 30mm rounds)?

**Comment by esteldunedain** [comment]
> What do we do with the new classes that did not exist before (e.g. the 30mm rounds)?

I think you should appy the ball tracers to them too.

BTW, is that list of tracers complete? It would be very usefull for #1008

**Comment by esteldunedain** [comment]
One more thing; should be rename the pbo to "balltracers"??

**Comment by ulteq** [comment]
> BTW, is that list of tracers complete?

Yes

> One more thing; should be rename the pbo to "balltracers"??

Yes

**Comment by jaynus** [comment]
> We can't rename it without changing all the p3d files as well.

Easily doable, I already had to do it once. These are all MLODs so there is nothing stopping is from renaming it.

**Comment by ulteq** [comment]
Those ball tracers are pretty ugly by the way.

**Comment by jaynus** [comment]
They are 10000x better than the laser beams

**Comment by ulteq** [comment]
Ready for merge.

**Comment by ViperMaul** [comment]
Any one test and confirm this?

**Comment by sargken** [comment]
Bring em back they are alot nicer than the ones currently or make it optional

**Comment by jaynus** [comment]
I didn't see any difference on some vanilla weapons. Maybe I was missing something. @ulteq ?

**Comment by ulteq** [comment]
> I didn't see any difference on some vanilla weapons.

Which vanilla weapons?

**Comment by jaynus** [comment]
My setup was messed up at the time, this is good to merge.

**Pull request merged**
