### PR TITLE
Fix for #2495

### PR DESCRIPTION
**Pull request by jokoho48**
Fix for #2495

### CODE REVIEW

**Comment by PabstMirror** [comment]
:+1:

**Comment by bux578** [comment]
oh, those errors ...

**Comment by commy2** [comment]
"Cleanup" :D

**Comment by Glowbal** [comment]
Well I love this one. :+1:

**Comment by jokoho48** [comment]
that was @MikeMatrix

**Comment by commy2** [comment]
Who merged it? That is the question.

**Comment by jokoho48** [comment]
@PabstMirror merged it ;D

**Pull request merged**
