### PR TITLE
Toolkit in misc box

### PR DESCRIPTION
**Pull request by SzwedzikPL**

### CODE REVIEW

**Comment by jonpas** [comment]
Isn't misc box supposed to have ACE3 items only?

**Comment by SzwedzikPL** [comment]
Toolbox is used by ace so i dont see any reason why toolkit shouldn't be in misc box :)

**Comment by Glowbal** [comment]
It's really a vanilla item. I'm not certain it belongs in the Misc box from ACE.

**Comment by SzwedzikPL** [comment]
> It's really a vanilla item. I'm not certain it belongs in the Misc box from ACE.

Ok, so nevermind.

**Pull request closed without merging**
