### PR TITLE
Added a 5 second delay when setting a timer based trigger.

### PR DESCRIPTION
**Pull request by CorruptedHeart**
Fixes https://github.com/acemod/ACE3/issues/319 there is no notification that the explosive is armed though.

Can someone suggest something that could be used as a notification? A sound perhaps?

### CODE REVIEW

**Comment by jaynus** [comment]
> Can someone suggest something that could be used as a notification? A sound perhaps? 

A clicking sound or an ACE hint would be ideal.

**Comment by esteldunedain** [comment]
Isn't 5 sec to much now that you'd changed the anim?

**Comment by CorruptedHeart** [comment]
There was no animation when setting the trigger. Now there is though. Quick put one though.

**Comment by esteldunedain** [comment]
@CorruptedHeart, I've just checked again. The 5 secs are completely unnecesary now. The ticket is from before the interaction with explosives was added. At that time the long medical animation due to placing the explosive used to happen AFTER selecting the trigger time.

**Comment by CorruptedHeart** [comment]
So then this can be closed then as well as the corresponding issue.

**Pull request closed without merging**
