### PR TITLE
Ballistics - B_50BW_Ball_F updated

### PR DESCRIPTION
**Pull request by Laid3acK**
**When merged this pull request will:**
- update the `B_50BW_Ball_F` according with the [Beowulf 12" Barrel Ballistics](http://www.alexanderarms.com/images/pdfs/beowulf_ballistics.pdf#page=2).
(1800 ft/s: 549 m/s close with the vanilla `typicalSpeed = 550;`)
- update the AtragMx GunList.
- update the `arifle_ARX_base_F` with the `arifle_Katiba_F` values (same caliber and magazines).

> ##########################################
Ammo Class: B_50BW_Ball_F
_drag model: 1_
_ballistic coefficient: 0.21_
MaxRanges (m): [300, 300]
MuzzleVelocities (m/s): [544, 564]
Max. Velocity diff (m/s): 20.45
Max. Drop diff (cm): 0.81
Max. Tof diff (ms): 8.5
Optimal airFriction: 0.00209809

Issues : 
- Primary weapon rangecard (`B_65x39_Caseless_green`) with the .50BW selected (`class Secondary: Rifle_Base_F`).
- With a sniper scope, the turrets don't work when the .50BW is selected.
- the .50BW `ACE_barrelLength = 304.8;` and `ACE_barrelTwist = 508.0;` are overwritten in-game by the Katiba `ACE_barrelLength = 508.0;` and the `ACE_barrelTwist = 203.2;`.

### CODE REVIEW

**Comment by Laid3acK** [comment]
This PR is only useful with the default ballistic. 
i tried a quick compat with a rifle and same 0.50BW values, 
the result and the bullet trajectory are good in-game according with [Strelok values](https://steamuserimages-a.akamaihd.net/ugc/779624699881654383/E508409294CB857A74414BB852215F8D0E305C2E/).
The advanced ballistics doesn't work with a "Secondary" weapon actually.

**Comment by jonpas** [comment]
>  The advanced ballistics doesn't work with a "Secondary" weapon actually.

Hmm, don't see a reason it shouldn't, so this could be added.

**Comment by Laid3acK** [comment]
I don't understand what's happening exactly.
The .50BW has the Katiba rifle twist and the bullet trajectory in game with adv. ballistics enabled is completely wrong.

**Comment by Laid3acK** [comment]
I can fix that temporarily with `ACE_caliber = 4.55;` instead `ACE_caliber = 12.7;`.
With this bullet diameter, i have exactly the same .50BW spin drift with the correct rifle twist 20".

**Comment by Laid3acK** [comment]
Confirmed in-game with `ACE_caliber = 4.55;`, the .50BW works as it should be now with AB enabled.
Better than nothing ?

**Comment by Laid3acK** [comment]
With the vanilla Arma 3, the `arifle_ARX_base_F` `initSpeed = -1.125;` overwrites the `Secondary: Rifle_Base_F` `initSpeed = 0;`. 

The vanilla .50BW has a MV 652 m/s = `10Rnd_50BW_Mag_F` `initSpeed = 580;` x `initSpeed = -1.125;`. 

Seems to be a BI bug, not ACE3.

**Comment by Laid3acK** [comment]
Last tests in-game with `ACE_caliber = 4.55;` and no dispersion, the .50BW external ballistic in-game matches with Strelok and the AtragMx. Until a BI fix, the only solution i found.

**Pull request merged**
