### PR TITLE
Tripple head monitor PIP optics fix

### LINKED ISSUE #1121: PIP optics in triple monitor broken
ACE3 Version: 3.0.0.2 50abf643

**Mods:**
* `@cba_a3`
* `@ace3`
* `@task_force_radio`

**~~Placed~~ ACE3 ~~Modules~~ userconfig:**
* Advanced Ballistics
  * Advanced Ballistics (Boolean): `Yes`
* BlueForceTracking 
  * `Enabled`
* Medical Settings
  * Medical Level (Option): `Advanced`
* MK6 Settings
  * `Enabled`

**Description:**
When paying in triple monitor setup PIP optics are broken, as seen in this screenshot:
http://i.imgur.com/JXbzbPC.jpg

**Steps to reproduce:**
* Play with 3 monitors
* Attach a PIP optic
* Watch the weirdness?

**Where did the issue occur?**
Multiplayer - Dedicated Server

**RPT log file:**
N/A

### PR DESCRIPTION
**Pull request by PabstMirror**
#1121

* Fixes scaling on scope's body/reticule
* Adds blackout on tripple head area's not covered by the PIP (these will never show for people not in tripplehead mode)

If we can figure out a way to make `ace_optics_pip.p3d` work on tripplehead we won't need the side blinders.

This is hard to test on my setup.  If someone with a native tripplehead setup could test this branch it would be extremely helpful. 

Current:

Fix:

### CODE REVIEW

**Comment by PapaReap** [comment]
I would be happy to test this out, as I have triple head displays and experiencing the same as the above photos. 

The problem I'm having is I'm pretty green to this and when I try to build from https://github.com/acemod/ACE3/tree/aef20f635a57fbd6e46a82cde7e785306edbcd13 

I'm having no luck with the build to be able to test. I've been able to build from previous versions of Ace 3 before, however I'm not sure what I'm doing wrong atm.

Anyways, myself and several other members of my group all run 3 displays and would love to help if we can, just let me know what we might be able to do.

**Comment by PabstMirror** [comment]
http://www.filedropper.com/aceoptics

**Comment by PapaReap** [comment]
This is definitely an improvement. Running current cba, ace official release w/ new optics.pbo.
I use 16:10 (1680x1050) monitors with 5292x1050 resolution w/ preferred 24.5 Triple Head.
I will see if I can get some of the guys running (1920x1080) monitors to do some testing later this evening.

RCO (PIP) 5292x1050 24.5 - TripleHead
rco pip 5292x1050 24 5-triplehead

RCO (PIP) 5292x1050 16.3 - TripleHead
rco pip 5292x1050 16 3-triplehead

RCO (PIP) 5292x1050 12.3 - TripleHead
rco pip 5292x1050 12 3-triplehead

RCO (2D) 5292x1050 24.5 - TripleHead
rco 2d 5292x1050 24 5-triplehead

RCO (2D) 5292x1050 16.3 - TripleHead
rco 2d 5292x1050 16 3-triplehead

RCO (2D) 5292x1050 12.3 - TripleHead
rco 2d 5292x1050 12 3-triplehead

**Comment by PabstMirror** [comment]
Looks like the only problem is the side-"blinders" aren't wide enough in PIP mode depending on the aspect ratio you pick. 

I'll see what I can do.

**Comment by PapaReap** [comment]
Sure thanks, give a shout when you would like more testing. I did test all the other variety of scopes with same results.

I suppose the side-"blinders" are for sure necessary for the time being, almost feels like driver of a tank :), still looks better than seeing different zoomed terrain's.

**Comment by PabstMirror** [comment]
@PapaReap - 

If you want to give this version a shot, I think I fixed the sides for pip and removed them from the 2d variants.

http://www.filedropper.com/aceoptics_1

**Comment by PapaReap** [comment]
@PabstMirror 
Will do

**Comment by PapaReap** [comment]
2d works great, pip is an improvement but until a fix to not having to use the blinders the pip most likely won't be used by triple head users.

**Comment by ViperMaul** [comment]
@PabstMirror, @PapaReap: 
Checking status on this. 
Do we have a user setting for this?
Is this ready to go as is?

**Comment by PabstMirror** [comment]
Merged Via 30adc2d463846011f8a31646b07a3c52a5dcf7ec to avoid adding all the weird commits in this branch.

**Pull request closed without merging**
