### PR TITLE
Remove remaining usage of player

### PR DESCRIPTION
**Pull request by BaerMitUmlaut**
**When merged this pull request will:**
- Remove the remaining usage of `player` instead of `ACE_player`.

### CODE REVIEW

**Comment by esteldunedain** [comment]
I think `fnc_setHearingCapability.sqf` came CSE, and it'is not used in ACE; maybe you should remove it altogether.

**Comment by PabstMirror** [comment]
The function looks like a good idea because both hearing and medical both try to change volume (with hearing overwriting medical)

But I think we can fix conflicts in the hearing module by checking if player is Unconscious.

**Comment by Glowbal** [comment]
Using such an approach would make it easier for any other kind of modification to adjust hearing. Makes it more flexible

**Comment by BaerMitUmlaut** [comment]
Guys have you forgotten about the unified status effect handlers? This is basically made for it.

**Pull request merged**
