### PR TITLE
WIP: Guided Bombs

### PR DESCRIPTION
**Pull request by xrufix**
**When merged this pull request will:**
- Change missileguidance framework so it works with properly configured bombs.
- Add LOAL-capabilities to laser guided bombs.
- Guidance based on predicted flight path, so bombs can be released in a ballistic curve (Paveway-III-style)
- Some optimizations to missileguidance functions.

**Current issues:**
- [ ] Flight path predicted based on ideal conditions (without air friction taken into account). Therefore bombs will impact slightly too early (ca. 3-5 m when released at 500km/h at 1000m ASL).

**ToDo:**
- [ ] Move ammo and weapon configs to own module `ace_bombs` ?
- [ ] Configs for vanilla bombs.
- [ ] remove vanilla locking without breaking AI.
- [ ] GPS guidance.
- [ ] Bombs without flight path prediciton (Paveway-II-style, LOAL required for optimal results).

### CODE REVIEW

**Comment by LorenLuke** [comment]
If possible, I'd recommend trying to interface with the targeting pod camera as a quick way to get a GPS coordinate, if manual entry or datalink or something can't be a thing.

**Comment by ski2060** [comment]
Hey guys.  Maybe look at the ITC Aircraft Improvement Mod to see what they've done by integrating ACE Micro-DAGR waypoints as GPS targeting and steerage waypoints for Bomb guidance.
Dunno if it's something that can be rolled into ACE with the author's OK, or at least what is possible for your Guidance improvements.

**Comment by xrufix** [comment]
I haven't worked on this for quite a while. The reasons is I can't figure out how to calculate the bombs movements. I thought when the function simply changes the bombs pitch/yaw/roll then the engine will calculate velocity. But obviously, p/y/r-changes change velocity as well, so the bomb can even fly up after release if it's pulling up its nose. 

I couldn't find a way to prevent this.

**Comment by Mike-MF** [comment]
Closing due to age and/or inactivity, unlikely to be finished or has to be reworked due to other changes over the years. May be re-opened if someone finds it useful, even better just open a new up-to-date PR.

**Pull request closed without merging**
