### PR TITLE
Replaced check for cargo function by check for ace_cargo in Repair

### PR DESCRIPTION
**Pull request by jonpas**

### CODE REVIEW

**Comment by PabstMirror** [comment]
Why don't we just add the event handler in cargo's CfgEventHandlers.hpp?

**Comment by jonpas** [comment]
Then you have to check if `ace_repair` is loaded since that's where the repair items are. I think it's better this way, either way you have to check if one another exists.

**Comment by PabstMirror** [comment]
It should be fine to add entries to `Extended_Init_EventHandlers` for vehicles even if they don't exist.

CBA doesn't iterate though all XEH.
CBA just goes through the inheritance chain for XEH enabled vehicles.

So if `ACE_RepairItem_Base` doesn't exist, the XEH entry won't do anything.

**Comment by jonpas** [comment]
Confirmed working, I've moved it over to cargo. Thanks for the insight. :)

**Pull request merged**
