### PR TITLE
Wake up without epi - fixed version of #1762

### PR DESCRIPTION
**Pull request by Winter259**
Another victim to my amateur git skills...

### CODE REVIEW

**Comment by Winter259** [comment]
In my testing, AI still gets up after about 10 seconds, even if the setting is disabled. Any ideas?

**Comment by Kilo1-1** [comment]
Winter, have you tried to reference the AGM wakeup feature to see how it compares with yours?  The AGM wakeup worked fine even with AI.

**Comment by Glowbal** [comment]
I am not certain if this is needed anymore with the changes to basic medical unconsciousness.

**Comment by Winter259** [comment]
Sorry for putting this on the back burner, had other projects steal my attention. From the changes I had made, the effects of #1964 had happened, I couldn't figure out why players & AI would wake up. How has basic medical uncon changed?

**Comment by galevsky** [comment]
We still have unconscious players that wake up after 10 sec in v3.3.1, how can we disable this weird feature ? How can I prevent unconscious guys to wake up without epinephrine shot from medic ? Is there any settings with maximum unconscious duration that can also disable it if set to -1 ?

Many thanks you for your help !

**Comment by galevsky** [comment]
Any news about that hot topic ? I know entire teams who prefer not to use ACE3 until the wake-up-without-epinephrine is not disabled, my clan is also waiting for a solution to prevent it...  so weird to play no-respawn  missions with Elite settings BUT shooting down the same guy many times due to the magic wake-up with no medic action required !

Thank you for your help !

**Pull request closed without merging**
