### PR TITLE
Translatíon stuff Not fully done yet

### PR DESCRIPTION
**Pull request by meat147**
Options needs still tweaking

### CODE REVIEW

**Comment by bux578** [comment]
There's sth wrong with that PR.

**Comment by esteldunedain** [comment]
This PR is made from meat147/master to acemod/medicalFixes, so some new commits to master show here. Merging the most up to date master onto the acemod/medicalFixes branch should remove those things from the diff, so no problem.

**Comment by Glowbal** [comment]
Latest master has been merged into medicalFixes. We probably have a merge conflict with the new settings for litter now.

**Comment by meat147** [comment]
i will up date my branch to your current Master and then Make a new pr

**Pull request closed without merging**
