### PR TITLE
added missile camera

### PR DESCRIPTION
**Pull request by kripto202**
-adds the missile cam to the hellfire missiles
-added cameraViewAvailable = 1; in line 26 
-video proof to have missile cam on the hellfires https://www.youtube.com/watch?v=KcEoRae6Yog

### CODE REVIEW

**Comment by PabstMirror** [comment]
I don't think it's a hellfire in that video,
it launches from the ground
it does look a lot like the spike (see https://github.com/acemod/ACE3/issues/1059#issuecomment-100301651)

**Comment by kripto202** [comment]
hellfire missiles aren't just air-to-ground missile, it is also a ground-to-ground missile

**Comment by kripto202** [comment]
also hellfire missiles can be launched through a simple launcher https://www.youtube.com/watch?v=RHPVDRXKGfc

**Comment by kripto202** [comment]
https://www.youtube.com/watch?v=piY2gbplUAw

**Comment by commy2** [comment]
This PR looks broken.

**Comment by kripto202** [comment]
Not surprised since I never used github to this level. I still can't seem to update my fork.

**Comment by tbeswick96** [comment]
Hellfire missiles don't have a camera feed. The nose is entirely sensor.
The videos linked are all either Javelin missiles or TOW, not hellfires.

**Comment by BaerMitUmlaut** [comment]
Pretty sure the first one is a Spike.
The second one is a Javelin (Hellfires cannot be shoulder launched and aren't soft launched either).
Third video could be a Spike as well (Hebrew text pretty much confirms this).

**Comment by jonpas** [comment]
Closing as Hellfire missile don't actually have that, as pointed out by all the comments above.

Thanks for the wanted contribution @kripto202, you are of course free to use this yourself or whatever, just not going to be part of ACE3.

**Pull request closed without merging**
