### PR TITLE
Fix suppression for basic medication

### PR DESCRIPTION
**Pull request by diwako**
**When merged this pull request will:**
- Fix basic medication not suppressing pain

Addressing #7409

### CODE REVIEW

**Comment by commy2** [comment]
Please explain.

**Comment by diwako** [comment]
> Please explain.

When advanced medication is disabled, the pain suppression variable will be always set to 0. This happens right at the beginning of the changed file with
```sqf
_unit setVariable [VAR_PAIN_SUPP, 0 max _painSupressAdjustment, _syncValue];
```

Turns out the value for `_painSupressAdjustment` is always 0 when on basic medication. This value comes from the `handluUnitsVital` function. 
https://github.com/acemod/ACE3/blob/master/addons/medical_vitals/functions/fnc_handleUnitVitals.sqf#L101

The value will be always 0 because advanced medication is not enabled, no medication will be set on the unit. In case of morphine, the pain suppression value will be altered and then you exit out of the medication function.
https://github.com/acemod/ACE3/blob/master/addons/medical_treatment/functions/fnc_medicationLocal.sqf#L30

This means in the `handleUnitVitals` there is no medication to iterate over and to add to the value for `_painSupressAdjustment`.

The fix is to rearrange when the `updatePainSuppress` function updates the current pain suppression value. It does not make sense to set the value and then set it again based on the already altered value for pain suppression on that unit. Especially if that altered value is always 0.
Hence why I moved the initial set of the variable into the else case, as only in the case of advanced medication being enabled the value for `_painSupressAdjustment` can be 0.

**Comment by commy2** [comment]
But there is no function call between the previous and the new position of setVariable.

**Comment by diwako** [comment]
Not that is misunderstand, there was none and there should not be any.

The pain suppression value is being set in 2 functions specifically. One is is `ace_medical_treatment_fnc_medicationLocal` specifically when advanced medication is disabled and the other is  `ace_medical_vitals_fnc_updatePainSuppress`.

For basic medication the first function is used to increase the value and the second is used to decrease the value of the pain suppression over time. The bug is `ace_medical_vitals_fnc_updatePainSuppress` sets the value to the given value of `_painSupressAdjustment` and then decreases the value as we are in basic medication. But the pain suppression value was already overwritten with the wrong value `0`, so the logic thinks you just have no morphine in your blood system at all. That is why i moved the first `setVariable`.

`ace_medical_vitals_fnc_updatePainSuppress`  is being called from `ace_medical_vitals_fnc_handleUnitVitals`  and `ace_medical_treatment_fnc_medicationLocal` when ever someone injects an auto injector.

**Pull request merged**
