### PR TITLE
Port of AGM_FastRoping

### PR DESCRIPTION
**Pull request by KoffeinFlummi**
Still not quite sure how to properly do the giant spawn in fnc_fastRope...

### CODE REVIEW

**Comment by jaynus** [comment]
Note from meeting: Slingloading physx can apply to ANY object now so this is a definite work item.

**Comment by SzwedzikPL** [comment]
Any plans? status? This is one of the most wanted features :)

**Comment by Knight1981** [comment]
Yeah please add fast rope in the near future! This is really the most wanted feature :)

**Comment by i3r4ndon** [comment]
One of the features I look forward to having available again the game the most. :)

**Comment by BaerMitUmlaut** [comment]
I'm working on this right now.

**Comment by SzwedzikPL** [comment]
@BaerMitUmlaut great news!

**Comment by Glowbal** [comment]
New progress happens here #2904

**Pull request closed without merging**
