### PR TITLE
Disable marker editing for everything non-icon

### PR DESCRIPTION
**Pull request by Timi007**
**When merged this pull request will:**
- Disable marker editing for everything non-icon

[Comment from PabstMirror](https://github.com/acemod/ACE3/pull/6564#issuecomment-423861538)

### CODE REVIEW

**Comment by commy2** [comment]
What else are there for shapes aside from "ICON" and "POLYLINE" (?).

**Comment by Timi007** [comment]
According to the [Wiki](https://community.bistudio.com/wiki/setMarkerShape): "ICON", "RECTANGLE", "ELLIPSE" and "POLYLINE"

**Comment by commy2** [comment]
So actually this also disables editing for everything non-ICON? (POLYLINE, RECTANGLE and ELLIPSE)?

**Comment by jonpas** [comment]
Can you even place them in game? Only Editor IIRC

**Comment by commy2** [comment]
Well, one could've easily written `!= "POLYLINE"` if one wanted to make these types still editable.
Or if one doesn't want to, one would name the PR accordingly.

**Comment by commy2** [comment]
Thanks. These are the things that bother me.

**Comment by PabstMirror** [comment]
Can't test now, but I think the "straight lines" feature ace still has might be type rectangle. and probably don't want to convert those to icons either

**Pull request merged**
