### PR TITLE
Parse List Common Function

### PR DESCRIPTION
**Pull request by jonpas**
Used for parsing strings in modules, has params for optional remove whitespace (default is trim) and to check for object existence. Rerouted part of `assignObjectsInList` through this as well.

### CODE REVIEW

**Comment by MikeMatrix** [comment]
:+1:

**Comment by jonpas** [comment]
Status? As soon as this gets merged (or closed) I'll replace string operations with new commands.

**Comment by commy2** [comment]
I'd say something, but I have no idea at all what this does.

**Comment by jonpas** [comment]
It parses modules which take strings, (eg. list of medical vehicles or list of repair facilities), checks for nil, removes or trims whitespace (all parameters). It is used in all modules that can take a list and the code was duplicated in each of them, this simply makes one function that all modules can use. It can of course be used for something else than modules, hence why it's in common.

**Comment by Glowbal** [comment]
I wonder if modules isn't a better location for this.

**Comment by jonpas** [comment]
I'd say no, it doesn't take module logic, it can be used for anything else that requires parsing string lists.

**Comment by jonpas** [comment]
Merge conflicts resolved.

**Comment by jonpas** [comment]
Status?

**Comment by commy2** [comment]
I still have no idea what this does, haha.

**Comment by jokoho48** [comment]
it combine a function that used in closly every module :D

**Comment by commy2** [comment]
:+1:  Merge then if anyone can confirm this works.

**Comment by jonpas** [comment]
If someone else can give it a test that would be great!

**Comment by jonpas** [comment]
Self-note #2565

**Comment by jonpas** [comment]
Added vehicle support from #2565 for `synchronizedObjects` with an optional parameter.

**Pull request merged**
