### PR TITLE
German and French translations

### PR DESCRIPTION
**Pull request by johnb432**
Adds completed German and French translations.

### CODE REVIEW

**Comment by bux** [comment]
@johnb432 could you please separate the german and french changes into one PR each?

**Comment by commy2** [comment]
What for? Separate review? Can't this be handled all in one PR?

**Comment by bux** [comment]
yeah, separate reviews.
I've already spotted 5+ mistakes in the german ones.

**Comment by johnb432** [comment]
I tried my best, not a native speaker but decided to invest a little time into something constructive. If it's unusable, just forget it.

**Comment by bux** [comment]
c pas grave. I've checked the first few translations and they are correct as they make sense but there were some typos by using the wrong "Kasus" (Not using Genetiv etc...)

It just easier to have one of our french guys just checking french translations and one of our german guys just checking german translations. That's why I was asking if you could separate them.

**Comment by Elgin675** [comment]
I'm sorry, but why do you translate french ? You're translating text that I've already translated recently.
And sometimes it doesn't make sense !
French is clearly not your native language, so please avoid introducing new mistakes ;) !

**Comment by johnb432** [comment]
Fuck it, seems like nobody appreciates it, which I can understand to a degree.

**Comment by bux** [comment]
@johnb432 please don't be discouraged. We are actually appreciating every effort to help out with ACE3.

**Pull request closed without merging**
