### PR TITLE
fix error when loading save game, fix #3391

### LINKED ISSUE #3391: Error loading savegame latest master
```
17:36:20 Error in expression <= 12) then { 
(_display displayCtrl 51) ctrlAddEventHandler ["Draw", ace_interac>
17:36:20   Error position: <ctrlAddEventHandler ["Draw", ace_interac>
17:36:20   Error Type Any, expected String
17:36:20 File z\ace\addons\interact_menu\XEH_displayLoad.sqf, line 8
```

### PR DESCRIPTION
**Pull request by commy2**
### When merged this pull request will:

1. fix #3391

### CODE REVIEW

**Comment by commy2** [comment]
This is because in savegames, the map display is loaded before preInit.

**Comment by esteldunedain** [comment]
But how does the fix work? I can't see any difference between before and after

**Comment by commy2** [comment]
DFUNC is undefined. {_this call FUNC()} is a vali function even when FUNC() is undefined at that point.
It's RV being shit again.

**Comment by esteldunedain** [comment]
> DFUNC is undefined. {_this call FUNC()} is a vali function even when FUNC() is undefined at that point.

Perfect

**Comment by commy2** [comment]
So merge? I need this in CBA.

**Comment by commy2** [comment]
I guess the error is valid. The implementation of save game just has huge differences between normal games (and restarted ones ...)
We will have working save games eventually. Even if it means I have to turn everything upside down.

**Pull request merged**
