### PR TITLE
Repair - Fix isInRepairFacility for buildings at height

### LINKED ISSUE #6560: Repair Facility dont work on carrier
**Arma 3 Version:** 1.84.144923 (stable)
**CBA Version:** v3.8.0.180801 (stable)
**ACE3 Version:** v3.12.3.36 (stable)

**Mods:**
- [CBA_A3](https://steamcommunity.com/sharedfiles/filedetails/?id=450814997)
- [ACE3](https://steamcommunity.com/sharedfiles/filedetails/?id=463939057)

**Description:**
Repair Facility dont work on carrier. 
Objects set as repair facility are recognize only as repair vehicle not facility. 
Works fine on ground. 
- "Full Repair Location" is set to "Repair Facility Only"
- "Allow Full Repair" is set to "Anyone"

If i set "Full Repair Location" to "Repair Facility or Vehicle" or "Repair Vehicle Only" Full Repair seems to work fine. Tested with many objects from the editor i.e. "Huron Repair/Refuel/Ammo Container", "all Helipads" etc...

**Steps to reproduce:**
- Start ArmA3 with CBA + ACE
- Open the editor on any map (tested it on altis and stratis)
- Spawn the USS Freedom
- Place a playable unit with a toolkit in backpack on the carrier
- Place an object (i.e Huron Repair Container) on the carrier
- Set the object as repair facility
- Spawn a vehicle (i.e. M-ATV) on the carrier
- Damage it via the editor or with a weapon (tested both)

- Check the addon options in ace logistics
  - "Full Repair Location" is set to "Repair Facility Only"
  - "Allow Full Repair" is set to "Anyone"

- Try a full repair on the vehicle near the repair facility

Change the "Full Repair Location" now to "Vehicle Facility Only" and Full Repair is now available.

**Where did the issue occur?**
Singleplayer / Editor (Singleplayer) / Editor (Multiplayer)

**Placed Modules:**
none

**RPT log file:**
https://pastebin.com/Qvuwzt81

### PR DESCRIPTION
**Pull request by PabstMirror**
Fix #6560

On carrier, `position player` z is 0

### CODE REVIEW

**Comment by bux** [comment]
Would it make sense to rename the file to `fnc_isNearRepairFacility.sqf`?

**Comment by bux** [comment]
@Dystopian I know. We have procedures for such things:

In short: Rename the function, keep the old function name which in turn logs a deprecation warning and just calls the new function.

**Comment by Dystopian** [comment]
@bux I know :smile:
I meant maybe it's not worth it just for renaming. Moreover at Arma EOL.

**Comment by commy2** [comment]
`nearObjects` requires AGL, but `position` reports AGLS. Could have also used:
```sqf
ASLToAGL getPosASL _object nearObjects 7.5
```
but OBJECT is faster.

**Pull request merged**
