### PR TITLE
optional pbo to disable cross hair

### PR DESCRIPTION
**Pull request by commy2**
**When merged this pull request will:**
- Dunno if this is still needed. Someone made a request for it and I forgot about it. Found it while going through my unmerged branches.

### CODE REVIEW

**Comment by jonpas** [comment]
This control is hardcoded right? (no IDC/IDD)

**Comment by commy2** [comment]
No IDC. It's engine behaviour. It does adjust for camera movement etc.

**Comment by jonpas** [comment]
But isn't there a difficulty setting for crosshair specifically? Not sure if it's part of some other UI setting.

**Comment by commy2** [comment]
I have no idea.

**Comment by 654wak654** [comment]
Crosshairs have their own difficulty setting, they always did.

**Comment by esteldunedain** [comment]
> Crosshairs have their own difficulty setting, they always did.

Close?

**Comment by jonpas** [comment]
In that case I think this PR is pointless (sorry @commy2 !).

**Comment by PabstMirror** [comment]
It's a ACE_isOptional
So this allows a server to have crosshairs on, but users can disable them by adding this pbo.

**Comment by commy2** [comment]
^ Yeah. I vaguely remember something about this. A shame that I can't remember who suggested this.
Also, a shame that the new settings stuff isn't made in SQF like 3den, so we can fix and tweak it where necessary.

**Comment by Gwynblade** [comment]
Oh, I just saw this, it's me who requested it. When played with buddies that like crosshair on, we often had to compromise, sometimes off, sometimes on. With this, everybody can play how they like.

Thanks for making! :)

**Pull request merged**
