### PR TITLE
Add Headbag Feature

### PR DESCRIPTION
**Pull request by jokoho48**
Add Headbag Module
Preview
3 kinds of Headbags
Image
Image
Image

you can wear this as helmet and than you can see normal but if someone other use in ACE interaction Menu at you Add Headbag than you see Only this 
Image

This Feature is in WIP and Not Finish
Planed Features:
- [ ] Add Posible to Remove Headbag if not Captive
- [ ] Add Stringtable
- [ ] Fix Issue that Pause Menu brake Screentexture
- [ ] Add More Kinds of Headbags
- [ ] Update all Comments and Remove Uneeded

3D Mesh and BaseTexture by Jrudy(ACE Public Slack)
Texture Edit, Import, Skinning, Config and Code by Me
Hop you like the Feature

### CODE REVIEW

**Comment by SilentSpike** [comment]
Should this be it's own addon or would it make more sense for it to be a feature of ace_captives?

**Comment by jokoho48** [comment]
Yeah good idea but this is currently WIP and have many issues with that i currently struggling

**Comment by bux578** [comment]
:+1: Loving this ... but to be honest, I don't like the variants with the face and the "finger". Makes me think of the Payday games or Team Fortress Hats.

**Comment by gienkov** [comment]
Black, tan and white would fit this better. People can do retextures if
they want.
21 sie 2015 5:43 PM "bux578" <notifications@github.com> napisał(a):

**Comment by Glowbal** [comment]
> Black, tan and white would fit this better. People can do retextures if they want.
:+1:

**Comment by nomisum** [comment]
> Black, tan and white would fit this better. People can do retextures if they want.
:+1: 

I think it is an awesome addition for missions with playable captives like Dark Business. 

Would be great to optionally disable interaction while wearing the headbag. Thus it could serve the purpose of handcuffs without disabling movement.

Second idea: Make the overlay a bit translucent but blur the world with postprocessing. So you can at least see a bit of light/shadow movement. I'd hack this in myself when this is released in stable.

**Comment by licht-im-Norden87** [comment]
I'd like the feature to have some sort of symbols telling you where you are forced to go. Like if you are forced to go left there should be an arrow indicating the direction.

**Comment by Glowbal** [comment]
Closing this - probably better suited for ACEX and no work done on it since a while.

**Pull request closed without merging**
