### PR TITLE
Remove deprecated drop action

### PR DESCRIPTION
**Pull request by gienkov**

### CODE REVIEW

**Comment by alganthe** [comment]
note: This is for carrying and is *NOT* a duplicate.

**Comment by Glowbal** [comment]
I don't consider this a deprecated action. Dropping a carried/dragged object is one thing where I'd consider the scroll wheel action is to be useful/easy to use.

**Comment by bux578** [comment]
What @Glowbal said!

**Comment by gienkov** [comment]
Keybind would be better for this.

**Comment by SilentSpike** [comment]
Disagree, over-saturating the game with keybinds is a horrible idea

**Comment by jokoho48** [comment]
:-1: i dont like the idea because i personaly use the action menu and keybinding is a very horrible idea like @SilentSpike

**Comment by MikeMatrix** [comment]
Same opinion as @SilentSpike. Creating an option for general purpose things is a nice idea, but don't force it.
Also I use the addAction menu for that as well.

**Comment by SilentSpike** [comment]
Adding a self interaction option for it could work though (if there isn't already)

**Comment by MikeMatrix** [comment]
I believe there is already

**Pull request closed without merging**
