### PR TITLE
Vehicles - Mousewheel will set speed limiter value to even multiples

### PR DESCRIPTION
**Pull request by PabstMirror**
Before if you set speedlimter at 22
22->27->32

now
22->25->30

### CODE REVIEW

**Review by jonpas — APPROVED** [review]
Yeees!

**Comment by jokoho48** [comment]
why only do that with 5? should this maybe be done always?

**Comment by PabstMirror** [comment]
it's weird if the setting is something like `6.2`, you get floating point rounding errors

**Review by mharis001 — APPROVED** [review]

**Comment by mharis001** [comment]
Maybe change the setting to always be round numbers (`__trailingDecimals` to `-1`). It is already set to `0` (don't show decimals).

**Review by mharis001 — APPROVED** [review]

**Pull request merged**
