### PR TITLE
Remove line drawing

### LINKED ISSUE #3859: Using MapTools draws lines on map
image

Ctrl-Drag both rotates mapTools and now draws lines in 1.60.

I'm not sure how we want to fix this?
 - Try to delete the created marker
 - Drop ace's line drawing feature and just use the 1.60 version.

Tagging @esteldunedain

### PR DESCRIPTION
**Pull request by PabstMirror**
**When merged this pull request will:**
- Remove line drawing from maptools, and change maptools interaction to ALT from CTRL
- Also did some minor cleanup on mapTools.

Note, based off of PR #3815 to avoid adding conflicts, so PR diff is a mess until that's merged.
Changes in commit 73215b707daf61bd36145284904e05dc6e55f29d

Close #3859

### CODE REVIEW

**Comment by VKing6** [comment]
Is the ALT hardcoded, or can it be changed in settings?

**Comment by esteldunedain** [comment]
> Is the ALT hardcoded, or can it be changed in settings?

It is hardcoded. We don't have an infrastructure to configure modifier keys (those are not handled by CBA).

-------------

Looks very good, and ready to be merged as soon as the event handler stuff is.

I hope the *Unique Maps PR* #3601 can be massaged to work with BIS line markers eventually. It should be possible, given it already works with vanilla markers.

:+1:

**Comment by SzwedzikPL** [comment]
> I hope the Unique Maps PR #3601 can be massaged to work with BIS line markers eventually. It should be possible, given it already works with vanilla markers.

I'm working on this :)

**Comment by PabstMirror** [comment]
We could make an ace setting to handle different modifier keys, I think there is a server option to turn off line drawing so some people might want it back on CTRL.

CTRL draws lines
SHIFT places personal waypoint
ALT, in SP editor, is teleport

**Comment by esteldunedain** [comment]
> I'm working on this :)

@SzwedzikPL, I'm glad to hear it.

**Pull request merged**
