### PR TITLE
Change ace_map settings to use CBA init directly

### PR DESCRIPTION
**Pull request by mharis001**
**When merged this pull request will:**
- Convert all ace_map settings to CBA settings directly
- Give BFT settings their own category
- Make default channel setting a list

### CODE REVIEW

**Comment by jonpas** [comment]
I think this is perfect to change the rest of the settings in this component.

@PabstMirror should we remove reading the setting from module (call to the function that applies it)?

**Comment by mharis001** [comment]
@jonpas I can convert the settings in map component if that is decided

**Comment by jonpas** [comment]
@mharis001 thank you! Let's wait to hear from others first.

**Comment by mharis001** [comment]
Should BFT be its own component, or maybe a more generalized unit tracking? I dont know in terms of realism but i'd assume some OPFOR factions would have BFT like technology.

**Comment by commy2** [comment]
I think the BFT settings should be in their own Category.

**Comment by mharis001** [comment]
Remove question mark at the end of displayName of `BFT_ShowPlayerNames` and `BFT_HideAiGroups`?

**Comment by commy2** [comment]
YES! Please do that! Also remove the `:` if present. Some other settings use that and it also doesn't belong.
Also worth looking into how to capitalize the English.

**Comment by mharis001** [comment]
I think sentence case would be better than title case for settings.

**Comment by PabstMirror** [comment]
Take a look at https://github.com/acemod/ACE3/pull/5581/files#diff-e1cf3ccb88bb6158f0e98e8cbd4f9483R4

We'll want to leave the ace_settings in, but empty except for `movedToSQF = 1;`

(Because we need to know at preInit if a mission config setting is a change, or a brand new setting for the mission)

**Comment by mharis001** [comment]
Thats my bad. I'll fix it.

**Comment by jonpas** [comment]
> Do you want to also place all settings in a `initSettings.sqf` file?

Yes, please.

**Comment by PabstMirror** [comment]
We could keep BFT stuff in same category and just put them in a sub category
image

CBA 3.6 isn't out yet, so we can always do this in a later PR
`[format ["ACE %1", localize LSTRING(Module_DisplayName)], localize LSTRING(BFT_Module_DisplayName)],`

**Comment by mharis001** [comment]
Sub category sounds good once CBA 3.6 is released.

**Pull request merged**
