### PR TITLE
compat_RHSus : Change for default ACE_12.7x99

### PR DESCRIPTION
**Pull request by J3aLeiNe**
- rhsusf_ammo_127x99_M33_Ball = B_127x99_Ball from addons/ballistics/CfgAmmo.hpp

 - rhsusf_ammo_127x99_mk211 = ACE_127x99_API from addons/ballistics/CfgAmmo.hpp

### CODE REVIEW

**Comment by J3aLeiNe** [comment]
By request from @esteldunedain , sorry for the inconvenience. :)

**Comment by J3aLeiNe** [comment]
Re and recheck all ammos, seems to be correct now.

**Comment by J3aLeiNe** [comment]
Last commit for AB entries, close for me.

**Comment by J3aLeiNe** [comment]
I am bad, this last commit should be in a another PR, sorry.

**Comment by PabstMirror** [comment]
:+1:

**Pull request merged**
