### PR TITLE
Added Dutch translation

### PR DESCRIPTION
**Pull request by StealthyPredator**
Added a part of the Dutch translation. Added my name to the AUTHORS list.

### CODE REVIEW

**Comment by StealthyPredator** [comment]
Are these updated added to the pull request? Because I cannot create a new PR.

**Comment by StealthyPredator** [comment]
Hello? Anybody there? I cannot continue this way and I am eager to continue translating...

**Comment by Glowbal** [comment]
Does A3 even support Dutch?

**Comment by esteldunedain** [comment]
> Does A3 even support Dutch?

**Comment by jaynus** [comment]
What would do we for unsupported languages? Add an optionals that overrides all the english with dutch?

**Comment by StealthyPredator** [comment]
Hmm.. That is a good one...I do not see it in the language list :-(.  I did not check that before I started. Darn it!  Guess I did all of this for nothing.

**Comment by StealthyPredator** [comment]
Arma 3 supports the following languages:
•English
•German
•Italian
•Spanish
•French
•Korean*
•Japanese*
•Russian
•Polish
•Czech
•Brazilian Portuguese

So no Dutch :-(.

**Comment by StealthyPredator** [comment]
So what's the plan? Scrap it or keep it? Either way... I tried to contribute :-).

**Comment by esteldunedain** [comment]
> What would do we for unsupported languages? Add an optionals that overrides all the english with dutch?

No, that's not worth it. IMO it's safe to assume that if a player is confortable playing the unlocalized vanilla game the same should apply for ACE.

**Comment by StealthyPredator** [comment]
Thanks for those replies guys! I will leave it to you guys, the collaborators and owners to decide what you want to do. You know where to find me (here) if you need something translated into the Dutch language :-).

**Comment by esteldunedain** [comment]
Thanks @StealthyPredator and sorry for not realizing this sooner.

**Comment by StealthyPredator** [comment]
Not a problem :-).

**Pull request closed without merging**
