### PR TITLE
Interact menu - Convert 'use list menu' setting to 'use wheel menu'

### PR DESCRIPTION
**Pull request by alganthe**
**When merged this pull request will:**
- Convert "use list menu" setting to "use wheel menu"  which is false by default.

Lists are superior, can display more elements at once and are easier to read.

### CODE REVIEW

**Comment by Drofseh** [comment]
I do think `circle` sounds better than `wheel` in English.
"Use circular menu"

**Comment by alganthe** [comment]
it's all synonyms, radial sound good too but it might be harder to translate, so I kept it simple

**Comment by Drofseh** [comment]
It doesn't work grammatically in English because wheel is a noun.
It would have to be "Use wheel shaped menu".
Circular is an adjective, so "Use circular menu" works.

**Comment by PabstMirror** [comment]
Is this a real PR or a shitpost?

**Comment by alganthe** [comment]
That's not very nice pabst, and yes this is a real PR, list are superior to radial and should be made default, they can display more entries with longer text and are easier to navigate, as such they should be made the default behavior of the interaction menu.

**Comment by bux** [comment]
Let's not change years old defaults.

**Comment by jonpas** [comment]
I am undecided, if most agree it should not be merged, let's just close it.

**Comment by PabstMirror** [comment]
Sorry for my rude comment
https://github.com/acemod/ACE3/pull/6609 was just merged 
so if we wanted to change any defaults now would be a good time
but I still think keeping defaults the same is for the best

**Comment by commy2** [comment]
I would've just changed value = 0; to value = 1;

**Comment by Drofseh** [comment]
I would still like to see this changed.
List is vastly superior to radial for ease of use.
Sub-nodes appear in more predictable places, you can have a much larger number of sub-nodes before you run into space constraints, and you can have longer node name strings before the end of the string runs into another node.

**Comment by jonpas** [comment]
I am still in favour of this change, and @commy2's comment:

> I would've just changed value = 0; to value = 1;

**Comment by SilentSpike** [comment]
I personally think list should be the default, however would just change the default setting value rather than create a new setting for backwards compatibility.

**Comment by jonpas** [comment]
Replaced by #8217.

**Pull request closed without merging**
