### PR TITLE
Compats RHS GREF - Increase fuseTime values

### PR DESCRIPTION
**Pull request by Whigital**
**When merged this pull request will:**
- Updates `rhs_fuseTime` array for `rhsgref_ammo_rkg3em` grenades to account for delay used in `ace_advanced_throwing_fnc_throw`
- Partial fix for https://github.com/acemod/ACE3/issues/7534

### CODE REVIEW

**Comment by commy2** [comment]
Where are these numbers from?

**Comment by severgun** [comment]
> Where are these numbers from?
Check comments at issue ticket.
Native RHS config values are `rhs_fuseTime[] = {0.3,0.35,0.4};`
Add 0.3 sec delay to compensate
https://github.com/acemod/ACE3/blob/c73f64617fcc2b1211878423296e9558068eb8f6/addons/advanced_throwing/functions/fnc_throw.sqf#L83
Result: `rhs_fuseTime[] = {0.6,0.65,0.7};`

**Comment by Whigital** [comment]
See the issue for reasoning/background. Could update the comment in the config with more details for future reference.

**Comment by commy2** [comment]
>This PR can affect regular throw in bad way, but I think in most cases it will be OK.

Then it's a no go and needs something less hacky/more sophisticated.

**Comment by severgun** [comment]
> Then it's a no go and needs something less hacky/more sophisticated.

Theoretically, what can happen is that grenade will hit target before metamorphosis and disappear.
First ammo have 
```
explosionTime = -1;
explosionEffects = "";
hit = 0.1;
indirectHit = 0;
```

**Pull request closed without merging**
