### PR TITLE
Optionalized Cargo Loaded Hint

### PR DESCRIPTION
**Pull request by jonpas**
And disabled it when called through `addCargoItem`, for example `addSpareParts`, which happens on vehicle init, would show the hint, even if the vehicle would be spawned during the mission.

### CODE REVIEW

**Comment by commy2** [comment]
^ yeah thats a bug in the current master.
I plan on reworking this anyway, but this at least fixes this bug in master for now.

**Comment by jonpas** [comment]
I "created" the bug as well since I added that when adding spare parts framework.

How do you plan to rework it?

**Comment by commy2** [comment]
A function that is called by action that ends in a progress bar.
A callback function called from the progress bar.
And a load function that is called by the callback function that also can be used as API.

Hint, animations etc. are done by the first two. Same for unloading.

**Comment by jonpas** [comment]
Sounds good!

**Comment by commy2** [comment]
:+1:

**Comment by SilentSpike** [comment]
Regarding the rework discussion here, should be handled by the changes made in #2628

You may want to build upon what's there though

**Pull request merged**
