### PR TITLE
Missile guidance for RHS hellfire and DAGR

### PR DESCRIPTION
**Pull request by TheNiner**
**When merged this pull request will:**
- Add the hellfire missile guidance to the RHS hellfire and DAGR

### CODE REVIEW

**Comment by PabstMirror** [comment]
Sorry for the delayed response on this.
RHS is suppose to be adding pylon support, hopefully soon

> will all aircraft eventually transition to have jets DLC compatible loadouts?
>this is already done and part of the next update.
From their facebook, aug 21st

We could merge this now and update to plyons when they do,
but I think I'd rather wait for them to release the pylon update; 
ace_hellfire is somewhat complex to use and I'm worried about forcing it's use on their helicopters

**Comment by shukari** [comment]
0.4.3 is out

**Comment by cych** [comment]
need an ACE fix for the just released dynamic weapon loadout. when selected via this new system the hellfire in the weapon cycle lost the ACE supported feature (missile trajectory mode, laser code)

**Comment by PabstMirror** [comment]
Looks like hardpoint `RHS_HP_HELLFIRE_RACK` will work nicely.

**Comment by bux** [comment]
#5577

**Pull request merged**
