### PR TITLE
Change key items mass from 0 to 0.1

### PR DESCRIPTION
**Pull request by alganthe**
**When merged this pull request will:**
- Change ace keys and lockpick to have 0.1 mass instead of 0.

### CODE REVIEW

**Comment by PabstMirror** [comment]
The reason they were 0 is because they get added to player's inventory and I didn't want to worry about a unit having no space left.

But I guess 0.1 is still small enough it shouldn't be a problem

**Comment by alganthe** [comment]
thing is with 0 you can have thousands of them, it's not an issue with BIS arsenal because adding items so slow but with ACE3 arsenal I can have 10 000 under a minute.

**Comment by commy2** [comment]
I'd say you should fix your arsenal instead and cap the number of items for the "fill all" option or whatever you're doing. There could be many more items with no mass in 3rd party mods out there and this won't help at all for those.

**Comment by alganthe** [comment]
Then you'd require to do the same for vanilla arsenal, it's slow but still possible.

**Comment by commy2** [comment]
The slowness makes it not feasible though.

**Comment by jonpas** [comment]
Why is that a problem either way, tbh if people are so stupid to do that they deserve a crashed server. For public servers and whatnot you can add a setting (maybe even default enabled) which caps amount of one item to something like 100.

**Comment by commy2** [comment]
No! Not every small thing needs a setting. Just limit all items to idk. 100 or whatever and you fix it very elegantly. There is no use in having more than enough of any type of item, so a setting would be bloat.

**Comment by commy2** [comment]
That said, all items should have a weight. And if you worry about the inventory being full then consider something like: https://github.com/CBATeam/CBA_A3/blob/master/addons/common/fnc_addItem.sqf which spills the item on the ground if needed.

**Comment by PabstMirror** [comment]
This uses magazineDetail ID stuff, so I can't just add it to a ground container

**Comment by PabstMirror** [comment]
Still needed, or fix in arsenal?

**Comment by alganthe** [comment]
still "needed", it doesn't break anything per se, it's just a really bad idea to have items with 0 mass.

**Comment by alganthe** [comment]
keys are considered unique items in ace arsenal now as far as i'm aware, closing.

**Pull request closed without merging**
