### PR TITLE
outline interaction menu text

### PR DESCRIPTION
**Pull request by commy2**

### CODE REVIEW

**Comment by PabstMirror** [comment]
This will ignore shadow color so we can either remove that option, or make shadowType a user option as well.

**Comment by ulteq** [comment]
This seems to be already merged into master: https://github.com/acemod/ACE3/blob/master/addons/interact_menu/functions/fnc_renderIcon.sqf#L35-L37

**Comment by commy2** [comment]
^ fixed in https://github.com/acemod/ACE3/commit/f96deadd20cc5528044353eb518e5f84898d8bbb

Probably left ST open by accident when switcing branches.

**Comment by ViperMaul** [comment]
Status?

**Comment by esteldunedain** [comment]
Closing this because it's now part of #921

**Pull request closed without merging**
