### PR TITLE
Fix Events Framework documentation 3.1 section

### PR DESCRIPTION
**Pull request by jonpas**
**When merged this pull request will:**
- Title
- Use `target="_blank"` for CBA Events documentation link
- ~~Add dots after section numbers~~
- Use code for component names

### CODE REVIEW

**Comment by bux578** [comment]
I don't like the closing point on the numbers.

That's how we have it everywhere:
`1.`
`1.1`
`1.1.1`

**Comment by jonpas** [comment]
> That's how we have it everywhere:

Not true, we have a terrible mix of both.

**Comment by jonpas** [comment]
I am all for standardizing it, don't get me wrong. :laughing: 
I like closing point on main numbers and no in subsequent. And it appears it is [documented](http://ace3mod.com/wiki/development/documentation-guidelines-and-tips.html) like that as well. I shall change it.

**Comment by jonpas** [comment]
Done, and another PR for streamlining closing points opened.

**Pull request merged**
