### PR TITLE
convert common events to CBA playerEvents

### PR DESCRIPTION
**Pull request by commy2**
TODO:
- [x] remove PFH in common
- [ ] call ACE events as wrapper, deprecate?

### CODE REVIEW

**Comment by esteldunedain** [comment]
> call ACE events as wrapper, deprecate?

Yes, exactly.

Nice @commy21

**Comment by commy2** [comment]
merging this, because the `release` one is already merged too.

**Comment by esteldunedain** [comment]
hold on

**Comment by esteldunedain** [comment]
It's missing the deprecation warnings

**Comment by commy2** [comment]
That's true. The release branch one doesn't have them either.

We have other branches for 3.6.0 targeting master (e.g. !3980), so I guess we merge

**Comment by commy2** [comment]
oops
... merge them together before making the next RC.

**Comment by commy2** [comment]
How would I do that best?

**Comment by Glowbal** [comment]
I will sort it out @commy2

**Pull request merged**
