### PR TITLE
Add ACE hand load magazine type

### LINKED ISSUE #5592: ACE mortar rounds not in arsenal
**Arma 3 Version:** stable
**CBA Version:** stable
**ACE3 Version:** stable

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
All this mortar rounds dont show up in the arsenal... so if you add them to a supplybox per mod and then edit the box in eden... the mortar rounds are not shown because the arsenal dont know this rounds...
"ACE_1Rnd_82mm_Mo_HE",
"ACE_1Rnd_82mm_Mo_Smoke",
"ACE_1Rnd_82mm_Mo_Illum",

**Steps to reproduce:**
- get full arsenal
- try endless to get the mortar rounds

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

### PR DESCRIPTION
**Pull request by AACO**
**When merged this pull request will:**
- Add a `CfgMagazines` `type` to each of the ACE hand loaded mortar magazines, so they're view-able in the virtual arsenal, and virtual ammo boxes

Resolves #5592

Only concern is possible confusion for users not using ammo handling

How it looks in VA: https://i.imgur.com/KoRzRfu.png
Proof that it still loads properly (but please still test 😉 ): https://i.imgur.com/HqAW3UM.png

### CODE REVIEW

**Comment by AACO** [comment]
Doesn't work for cargo ammo storage (just normal virtual arsenal), will investigate further and reopen with a better solution (if found)

**Comment by AACO** [comment]
Yeah, due to the way the ammo boxes component is built, magazines/items can't be added unless they're public scoped, so I don't think there's a good fix for this (outside extending the ammobox scripting, which I for sure don't want to do)

**Comment by jonpas** [comment]
But those are public scoped.

**Comment by AACO** [comment]
@jonpas a magazine of a public scoped gun, it's really rough to add anything to this without adding a legit gun or misc item
```SQF
_types = [
			["AssaultRifle","Shotgun","Rifle","SubmachineGun"],
			["MachineGun"],
			["SniperRifle"],
			["Launcher","MissileLauncher","RocketLauncher"],
			["Handgun"],
			["UnknownWeapon"],
			["AccessoryMuzzle","AccessoryPointer","AccessorySights","AccessoryBipod"],
			["Uniform"],
			["Vest"],
			["Backpack"],
			["Headgear","Glasses"],
			["Binocular","Compass","FirstAidKit","GPS","LaserDesignator","Map","Medikit","MineDetector","NVGoggles","Radio","Toolkit","Watch","UAVTerminal"]
		];
		_typeMagazine = _types find "Magazine";

		if (isnil "AmmoBox_list") then {
			_list = [[],[],[],[],[],[],[],[],[],[],[],[]];

			//--- Weapons, magazines and items
			_magazines = []; //--- Store magazines in an array and mark duplicates, so nthey don't appear in the list of all items
			{
				_weaponCfg = _x;
				_weapon = tolower configname _weaponCfg;
				_weaponType = (_weapon call bis_fnc_itemType);
				_weaponTypeCategory = _weaponType select 0;
				_weaponTypeSpecific = _weaponType select 1;
				_weaponTypeID = -1;
				{
					if (_weaponTypeSpecific in _x) exitwith {_weaponTypeID = _foreachindex;};
				} foreach _types;
				//_weaponTypeID = _types find (_weaponType select 0);
				if (_weaponTypeCategory != "VehicleWeapon" && _weaponTypeID >= 0) then {
					//_weaponCfg = configfile >> "cfgweapons" >> _weapon;
					_weaponPublic = getnumber (_weaponCfg >> "scope") == 2;
					_listType = _list select _weaponTypeID;
					if (_weaponPublic) then {
						_displayName = gettext (_weaponCfg >> "displayName");
						_picture = gettext (_weaponCfg >> "picture");
						{
							_item = gettext (_x >> "item");
							_itemName = gettext (configfile >> "cfgweapons" >> _item >> "displayName");
							_displayName = _displayName + " + " + _itemName;
						} foreach ((_weaponCfg >> "linkeditems") call bis_fnc_returnchildren);
						_type = if (getnumber (configfile >> "cfgweapons" >> _weapon >> "type") in [4096,131072]) then {1} else {0};
						_listType pushback [_displayName,_weapon,_picture,_type,false];
					};
					//--- Add magazines compatible with the weapon
					if (_weaponPublic || _weapon in ["throw","put"]) then {
						{
							_muzzle = if (_x == "this") then {_weaponCfg} else {_weaponCfg >> _x};
							{
								_mag = tolower _x;
								if ({(_x select 1) == _mag} count _listType == 0) then {
									_magCfg = configfile >> "cfgmagazines" >> _mag;
									if (getnumber (_magCfg >> "scope") == 2) then {
										_displayName = gettext (_magCfg >> "displayName");
										_picture = gettext (_magCfg >> "picture");
										_listType pushback [_displayName,_mag,_picture,2,_mag in _magazines];
										_magazines pushback _mag;
									};
								};
							} foreach getarray (_muzzle >> "magazines");
						} foreach getarray (_weaponCfg >> "muzzles");
					};
				};
			} foreach configproperties [configfile >> "cfgweapons","isclass _x"];

			//--- Backpacks
			{
				_weaponCfg = _x;
				_weapon = tolower configname _weaponCfg;
				_weaponType = _weapon call bis_fnc_itemType;
				_weaponTypeSpecific = _weaponType select 1;
				_weaponTypeID = -1;
				{
					if (_weaponTypeSpecific in _x) exitwith {_weaponTypeID = _foreachindex;};
				} foreach _types;
				//_weaponTypeID = _types find (_weaponType select 0);
				if (_weaponTypeID >= 0) then {
					//_weaponCfg = configfile >> "cfgvehicles" >> _weapon;
					if (getnumber (_weaponCfg >> "scope") == 2) then {
						_displayName = gettext (_weaponCfg >> "displayName");
						_picture = gettext (_weaponCfg >> "picture");
						_listType = _list select _weaponTypeID;
						_listType pushback [_displayName,_weapon,_picture,3,false];
					};
				};
			} foreach configproperties [configfile >> "cfgvehicles","isclass _x"];

			//--- Glasses
			{
				_weaponCfg = _x;
				_weapon = tolower configname _weaponCfg;
				if (getnumber (_weaponCfg >> "scope") == 2) then {
					_displayName = gettext (_weaponCfg >> "displayName");
					_picture = gettext (_weaponCfg >> "picture");
					_listType = _list select 10;
					_listType pushback [_displayName,_weapon,_picture,3,false];
				};
			} foreach configproperties [configfile >> "cfgglasses","isclass _x"];

			//--- Sort
			{_x sort true;} foreach _list;

			AmmoBox_list = _list;
		};
```

**Comment by PabstMirror** [comment]
```
class CfgWeapons {
    class ace_dumGun {
        scope = 2;
        magazines[]={"ace_mortarShell", "ace_spareBarrel"};
        displayName = "zzz - ACE dummy Gun (do not use)";
```
?

**Comment by AACO** [comment]
@PabstMirror that'd 100% work, but seems too hacky/unintended fallout

**Comment by commy2** [comment]
>If the magazine config type is set to magazine (multiple of 256) it should show up in the arsenal, I'll test it out and try to create a PR for this.

This was a very optimistic assumption.
Just make these CfgWeapons and use CBA_miscItem as base class. Might need some rewriting of some scripts and ammo box configs.

**Comment by AACO** [comment]
It works fine for virtual arsenal, and I've used it in the past. The problem was with the crate systems, which uses vastly different logic.

**Comment by shukari** [comment]
Any more progress here? Issue #5592 is still there.

**Pull request closed without merging**
