### PR TITLE
Medical GUI - Increase Medical Menu side panel height

### PR DESCRIPTION
**Pull request by LinkIsGrim**
**When merged this pull request will:**
- Title.

Before:

After:

### IMPORTANT

- [ ] If the contribution affects [the documentation](https://github.com/acemod/ACE3/tree/master/docs), please include your changes in this pull request so the documentation will appear on the [website](https://ace3.acemod.org/).
- [x] [Development Guidelines](https://ace3.acemod.org/wiki/development/) are read, understood and applied.
- [x] Title of this PR uses our standard template `Component - Add|Fix|Improve|Change|Make|Remove {changes}`.

### CODE REVIEW

**Comment by LinkIsGrim** [comment]
CHANGED:
in changelog

/shrug

**Comment by jonpas** [comment]
It's an improvement anyways.

**Review by PabstMirror — APPROVED** [review]

**Comment by LinkIsGrim** [comment]
Moving it up was intentional.

**Comment by PabstMirror** [comment]
3rd is more symmetrical to my eye but it's not a big deal

**Pull request merged**
