### PR TITLE
Wire cutters sound effect

### PR DESCRIPTION
**Pull request by PabstMirror**
Changes wirecutters sound effect from that powersaw to a manual wire clipper.
Also makes it a playSound3d (10m range) so your teammates can tell what you're doing and for tvt game-play.

### CODE REVIEW

**Comment by esteldunedain** [comment]
:+1:

**Comment by jaynus** [comment]
How loud is it 10m away? That's a little far if it's full volume

**Comment by esteldunedain** [comment]
> How loud is it 10m away? That's a little far if it's full volume

I think that 10m is the max range; AFAIK playSound3D drops off from full volume at range 0 to zero volume at max range.

**Comment by commy2** [comment]
Much better.

Two points:
- ACE_Wirecutter_sound is unused
- ACE_Wirecutter_sound class has the CfgSounds setup from A2. The max range is missing! This won't work in A3 like that. (Take a look at common for an example)

**Comment by licht-im-Norden87** [comment]
I think 10m are ok. Imagine a silent situation where  someone is cutting a fence. Would be as loud as hell.

**Comment by commy2** [comment]
:+1: for merge

**Pull request merged**
