### PR TITLE
Changed hellfire interaction check & added N variant

### PR DESCRIPTION
**Pull request by tbeswick96**
**When merged this pull request will:**
- Change the check in the interaction condition to check for `ace_hellfire_enabled` config value instead of just the raw `ace_hellfire_launcher` weapon.
- This allows other launchers to be made and be compatible (for example, N-variant hellfires)
- Added November (Thermobaric) hellfire ammo, magazines, and weapon. (https://en.wikipedia.org/wiki/AGM-114_Hellfire#Variants) Have used the settings committed for some time with no balance issue. Not as good against tanks, better against infantry and bunkers etc.

### CODE REVIEW

**Comment by tbeswick96** [comment]
I don't think the `[ACE]` in the naming of magazines etc such as `AGM-114K [ACE]` needs to be there really. Just extra text with no real meaning.

**Comment by PabstMirror** [comment]
Here is another mod's pylon loadout which has their own hellfires, adding the `[ACE]` makes it clear which system you will get.

image

**Comment by tbeswick96** [comment]
@PabstMirror Gotcha makes sense

**Comment by tbeswick96** [comment]
No problem :)

**Pull request merged**
