### PR TITLE
mk6mortar and missing entries

### PR DESCRIPTION
**Pull request by alganthe**
- mk6 mortar doc added
- apl doc added
- classnames fixed (forgot an entry)

### CODE REVIEW

**Comment by bux578** [comment]
Could you add some text to the descriptions in the header. That would be awesome :)

**Comment by alganthe** [comment]
done

**Comment by bux578** [comment]
apl ... classnames ... :smile:

**Comment by alganthe** [comment]
oh right i'll also update the mortar instructions with crosswind enabled

**Comment by alganthe** [comment]
UPDATE: added a guide for using the table with crosswinds enabled and descriptions for what bux pointed out

**Comment by Glowbal** [comment]
Is this ready and correct?

**Comment by PabstMirror** [comment]
Few things I might want to add, but it is a fantatic start, thank you for the work.

**Pull request merged**
