### PR TITLE
Remove FFAA Compatability

### PR DESCRIPTION
**Pull request by Glowbal**
Compatability mod gives to many build errors and contains references to external files. Should not be part of ACE3.

Main reason is the `Extended_Eventhandlers.hpp` file.

### CODE REVIEW

**Comment by bux578** [comment]
@FFAAMOD

**Comment by FFAAMOD** [comment]
Yes I see. It's supposed to contain references to external files as some _init of some vehicles call to several scripts inside FFAA MOD. I don't know how to handle this situation so I inmediately uploaded the ffaa comp in our repository so ffaa dev member can test this, release it in a future and take out this ffaa comp from ACE3 repo.

**Comment by jonpas** [comment]
It is of course preferable to have it on your side, but we don't mind it as an optional. Of course, for that it has to be buildable, we'll just revert remove it for now, feel free to try to fix it (it has to build with `make.py`) and PR again if you want to have it in ACE3 repo.

**Comment by FFAAMOD** [comment]
Alright.

**Comment by Glowbal** [comment]
Thanks @FFAAMOD. Let us know if you need anything to get that compatability working fully.

For now, we are going to revert the compatability pbo.

**Pull request merged**
