### PR TITLE
ACE clipboard extension to bypass clipboard limit of arma. Close #991

### LINKED ISSUE #991: Export to clipboard cuts text after 8614 chars

### PR DESCRIPTION
**Pull request by jaynus**
An extension which simply provides direct access to the windows clipboard, circumventing the arma3 size limitations to the clipboard.

### CODE REVIEW

**Comment by esteldunedain** [comment]
Should be ready. Needs testing.

**Comment by esteldunedain** [comment]
100% less crashes now.

**Comment by commy2** [comment]
:+1:

**Comment by KoffeinFlummi** [comment]
But what about linux?

**Comment by commy2** [comment]
:Kappa:

**Comment by jaynus** [comment]
RVExtension has the 4096 byte limit on function messages sent to it. Working on spliting.

**Comment by jaynus** [comment]
Tested, working.

**Pull request merged**
