### PR TITLE
Only use addActionEventHandler when needed

### PR DESCRIPTION
**Pull request by PabstMirror**
- Only install addActionEventHandler when the interaction menu is
actually open
- Less SQF running all the time (action's conditional was checked each frame, even if menu closed)
- it should help with issue #4066

### CODE REVIEW

**Comment by esteldunedain** [comment]
I think we only need to add the EH if `GVAR(useCursorMenu) == false`

**Comment by esteldunedain** [comment]
`ace_common_fnc_addActionEventHandler` has a fairly complex compile in there. It's probably not that bad to run it every time the IM is opened, but it might increase the lag spike slightly.  Theoretically that compiled code could be cached and reused, but I'm not sure if it's worth it.

**Comment by commy2** [comment]
I don't like this method. We shouldn't change our ways just because a random mission removes all actions. :-1:

**Comment by PabstMirror** [comment]
The compile is 0.0292 ms, so shouldn't be a problem.

I had been wanting to do this for a while for the performance improvements, the fact that this also fixes another mod's compatibility problem is just a side bonus.

**Comment by esteldunedain** [comment]
> The compile is 0.0292 ms, so shouldn't be a problem.

Perfect, never mind then

**Comment by PabstMirror** [comment]
Not critical for 3.6.1, will bump to 3.7

**Pull request closed without merging**
