### PR TITLE
Map Tools - Add Vernier Scale and Improve resolution

### PR DESCRIPTION
**Pull request by LorenLuke**
**When merged this pull request will:**
- Adds a Vernier scale (4 mils) to the maptools, allowing visual use for slightly more accurate reading of milliradian directions.

### CODE REVIEW

**Comment by veteran29** [comment]
Needs to make sure we're using only the highest mip of the texture to prevent blurry maptools on lower texture settings. (https://github.com/arma3/MipMapTool)

**Comment by bux** [comment]
Could you add an example image to the description please :)

**Comment by LorenLuke** [comment]
Worth noting, the actual point of rotation is ever so slightly offset, so sometimes the scale will not align exactly as it should, but it still will be read within +/-3 mils or so. Which is no more than 12 meters error at 4km, and still aligns to compass fine.

Center section (basically identical to both maptools):
Center
Large map tool oriented north:
Large
Small maptool oriented north:
Small
5468:

3542:

1652:

4748:

**Comment by bux** [comment]
Could you try using another color than cyan. Imho it is hard to read, especially on the gray background.

**Comment by LorenLuke** [comment]
@bux 
> Could you try using another color than cyan. Imho it is hard to read, especially on the gray background.

Are you referring to the numbers or the lines, or both? I personally fine the lines fine, and would like to keep them that color, as it contrasts to the white, the black, and the red, but if you want to have the numbers changed, I could do that easily (my only concern with those small numbers being black is associating them with the cyan lines). 

If you have another color you believe to work better for either the numbers or the lines, I'm more than willing to hear what you have in mind.

**Comment by Drofseh** [comment]
I really don't like the cyan colour either. I think we should stay with red or black, probably red in this case.

**Comment by LorenLuke** [comment]
Not committed at time of posting, but... here's it in red, and not on the VR map.

1874:

2686:

5318:

**Comment by TymoteuszKazubski** [comment]
Red looks way more readable IMHO.

**Comment by LorenLuke** [comment]
Ready in red.

**Comment by dedmen** [comment]
The texture is just 2k, I think it might make sense here to go 4k for this?

**Comment by LorenLuke** [comment]
@dedmen 
> 4k
While I don't disagree, my general workflow has been 
+ paa to png
+ edit in photoshop
+ save as interlaced png
+ img to paa

Because of this I didn't want to mess with scaling at all in case it threw it off, and am unsure how to go about making a higher resolution image while guaranteeing the whole thing isn't just going to be twice as big in scale as the original.

**Review by LinkIsGrim — APPROVED** [review]

**Pull request merged**
