### PR TITLE
CheckPBOs in ACE_Settings

### PR DESCRIPTION
**Pull request by jonpas**
#1123

### CODE REVIEW

**Comment by Glowbal** [comment]
This looks good. I will look at it in more detail later today.

**Comment by esteldunedain** [comment]
If the settings command to do so, the pbo checking code should be run after postInit without needing the module.

**Comment by jonpas** [comment]
I think that requires some restructuring if I understood what you mean (running check version without needed the module placed)?

**Comment by esteldunedain** [comment]
Yes. I think it's simply a matter of installing a "SettingsInitialized" even handler that runs the module code if the correct settings are set. That routine and the module should set some flag to avoid checking it twice if the module is present.

**Comment by ViperMaul** [comment]
@jonpas, @Glowbal 
I would really like to see this one completed for 3.1.0 in the next 3 days if possible.

**Comment by jonpas** [comment]
I will have time to work on it tomorrow or Thursday. I don't particularly get @esteldunedain 's comment though, I have to dive into the code way more. :grin:

**Comment by jonpas** [comment]
@esteldunedain I am actually confused by your statement, `SettingsInitialized` hasn't been added yet as far as I can see, so what exactly do you want me to do here?

**Comment by esteldunedain** [comment]
> @esteldunedain I am actually confused by your statement, SettingsInitialized hasn't been added yet as far as I can see, so what exactly do you want me to do here?

It was merged today, so it should be gtg

**Comment by jonpas** [comment]
Yep yep, will work on it today or tomorrow. Thanks!

**Comment by jonpas** [comment]
I did what @esteldunedain wanted or at least I think I did. I streamlined module settings loading and then calling the actual function from withing `SettingsInitialized`, it all works locally it seems but it should probably be tested on dedicated as well, if someone can do that it would be greatly appreciated.

**Comment by Glowbal** [comment]
This is now always checking pbos, no?

Script looks ok from that I can tell, just need someone to test this on a dedicated server with JIP, like @jonpas said.

**Comment by jonpas** [comment]
AFAIK it will now always check ACE3 PBOs but only display warnings, if `checkPBOsCheckAll` is set to true then it will check all.

Is it by default that when no module is present it doesn't check at all? TBH I'd prefer it always checks, it gets rid of a lot of wrong testing setups where players have different ACE3 versions installed.

Code itself has to be cleaned up at some point as well though.

**Comment by Glowbal** [comment]
Thank you @jonpas

**Comment by jonpas** [comment]
Thank you!

**Pull request merged**
