### PR TITLE
Medical Statemachine  - Add var check to disable `preventDeathFlinch`

### PR DESCRIPTION
**Pull request by PabstMirror**
mods/missions can disable with `ace_medical_statemachine_preventDeathFlinch = false`

### CODE REVIEW

**Review by johnb432 — CHANGES_REQUESTED** [review]
Can we get documentation on this?

**Comment by johnb432** [comment]
> You want _another_ medical setting for something only scripters will use?

I like giving options.

**Comment by Drofseh** [comment]
I don't think we need this at all tbh

**Comment by PabstMirror** [comment]
never heard back why this was needed, closing but we can reopen if there is a reason for it

**Pull request closed without merging**
