### PR TITLE
To be deleted

### PR DESCRIPTION
**Pull request by 11RDP-LoupVert**
Adjusted Russian ammo
Figures are from "Munitions militaires russes : Pour armes légères
1868-2007" book by Philippe Regenstreif  (ISBN-13: 978-2703003137).

**When merged this pull request will:**
- change a few figures

### CODE REVIEW

**Comment by bux** [comment]
@11RDP-LoupVert You now added french translations to this PR.

It would be better if you could separate them in two PRs.

**Comment by 11RDP-LoupVert** [comment]
Got it bux, thank you. Still finding my way with Git.

**Comment by 11RDP-LoupVert** [comment]
Superseded by https://github.com/acemod/ACE3/pull/5043

**Comment by commy2** [comment]
Can't delete Github Issues or Pull Requests, but can close them.

**Pull request closed without merging**
