### PR TITLE
Nightvision - Increase max amount of IR rays to 64

### PR DESCRIPTION
**Pull request by Neviothr**
**When merged this pull request will:**
- Increase the maximum amount of rendered IR rays to 64, as mentioned [here](https://youtu.be/sOrUP0Rq6Jg?t=498).

### CODE REVIEW

**Comment by veteran29** [comment]
What happens to dynamic lights if there's 64 rays? Will they be disabled?

**Comment by Neviothr** [comment]
I haven't noticed anything different with dynamic lights. Are they supposed to be affected by this?

**Comment by BaerMitUmlaut** [comment]
Lasers are not light sources, they're objects with an emissive material (which means they will always be drawn at full brightness and not be affected by shadows, they do not emit light). They should not affect light sources at all.

**Comment by dedmen** [comment]
> They should not affect light sources at all.

Yes they don't.
Also for reference the default number of rays is 24.

**Comment by Neviothr** [comment]
> > They should not affect light sources at all.
> 
> Yes they don't.
> Also for reference the default number of rays is 24.

Added as a comment just in case.

**Pull request merged**
