### PR TITLE
Add action to detonate all explosives on a detonator

### LINKED ISSUE #2108: Simultaneous explosive detonation
Was playing with mode for a while. Found quite annoying thing about explosives - it is not possible to detonate several charges simultaneously with one player. It ruins ambushes sometimes... =(
Is it a realism feature? It would be nice if in next version there would be a menu that will pop-up on charge setup so you can assign it to different detonation groups.
The best idea is just to have a popup window after chosing detonator where you can choose radio channel used for detonation and then to have possibility to choose detonator channel.

Also have a small question about Claymore mine... is it for realism purposes that auto detonation by walking enemies is deleted?

### PR DESCRIPTION
**Pull request by VKing6**
This PR will add an action to the detonator menu to detonate all explosives associated with it.
Example can be seen [here](http://i.imgur.com/oGUEKTl.jpg?1)

This fixes #2108 and will probably deprecate #1219.

### CODE REVIEW

**Comment by commy2** [comment]
Aren't all these `ACE_player` supposed to be `_unit`?

**Comment by VKing6** [comment]
Maybe? I honestly have no idea

**Comment by CorruptedHeart** [comment]
The `ACE_Player` should probably be `_unit` although for the UI part of explosives it can only ever really be done by the player. However, it was designed in such a way that it doesn't necessarily have to be.

**Comment by BaerMitUmlaut** [comment]
In what case would `_unit` not be the same as `ACE_player`? I mean we're talking about the *self*-interaction menu.

**Comment by CorruptedHeart** [comment]
Well if there ever becomes a case where you'd want to detonate someone's explosives or something.

**Comment by BaerMitUmlaut** [comment]
The function called by the self-interaction menu still receives `ACE_player` as a param. Or am I misunderstanding something here?

**Comment by Glowbal** [comment]
If it does, all code in this function should probably use `_unit`. No need to provide a unit as the input parameters and still use `ACE_player` in the code.

**Comment by commy2** [comment]
Not using ACE_player inside functions also makes it easier to eventually port them to AI. That's why I'm asking.

**Comment by VKing6** [comment]
At first test there doesn't appear to be any problems changing `ACE_Player` to `_unit`.

**Comment by jonpas** [comment]
Do it then. :)

**Comment by rlex** [comment]
Thanks for that feature, i know some of my squadmates asked for it.
Note on translation:
"Подрыв Все" is a bit wrong in russian. "Подрыв всех" is better, but still sounds a bit weird.

**Comment by esteldunedain** [comment]
:+1: to merge

**Comment by VKing6** [comment]
> "Подрыв Все" is a bit wrong in russian. "Подрыв всех" is better, but still sounds a bit weird.
I'll change it. If you can think of a better phrase feel free to suggest it.

**Comment by Glowbal** [comment]
Thanks @VKing6

**Pull request merged**
