### PR TITLE
Convert to LF line endings gh-pages

### PR DESCRIPTION
**Pull request by jonpas**
**When merged this pull request will:**
- Same as #3840 but for `gh-pages`

### CODE REVIEW

**Comment by bux578** [comment]
https://github.com/acemod/ACE3/blob/gh-pages/src/.editorconfig

**Comment by jonpas** [comment]
Why exactly is that file in there in the first place? It has same settings as the one in root.

**Comment by jonpas** [comment]
@bux578 ^ ?

**Comment by bux578** [comment]
because reasons?

**Comment by jonpas** [comment]
So it can be removed? :o

**Pull request merged**
