### PR TITLE
Improve - medic param to remaining treatment EHs

### PR DESCRIPTION
**Pull request by tuntematonjr**
**When merged this pull request will:**
- add medic parameter to remaining local treatment events

### IMPORTANT

- If the contribution affects [the documentation](https://github.com/acemod/ACE3/tree/master/docs), please include your changes in this pull request so the documentation will appear on the [website](https://ace3.acemod.org/).
- [Development Guidelines](https://ace3.acemod.org/wiki/development/) are read, understood and applied.
- Title of this PR uses our standard template `Component - Add|Fix|Improve|Change|Make|Remove {changes}`.

### CODE REVIEW

**Comment by tuntematonjr** [comment]
it seems that these are not in https://ace3.acemod.org/wiki/framework/events-framework#22-medical-ace_medical
should those be added there?

**Comment by PabstMirror** [comment]
generally 
- `treatment_fnc_x` handles the logging based on the medic and then sends event to 
- `treatment_fnc_xLocal` which just does the actual healing

So I'm not sure why is this needed?

**Comment by tuntematonjr** [comment]
Some use the local event for patients to display message that someone is healing you, this would allow just showing the medics name there.
I was trying to do that and noticed that some of the local evets did not have the medic param transfered.

But yeah, it can also be done from the medics event or `ace_treatmentStarted`, `ace_treatmentSucceded`, `ace_treatmentFailed`.
So if you think this is too minor thing, this can be closed.

**Comment by PabstMirror** [comment]
sorry this got delayed,
do you still have a use for this? I know your excellent TunCon mod already updated

if we use this, we'll have to add something for medical_ai because they also call these same events

**Comment by tuntematonjr** [comment]
Hey, no problem.
Yeah, i don't personally need these anymore, so if this needs more changes, i think it is not worth it 👍

**Pull request closed without merging**
