### PR TITLE
ace_map: More realistic flashlight glow + minor fix

### PR DESCRIPTION
**Pull request by voiperr**
**When merged this pull request will:**
- Fix https://github.com/acemod/ACE3/issues/3605
- Change external flashlight glow object from a sprite effect (infinite visibility) to a light source (~500m visibility; depends on conditions)
- Glow appears on unit's neck/chest, so you can no longer see it from behind or, when he's prone, from above
- Glow objects are now detached before being deleted, preventing dozens (potentially hundreds) of duplicate objNulls attached to players

**Preview Images**

5m old: http://i.imgur.com/0hEeKYq.png [plain] http://i.imgur.com/GeCLSQr.png [nvg]
5m new: http://i.imgur.com/YRHl50J.png [plain] http://i.imgur.com/kSa7AMP.png [nvg]
100m old: http://i.imgur.com/C1bKiJE.png [plain] http://i.imgur.com/rqun1L1.png [nvg]
100m new: http://i.imgur.com/jtFNK7l.png [plain] http://i.imgur.com/BRlV6nA.png [nvg]
300m old: http://i.imgur.com/1Wsu9CX.png [plain] http://i.imgur.com/fHJTvjC.png [nvg]
300m new: http://i.imgur.com/zAZR288.png [plain] http://i.imgur.com/ZBvHJEP.png [nvg]

### CODE REVIEW

**Comment by jonpas** [comment]
Great work!

Spaces before and after `=`.

**Comment by esteldunedain** [comment]
For reference this is the original flashlight PR from @voiperr #1816 

The PR looks perfectly fine, and the effect looks really much better

I'm assigning this back to you @jonpas.

**Comment by bux578** [comment]
Good job.

**Comment by jonpas** [comment]
@voiperr All done? You got 12 hearts, I'd say this is good for merge. :smile:

**Comment by voiperr** [comment]
It's good to go, thanks.

**Pull request merged**
