### PR TITLE
fix dagr not showing after aiming

### PR DESCRIPTION
**Pull request by SzwedzikPL**
Fix for dagr not showing after aiming (cameraView gunner)

### CODE REVIEW

**Comment by ulteq** [comment]
The DAGR is currently the only device which is hidden while you aim.

I'd say we either remove the `cameraView` check completely, or make all devices behave like that.

I prefer the former.

**Comment by SzwedzikPL** [comment]
> The DAGR is currently the only device which is hidden while you aim.

MicroDAGR behave is ok :)

**Comment by SzwedzikPL** [comment]
Merged with https://github.com/acemod/ACE3/pull/1595 :)

**Comment by bux578** [comment]
> I'd say we either remove the cameraView check completely, or make all devices behave like that.

the latter :)

**Pull request closed without merging**
