### PR TITLE
fix Issue with forEach Loops and deleteAt Index

### PR DESCRIPTION
**Pull request by jokoho48**

### CODE REVIEW

**Comment by jonpas** [comment]
First SQF Validator fix!? :D

**Comment by jokoho48** [comment]
what ou mean? you mean that we must integrate this in the SQF Validator?

**Comment by jonpas** [comment]
No, only that it found an error, which is good. :)

**Comment by jokoho48** [comment]
aha ok yeah i miss click befor and delete a bracket :D

**Comment by SilentSpike** [comment]
:cry: Should I obliterate it from the branch history or do you want to revert it in a new commit?

**Comment by jokoho48** [comment]
sorry i dont have much time currently feel free to do :D

**Comment by SilentSpike** [comment]
I believe this issue is also present in `addons/huntir/functions/fnc_cam.sqf`

**Comment by jokoho48** [comment]
yeah posible

**Comment by SilentSpike** [comment]
That file could use a bit of a minor re-write just to make it more readable anyway. Might be best to handle it in another PR

**Comment by Glowbal** [comment]
Is this done?

**Comment by SilentSpike** [comment]
I suggest we merge this and handle the huntIR issue elsewhere

**Pull request merged**
