### PR TITLE
Nametags - Use EyePos of target / windows

### LINKED ISSUE #1280: Nametags: Intersect position is not eye to eye
On the infrequent instance you cannot see a person's face, but can see their body, you can ID them perfectly fine. Ideally, you have to see their face to ID them.

### PR DESCRIPTION
**Pull request by PabstMirror**
Should fix #1280 and #1282

Uses eyePos of target
Also it doesn't ignore `vehicle ACE_player` for the LOS check,  So units need to be visable from a window.

I was playing around with checking face direction, something like
```
_faceVectorToCamera = _targetEyePosASL vectorFromTo _pos;
_faceAngle = acos (_faceVectorToCamera vectorDotProduct (eyeDirection _target));
systemChat format ["%1 - %2", _target, _faceAngle];
if (_faceAngle > 100) exitWith {};
```

So nametags won't show if someone has their back to you, but I'm not sure if we want to go that far?

### CODE REVIEW

**Comment by bux578** [comment]
> So nametags won't show if someone has their back to you, but I'm not sure if we want to go that far?

I like the idea but - i guess - IRL you could differentiate your fellow squad members by their distinctive body shapes, postures, way of walking/moving, gestures.

**Comment by VKing6** [comment]
Let it be all-round. While a neat idea there are too many variables IMO to make it work well in game.

There should be a check for lighting conditions, though, so you can't see the name tag from further away than you can see the actual player. Ref #1200.

**Comment by bux578** [comment]
^ agree

ShackTac Nametags implements something similar

**Comment by jonpas** [comment]
A check for light and then simply changing fade coefficient correspondingly should do the magic.

**Comment by esteldunedain** [comment]
> I like the idea, but - i guess - IRL you could differentiate your fellow squad members by their distinctive body shapes, postures, way of walking/moving, gestures.

Yes, exactly.

**Comment by jaynus** [comment]
I think make it a setting (for face vs. body) - and implement the lighting and this PR would be gtg.

**Pull request merged**
