### PR TITLE
ATragMX Documentation (Wiki)

### PR DESCRIPTION
**Pull request by GanX44**
Hello ACE Team

Thank you for a great mod. I hope that i can contribute by adding some documentation for the ATragMX in the Wiki. I hope that it is up to your standards, if not then please let me know so i can fix it.

**When merged this pull request will:**
1. Add documentation to atragmx.md
2. Add pictures used in the atragmx.md to "/docs/img/wiki/feature/"
3. Add my name to AUTHORS.txt

-- 
Kind Regards

Sergeant Major - GanX
Server Administrator
The Art of Warfare
Arma III Division
2nd Battalion

### CODE REVIEW

**Comment by GanX44** [comment]
Hi @jonpas

I know that i am going to sound rude now which is not my intent at all, but can i please get an answer on if you plan to use this or not?
I know that J3aLeiNe is working on the ATragMX wiki as well, but what he is writing is a Tutorial and not a wiki entry. Its examples on how to do stuff not explanations of the features.

The above pull is a structured run through of all the ATragMX functions, it is written and setup as some of the already existing wiki pages to follow a certain standard.

Can you please read through both of these requests and decide which one you would like to implement? I consider mine to be finished, so i do not plan on adding anything else. (Unless new features become available)

**Comment by jonpas** [comment]
Yes, I have merged J3aLeiNe's PR. You can add your stuff on top, however it was brought to my attention that what you wrote is not with enabled Advanced Ballistics.

Wiki written as a tutorial/example is no issue if it makes the user understand it better.

**Comment by GanX44** [comment]
@jonpas Hello again

Sorry for the wait, i was away on a business trip. My apologies for marking features as not being in use. I took the screenshots in the virtual arsenal and was unaware that some menu features in the ATragMX would be unavailable due to Advanced ballistics not being enabled in that state.
I do however need you to clear something up for me. I have added "Muz Vel Table", "Drag Coef Table" and "Truing Drop". However i can still not access "Accuracy 1st" and "Gun Note". Can i assume that these features are not implemented in game since i cannot access them in the ATragMX?

Everything should otherwise be in order. I have rearranged the menu points so they fit with the recently added documentation and i have removed my own Example at the end since the ones provided in the current documentation where pretty good.

Please let me know if you need me to change anything else. :)

**Comment by ulteq** [comment]
> However i can still not access "Accuracy 1st" and "Gun Note". Can i assume that these features are not implemented in game since i cannot access them in the ATragMX?
Correct, they're not implemented.

**Comment by PabstMirror** [comment]
Closed for https://github.com/acemod/ACE3/pull/4982

**Pull request closed without merging**
