### PR TITLE
Show Version / HTML Git Version on main menu

### PR DESCRIPTION
**Pull request by PabstMirror**
Shows current version
TODO: will show current git release version from a maintained site (right now just a demo of ace3mod.com)

untitled

### CODE REVIEW

**Comment by jaynus** [comment]
:thumbsup:

**Comment by jonpas** [comment]
Pretty sleek! :+1: 

Can do actual news through that then, since it gets pulled from a page, or anything else you want members to know.

**Comment by SzwedzikPL** [comment]
I think its better idea to create buttons to switch between ace & a3 info
like that: http://i.imgur.com/5cRMTBA.jpg

Looks bit nicer and have all functions :)

**Comment by jaynus** [comment]
> I think its better idea to create buttons to switch between ace & a3 info

No one will ever see it then; we would rather sacrifice cleanliness to avoid confusion.

**Comment by SzwedzikPL** [comment]
I see

**Comment by PabstMirror** [comment]
If someone wants to do some web magic and dynamically pull the version from git, otherwise we can just do a simple static webpage that we update.

image

For ARMA - HTML just keep it simple
think of it as a very very old version of Internet Explorer :smile:

html:
```
<html>
<head>
<title>ACE3</title>
</head>
<body>
<h1>Latest: 3.0.1</h1>
<h1><a href="https://github.com/acemod/ACE3/releases">Download</a></h1>
<p><a href="http://ace3mod.com/wiki/user/how-to-report-an-issue.html">Report An Issue</a></p>
</body>
</html>
```

**Comment by jonpas** [comment]
https://github.com/acemod/ACE3/blob/gh-pages/index.html#L47 uses hard-coded as well, might be worth doing some git version fetching, but I have no idea how, so feel free to ignore this comment!

**Comment by bux578** [comment]
http://ace3mod.com/version.html

**Comment by Tourorist** [comment]
Since it's in the middle and not leading, could we perhaps not capitalize the indefinite article there, to read as follows instead:
* Report **a**n Issue

As per our general style for documentation.

**Comment by ViperMaul** [comment]
@bux578, looks good thanks!

**Comment by ViperMaul** [comment]
@PabstMirror 
I am bringing in comments from staff. 
* would it be possible to make that box a bit more small/discrete?
* Bottom right without the box maybe?
* Perhaps a mimimal button the size of ACE Options that pulsates when there is a version mismatch. When you click on the button it expands revealing the ACE News.

These thoughts are from from separate members. The theme shows that although there is value here we prefer not to be all up in your face. We do not necessarily want to steal all the real-estate on the main screen.

**Comment by jaynus** [comment]
Is there any reasoning behind any of that @vipermaul ? I'm actually of the exact opposite opinion on all that. I must have missed the discussion on that :p

**Comment by ViperMaul** [comment]
I've given you the only reason I can surmise when I interviewed them. And their reason enough for me. If you want a reason behind the reason will probably need to ask them yourself.

**Comment by jaynus** [comment]
Can anyone expand on what 'main menu real estate' we are stealing from anything? The only modifications I know which also do main menu overlays are RHS and TFR. TFR takes over the vanilla news menu and breaks it, so I don't see that as a conflict. 

I'm not very fond of going the "tiny little version in the corner" route, as most people will not notice is - we also need to remember, a lot of people use launchers/syncers for their game and do not actually even ever see the main menu that often. Therefore, this is a cursory super-easy-mode user change at most. That by itself would warrant being more visible at the main menu.

Last reason - We can add more debug functionality to this specific window via extensions. We can expand this to full debug dumps, configuration dumps, system reports, option configurations, auto-config, all sorts of fun stuff in the future. This would all warrant keeping it semi visible, and at least big enough to warrant a few buttons on it (plus the update information).

**Comment by ViperMaul** [comment]
The debug functionality should probably go into ACE Options or right underneath ACE Options.

**Comment by ulteq** [comment]
Can we enable it by default and add an ACE3 Option to hide it?

**Comment by PabstMirror** [comment]
Cut height in half and users can turn it off in options.
I can't find anyway to access the loaded html data to do version comparison (could do some cool things if we could parse live data from the web)

**Comment by esteldunedain** [comment]
Just wondering if this would look more elegant if we put the whole ACE box as-is *below* the Intel box.

Anyway, gj!

**Comment by ViperMaul** [comment]
@esteldunedain :+1:

**Comment by bux578** [comment]
> I can't find anyway to access the loaded html data to do version comparison

how about pulling another website that contains ONLY the version string?

**Comment by SzwedzikPL** [comment]
You can sent GET request by htmlLoad
```htmlLoad format["http://ace3mod.com/version.php?version=%1", _aceversion];```
and php script based on version will return text with or without warning about outdated mod.

**Comment by PabstMirror** [comment]
Bux the problem is reading the loaded data.  `ctrlText` doesn't work on rscHTML as far as I can tell.

**Comment by esteldunedain** [comment]
That looks much better IMO.

**Comment by bux578** [comment]
Could you try to add a little padding to box. (distance between border and text)

**Comment by ViperMaul** [comment]
After adding the padding
It finally gets a :+1:

**Pull request merged**
