### PR TITLE
runOnHover can now be CODE & SurgicalKits

### PR DESCRIPTION
**Pull request by GitHawk**
1)
Expanded render, compileMenu, compileMenuSelfAction so runOnHover can be CODE
e.g. runOnHover = QUOTE([] call DFUNC(myRunOnHoverCheck););
This allows more dynamic menus.

2)
- added SurgicalKit action to other body parts
- fixed vanilla damage in bandageLocal
- added ACE messge to CPRLocal informing about sucess
- added surgicalKit and surgicalKitLocal functions
- fixed some german translations
- added surgicalKit functions to preInit

### CODE REVIEW

**Comment by jaynus** [comment]
Edited title to include Surgical kits as there was code included for those as well. New hover code looks good, it caches appropriately so we aren't taking PFH compile overhead.

@esteldunedain @Glowbal

**Comment by GitHawk** [comment]
Yes, that was the other suitable option. And I didn't like it either.

**Comment by esteldunedain** [comment]
The runOnHover part seems fine. I first assumed it was neccesary for the surgical kit stuff, but it's not the case; it should have been a sepparate PR, but meh.

**Comment by GitHawk** [comment]
I forgot to push the surgicalKit stuff to a different branch - sry

**Comment by Glowbal** [comment]
Surgical kit will not go in. We have a different implementation for that which is (nearly) completed. #1392

Please remove it from this PR and @esteldunedain can asses if we will take the `runOnHover`.

**Comment by esteldunedain** [comment]
The run on hover stuff is basically a single commit. I can just cherry-pick it from this branch into master; no need for a separate PR.

**Comment by GitHawk** [comment]
@Glowbal My implementation follows the other stuff (e.g. bandage) and is complete.

**Comment by GitHawk** [comment]
@esteldunedain Have you cherry-picked my additions yet?
@Glowbal Please consider at least using my changes in bandageLocal as it will reset vanilla damage.

**Comment by GitHawk** [comment]
@esteldunedain I removed the medical stuff. Please merge, so I can continue develloping/debugging ACE.

**Comment by esteldunedain** [comment]
> @esteldunedain I removed the medical stuff. Please merge, so I can continue develloping/debugging ACE.

Thanks

**Pull request merged**
