### PR TITLE
Removed ability to interact with tactical ladder while climbing

### PR DESCRIPTION
**Pull request by jonpas**
You could pick up the ladder (and fall) or position it (and remain in climbing animation until you redeployed it). This fixes both.

### CODE REVIEW

**Comment by PabstMirror** [comment]
Can check via config:

`{((getNumber (configFile >> "CfgMovesMaleSdr" >> "States" >> (animationState _player) >> "onLadder")) == 0)}`

**Comment by jonpas** [comment]
@PabstMirror thanks!

**Comment by commy2** [comment]
The underlying issue is that you can interact on a ladder.
This will be fixed in https://github.com/acemod/ACE3/pull/2320

This PR can be closed I think.

**Comment by jonpas** [comment]
Replaced by #2320

**Pull request closed without merging**
