### PR TITLE
hide 1.71 mine detector actions

### PR DESCRIPTION
**Pull request by commy2**
**When merged this pull request will:**
- Alternative to #5147. Hide the actions instead.

### CODE REVIEW

**Comment by CorruptedHeart** [comment]
Will this not affect the new airplane UI stuff?

**Comment by jonpas** [comment]
As far as I understand this config, it will remove both left and right action menu entries, still allowing you to use them via keybinds, but that has a huge downside of those actions not being available inside vehicles (eg. airplanes) where they should be.

**Comment by commy2** [comment]
I thought these are for the mine detector. All they do is bring up that thing and I have the actions outside of vehicles.

**Comment by jonpas** [comment]
They are used for many things starting with new sensor stuff all the way to mine detectors. Thre are basically 2 screens you can select what you want displayed on.

**Comment by BlueNexus** [comment]
I strongly recommend not merging this, due to the fact that it will make accessing critical parts of the new plane UI difficult.

**Comment by jonpas** [comment]
Yeah, no worries, this won't get merged. :)

**Pull request closed without merging**
