### PR TITLE
Pass functions by reference to BI event handlers

### PR DESCRIPTION
**Pull request by mharis001**
**When merged this pull request will:**
- Pass functions by reference to `addEventHandler` and `addMissionEventHandler`
Should provide a slight performance improvement

### CODE REVIEW

**Comment by mharis001** [comment]
Also, the formatting on the [coding guidelines](https://ace3mod.com/wiki/development/coding-guidelines.html#73-event-driven) for this is weird

**Comment by 654wak654** [comment]
Isn't this what the `LINKFUNC` macro already does?

**Comment by dedmen** [comment]
https://github.com/acemod/ACE3/blob/81e02a73369d341ef21d0b8fc1ad9c62e1688f2e/addons/main/script_debug.hpp#L7-L15

**Comment by commy2** [comment]
Btw, `LINKFUNC()` should be changed to `{call FUNC()}`.

**Pull request merged**
