### PR TITLE
Add missing medical category to delayUnconCaptive

### PR DESCRIPTION
**Pull request by jonpas**
### When merged this pull request will:

1. Ref. title

### CODE REVIEW

**Comment by jokoho48** [comment]
@jonpas this is not a client setting and dont need a category

**Comment by PabstMirror** [comment]
Categories should still work on the config exporter

**Comment by jonpas** [comment]
What @PabstMirror said, descriptions should be there as well, but not that important and I don't know what exactly it does.

**Comment by Glowbal** [comment]
All settings should have a category. They are used within the config export browser, same as for regular client settings.

:+1: @jonpas

**Pull request merged**
