### PR TITLE
Fix 1.60 UBC (slingloads)

### PR DESCRIPTION
**Pull request by PabstMirror**
**When merged this pull request will:**
- Fix 1.60 UBC (slingloads)

### CODE REVIEW

**Comment by commy2** [comment]
This also improves the positioning of `GVAR(hooks)[]` from the refuel module, right?

**Comment by PabstMirror** [comment]
I noticed that too, but it's just git diff's being weird:

Compare 
current: https://github.com/acemod/ACE3/blob/master/addons/refuel/CfgVehicles.hpp
new: https://github.com/acemod/ACE3/blob/598c3dc1812e54a36ccb2043705bab7200f99917/addons/refuel/CfgVehicles.hpp

**Comment by jonpas** [comment]
It's because lines were swapped out and it doesn't see it as connected.

**Comment by commy2** [comment]
roger

**Pull request merged**
