### PR TITLE
IED pressure plates

### PR DESCRIPTION
**Pull request by jonpas**
#1191 

Thanks to @legman for his config!

### CODE REVIEW

**Comment by esteldunedain** [comment]
:+1: Looks perfect to me

**Comment by esteldunedain** [comment]
@jonpas, @legman: we need legman added to authors.txt, with a valid email address before merging this.

Thank you very much to both of you

**Comment by jonpas** [comment]
@legman if you give me your email address I can add you.

**Comment by legman** [comment]
hey lads - my email is juicemelon@msn.com

**Comment by jonpas** [comment]
Added, thanks!

**Comment by esteldunedain** [comment]
Merged, thank you both again.

**Comment by jonpas** [comment]
Yay! :hand: @legman

**Comment by legman** [comment]
I am currently making some amends to this change - how should I go about providing you with the changes when I am done?

**Things I am changing:**

- Separated out several IED ammo types which stops the default IED being pressure plated. (This caused a bug where any IED armed, even with a cellphone would be triggered when stepped on)
- Improved class inheritance for new IEDs
- Making the urban IEDs have less BOOM than the 'Artillery Shell' IEDs but support fragmentation and act more like a AP Mine

**Comment by legman** [comment]
Also I noticed 'ACE_explodeOnDefuse' is either on or off, it would be nice if this had some random chance to it such as an additional param 'ACE_explodeOnDefuseChance' which ranges from 0.0 - 1.0?

Let me know what you think of this idea as it could easily be implemented into **fnc_defuseExplosive**

**Comment by jonpas** [comment]
Best is if you simply pull request your changes.

**Comment by legman** [comment]
ok awesome thanks!

**Pull request merged**
