### PR TITLE
new unconsciousness ragdol

### PR DESCRIPTION
**Pull request by BioZ0102**
Make player/AI be in ragdol when unconsciousne. like in screenshots.

### CODE REVIEW

**Comment by bux578** [comment]
There's something wrong with this.
Feature requests go here: https://github.com/acemod/ACE3/issues/3594/

**Comment by PabstMirror** [comment]
@BioZ0102 

Adding this code to init.sqf should trigger the 1.62 ragdoll
```
["ace_unconscious", {
    params ["_unit", "_state"];
    if (local _unit) then {
        _unit setUnconscious _state;
    };
}] call CBA_fnc_addEventHandler;
```

**Comment by esteldunedain** [comment]
Why are we not doing that anymore? d0c30577afd62b8f125711a4c1700b495af32cee

**Comment by Glowbal** [comment]
It was removed because I didn't get to try it out properly yet at that time and we were just before the release. It wasn't doing anything in earlier releases and I didn't feel like keeping it if I didn't know the full effects.

**Comment by commy2** [comment]
There is a annoying heartbeat sfx that plays with this. This is also confusing as the rhytm of the heart beat has nothing to do with what is simulated in advanced medical.

we will come back to this I think. No point in making feature requests now.

**Pull request closed without merging**
