### PR TITLE
Export debug report from options menu

### PR DESCRIPTION
**Pull request by PabstMirror**
#1296

Added a few extra minor debugs stuff to the code from @esteldunedain.

Tagged WIP because right now i'm getting occasional crashes with `ace_clipboard`.  I'm getting them on master with the export config button as well.  Need to clean that up before adding this feature that end users will have access to.

### CODE REVIEW

**Comment by ViperMaul** [comment]
Let's consider sending this to the RPT file as well. 
That way we can say. Hit the Debug Button and paste the info in chat or just send us your RPT file.

**Comment by PabstMirror** [comment]
Right now it dumps to both.
I added some basic debug stuff to the top of the array size dump:
```
~~~~~~~~~ACE Debug~~~~~~~~~
time = 13.975

------Performance------
diag_fps = 62.0155
count ace_common_waitAndExecArray = 0
count cba_common_perFrameHandlerArray = 24 (max 25)
count diag_activeSQFScripts = 12
count diag_activeSQSScripts = 0
count diag_activeMissionFSMs = 0

------Player------
typeOf = null
animationState = null

------Array Info (count >= 10)------
slx_xeh_classes - ARRAY SIZE: 14
ace_interact_menu_act_o_soldier_sl_f - ARRAY SIZE: 15
ace_interact_menu_act_o_soldier_lat_f - ARRAY SIZE: 15
...
```

**Comment by ViperMaul** [comment]
@PabstMirror 

1) Using that branch it doesn't dump to RPT for me. Only Clipboard. The content looks nice. 
2) if I hit the debugButton from the main screen as opposed to being in game, I crash.

**Comment by ViperMaul** [comment]
Disregard my last. Issue with Git Pull. 
Looks good. :+1:

**Pull request merged**
