### PR TITLE
Medical - Reduce bleeding rates

### PR DESCRIPTION
**Pull request by mharis001**
**When merged this pull request will:**
- Scale back bleeding rates for wounds by 5 times

Should help correct the currently very fast bleed out times with even just one large wound. These values will likely need to be further adjusted as more testing is done.

### CODE REVIEW

**Comment by TheMagnetar** [comment]
Ideally real values (publication) should be used to adjust the bleeding rates instead of taking a value that we thing that more or less fits

**Comment by mharis001** [comment]
Agreed. I will try to search for real values however, it is difficult to find reference material.

**Comment by TheMagnetar** [comment]
There is also the maximum blood loss limit depending on the body part. There we can also do some adjustments... I also have something but I must check the authenticity of the data.

**Comment by severgun** [comment]
> Ideally real values (publication) should be used to adjust the bleeding rates instead of taking a value that we thing that more or less fits

I think it will be even faster and no playable

**Comment by PabstMirror** [comment]
I belive this is from 2 things, the swich from total blood from a 0-100 scale to 0-6 (liters)
I think I attempted to solve this by adjusting bleed rates in code:
https://github.com/acemod/ACE3/blob/master/addons/medical_damage/functions/fnc_woundsHandlerSQF.sqf#L102-L104
```
private _nastinessLikelihood = linearConversion [0, 20, (_woundDamage / _thresholdWoundCount), 0.5, 30, true];
private _bleedingModifier = 0.25 + 8 * exp ((random [-4.5, -5, -6]) / _nastinessLikelihood);
private _painModifier = 0.05 + 2 * exp (-2 / _nastinessLikelihood);
```
We might want to adjust those values (effecting randomness) as well.

**Comment by SilentSpike** [comment]
If we want to keep the bleeding proportional to how it was on a 0-100 scale in a 0-6 scale these values should be updated as `x/100 * 6`.

I did a quick test of this and it seems somewhat reasonable, unit was stable with a class I hemorrhage with two 6.5mm shots to the body. Third shot killed him.

I think in order to correctly solve this bleeding issue, we first need to choose time periods that are reasonable to survive one of each given wound type and then set the bleeding values and modifier calculations so that they average those time scales.

**Comment by PabstMirror** [comment]
Handled by #7010

**Pull request closed without merging**
