### PR TITLE
Cleanup Interaction Menu

### PR DESCRIPTION
**Pull request by PabstMirror**
Privates, params (~8% speedup)

I implemented but left disabled a fix for #2196 (Distance in ACE_Action's sub-actions not respected) (https://github.com/acemod/ACE3/commit/ed4cc42897fb4b00e8b31dd68f4f80b3168946d5#diff-078fc18f72c95b3cad3e8fdf7fca9d48R38)

It's a big change because most things have been written assuming that gets ignored. 
We can cleanup our stuff, but we risk breaking compatibility with missions/other addons by turing it on.

### CODE REVIEW

**Comment by esteldunedain** [comment]
:+1:

**Comment by commy2** [comment]
>Privates, params (~8% speedup)
That is really nice!

**Comment by PabstMirror** [comment]
I noticed that PR #1294 was having no effect anymore because `ace_interact_menu_fnc_addActionToClass` called compile with a classname before interaction_menu's compile with the object type happened.

This compiled a action for CaManBase and then copied it to all other man classes.

I fixed it, but now I'm not sure if that correct.  It apparently has been working for some time as is.  And it gives us the ability to add actions to different unit classes by config.

With https://github.com/CBATeam/CBA_A3/issues/42 fixed, maybe we should remove instead of fixing?

**Comment by esteldunedain** [comment]
> With CBATeam/CBA_A3#42 fixed, maybe we should remove instead of fixing?

I think it should be removed. It was intended to reduce the compile time of actions on mission start to help prevent CBA from interrupting, which should no longer happen.

**Pull request merged**
