### PR TITLE
Practice Ammunition

### PR DESCRIPTION
**Pull request by bux578**
#734

### CODE REVIEW

**Comment by esteldunedain** [comment]
:+1: Not exactly realistic, but nice to have.

**Comment by jonpas** [comment]
Rubber bullets! Very useful for us, thanks!

**Comment by esteldunedain** [comment]
> Rubber bullets

I believe those go substantially slower than the real thing

**Comment by jonpas** [comment]
Shhhh :grin:

**Comment by VKing6** [comment]
I've never seen the point of practice ammo in a game (isn't it all practice, in the perspective of not shooting each other with real guns?), but I know some people who will find it useful.
Just don't add blanks, please?

**Comment by bux578** [comment]
> I've never seen the point of practice ammo in a game

PvP CQC/CQB Training. Remove the need for `allowdamage false` or to revive/respawn after each round of training. That's what I was thinking about.

**Comment by VKing6** [comment]
Do you intend to make it work with the medical system to make people react to being hit?

**Comment by bux578** [comment]
If I can manage to do so, yeah. CamShake, OnScreen message... something like that. Feel free to give  ideas

**Comment by esteldunedain** [comment]
> If I can manage to do so, yeah. CamShake, OnScreen message... something like that. Feel free to give ideas

What about calling `ace_hitreactions_fnc_fallDown`? It already does cam shake for the player, and a fall animation for the shooter to see. Otherwise, a simple camShake like the one on that function could work.

Anyway, I think you'll need a config an entry defining the bullet as blank (to be on the safe side, and don't rely on `hit = 0`). I think you should check for that [here](https://github.com/acemod/ACE3/blob/master/addons/medical/functions/fnc_handleDamage.sqf#L38).

**Comment by headedhorseman101** [comment]
What might be a good idea is to knock the target out upon the impact of a certain number of hits (could be a settable value possibly?) which would allow oversight from someone in Zeus or an moderator of some sort to see what happened in the scenario easier. That way there isn't any damage done either.

**Comment by Daishiknyte** [comment]
Alternative use:  Stun rounds for stopping units from running around when you're trying to capture one.

**Comment by Glowbal** [comment]
@bux578 should we get this in in the current state or wait until a more polished version?

**Comment by bux578** [comment]
@Glowbal this is far from being working. I haven't had the time yet to do anything here.

**Comment by bux578** [comment]
I'll close this one. Even so I'd like to see that feature. I currently don't have the time.

**Pull request closed without merging**
