### PR TITLE
Small Improvement in Nametags

### PR DESCRIPTION
**Pull request by jokoho48**

### CODE REVIEW

**Comment by SilentSpike** [comment]
Seems trivial to me, merging

**Comment by Glowbal** [comment]
Actually I am wondering besides readability if this has any performance gains? Did you do a test?

**Comment by jokoho48** [comment]
at 1000000 this is the results
Old: Frames: 2155 Time: 35.917
New: Frames: 1329 Time: 22.151
TestCode: http://pastebin.com/WFZ2tcXL

**Comment by jonpas** [comment]
That's pretty nice!

**Comment by jokoho48** [comment]
thats the reason why i create this PR and i think thats not so Trivial than it looks like

**Pull request merged**
