### PR TITLE
Translation - Korean v2.0

### PR DESCRIPTION
**Pull request by jtj5283449**
**When merged this pull request will:**

- Will translate over 1000 lines which wasn't translated before
- Minor adjustments and synchronization between some gears and items name so it can go smooth with vanilla items (Needs more time to overhaul the translation)

### CODE REVIEW

**Comment by PabstMirror** [comment]
I don't understand the diff, did the encoding change?

**Comment by bux** [comment]
@jtj5283449 There's something wrong with the files you've committed. 
image
That's a lot of changed lines :)

**Comment by jtj5283449** [comment]
my apologies, I don't know how to github and as you can tell I got a brain made with cinderblock. I simply uploaded xml files into my clone and requested merge. I guess I should've done something else

**Review by PabstMirror — APPROVED** [review]

**Comment by PabstMirror** [comment]
Mass replaced \r\n with \n
probably happened because files were uploaded
imho this is not a problem we should have had to deal with, github.com should be smart enough to handle that

**Pull request merged**
