### PR TITLE
Translation to Portuguese

### PR DESCRIPTION
**Pull request by ToasterBR**
Done all remaining portuguese translations, including some minor
corrections

### CODE REVIEW

**Comment by bux578** [comment]
Wow, good job, thank you. Please add yourself to the Authors.txt with a valid email address and we'll merge this.

**Comment by ToasterBR** [comment]
LOL. Thanks? 
Btw, glad I could help. Keep the good work!

**Comment by esteldunedain** [comment]
:+1: for the translation quality, as far as my portuguese goes (like half an inch)

**Comment by KoffeinFlummi** [comment]
Thanks!

**Pull request merged**
