### PR TITLE
Medical GUI - Remake body outline textures

### PR DESCRIPTION
**Pull request by amsteadrayle**
**When merged this pull request will:**
- Title

### IMPORTANT

- [ ] If the contribution affects [the documentation](https://github.com/acemod/ACE3/tree/master/docs), please include your changes in this pull request so the documentation will appear on the [website](https://ace3.acemod.org/).
- [x] [Development Guidelines](https://ace3.acemod.org/wiki/development/) are read, understood and applied.
- [x] Title of this PR uses our standard template `Component - Add|Fix|Improve|Change|Make|Remove {changes}`.

### CODE REVIEW

**Comment by amsteadrayle** [comment]
I wasn't satisfied with the body outline textures I made, so I gave it another try.
image

**Comment by amsteadrayle** [comment]
And just for public reference, I make these outlines with an ImageMagick script:
```bat
@echo off
setlocal enabledelayedexpansion

@REM Loop over all arguments
for %%x in (%*) do (
    SET final_img=%%~nx_s%%~xx
    SET scratch=%%~nx_scratch%%~xx

    copy /Y "%%~x" "!final_img!"
    copy /Y "%%~x" "!scratch!"

@REM Scale up now and scale back down at the end to smooth everything out
@REM Dilate a little to get the edge offset
    magick mogrify -filter spline -resize 200%% ^
        -morphology Dilate Octagon:3 ^
        !scratch!
@REM Dilate a lot to get the edge thickness
    magick mogrify -filter spline -resize 200%% ^
        -morphology Dilate Octagon:8 ^
        !final_img!

@REM Subtract to get just the edge
    magick composite !scratch! !final_img! -compose difference !final_img!

@REM Original picture has alpha values up to 77. Now scale it up to full 255
    magick mogrify -channel A -level 1%%,30%% +channel ^
        -filter Lagrange -resize 50%% ^
        !final_img!

    del !scratch!
)
```

**Comment by jonpas** [comment]
Feel free to put that script in source somewhere. Maybe extras folder.

We could squeeze this in 3.16.0 IMO.

**Review by LinkIsGrim — APPROVED** [review]

**Comment by LinkIsGrim** [comment]
@jonpas your call, click the button

**Review by BrettMayson — APPROVED** [review]

**Pull request merged**
