### PR TITLE
Casings - Add CUP Casings

### PR DESCRIPTION
**Pull request by Mike-MF**
**When merged this pull request will:**
- Adds the 2 casings provided by CUP.

### CODE REVIEW

**Comment by Drofseh** [comment]
Does this not create a dependency?

**Comment by jonpas** [comment]
No, it's dynamically spawned, and only if that cartridge was fired, which it can't if there is no CUP.

**Comment by veteran29** [comment]
That whole mapping not being config based is quite meh IMO. Could use a refactor.

**Review by LinkIsGrim — COMMENTED** [review]
What if model doesn't exist?

**Comment by jonpas** [comment]
It's used by that casing, how could it not exist?

**Comment by PabstMirror** [comment]
result is cached, so we could do a `fileExists` check
but I agree that it should be safe as is,
a mod would have to be using `CUP_FxCartridge_545` but not require cba_weapons

**Comment by LinkIsGrim** [comment]
> It's used by that casing, how could it not exist?

Mod actually needs CUP but doesn't have it in requiredAddons, user doesn't load CUP -> model doesn't exist.
I can see this potentially happening for some of the weapon pack mods on the workshop.

**Review by LinkIsGrim — APPROVED** [review]

**Pull request merged**
