### PR TITLE
Code cleanup Zeus module

### PR DESCRIPTION
**Pull request by MikeMatrix**
Code cleanup of the Zeus module.

Split PRs from #1989.

### CODE REVIEW

**Comment by kripto202** [comment]
I can't shake the feeling there is a typo on the requiredAddon in fnc_handleZeusUnitAssigned.sqf

**Comment by MikeMatrix** [comment]
@kripto202 I don't know what you're talking about. There is no typo there.

(In all seriousness, I can't even explain how it got there in the first place O_O)

**Comment by bux578** [comment]
> (In all seriousness, I can't even explain how it got there in the first place O_O)

You guys fixed the typo in the `private` line but not where the variable is used in the code.

**Comment by MikeMatrix** [comment]
@bux578 actually it looks like that typo got introduced in the first commit of this PR...

**Comment by bux578** [comment]
ah yes... too early

**Comment by MikeMatrix** [comment]
Probably also the reason for the typo initially...

**Comment by jonpas** [comment]
What's the decision for using params vs CBA PARAMS_X now? Since it's exactly the same thing in this case, shouldn't PARAMS_X be used for better debugging purposes? And params should be used directly only where replacing BIS_fnc_param/requiring more options?

**Comment by SilentSpike** [comment]
I'm not sure in regards to updating old code like this, but I know for any future written code it's basically just the developers choice.

**Comment by jonpas** [comment]
But PARAMS_X does give you EXPLODE macro debugging. Best solution would probably be one macro/command for all cases of course, not sure if that's doable.

**Comment by bux578** [comment]
https://community.bistudio.com/wiki/params

> In addition to simple parsing directly into variables, input can be tested in case it is undefined, of the wrong type or of the wrong size (if array) and substituted if necessary with default values. Substitutes can also be logged into .rpt file, if allowFunctionsLog param in description.ext is set to 1.

**Comment by jonpas** [comment]
Ooh I missed that one! Thanks bux! 

My final thought is that entire ACE3 codebase should be unified, so there isn't mix of macros abd commands, IMO best would just be to use param/params everywhere. Of course it's not up to me, I just say stuff around here. :grin:

**Pull request merged**
