### PR TITLE
Add more filters to ammo boxes

### PR DESCRIPTION
**Pull request by commy2**
Currently adds "Backpacks", "Vests" and "Uniforms" filter.

### CODE REVIEW

**Comment by MikeMatrix** [comment]
:+1: apart from the `// by commy2`s

**Comment by commy2** [comment]
I'll add the header tomorow, together with maybe some additional filters. Whatever seems usefull.

**Comment by MikeMatrix** [comment]
Good idea

**Comment by commy2** [comment]
Done.

**Comment by bux578** [comment]
:+1: That's some awesome stuff!

**Comment by jonpas** [comment]
Very nice!

**Comment by commy2** [comment]
Now also removes backpacks from the weapons filter, backpacks and grenades from the magazines filter and backpacks, uniforms and vests from the items filter.

Also fixed a problem with modded grenades.

Should be ready now.

**Comment by MikeMatrix** [comment]
:+1:

**Comment by PabstMirror** [comment]
commy, what do you think about adding this to the `inventory` module (which does very little on it's own)?

**Comment by commy2** [comment]
Yeah. That would make sense.

**Comment by commy2** [comment]
Done. Merge?

**Comment by bux578** [comment]
:+1:

**Pull request merged**
