### PR TITLE
remove asdg message

### PR DESCRIPTION
**Pull request by bux578**
new cba will include asdg jr

### CODE REVIEW

**Comment by bux578** [comment]
Once the new cba gets released

**Comment by jokoho48** [comment]
but than you must load everytime the ace_asdg_comp

**Comment by jonpas** [comment]
> but than you must load everytime the ace_asdg_comp

New CBA will have Joint Rails integrated.

**Comment by Glowbal** [comment]
:+1:

**Comment by jokoho48** [comment]
i think that we must include the ace_asdg_comp in the main ACE

**Comment by jonpas** [comment]
Why @jokoho48 ? What's currently there will be moved into main config since CBA is already a requirement anyways.

**Pull request merged**
