### PR TITLE
Localization of key binding categories

### PR DESCRIPTION
**Pull request by MikeMatrix**
Adjusted keybinding categories to be localizable.

### CODE REVIEW

**Comment by Glowbal** [comment]
I am pretty certain there is a reason we didn't localize those. There is a function from the CBA keybinding API to make the name look pretty but we never got around to use it.

**Comment by Glowbal** [comment]
I did a quick check: I believe it was because when changing the game language, you would lose all keybinding settings because it would be classified as a different mod.

Instead, we should use `cba_fnc_registerKeybindModPrettyName`.

```sqf
[MOD_NAME, LOCALIZED_STR] call cba_fnc_registerKeybindModPrettyName;
```
ref: https://github.com/CBATeam/CBA_A3/blob/master/addons/keybinding/fnc_registerKeybindModPrettyName.sqf

**Comment by MikeMatrix** [comment]
@Glowbal makes sense, couldn't really test it, since I'm running English only. I'll update to use that function instead.

**Comment by MikeMatrix** [comment]
Woops wrong button

**Comment by jonpas** [comment]
New PR might be better anyways. :)

**Comment by MikeMatrix** [comment]
Yea true. I'll work on this and get back with a new PR

**Pull request closed without merging**
