### PR TITLE
Medical - Fix adv wound not stacking

### LINKED ISSUE #4345: Wounds do not stack anymore in advanced medical
**Arma 3 Version:** `1.64` RC
**CBA Version:** `3.0.0`
**ACE3 Version:** `3.7.0` release; commit: f3dc1afdbfc8dc05c6057a5d6806c1a7cc10e6db

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- Wounds received in advanced medical do not stack anymore resulting in a massive list.
- http://puu.sh/r1lXx/f8c5244673.jpg

**Steps to reproduce:**
- inflict large amount of damage with advanced medical enabled and check the person.

**Where did the issue occur?**
- SP

**Placed Modules:**
- Medical settings
- Advanced medical settings

**RPT log file:**
- https://gist.github.com/alganthe/602f32524a75e0a24146ff334e37e6b0

### PR DESCRIPTION
**Pull request by PabstMirror**
Close #4345

### CODE REVIEW

**Comment by Glowbal** [comment]
:+1: nice. And it resulted in a script error..

**Comment by Glowbal** [comment]
lgtm

**Comment by donkeypunchepoch** [comment]
Is there any course of action for this error. I am in early alpha testing with ace medical fully persistent and this error is a setback. Is there anything I can do to help. I've investigated it a little but so far and it looks as tho argument 2 is coming up 'any' for the handledamage_advanced. I will look into it further if need be

**Comment by PabstMirror** [comment]
@donkeypunchepoch - are you getting an error with 3.7?
Please make a new issue and include a rpt and we'll take a look.

**Pull request merged**
