### PR TITLE
Documentation - Update Wiki AtragMx 

### PR DESCRIPTION
**Pull request by Laid3acK**
**When merged this pull request will:**
- Delete all outdated Horus manual links.
- Add descriptions copy/paste from Horus manual.
- Update picture with outdated values.
- Add resources (Ruthberg missions).
- Add a AtragMx with default ballistic chapter.
- Add a AtragMx with Vector 21 and DAGR chapter.
- Add minor updates, corrections, descriptions.

### IMPORTANT

- If the contribution affects [the documentation](https://github.com/acemod/ACE3/tree/master/docs), please include your changes in this pull request so the documentation will appear on the [website](https://ace3.acemod.org/).
- [Development Guidelines](https://ace3.acemod.org/wiki/development/) are read, understood and applied.
- Title of this PR uses our standard template `Component - Add|Fix|Improve|Change|Make|Remove {changes}`.

### CODE REVIEW

**Review by LinkIsGrim — COMMENTED** [review]
I'm not a fan of having links to a random mega.nz folder.

**Comment by Drofseh** [comment]
I agree, those need to be hosted somewhere else

**Comment by johnb432** [comment]
> I'm not a fan of having links to a random mega.nz folder.

What about putting them on ace' steam workshop?

**Comment by Laid3acK** [comment]
The best solution in my opinion.
Fell free to host these missions as your convenience and update links.

**Comment by jonpas** [comment]
If those missions do not have large assets, we should put them into ACE3 like the Arsenal mission is. Or under `extras`

**Comment by Laid3acK** [comment]
Original missions by Ruthberg without any modification:
- 360_Degree_Training_Course.zip = 255 ko
- 360_Degree_Training_Course-Framework.zip = 22 ko
- AB_Verification_ACE.VR.zip = 23 ko
Personally, i think `extras` is a good idea but as you want.

**Comment by LinkIsGrim** [comment]
@Laid3acK is this good for review (besides the missions?)

**Comment by Laid3acK** [comment]
Yes, seems to be ok for me.

**Comment by LinkIsGrim** [comment]
Will add missions to "Scenarios" menu with descriptions.

**Review by LinkIsGrim — APPROVED** [review]

**Pull request merged**
