### PR TITLE
Medical AI - Fix AI healing itself too fast when hit

### LINKED ISSUE #7649: AI will heal right after being shot if they've not shot recently
**Mods (complete and add to the following information):**
- **Arma 3:** `1.98` (profiling)
- **CBA:** `3.15.0`
- **ACE3:** `3.13.1`
_Make sure to reproduce the issue with only CBA and ACE3 on a newly created mission!_

**Description:**
AI starts healing instead of fighting back if you suprise them and shot them before they can shoot back..

**Steps to reproduce:**
- See this video: https://streamable.com/emkfic

**Expected behavior:**
AI does not heal right after being shot.

**Where did the issue occur?**
- SP/MP

**Log Files:**
- [Arma3_x64_2020-04-19_16-02-43.rpt.txt](https://github.com/acemod/ACE3/files/4499245/Arma3_x64_2020-04-19_16-02-43.rpt.txt)

### PR DESCRIPTION
**Pull request by BaerMitUmlaut**
**When merged this pull request will:**
- Fix #7649

### CODE REVIEW

**Review by veteran29 — APPROVED** [review]
LGTM

**Comment by PabstMirror** [comment]
Would `[QEGVAR(medical,woundReceived)` be a better event? 
I think it might trigger less often

we could also just add this to medical engine to be made available for other things.  Engine_handleDamage: line 51
```
if (_hitPoint isEqualTo "ace_hdbracket") exitWith {
    _unit setVariable [QEGVAR(medical,lastDamageSource), _shooter];
    _unit setVariable [QEGVAR(medical,lastInstigator), _instigator];
    _unit setVariable [QEGVAR(medical,lastHitTime), CBA_missionTime]; // <-- NEW
```

**Comment by BaerMitUmlaut** [comment]
We're only setting a local object variable in the EH, I don't think we really need to optimize that, that's about as low impact as it gets. HandleDamage triggers more often than Hit, woundReceived should trigger about as often as Hit.

Something I forgot: I would like to bump the timer again with suppression, but the suppression EH will be a nice and fast solution so I want to wait for that rather.

**Review by PabstMirror — APPROVED** [review]

**Review by mharis001 — APPROVED** [review]

**Comment by BrettMayson** [comment]
Would it be worth it to make it a setting?

**Comment by BaerMitUmlaut** [comment]
I'd prefer if this stuff stays hidden from the average user and "just works".

**Comment by BrettMayson** [comment]
Hidden global variable? I just find 30 seconds a little for my taste, but I also understand if it is too niche

**Review by PabstMirror — APPROVED** [review]

**Review by jonpas — APPROVED** [review]

**Pull request merged**
