### PR TITLE
Arsenal - Improved some case sensitivity for arsenal

### PR DESCRIPTION
**Pull request by johnb432**
**When merged this pull request will:**
- Make right side panels for choosing weapon attachments (when a weapon selected) case sensitive.
- `ace_arsenal_fnc_removeVirtualItems` & `ace_arsenal_fnc_addVirtualItems` are no longer case sensitive.

`bis_fnc_compatibleItems` already returns case sensitive names, so no need to go find the config names of the items again.

Addresses #8844.

Thanks @commy2 for helping!

### IMPORTANT

- [ ] If the contribution affects [the documentation](https://github.com/acemod/ACE3/tree/master/docs), please include your changes in this pull request so the documentation will appear on the [website](https://ace3mod.com/).
- [x] [Development Guidelines](https://ace3mod.com/wiki/development/) are read, understood and applied.
- [x] Title of this PR uses our standard template `Component - Add|Fix|Improve|Change|Make|Remove {changes}`.

### CODE REVIEW

**Comment by Salluci** [comment]
Is `GVAR(virtualItems)` sanitized? It takes user input via `fnc_addVirtualItems`.

**Comment by johnb432** [comment]
> Is `GVAR(virtualItems)` sanitized? It takes user input via `fnc_addVirtualItems`.

No it's not. It's something I've overlooked - I have pushed a fix for that.

**Comment by Salluci** [comment]
If you can confirm that all classnames in arsenal variables are config case with this, some more optimizations can be done elsewhere, like in the loadouts menu.

Something for another PR, but worth asking.

**Review by PabstMirror — APPROVED** [review]

**Comment by commy2** [comment]
It would be better to handle everything as lower case. Config case is not consistent across versions, or even modsets and therefore clients.

**Comment by johnb432** [comment]
> It would be better to handle everything as lower case. Config case is not consistent across versions, or even modsets and therefore clients.

Is this something that should be done in this PR or should I make another one?


On a separate note: I have looked through the code of the arsenal component.
There are multiple improvements and cleanup that can be made. I also have some suggestions, e.g the usage of hashmaps wherever possible.
Is this something you guys are interested in?

**Comment by Salluci** [comment]
If you wanna tackle that maybe wait for 2.10 and the new `compatibleItems`/`compatibleMagazines` commands.

**Comment by hypoxia125** [comment]
`bis_fnc_compatibleItems` no longer returns case sensitive - ace arsenal no longer works when using `bis_fnc_compatibleItems` as a getter to grab magazines for adding virtual items

Excerpt from `bis_fnc_compatibleItems`:

```
// Add only unique entries to output
{
    private _magazine        = tolower _x;
    private _magazineCfg    = configfile >> "cfgmagazines" >> _magazine;

    if ( (getnumber (_magazineCfg >> "scope") isEqualTo 2) || _showHidden ) then {
        _compatibleMagazines pushBackUnique _magazine;
    };
} foreach _magazinesList;
```

**Comment by johnb432** [comment]
> `bis_fnc_compatibleItems` no longer returns case sensitive - ace arsenal no longer works when using `bis_fnc_compatibleItems` as a getter to grab magazines for adding virtual items
> 
> Excerpt from `bis_fnc_compatibleItems`:
> 
> ```
> // Add only unique entries to output
> {
>     private _magazine        = tolower _x;
>     private _magazineCfg    = configfile >> "cfgmagazines" >> _magazine;
> 
>     if ( (getnumber (_magazineCfg >> "scope") isEqualTo 2) || _showHidden ) then {
>         _compatibleMagazines pushBackUnique _magazine;
>     };
> } foreach _magazinesList;
> ```

`bis_fnc_compatibleItems` returns config sensitive entries because CBA overwrites the `bis_fnc_compatibleItems` function.

As for what you quotes, that's from `bis_fnc_compatibleMagazines`, which was never used. `CBA_fnc_compatibleMagazines` is a better alternative, or now with 2.10 `compatibleMagazines` works too.

**Pull request closed without merging**
