### PR TITLE
Vector - New reticle using CBA scripted optics

### LINKED ISSUE #6601: Vector21 has got wrong zoom factor
**Arma 3 Version:** `1.84` (stable)
**CBA Version:** `3.8.0` (stable)
**ACE3 Version:** `3.12.3` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
- The zoom factor of the vector21 is too low, compared with it's real counterpart (according to this: [https://www.safran-vectronix.com/product/vector-21/](url)).

**Steps to reproduce:**
- take a vector21 and a rifle with a 5x zoom scope (e.g. MOS). see that the zoom factor of the 5x scope is bigger than the zoom factor of the vector.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- None.

### PR DESCRIPTION
**Pull request by commy2**
**When merged this pull request will:**
- sets magnification to 7x as irl
- uses scripted reticle with adjusted mildots for the new correct magnifcation
- new editor categories
- day version added to the ACE box, zeus and the editor
- gwh item uses the binocular dummy model that makes the item not stuck half in the ground
- close #6601

- [x] reticle wip
- [x] scripts not working
- [x] #6931
- [x] illum mode fix / control idcs
- [x] radblur

### CODE REVIEW

**Comment by commy2** [comment]
Notes for me:
`RETICLE_SAFEZONE_` scale cfg entry?

**Comment by Blutze** [comment]
Neat.

Also ref #6601.

**Comment by commy2** [comment]
requires https://github.com/CBATeam/CBA_A3/pull/1141 and https://github.com/CBATeam/CBA_A3/pull/1142.

**Comment by commy2** [comment]
Done.

**Pull request merged**
