### PR TITLE
Fix checking vitals anim

### PR DESCRIPTION
**Pull request by gienkov**
It uses animations that don't match at all what you are doing anyway so I think it's better to just disable anim for that actions which are:
* Checking pulse
* Checking BP
* Checking response

### CODE REVIEW

**Comment by esteldunedain** [comment]
I think the "Put" animation would be better than nothing. It's very short, but at least fellow soldier can see that you did something.

**Comment by gienkov** [comment]
Can you tell me what name it has? "Put" may suit checking vitals well.
What about checking while lying down?

**Comment by esteldunedain** [comment]
> Can you tell me what name it has? "Put" may suit checking vitals well.

TBH I don't know. We usually use `_unit playActionNow "PutDown";`, which plays the action correctly in any pose (including prone). I'm pretty sure that just plays a different anim depending on the current pose, but I don't know their names.

**Comment by Glowbal** [comment]
Those should have been disabled, since the others are also all empty.

But we do need some matching animations in the future for those.

**Pull request merged**
