### PR TITLE
Docs: README fixes

### PR DESCRIPTION
**Pull request by Tourorist**
The page previously titled as "Getting started" was renamed to "Information center", in the process changing its physical location within the site hierarchy and breaking the old link as a result.

### CODE REVIEW

**Comment by Tourorist** [comment]
Have been playing a catch up game (with #2714) since yesterday, in the hopes of avoiding or at least minimizing potential conflicts at the time of merge.

**Comment by jonpas** [comment]
I can fix merges on my side, feel free to merge this first. :)

**Comment by bux578** [comment]
Thanks @Tourorist. Could you rebase your commits to one commit with a good commit message? That would be aweseom :smile:

**Comment by Tourorist** [comment]
@bux578, some assistance please. I've tried combining them all in ed23bdd, which seem to have worked but how do I now remove the prior individual commits?

**Comment by MikeMatrix** [comment]
@Tourorist Try [this](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html)

**Comment by Tourorist** [comment]
@MikeMatrix, that's exactly the guide I followed, but I guess I wasn't as exact in performing its steps. :smile: 

Anyway, I've taken up too much of everyone's time already. For now, let's just merge the PR by @jonpas instead of mine. Meanwhile, in time for my next pull, I will try to learn the use of 'rebase' command properly.

**Comment by SilentSpike** [comment]
Since rebase has been mentioned: https://www.atlassian.com/git/tutorials/merging-vs-rebasing/the-golden-rule-of-rebasing

**Pull request closed without merging**
