### PR TITLE
Medical - Allow placing unconscious in a body bag

### PR DESCRIPTION
**Pull request by BrettMayson**
**When merged this pull request will:**
- Adds a setting allowing the placing of unconscious units in a body bag

Makes it a little harder for medics to rapidly determine if someone is dead or unconscious

### CODE REVIEW

**Comment by PabstMirror** [comment]
ref https://github.com/acemod/ACE3/blob/master/addons/medical_treatment/functions/fnc_placeInBodyBag.sqf
```
if (alive _patient) then {
    TRACE_1("Manually killing with setDead",_patient);
    [_patient, "buried_alive"] call EFUNC(medical_status,setDead);
};
```
lol

**Comment by jonpas** [comment]
We should think about how the user (medic) can figure out if someone is dead. Not by simple interaction but through vitals.

**Comment by PabstMirror** [comment]
What if we always show the action on unconscious units and allow the progress bar to go to completion
but only do the hard killing if setting is enabled, 
otherwise show a little hint like "The body twitched and may not be dead"

**Comment by jonpas** [comment]
Yes, I like that idea @PabstMirror !

**Comment by BrettMayson** [comment]
I like that idea too, but would like it to be an on by default setting we can turn off to achieve the original functionality of this PR.

**Review by jonpas — APPROVED** [review]

**Pull request merged**
