### PR TITLE
Remove CPR action from dead people

### PR DESCRIPTION
**Pull request by gienkov**
You can do CPR on units that are dead - this should fix that.

### CODE REVIEW

**Comment by Glowbal** [comment]
This would give people another indication whatever or not someone is death.

**Comment by bux578** [comment]
^

**Comment by gienkov** [comment]
Well plain indication that someone is clearly dead is ragdoll...

**Comment by BryanBoru** [comment]
Hold on, so we want it that the only way to do CPR is if there is a chance to save them? In Reality CPR has a slim success rate at 18%. However, in game it seems if you hit the magic mix of epi and CPR they almost always come back, quite unrealistic as it is. So if the concern is "people will waste time doing CPR on the dead" well, who else would get CPR but the dead? I think it will help players understand the futility of CPR. Leave it to them to call off the CPR after a few rounds of failure, especially if they don't notice the ragdall (which I wish would just happen at unconsciousness since there should never be a hint of unsurvivable besides the level of trauma a patient has).

**Comment by jonpas** [comment]
:+1: for new label!

**Pull request closed without merging**
