### PR TITLE
Aegis Compat - Overwrite some Aegis changes

### PR DESCRIPTION
**Pull request by johnb432**
**When merged this pull request will:**
- "Compat" is too strong of a term, the purpose of this is to only overwrite some changes Aegis makes, in order to fix the stuff that is currently broken when loading both Aegis and ACE.

I've added the "ignore-changelog" tag because I don't want people thinking this is an official ACE-Aegis compat, as atm it's only doing fixes. Personally I'm not planning on adding any compatibility, but I decided to add it for future use.
In order to drop the word "compat", the only alternative would be to add this into the vehicles addon directly.

### IMPORTANT

- If the contribution affects [the documentation](https://github.com/acemod/ACE3/tree/master/docs), please include your changes in this pull request so the documentation will appear on the [website](https://ace3.acemod.org/).
- [Development Guidelines](https://ace3.acemod.org/wiki/development/) are read, understood and applied.
- Title of this PR uses our standard template `Component - Add|Fix|Improve|Change|Make|Remove {changes}`.

### CODE REVIEW

**Review by PabstMirror — APPROVED** [review]

**Comment by PabstMirror** [comment]
We should put it in the patch notes so it's not a surprise to people
- it might show up in requiredAddons in missions
- the `ace client/server mismatch` errors that people get from running different mods from server

**Comment by johnb432** [comment]
> We should put it in the patch notes so it's not a surprise to people
> 
>     * it might show up in requiredAddons in missions
> 
>     * the `ace client/server mismatch` errors that people get from running different mods from server

Would adding https://github.com/acemod/ACE3/blob/b9a361fd3906c9e1e7d37fba51f8190f5df66618/addons/vehicles/config.cpp#L15-L16 remove the requiredAddons problem?

**Comment by johnb432** [comment]
I haven't been able to make it create a dependency (I just placed down both variants of the Merkava in the editor - I'm not sure if you can do anything else).

**Comment by PabstMirror** [comment]
We never had any luck getting `addonRootClass` to work
but it's great if it's not creating dependency

I'd still like it in changelog for the mismatch errors people seem to always get but it's fine either way

**Review by PabstMirror — APPROVED** [review]

**Pull request merged**
