### PR TITLE
Documentation: Vehiclelock, Weather

### PR DESCRIPTION
**Pull request by BullHorn7**
Create feature/vehiclelock.md
Edit addon readme.md and missionmaker.md

### CODE REVIEW

**Comment by BullHorn7** [comment]
@PabstMirror please let me know everything is correct
I added the "Key modes" paragraph which might not be entirely relevant to players. Should it stay or should it go?

**Comment by ulteq** [comment]
Stuff that is not relevant for players should probably go here:
http://ace3mod.com/wiki/missionmaker/modules.html#1.17-vehicle-lock

**Comment by BullHorn7** [comment]
Removed a redundant paragraph. 
Moved the irrelevant stuff from vehiclelock.md to missionmaker.md and added a note in vehiclelock.md for users to consult with their mission maker about lock modes. 
Improved grammar and numbering of paragraphs.

**Comment by BullHorn7** [comment]
Added description for weather.md - toggling wind arrow & explanation for colors

**Pull request merged**
