### PR TITLE
Virtual attach object

### PR DESCRIPTION
**Pull request by PabstMirror**
This is for attach, but the same idea could be applied to explosives which has had issues like
#1234 (Glitching items into the player moves them over the map).
Both systems want to show a virtual object when placing something.

Instead of `createVehicle` and updating it's pos every frame, this just show the p3d on the hud in the same position and scale as it would be if it were real.

Pros: Zero network traffic, No physX collisions

Cons: Looks bad in 3rd person (it's rendered separately from the main scene, so there is no z-buffer), also no lighting/nvg effects:

### CODE REVIEW

**Comment by esteldunedain** [comment]
Great. I love this

**Comment by PabstMirror** [comment]
Video: https://www.youtube.com/watch?v=iVuB8Z6OE7I
2nd half shows how it looks in 3rd person.  Like I said, it's bad.  I think the size and position of the object are right, but it should be rendered behind the player's head and obscured.

I tend to be "Function Over Form", but I'm not sure how critical of an issue it will be for others.  Given all of the issues with real objects, I think it's worth it.

If people are ok with this then I'll try doing the same for explosives.

**Comment by esteldunedain** [comment]
> Given all of the issues with real objects, I think it's worth it.

I second that. @ViperMaul, @Glowbal, @KoffeinFlummi, I guess this is your call.

> If people are ok with this then I'll try doing the same for explosives.

I agree.

**Comment by esteldunedain** [comment]
Hey, quick idea. For third person placement, we could offset the origin of the ray 30 cm to the right of the head, so it would be less likely the head obscure the plcing position

**Comment by jonpas** [comment]
> I tend to be "Function Over Form", but I'm not sure how critical of an issue it will be for others.

Don't think it will be one at all, usually you put it down in a few seconds after selecting it anyways.

**Comment by PabstMirror** [comment]
@esteldunedain - 30cm was a perfect offset, looks better now that it is not over the head.

untitled2

**Comment by esteldunedain** [comment]
Yay! Over the shoulder third person action

**Comment by SilentSpike** [comment]
What's the status on this?

**Pull request merged**
