### PR TITLE
Chat visibility enhancement

### PR DESCRIPTION
**Pull request by VKing6**
Changed text and background colour for chat while on the map to let it be more visible

### CODE REVIEW

**Comment by esteldunedain** [comment]
:+1:

**Comment by jokoho48** [comment]
it is Posible to hide the Chat complett? with Module or with Settings?

**Comment by gienkov** [comment]
@jokoho48 Enable "Streaming UI" in Game options to do that.

**Comment by jokoho48** [comment]
i Mean to force it form Server or Mission side

**Comment by whiztler** [comment]
disableChannels[]={1,2,3,4}; // Restrict chat channels where
(0=Global),(1=Side),(2=Command),(3=Group),(4=Vehicle),(5=Direct),(6=System)

in description.exe

**Comment by ulteq** [comment]
> Changed text and background colour for chat while on the map to let it be more visible

:+1:

**Pull request merged**
