### PR TITLE
German - Update stringtable.xml

### PR DESCRIPTION
**Pull request by Clon1998**
Added german translations

### CODE REVIEW

**Comment by jaynus** [comment]
edited title for language

**Comment by KoffeinFlummi** [comment]
Thanks for your contribution! Please add yourself to the AUTHORS.txt file with a valid email address before we merge this.

**Comment by Clon1998** [comment]
I should have added me.

**Comment by KoffeinFlummi** [comment]
> I should have added me.

Nope...

**Comment by KoffeinFlummi** [comment]
Thanks.

**Pull request merged**
