### PR TITLE
Italian's Translation fixes

### PR DESCRIPTION
**Pull request by NukeDev**
Added translations
- atragmx
- attach
- ballistics
- captives

Cordially

### CODE REVIEW

**Comment by NukeDev** [comment]
Added other translations

**Comment by bux578** [comment]
Assigning to "Master of the Merge"

**Comment by NukeDev** [comment]
This is the another one where i did the ballistics changes

https://github.com/NukeDev/ACE3/commit/0b4bb6e4c9fe9841cca973b46a11aaff8e8201cf

**Comment by ulteq** [comment]
Did you add yourself to the AUTHORS.txt already?

**Comment by NukeDev** [comment]
Yes i did. 
You can close the topic

**Pull request merged**
