### PR TITLE
Medical Extension for handleDamage wounds

### PR DESCRIPTION
**Pull request by Glowbal**
Extension for handling advanced medical handleDamage wounds.

Performance test using `diag_tickTime`:
```
 0:26:53 "Extension perf: total 0.854004 avg: 8.54004e-005"
 0:26:54 "SQF perf: total 1.888 avg: 0.0001888"
```
10k runs.

### CODE REVIEW

**Comment by Glowbal** [comment]
This is ready. I will look into moving more stuff to the extension for future releases.

**Comment by Glowbal** [comment]
Note: this extension will be required on the server.

**Comment by esteldunedain** [comment]
> Note: this extension will be required on the server.

It's imperative we set up some cross compilation first then, so we can distribute de .so

**Comment by jaynus** [comment]
Relies on #1266

**Comment by Glowbal** [comment]
@jaynus does anything from the medical extension extension need to be changed with #1270 ?

**Comment by jaynus** [comment]
The above commit for the extension it will now build and work properly in linux and windows specifically in master

**Comment by Glowbal** [comment]
Just tested this. Works fine with the cross-platform integration.

**Pull request merged**
