### PR TITLE
fix broken time format for rallypoints, fix #2662

### LINKED ISSUE #2662: Rallypoint placement time has wrong fromat
`16:1` instead of `16:01`

### PR DESCRIPTION
**Pull request by commy2**

### CODE REVIEW

**Comment by commy2** [comment]
confirmed working.

**Comment by bux578** [comment]
Wouldn't this be better in common as a seperate function? 
`[date, "HH:ss"] call EFUNC(common,dateToString) // "12:01"`

**Comment by PabstMirror** [comment]
Could just use `[daytime, "HH:MM"] call BIS_fnc_timeToString`

**Comment by commy2** [comment]
```
{
private ["_in", "_format", "_min", "_hour", "_sec", "_msec"];

_in = _this select 0;

if (count _this > 1) then 
{
_format = _this select 1
} else
{
_format = "HH:MM:SS"
};

_min = _in mod 1;
_hour = _in - _min;
_sec = (60 * _min) mod 1;
_msec = (60 * _sec) mod 1;

_hour = (if (_hour <= 9) then {"0"} else {""}) + str _hour;

_min = (60 * _min) - ((60 * _min) mod 1);
_min = (if (_min <= 9) then {"0"} else {""}) + str _min;

_sec = (60 * _sec) - ((60 * _sec) mod 1);
_sec = (if (_sec <= 9) then {"0"} else {""}) + str _sec;

_msec = (60 * _msec) - ((60 * _msec) mod 1);
_msec = (if (_msec <= 9) then {"0"} else {""}) + str _msec;

switch _format do
{
case "HH": {format["%1",_hour]};
case "HH:MM": {format["%1:%2",_hour,_min]};
case "HH:MM:SS": {format["%1:%2:%3",_hour,_min,_sec]};
case "HH:MM:SS:MM": {format["%1:%2:%3:%4",_hour,_min,_sec,_msec]};
case "ARRAY": {[_hour,_min,_sec,_msec]};
default {""}
}

}
```

IDK overkill for this.

**Comment by commy2** [comment]
done

**Comment by Glowbal** [comment]
:+1:

**Pull request merged**
