### PR TITLE
Add flashsupressor to asdg_MuzzleSlot_338

### LINKED ISSUE #3344: .338 BadNews Lapua , Noreen Muzzle Attatchments (FlashSuppressor does not attatch)
**Arma 3 Version:** `1.56`
*( stable, *)

**ACE3 Version:** `3.4.2`
*(indicate if stable or dev, if dev indicate the commit the version is based on)*

**Mods:**
* `@CBA_A3`
* `@ace`
*  @mao_bloodmist_a3
*  @EWK_CIGS
*  @CUP-Terrains CORE
*  @CUP-Terrains MAPS

**Placed Modules:**
* *spectator settings, designate medical vehicle,friendly fire messages.*

**Description:**
* *InGame MP missions  CTI altis,Obtain a .338 Flash Suppressor from ACE Support Box, try to attatch FlashSuppressor .338 to Noreen Lapua.   The item is stowed in your inventory.
Attatchment are working for 6.5 muzzles. *

**Steps to reproduce:**
* *any combination of weapon attatchment .338 muzzle(flashSuppressor from ACESupport crate to NoreenLapua .338.*

**Where did the issue occur?**
* *Local MP , DED Server, Steam MP"*

**RPT log file:**
* https://www.dropbox.com/s/yib9c5dgbqswdjz/arma3_2016-02-19_08-09-10.rpt%20%20%20%20%20ACE%20%20%20becti.txt?dl=0

*
see 8:56,     8:00,

### PR DESCRIPTION
**Pull request by PabstMirror**
### When merged this pull request will:

Fix #3344 ?

I don't really know the JR stuff that well, but this seems to fix.
Should we switch other things to use the `compatibleItems` class instead of array?

### CODE REVIEW

**Comment by esteldunedain** [comment]
Do the other suppressor work, or should we do the same for all cases?

**Comment by PabstMirror** [comment]
Yeah, other DMRs are effected as well. But I'm not sure I really understand the JR configs.

Most guns have something like this:
```

class asdg_MuzzleSlot_762: asdg_MuzzleSlot { // for 7.62x39 suppressors
    class compatibleItems {
        ACE_muzzle_mzls_B = 1;
    };
};
```
Which make adding muzzle attachments clean, But the 6.5mm (like the MX) don't seem to use that?

**Comment by bux578** [comment]
tagging @robalo

**Comment by robalo** [comment]
Looks good to me. Here's how the slot is configured in CBA for vanilla attachments:
https://github.com/CBATeam/CBA_A3/blob/master/addons/jr/jr_classes.hpp#L141
And here's where the JR weapon slot is assigned to the weapon:
https://github.com/CBATeam/CBA_A3/blob/master/addons/jr/cfgweapons.hpp#L81

For MX there's an open issue #252.

**Comment by commy2** [comment]
:+1: works

**Pull request merged**
