### PR TITLE
Added some Dutch translations

### PR DESCRIPTION
**Pull request by Mad-0**
Added Dutch translations for some strings.

### CODE REVIEW

**Comment by commy2** [comment]
Dutch is not supported by the game?

**Comment by bux578** [comment]
Thank you for the effort. But is Dutch even supported by the game?

**Comment by bux578** [comment]
@Glowbal will know :)

**Comment by jokoho48** [comment]
https://support.bistudio.com/arma-3/steam/68 no its not supported

**Comment by Glowbal** [comment]
We appreciate the effort, but Dutch is not an by Arma 3 supported language. We therefore won't include it in our repository.

Note that if you are interested in having a fully Dutch translated version of ACE, there are ways to do so. iirc the Chinese community has done something like that. @bux578 will know.

**Pull request closed without merging**
