### PR TITLE
Unified status effect handler

### LINKED ISSUE #64: Unify the implementation of setForceWalk, setCapticityStatus and setDisableInputStatus
The first two come from agm, the last from cse. Unify the style on the three, or, if possible, use them as front end to a single generic function.

### LINKED ISSUE #2757: add setAllowDamageStatus, getAllowDamageStatus functions
-dragging fixFloating

### PR DESCRIPTION
**Pull request by PabstMirror**
Close #64
Close #2757 (which has been blocking progress on #2230)
Replace PR #2758 

Allows multiple sources to add and remove `forceWalk`, `setCaptive` and `allowDamage` (the event is called `blockDamage` because here any true should turn the result false).

 - Effect events are reapplied on locality switch
 - All effects are reset on respawn.
 - Only modify effects that we've actually set at some point (should maximize compatibility with missions that do not use this framework)

### CODE REVIEW

**Comment by esteldunedain** [comment]
:+1:

**Comment by MikeMatrix** [comment]
:+1:

**Comment by Glowbal** [comment]
You remove some methods here. Could you replace them with a wrapper around the new method if possible and print a warning message about deprecated?

**Comment by BaerMitUmlaut** [comment]
What about [allowSprint](https://community.bistudio.com/wiki/allowSprint)? This would be useful for a custom fatigue system.

**Comment by commy2** [comment]
^good idea

**Comment by PabstMirror** [comment]
@BaerMitUmlaut - added as `blockSprint` with about 5 lines (have to reverse some of these names because you want any true to make the result true)

@Glowbal They were listed as public so good catch, should also be useful for debugging to have a getter.

**Comment by Glowbal** [comment]
They are still missing the deprecated warning log print.

**Comment by esteldunedain** [comment]
> They are still missing the deprecated warning log print.

Take a look now

**Comment by jokoho48** [comment]
@esteldunedain i think you fuck something up

**Comment by esteldunedain** [comment]
> @esteldunedain i think you fuck something up

As far as I can tell it's github acting up. The extra changes it shows are already merged into master, so they shouldn't be shown in the diff.

**Comment by jokoho48** [comment]
no that not look right sorry but i think there is go something wrong

**Comment by PabstMirror** [comment]
I've seen this before
https://github.com/acemod/ACE3/branches  says it's 5 commits ahead of master
I could probably close and make pr for same branch and it would be fine.

**Comment by esteldunedain** [comment]
> I could probably close and make pr for same branch and it would be fine.

Or you could just merge it :wink:

**Comment by esteldunedain** [comment]
[This instructions](http://makandracards.com/makandra/13043-force-github-pull-requests-to-update-the-diff-against-its-target-branch) should solve the outdated diff problem, but I don't think they are worth it.

**Pull request merged**
