### PR TITLE
CheckPBO should ensure client isn't running any addons the server isn't

### PR DESCRIPTION
**Pull request by SilentSpike**
Fix for #1722

### CODE REVIEW

**Comment by SilentSpike** [comment]
As @CorruptedHeart points out in the issue, comparing these on the client isn't the most secure thing in the world.

Also I'm instinctively wary of PV'ing arrays. It might be more efficient to convert to string and back on each end.

**Comment by jonpas** [comment]
This looks good to me.

**Comment by bux578** [comment]
Should become more easy once `arrayIntersect` hits the floor

**Comment by SilentSpike** [comment]
Well, not exactly as we'd need the set difference rather than the set intersection

**Comment by bux578** [comment]
LINQ to SQF

**Comment by esteldunedain** [comment]
> Well, not exactly as we'd need the set difference rather than the set intersection

You can probably compute the intersection and the use somehting like this:
```sqf
{
    _originalArray = _originalArray - [_x];
} forEach _intersectionArray;
```

**Comment by SilentSpike** [comment]
Bad estse! :stuck_out_tongue_closed_eyes: 

```
_originalArray = _originalArray - _intersectionArray;
```

That works though, can just output them all as one message that way.

**Comment by esteldunedain** [comment]
Ok, this seems ready to be merged. Please do once it's confirmed working.

**Comment by SilentSpike** [comment]
@jonpas Any update on testing this?

**Comment by jonpas** [comment]
@SilentSpike I didn't get a chance to test this, I'll do it later today.

**Comment by SilentSpike** [comment]
Confirmed working, thanks again @jonpas :cookie:

**Comment by jonpas** [comment]
Yay, have a :banana: !

**Comment by BryanBoru** [comment]
Is this confirmed to be working? Can anyone walk me through is there is more to enabling it besides serverconfig.hpp settings?

**Comment by jonpas** [comment]
@BryanBoru Yes, confirmed working, enabling it is all you have to do.

**Pull request merged**
