### PR TITLE
Fixed link and spelling mistake on gh-pages

### PR DESCRIPTION
**Pull request by jonpas**

### CODE REVIEW

**Comment by jaynus** [comment]
We automatically copy from the master branch documentation folder to gh-pages. 

Please move this to merging into master documentation folder.

**Comment by jonpas** [comment]
Ah, will do, thanks!

**Comment by KoffeinFlummi** [comment]
The automatic copying isn't in yet, and I'll try to eventually generate the wiki authors page with the AUTHORS.txt file.

**Comment by jonpas** [comment]
Ok, cheers.

**Pull request closed without merging**
