### PR TITLE
German Stringtable: Additions and more 2

### PR DESCRIPTION
**Pull request by licht-im-Norden87**

### CODE REVIEW

**Comment by licht-im-Norden87** [comment]
I must say that I'm really sorry for creating 3PR because I had no clue how to put all commits into one branch.

**Comment by MikeMatrix** [comment]
@licht-im-Norden87 here's a little "no deep-stuff" guide on git
http://rogerdudler.github.io/git-guide/
Also in case you're interested in working with git some more, or trying to figure out how something else works, go take a look at
http://book.git-scm.com/

**Comment by bux578** [comment]
Or join our public chat: http://slackin.ace3mod.com/

**Comment by licht-im-Norden87** [comment]
@bux578 I'd have liked to see my translation in 3.4 but it doesn't really matters. Could you, if you havent, have a look on it and merge it?

**Comment by Glowbal** [comment]
Before someone merges this, please make certain that all commits here are cleaned up.

**Comment by licht-im-Norden87** [comment]
@Glowbal What exactly do you mean? Should I name all commits like (translation cargo, additions ...) or what is meant?

**Comment by PabstMirror** [comment]
Done via #2941

**Pull request closed without merging**
