### PR TITLE
Fixes bugged waves

### PR DESCRIPTION
**Pull request by ulteq**
Fixes: https://github.com/acemod/ACE3/issues/1025

### CODE REVIEW

**Comment by ParaMedicGer** [comment]
Could this have anything to do with this devbranch update?
http://forums.bistudio.com/showthread.php?149636-Development-Branch-Changelog/page53
ENGINE

    Fixed: Multiplayer ocean waves synchronization

**Comment by bux578** [comment]
Might ... but I've tested it in vanilla aswell and wasn't able to reproduce it.

**Comment by jaynus** [comment]
Maybe someone forgot if they were on dev branch?

**Comment by jaynus** [comment]
Is this good/ready to merge? @KoffeinFlummi @bux578 @ulteq

**Comment by bux578** [comment]
:+1:

**Comment by ulteq** [comment]
:+1:

**Pull request merged**
