### PR TITLE
Spotting scope - New reticle using CBA scripted optics

### PR DESCRIPTION
**Pull request by commy2**
**When merged this pull request will:**
- title
- requires CBA 3.11

<details><summary>Click to expand</summary>

</details>

There is a B reticle, which is apparently what the real thing uses, but the reticle is off set to the lower left, so it doesn't fit into the ocular at max magnification:

<details><summary>Click to expand</summary>

</details>

I could use that, but I would have to lower the max magnification from 35x to 25x for the reticle to fit.

- [x] attenuation fix

### CODE REVIEW

**Comment by commy2** [comment]
- [ ] If A model, make night version

**Comment by commy2** [comment]
Reticle A or B. Idk which one to chose.

**Comment by Blutze** [comment]
Less from a realism standpoint, and more... game design and balancing: Whats the point of being tripod bound instead of going handheld if you don't get more magnification than your shooter?

Also, why not both.

**Comment by commy2** [comment]
Someone would have to edit the p3d model.

**Comment by commy2** [comment]
Done.

**Comment by commy2** [comment]
Confirming the accuracy of the mildot reticle by comparison with the scripted retilce:





<details><summary>script</summary>

```sqf
private _unit = call CBA_fnc_currentUnit;
_unit addPrimaryWeaponItem "CBA_optic_debug";
_unit switchCamera "GUNNER";

private _debugReticle = uiNamespace getVariable ["CBA_debugReticle", displayNull];

if (!isNull _debugReticle) exitWith {
    "CBA_debugReticle" cutText ["", "PLAIN"];
    false
};

"CBA_debugReticle" cutRsc ["RscTitleDisplayEmpty", "PLAIN", 0, false];
private _display = uiNamespace getVariable "RscTitleDisplayEmpty";
uiNamespace setVariable ["CBA_debugReticle", _display];

private _vignette = _display displayCtrl 1202;
_vignette ctrlShow false;

// crosshair
private _horizontalBar = _display ctrlCreate ["RscText", -1];
_horizontalBar ctrlSetBackgroundColor [1,0,0,0.5];

private _width = safezoneW;
private _height = pixelH;
private _left = safezoneX;
private _top = 0.5 - pixelH/2;

_horizontalBar ctrlSetPosition [_left, _top, _width, _height];
_horizontalBar ctrlCommit 0;

private _verticalBar = _display ctrlCreate ["RscText", -1];
_verticalBar ctrlSetBackgroundColor [1,0,0,0.5];

_width = pixelW;
_height = safezoneH;
_left = 0.5 - pixelW/2;
_top = safezoneY;

_verticalBar ctrlSetPosition [_left, _top, _width, _height];
_verticalBar ctrlCommit 0;

// mildots
private _mildots = [];
_display setVariable ["CBA_debugReticle_mildots", _mildots];

for "_i" from 1 to 200 do {
    private _mildot = _display ctrlCreate ["RscText", -1];
    _mildot ctrlSetBackgroundColor [1,0,0,0.5];
    _mildot ctrlSetPosition [0,0,0,0];
    _mildot ctrlCommit 0;

    _mildots pushBack _mildot;
};

// magnification
private _magnification = _display ctrlCreate ["RscText", -1];
_magnification ctrlSetTextColor [1,0,0,2/3];

_width = safezoneW/30;
_height = safezoneH/30*(getResolution select 4);
_left = 0.5 + safezoneW/12 - _width/2;
_top = 0.5 - safezoneH/12*(getResolution select 4) - _height/2;

_magnification ctrlSetPosition [_left, _top, _width, _height];
_magnification ctrlCommit 0;

_display setVariable ["CBA_debugReticle_magnification", _magnification];

// draw script
private _script = _display ctrlCreate ["RscMapControl", -1];

_script ctrlSetPosition [0,0,0,0];
_script ctrlCommit 0;

_script ctrlAddEventHandler ["Draw", {
    params ["_control"];
    private _display = ctrlParent _control;

    private _zoom = 0.25 call CBA_fnc_getFOV select 1;
    private _start = AGLToASL positionCameraToWorld [0,0,0];
    private _end = AGLToASL positionCameraToWorld [0,0,1000];
    private _dir = _end vectorDiff _start;

    private _vDir = _start vectorFromTo _end;
    private _vLat = vectorNormalized (_vDir vectorCrossProduct [0,0,1]);
    private _vUp = _vDir vectorCrossProduct _vLat;

    // mildots
    private _mildots = _display getVariable "CBA_debugReticle_mildots";

    private _width = safezoneW/150*_zoom;
    private _height = safezoneH/150*_zoom*(getResolution select 4);
    private _left = 0.5 - _width/2;
    private _top = 0.5 - _height/2;

    {
        private _milpos = _start vectorAdd ([_dir, _vLat, -10*(360/2000/pi)*(_forEachIndex + 1)] call CBA_fnc_vectRotate3D);
        private _top = (worldToScreen ASLToAGL _milpos select 1) - pixelH/2;

        _x ctrlSetPosition [_left, _top, _width, pixelH];
        _x ctrlCommit 0;
    } forEach (_mildots select [0,10]);

    _width = safezoneW/500*_zoom;
    _height = safezoneH/500*_zoom*(getResolution select 4);
    _left = 0.5 - _width/2;
    _top = 0.5 - _height/2;

    {
        private _milpos = _start vectorAdd ([_dir, _vLat, -(360/2000/pi)*(_forEachIndex + 1)] call CBA_fnc_vectRotate3D);
        private _top = (worldToScreen ASLToAGL _milpos select 1) - pixelH/2;

        _x ctrlSetPosition [_left, _top, _width, pixelH];
        _x ctrlCommit 0;
    } forEach (_mildots select [10,40]);

    _width = safezoneW/150*_zoom;
    _height = safezoneH/150*_zoom*(getResolution select 4);
    _left = 0.5 - _width/2;
    _top = 0.5 - _height/2;

    {
        private _milpos = _start vectorAdd ([_dir, _vUp, -10*(360/2000/pi)*(_forEachIndex + 1)] call CBA_fnc_vectRotate3D);
        private _left = (worldToScreen ASLToAGL _milpos select 0) - pixelW/2;

        _x ctrlSetPosition [_left, _top, pixelW, _height];
        _x ctrlCommit 0;
    } forEach (_mildots select [50,10]);

    _width = safezoneW/500*_zoom;
    _height = safezoneH/500*_zoom*(getResolution select 4);
    _left = 0.5 - _width/2;
    _top = 0.5 - _height/2;

    {
        private _milpos = _start vectorAdd ([_dir, _vUp, -(360/2000/pi)*(_forEachIndex + 1)] call CBA_fnc_vectRotate3D);
        private _left = (worldToScreen ASLToAGL _milpos select 0) - pixelW/2;

        _x ctrlSetPosition [_left, _top, pixelW, _height];
        _x ctrlCommit 0;
    } forEach (_mildots select [60,40]);

    _width = safezoneW/150*_zoom;
    _height = safezoneH/150*_zoom*(getResolution select 4);
    _left = 0.5 - _width/2;
    _top = 0.5 - _height/2;

    {
        private _milpos = _start vectorAdd ([_dir, _vUp, 10*(360/2000/pi)*(_forEachIndex + 1)] call CBA_fnc_vectRotate3D);
        private _left = (worldToScreen ASLToAGL _milpos select 0) - pixelW/2;

        _x ctrlSetPosition [_left, _top, pixelW, _height];
        _x ctrlCommit 0;
    } forEach (_mildots select [100,10]);

    _width = safezoneW/500*_zoom;
    _height = safezoneH/500*_zoom*(getResolution select 4);
    _left = 0.5 - _width/2;
    _top = 0.5 - _height/2;

    {
        private _milpos = _start vectorAdd ([_dir, _vUp, (360/2000/pi)*(_forEachIndex + 1)] call CBA_fnc_vectRotate3D);
        private _left = (worldToScreen ASLToAGL _milpos select 0) - pixelW/2;

        _x ctrlSetPosition [_left, _top, pixelW, _height];
        _x ctrlCommit 0;
    } forEach (_mildots select [110,40]);

    _width = safezoneW/150*_zoom;
    _height = safezoneH/150*_zoom*(getResolution select 4);
    _left = 0.5 - _width/2;
    _top = 0.5 - _height/2;

    {
        private _milpos = _start vectorAdd ([_dir, _vLat, 10*(360/2000/pi)*(_forEachIndex + 1)] call CBA_fnc_vectRotate3D);
        private _top = (worldToScreen ASLToAGL _milpos select 1) - pixelH/2;

        _x ctrlSetPosition [_left, _top, _width, pixelH];
        _x ctrlCommit 0;
    } forEach (_mildots select [150,10]);

    _width = safezoneW/500*_zoom;
    _height = safezoneH/500*_zoom*(getResolution select 4);
    _left = 0.5 - _width/2;
    _top = 0.5 - _height/2;

    {
        private _milpos = _start vectorAdd ([_dir, _vLat, (360/2000/pi)*(_forEachIndex + 1)] call CBA_fnc_vectRotate3D);
        private _top = (worldToScreen ASLToAGL _milpos select 1) - pixelH/2;

        _x ctrlSetPosition [_left, _top, _width, pixelH];
        _x ctrlCommit 0;
    } forEach (_mildots select [160,40]);

    // magnification
    private _magnification = _display getVariable "CBA_debugReticle_magnification";
    _magnification ctrlSetText format ["%1x", _zoom toFixed 1];
}];

true
```

</details>

**Comment by commy2** [comment]
Image from OP is outdated. With help from CBA updates it now looks like this:


Original reticle, but magnification limited to 35x instead of 45x irl.

**Comment by commy2** [comment]
Done.

**Pull request merged**
