### PR TITLE
Server config export to exclude settings using default values 

### PR DESCRIPTION
**Pull request by Glowbal**
#776

### CODE REVIEW

**Comment by esteldunedain** [comment]
This won't work if you want to force client settings.

I'd prefer that we either do this on a sepparate button. As an alternative, we could always export all settings but add comments to the exported config indicating: the current default value of the setting and wheter or not that setting is client settable (most communities won't want to force most client settings, so probably default to isForced = 0 for those??)

**Comment by Glowbal** [comment]
I like that idea.

- [ ] Make the non default export only a seperate button
- [ ] Write additional comments for settings, detailing what they are (client setting, etc).
- [ ] Provide possible values if available
- [ ] Client settings default `isForced = 0;`

**Comment by jaynus** [comment]
I think the problem here is values changing with new releases. How are we to handle new defaults when they saved the old? Force them to export? 

Maybe at a minimum we automate some release note generation for changes settings - it should be a very easy diff between tags. This way when we change defaults or add remove configs, it's already documented for awareness

**Comment by esteldunedain** [comment]
> I think the problem here is values changing with new releases. How are we to handle new defaults when they saved the old? Force them to export?

Yes, that would work. If they enter a mission and reexport the data the new default would show on the comments. It's not perfect but it isn't terrible either.

Besides, we could post changing default parameters on the changelog.

**Comment by jaynus** [comment]
Yes, see my second suggestion :)

**Pull request closed without merging**
