### PR TITLE
No A10 tracers, Commanche tracers visible only in nvg

### PR DESCRIPTION
**Pull request by SzwedzikPL**

### CODE REVIEW

**Comment by bux578** [comment]
:+1:

**Comment by ViperMaul** [comment]
@SzwedzikPL 
Nice. Is there a Internet Reference for this?

**Comment by SzwedzikPL** [comment]
@ViperMaul not really but seems logic for me. I've never seen A10 using tracers ammo on yt. Same for apache :: commanche.

If someone find info that's not true you can close this pr :)

**Comment by gienkov** [comment]
GAU-8 doesn't shoot tracers, for combat deployment they use "combat mix" which is API/HEI mix.
https://youtu.be/teVJEgJnT7A?t=1m35s

**Comment by Nagrach** [comment]
Tracers are needed for Arma 3 Gau till the day when the A10 gets a propper FCS/CCIP and everything else that is needed for an proper gunrun

**Comment by SzwedzikPL** [comment]
> Tracers are needed for Arma 3 Gau till the day when the A10 gets a propper FCS/CCIP and everything else that is needed for an proper gunrun

I will try add FCS in https://github.com/acemod/ACE3/pull/1976

**Comment by Glowbal** [comment]
#2441

**Pull request closed without merging**
