### PR TITLE
Arsenal - Conditional on sorts

### LINKED ISSUE #7888: ACE Arsenal: Can't sort by amount of items in loadout anymore.
**Mods (complete and add to the following information):**
- **Arma 3:** `1.98.146373`
- **CBA:** `3.15.1`
- **ACE3:** `3.13.4`

**Description:**
Before this update, the right-hand panel of the ACE arsenal allowed sorting by the amount of items present in the unit's loadout.  Since using this version of ACE, the options on the right-hand panel largely mirror those on the left-hand side (see screenshot).

The new sorting modes like "by magnification" are very nice, but the missing "by amount" mode is very important for quickly editing existing loadouts.

Thanks for all the work, I appreciate the effort and understand that (if this isn't user error), these things do happen.

**Steps to reproduce:**
- Start Arma, go to Eden editor (choose any terrain).
- Place a NATO rifleman unit, right click it, choose Edit Loadout -> ACE Arsenal
- Select the unit's vest and attempt to sort its contents by amount.

**Expected behavior:**
As before this version, the "sort by amount" option should be usable.

**Where did the issue occur?**
- Eden Editor, also found in effect during a multiplayer game (on dedicated server, running other mods).

**Log Files:**
- [Gist](https://gist.github.com/Bubbus/6bf075f908c344e7e472043aada66d37)

**Screenshots:**

### PR DESCRIPTION
**Pull request by BrettMayson**
**When merged this pull request will:**
- Add a conditional field to the arsenal sorts
- Add `Sort by Amount` (Closes #7888)

### CODE REVIEW

**Comment by PabstMirror** [comment]
Open arsenal and click on vest:
```
private _sortConfig = _sorts select (_sorts findIf {(_x select 0) isE>
Error position: <select (_sorts findIf {(_x select 0) isE>
Error Zero divisor
File z\ace\addons\arsenal\functions\fnc_sortPanel.sqf..., line 101
```

**Comment by BrettMayson** [comment]
Which arsenal did you use? Main menu, editor, in game

I can have this fixed in the next few hours

**Comment by BrettMayson** [comment]
@PabstMirror Fixed

**Review by PabstMirror — APPROVED** [review]
tested working

**Comment by PabstMirror** [comment]
Looks good, I'm not sure if there is anything else we would want to pass to the condition code?
We can always add params later if needed

**Comment by BaerMitUmlaut** [comment]
https://github.com/acemod/ACE3/blob/9226035d597bf0fb2d6aadba2be8b5c1280ada56/addons/arsenal/functions/fnc_fillSort.sqf#L93

Missing semicolon!

**Pull request merged**
