### PR TITLE
Fix magazine weight being counted twice

### LINKED ISSUE #4745: Magazine Weight Bug
**Arma 3 Version:** `1.66` (stable)
**CBA Version:** `3.1.2.161105` (stable)
**ACE3 Version:** `3.8.2` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- When a magazine is loaded in your rifle, the weight of it is doubled. 
Link below describes problem, but as an example.
If you have 9 magazines in your vest and you weigh 17.6Kg, when you load your rifle, your total weight shouldn't change.  However currently if you load your rifle, your weight increases to 18.05Kg.
[Screenshots of issues](http://imgur.com/a/kTP5F)

**Steps to reproduce:**
- Open editor
- Place rifleman
- Preview in single player.
- Move ammunition between inventory, rifle and ground to see weight changes. 

**Where did the issue occur?**
- Single Player. Multi player not tested. 

**Placed Modules:**
- N/A

### PR DESCRIPTION
**Pull request by PabstMirror**
Fix #4745 / #4922

This will also work with advFatigue once we merge #4887

### CODE REVIEW

**Comment by bux** [comment]
Didn't they fix it already on dev branch?

**Comment by commy2** [comment]
The bug also applies to pistol and binocular magazines afaik.

**Comment by PabstMirror** [comment]
Will check dev

Pistol/laser desg mags are light
The problem is with 200 round belts and 7 kg rockets

**Comment by PabstMirror** [comment]
loadABS is working correectly in 1.68 RC
>Fixed: Inventory weight of loaded magazines was doubled (https://forums.bistudio.com/topic/143930-general-discussion-dev-branch/?page=862#comment-3147196 - UI still incorrect)

**Comment by commy2** [comment]
Nice.

**Pull request closed without merging**
