### PR TITLE
Update showHud func for 1.62 (squad radar)

### PR DESCRIPTION
**Pull request by PabstMirror**
In 1.62 `showHud`/`shownHud` now has 9 arguements.
- Changed ace_common_fnc_showHud to use 9 (and be backwards compatible)
- Updated all calls to func to use 9

### CODE REVIEW

**Comment by jonpas** [comment]
:+1: 
Self-note when this gets merged: add to client UI settings.

**Comment by PabstMirror** [comment]
I was going to ask you if we wanted to do that, I can add it to this PR.

**Comment by jonpas** [comment]
Yeah, it's only bound to difficulty in vanilla I think, no other way to toggle it, so I'd add it. I'll add it to this PR so you don't have to search where all it has to be added. :)

**Comment by jonpas** [comment]
Done from my side, I can't test it right now as I don't have RC downloaded.

**Comment by PabstMirror** [comment]
Thanks for UI intergration @jonpas 

Last dev rep says squad radar won't be in 1.62
So this will probably won't be part of 3.6.1

**Comment by jonpas** [comment]
Indeed, tagging with next milestone, we can make sure during the weekend, as the actual squad radar may not be there but the command may already support it.

**Comment by jonpas** [comment]
Not part of 1.62, retargeted into `master` branch in #4085

**Pull request closed without merging**
