### PR TITLE
Fix Armake problems

### PR DESCRIPTION
**Pull request by dedmen**
Don't specify skeletonName if you don't have a skeleton.
Add missing model.cfg entries even if they just refer to the default.

Btw model.cfg files are still mixed tabs/spaces.
I even found tabs and spaces on the same line, with the spaces being 3 space indent.
But I won't fix that in here. I just fixed that one because I noticed it there.

### CODE REVIEW

**Comment by thojkooi** [comment]
Nice, thanks for making this PR @dedmen!

**Comment by jonpas** [comment]
No, your additions are using tabs while stuff around it mostly uses spaces.

**Comment by dedmen** [comment]
Builds with 0 warnings/errors now.

**Comment by thojkooi** [comment]
Remaining warnings are all missing prefix for model.

**Comment by dedmen** [comment]
>Remaining warnings are all missing prefix for model.

I broke that then on my end? Thanks. I'll have to fix that.

**Pull request merged**
