### PR TITLE
Fix bouncing 40mm smoke

### PR DESCRIPTION
**Pull request by BaerMitUmlaut**
**When merged this pull request will:**
- Fix rubber 40mm smoke shells

### CODE REVIEW

**Comment by commy2** [comment]
please explain what's going on here.

**Comment by jonpas** [comment]
40mm smokes bounce a lot. Fire it at a hill and watch it bounce up and over. This fixes it.

**Comment by PabstMirror** [comment]
@commy2 - I think I found an explanation here: 
https://forums.bistudio.com/topic/191118-howto-make-ugl-40mm-smoke-grenades-less-bouncy/

**Comment by BaerMitUmlaut** [comment]
`shotSmokeX`, the simulation type for the current 40mm smoke grenades, is inherited from hand thrown smoke grenades, which are supposed to bounce. Because the 40mm ones travel at much higher speed, they bounce excessively when hitting the ground, making you miss your target _every single time_, which renders them useless for target marking - the main purpose of them irl.
This removes the bouncyness. I copied the `shotSmoke` simulation type from the artillery smoke shell.

**Comment by commy2** [comment]
So this PR changes shotSmokeX to shotSmoke to remove physx bounces of UGL smoke grenades?
Are there any other consequences changing the simulation has? Are all sounds and effects still working? Or do we have to redefine some entries?
shotSmoke seems to be usable if artillery shells and mortar rounds use it

**Comment by PabstMirror** [comment]
the round that comes out of arty/mortars is a a `simulation = "shotDeploy";`
which becomes the shotSmoke ammo on impact
doing it that way should guarantee no bounce.

We should double check how shotSmoke performs with air resistance as I believe it is disabled on some types. Making sure HE and Smoke rounds fly with similar flight paths in wind.

**Comment by commy2** [comment]
Yeah. And I somehow don't think we should totally get rid of the bouncing. Why not modify `deflecting` or even add a custom `deflectionSlowDown` (if that works)? 

`deflecting = 0;` should disable it without changing the simulation.

**Comment by BaerMitUmlaut** [comment]
A 40mm smoke shouldn't bounce unless it hits concrete or something it can't penetrate at all. In Arma that's rather the exception than the norm though.

>`deflecting = 0;` should disable it without changing the simulation.

You're right, it should. Doesn't though.

**Comment by BaerMitUmlaut** [comment]
Bad news: sound doesnt work. Good point commy. I'll try tweaking the X one again then...

**Comment by Neviothr** [comment]
I used this to disable the bouncing:
```class CfgAmmo {
    class SmokeShell;
    class G_40mm_Smoke : SmokeShell {
        simulation = "shotSmoke";
        deflectionSlowDown = 0.3;
    };
};```

**Comment by BaerMitUmlaut** [comment]
Closing because `shotSmokeX` is simply not fixable on our side.

**Comment by esteldunedain** [comment]
😢 It'd have been awesome

**Pull request closed without merging**
