### PR TITLE
add function to retrieve the control of the stamina bar

### PR DESCRIPTION
**Pull request by commy2**
this disables the stamina bar for the whole game sitting (not just mission):

`(call ace_common_fnc_getStaminaBarControl) ctrlShow false`

### CODE REVIEW

**Comment by licht-im-Norden87** [comment]
I dont know if i like it. In reality you always know in some way

**Comment by licht-im-Norden87** [comment]
I don't know if i like this. In reality you always know your personal exhaustion level in some way. (knowing running for another 12km is not possible anymore without having a break etc. ) Arma should give us this information to.

**Comment by commy2** [comment]
This only adds a function to return the control. The line I posted is completely optional.

**Comment by licht-im-Norden87** [comment]
Nevertheless I'd like to see another method to display your stamina. The current one is way to precise or in other words to "mathematical". What could be more realistic is an indicator using colors instead of a bar. (like the wind arrows) Starting with green slowly changes to orange and finally to red if you are to exhausted.

**Comment by commy2** [comment]
Sure. But all that has nothing to do with this PR.

**Pull request merged**
