### PR TITLE
Persistent database

### PR DESCRIPTION
**Pull request by tebsu**
-added persistent database
-does NOT have the correct schema (i just put it into the addons folder for now)
-requires extDB2 or extDB3 (i had the permission to include the mod but i didnt do so yet)

### CODE REVIEW

**Comment by sargken** [comment]
Whay does this doo?

**Comment by sargken** [comment]
What*

**Comment by jokoho48** [comment]
i think that is out of Scope

**Comment by jonpas** [comment]
@tebsu What is the point of this pull request? Can you explain what this would be used for and why it should be in ACE3?

**Comment by tebsu** [comment]
I talked to Flummi about this a few weeks ago and commy2 said, i should just create a pull request for this. What it does is, described here: https://forums.bistudio.com/topic/187092-sru-persistent-database-and-resupply/

As i am not continuing to develop on this mod, i asked if this could be maintained and implemented by the ACE team.

**Comment by Glowbal** [comment]
Closing because this does not fit within the scope of ACE. It does not stick to the ACE coding standards and is using unchecked and unescaped sql code. It also adds a dependancy on a third party mod that is not CBA.

**Comment by tebsu** [comment]
What a waste of time. People do not seem to read comments

**Comment by bux578** [comment]
@tebsu what comments are you referring to?

**Pull request closed without merging**
