### PR TITLE
Medical fixes

### PR DESCRIPTION
**Pull request by Glowbal**

### CODE REVIEW

**Comment by Glowbal** [comment]
- [ ] Switch event system over to new Synchronized Events

Current system is unreliable for JIP units.

**Comment by Glowbal** [comment]
This is ready.

**Comment by commy2** [comment]
#fix medical

**Comment by jonpas** [comment]
So many # emerging out of ACE3!

**Comment by esteldunedain** [comment]
@commy2 apparently thinks this is twitter

**Pull request merged**
