### PR TITLE
Mk6 fix leveling

### PR DESCRIPTION
**Pull request by PabstMirror**
#1498
#1818

* Show leveled elevation/azimuth.
* Fix some UI stuff

WIP - still need to do some more testing, but should be ready for 3.2

### CODE REVIEW

**Comment by austinjames314** [comment]
Awesome! Which method was used? Does this make the mortar stay level regardless of terrain, or make the azimuth and elevation show the true values for a tilted mortar?

**Comment by PabstMirror** [comment]
It shows the elevation that the gun will shoot at (what you see is what you get).
It's kind of hard to show 3d vectors in screenshots, but if you look below.
Red is how vanilla says it will shoot, blue is the weapon direction and yellow is how it actually shoots.

One fun bit of BIS logig: if the gun isn't looking at anything it will shoot via weapon direction.
So if you aim near the top of a mountain and shoot, then move your cursor 1 pixel up and aim at the sky, your next shot could be 30+ degrees off.

untitled

**Comment by austinjames314** [comment]
Cool. So the mortar is still tilted, but the elevation and azimuth displayed are the actual values, relative to the coordinate system, not relative to the slope of the ground. Sounds great! Fantastic! I've been waiting for this ever since I started playing Arma, thanks!

_"One fun bit of BIS logic: if the gun isn't looking at anything it will shoot via weapon direction.
 So if you aim near the top of a mountain and shoot, then move your cursor 1 pixel up and aim at the sky, your next shot could be 30+ degrees off."_

Wait, run that by me again? You're saying that if there's nothing in the mortar's sights, the rounds will follow the blue vector, and if there is, they follow the yellow vector? If so, that's messed up BIS!

**Comment by austinjames314** [comment]
Sorry to post something not quite on topic, but I figure you seem to have the mortars figured out.
Why do the smoke rounds not follow the same path as the HE rounds? #1814

**Pull request merged**
