### PR TITLE
README cleanup + Wiki revision

### PR DESCRIPTION
**Pull request by Tourorist**
* Appended the subheader with social links: Facebook, YouTube, Twitter, Reddit
* Converted the "BIF thread" link to a badge (akin to [TFAR](https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/master/README_EN.md))
* References to actual files are highlighted as code (`AUTHORS.txt`)
* Header and article capitalization according to the [WP convention](http://en.wikipedia.org/wiki/Wikipedia:Manual_of_Style/Capital_letters)
* Switched to issues-raw badge, in case of a possible localization (badges/shields#321)
* [Backblast area](http://en.wikipedia.org/wiki/Backblast_area) instead of just backblast, for clarity
* Added the link to [feature request guidelines](http://ace3mod.com/wiki/user/how-to-make-a-feature-request.html)
* Scaled up the logo to match the badges and subheader width

### CODE REVIEW

**Comment by esteldunedain** [comment]
Hi @Tourorist; while you are at this, could you update the feature list to that of the announcement thread? The list here is still coming from AGM

**Comment by Tourorist** [comment]
@esteldunedain, done.

By the way, on that list, what does AARs stand for? [Aerial refueling](http://en.wikipedia.org/wiki/Aerial_refueling)?

**Comment by esteldunedain** [comment]
Nope, Assistant Automatic Rifleman

**Comment by esteldunedain** [comment]
I like very much how the readme looks, except for the license bullet point (could be directly linked on the paragraph).

@KoffeinFlummi, you can check how this looks like [here](https://github.com/Tourorist/ACE3).

**Comment by Tourorist** [comment]
Shoved it in parentheses at the end (as **GPLv2**).

**Comment by jaynus** [comment]
The wiki links should point to ace3mod.com wiki pages instead of the documentation md raw files imo

**Comment by Tourorist** [comment]
@jaynus, done.

Also, you'll notice I linked the Download badge to source code. This is only a temporary solution until the first release, after which it will point directly to the latest version. For now, I think it's better than teasing visitors with a placeholder (#) and incorrect information about archive size.

**Comment by jaynus** [comment]
👍 great job on this; thanks. Are you interested in helping with the other wiki documentation portions? Those are in documentation folder (master branch); they get auto copied for the live site (which is in the gh-pages branch)

**Comment by Tourorist** [comment]
Sure, I can do a pass on them for consistency, style and wording. Will start sometime tonight, after work.

**Comment by bux578** [comment]
Awesome work @Tourorist 
As always!

**Comment by KoffeinFlummi** [comment]
Thanks!

**Pull request merged**
