### PR TITLE
reworking jamming

### PR DESCRIPTION
**Pull request by commy2**

### CODE REVIEW

**Comment by esteldunedain** [comment]
@commy2, I'm deeply against changing them this way. The previous values were based IRL data (MRBS) for operational temperatures whenever possible (not for vanilla weapons, but I addopted for those similar values than for other weapons).

Now for operational temperatures the probabilities are multiplied by almost 20 just because.

The first interval in the array represents the typical operational temperature of the barrel, so having the jam chance == MRBS on that interval makes the most sense.

>So for the MX it basically went from 
0.000143787 %
to
0.004%
each shot after firing one mag full auto.

On the current implementacion the jam chance goes up geometrically, so is increases faster and faster as the weapon gets hotter. Plus, we are talking about future weapons. In the AGM_Compatibility project we have much greater jam chances for older weapons (CUP, RHS, LH, etc) based on IRL data.

> Doesn't make any sense at all. Especially because temperature is no where near the reason a weapon usually jams.
As I said, all those factors are baked in the jam chances.

Maybe the cold weapon chance of zero should be upped a bit though.

**Comment by bux578** [comment]
It should be based on RL data, that's true. I was suggesting to include more environmental aspects into the calculations.

**Comment by commy2** [comment]
Let's stick the discussion to the issue. for clarity.

https://github.com/acemod/ACE3/issues/658

**Comment by commy2** [comment]
Closed in favor of https://github.com/acemod/ACE3/pull/146

**Pull request closed without merging**
