### PR TITLE
Docs: Installation - add optionals

### PR DESCRIPTION
**Pull request by BullHorn7**

### CODE REVIEW

**Comment by esteldunedain** [comment]
@BullHorn7, regarding compat pbos in optionals something like the following notice should be added to the documentation:

```
ACE policy is NOT to take care of compatibility with third party addons single handely. The current compat pbos were kickstarted by the ACE team as an example to modmakers, so it's clear which entries are needed for compatibility. The authors of those addons have been contatcted and many of those pbos are due to be included in their respective mods eventually.

Notice for mod makers: most of the config entries are inhert if ACE is not present, so most addons can be made ACE compatible without explicitly requiring ACE. For the rest of the things compatibility pbos are recommended to be created and distributed along the original mod content; feel free to consult with ACE devs about how to best implement that using the public slack channel. Third party mod makers and users shouldn't expect further compatibility pbos from the ACE team, except as working examples.
```

**Comment by BullHorn7** [comment]
@esteldunedain, should this be inside the installation guide? Perhaps this section is more effective in the mod-makers' section.

**Comment by esteldunedain** [comment]
> @esteldunedain, should this be inside the installation guide? 

Probably not, but a quick reference to it wouldn't hurt. I'd like to prevent people reading the guide from complaining that "there's no compat pbo for XYZ mod", etc

> Perhaps this section is more effective in the mod-makers' section.

Yes, that sounds better

**Comment by BullHorn7** [comment]
Looks like the Development -> Modularity and PBO Structure is the right place for that. I'll figure it out now.

**Comment by BullHorn7** [comment]
Added slightly modified versions of your text

**Comment by BullHorn7** [comment]
I don't know the meaning of the word `inhert` so I'm a little confused, not sure how to write this so it makes sense.

**Comment by esteldunedain** [comment]
Well, what I mean with "inhert" is that most of the entries don't do anything if ACE is not present, so it's safe to just include them in the base addon. If ACE is loaded the entries are used, and they are ignored otherwise. 

However, certain compatibility things needed for ACE would break the content in vanilla. Those are not "inhert", and therefore require a separate compat pbo to be delivered along the addon.

**Comment by BullHorn7** [comment]
I don't think this word exists.. Do you mean inherent? :p

**Comment by esteldunedain** [comment]
http://www.thefreedictionary.com/inert

**Comment by BullHorn7** [comment]
That sentence is a little complex/entangled. Let me know if you're not satisfied, I'll think of ways to simplify it.

**Comment by esteldunedain** [comment]
@BullHorn7, I think the text is good enough to be merged. Do you want me to do that?

**Comment by BullHorn7** [comment]
Yeah, let's do this.

**Pull request merged**
