### PR TITLE
Experiment with the bullet trace effect size

### PR DESCRIPTION
**Pull request by ulteq**
Tries to improve the visibility of the bullet trace effect on smaller screen.

### CODE REVIEW

**Comment by jaynus** [comment]
#378

**Comment by ulteq** [comment]
@lorenluke, can you give this a try?

**Comment by LorenLuke** [comment]
It's visible, even by my poor eyes' standards. Effect is effective.

**Comment by ulteq** [comment]
It looks quite unnatural on my screen. Both with smaller calibers like 5.56mm and bigger calibers like 12.7mm. We have to decrease the alpha value of the particle effect back to where it was.

**Pull request merged**
