### PR TITLE
Repair specialist rename, fixes #3186

### LINKED ISSUE #3186: improve term engineer and repair specialist
> "Repair Specialists" corresponds to the assign Engineer setting, not the in-game unit called "Repair Specialists", which is confusing.

### PR DESCRIPTION
**Pull request by Phyma**
**When merged this pull request will:**
- Will change the translation from Repair specialist to Advanced Engineer. See picture.
- Translation on other languages than English might be weird so  if its your native language and wrong then please review.

Did not have time to look through all stringtables in ACE so if you know there is a mention of ACE repair specialist somewhere else than repair then please say so. Should not be mentioned anywhere else.

http://steamcommunity.com/sharedfiles/filedetails/?id=940226455

Fixes #3186

### CODE REVIEW

**Comment by PabstMirror** [comment]
untitled

cut off in 3den (top row)

adding 
`sizeEx = "3.5 * (1 / (getResolution select 3)) * pixelGrid * 0.5"; // 4.32 default`
to line 18 of CfgEden.hpp gives bottom row

**Comment by jonpas** [comment]
What about just using `Adv. Engineer`?

**Comment by Phyma** [comment]
hehe yeah i wrote that in private to PabstMirror :P But yeah thinking about Adv. Engineer aswell :)

**Comment by jonpas** [comment]
`git stash` to the rescue. ;)

**Comment by Phyma** [comment]
Fixed!

**Comment by Phyma** [comment]
Okey so we did this. Thoguth that we didnt want to change the variables to not break things. But might have been mistaken

**Comment by PabstMirror** [comment]
Fixed all usage of those stringnames in ace.
Should help when they get re-translated (avoid people using the old term again)

**Pull request merged**
