### PR TITLE
Remove Atropine

### PR DESCRIPTION
**Pull request by alganthe**
**When merged this pull request will:**
- Remove atropine

As per decided, atropine has been commented out for the moment, I feel that deleting the entries would just create more work later when we decide to add it back.

### CODE REVIEW

**Comment by SilentSpike** [comment]
>when we decide to add it back

Never again 😆

**Comment by Drofseh** [comment]
I'd like to keep it personally.

Either way though, won't removing it like this break currently existing missions/loadouts.

**Comment by jonpas** [comment]
We are removing it that has been decided. If anyone wants it, they can take this and make a patch mod that adds it. However there is little reason with epi and adenosine doing what they should.

**Comment by dedmen** [comment]
> Either way though, won't removing it like this break currently existing missions/loadouts.

Missions no, they should just print a warning to RPT.
Saved loadouts in arsenal, not for ACE Arsenal, it just won't add that item when you load the loadout.
BI Arsenal loadouts might break?

**Comment by alganthe** [comment]
BI arsenal loadouts break even if you don't do anything, I don't think we should worry about that.

**Comment by SilentSpike** [comment]
We could just `scope=1` the item and keep it removed from the treatment config so it does nothing?

**Comment by dedmen** [comment]
> I don't think we should worry about that.

Same thought.

> We could just scope=1 the item and keep it removed from the treatment config so it does nothing?

I did the same in TFAR worked fine until BI changed Arsenal to no longer accept scope=1 items, but they reverted that "fix" for now.

**Comment by Drofseh** [comment]
I'd like a scope=1 item as well, maybe with strings that say it no longer has a use in Ace medical.

**Comment by grenadier2510** [comment]
I am in favor of the return of atropine!

**Pull request merged**
