### PR TITLE
Split keybindings into different sub-categories

### PR DESCRIPTION
**Pull request by Glowbal**
#327

### CODE REVIEW

**Comment by Glowbal** [comment]
Categories are:
- ACE3
- ACE3 Equipment
- ACE3 Vehicle
- ACE3 Movement
- ACE3 Weapon

**Comment by commy2** [comment]
:+1:

**Comment by jaynus** [comment]
:thumbsup:

**Comment by esteldunedain** [comment]
:+1: Should we localize the categories?

**Comment by commy2** [comment]
Yes. But how would that work witout having different categories for each language?

**Comment by esteldunedain** [comment]
> Yes. But how would that work without having different categories for each language?

I think it would probably work: categories on the former language would not appear any more when you change to a new one and restart the mission (your bindings wouldn't carry over either). But I don't think this is supported by CBA and we probably shouldn't localize it just in case.

**Comment by Glowbal** [comment]
Localization wouldn't work. We could give is the unlocalized string, for example `STR_ACE_Movement_KeyBindingCategory`, but that would require CBA to localize the category name before displaying it. That would be the best solution.

At the moment however, if we want to keep keybindings when changing the language we have to stick with what we have now.

**Comment by esteldunedain** [comment]
Yep, I agree

**Comment by commy2** [comment]
So, merge?

**Comment by Glowbal** [comment]
Merge all the things

**Pull request merged**
