### PR TITLE
adding missing string on tchinese

### PR DESCRIPTION
**Pull request by dfr1238**
add some missing string on tchinese,hope all clear now
first time using [tabler](https://github.com/bux/tabler/releases) to finish

### CODE REVIEW

**Comment by commy2** [comment]
Pink wall, is this due to line endings?

**Comment by dfr1238** [comment]
> 
> 
> Pink wall, is this due to line endings?

i am sorry,but i don't understand wat you mean?

**Comment by commy2** [comment]
https://stackoverflow.com/questions/19394754/how-to-solve-the-wall-of-pink-in-github-for-windows

**Comment by dfr1238** [comment]
> 
> 
> https://stackoverflow.com/questions/19394754/how-to-solve-the-wall-of-pink-in-github-for-windows

got it,i update xml now

**Comment by commy2** [comment]
Translation is now complete. Thank you. :>

**Pull request merged**
