### PR TITLE
Disables the CfgAISkill class to prevent it from affecting players.

### PR DESCRIPTION
**Pull request by ulteq**

### CODE REVIEW

**Comment by jaynus** [comment]
@commy2 should probably merge this just to okay it.

**Comment by esteldunedain** [comment]
:+1: for merging this @commy2. We confirmed that at least the `reload` entry is messing with the ability to fire quickly in semi mode.

**Comment by commy2** [comment]
I read the conversation on Slack. GJ BI. I'll merge it after a bit of testing with the new AI behavior

**Comment by bux578** [comment]
Did someone make a ticket out of it? We should tell BI, just in case. I would do it but i have no idea what to write.

**Comment by esteldunedain** [comment]
We did no tickets AFAIK. It's not that easy to describe though.

**Pull request merged**
