### PR TITLE
French loc improvement

### PR DESCRIPTION
**Pull request by 11RDP-LoupVert**
(French) text as it is clutters the interface interface, making it
uneasy for medic to use the it smoothly.
 

Hopefully suggested changes fixes that.

There were a few typos and, in my opinion, unaccurate or missing
translation.
Based on French Army Field Manual, actual paramedical personnel and past
work on XMedSys.

**When merged this pull request will:**
- Improve Medical usability in French version

### CODE REVIEW

**Comment by 11RDP-LoupVert** [comment]
How can I fix that Jon?

**Comment by jonpas** [comment]
Your editor has to be changed to use spaces instead of tabs, then you have to mass convert it back (as your commit converts everything to tabs).

**Comment by jonpas** [comment]
@alganthe could we get you to take a quick look at this?

**Comment by alganthe** [comment]
French is quite verbose, the best way to avoid that issue is to use the line display instead of the circular one.
There's also the option to remove the verbs and simply add the name of the item that is to be used, it may lead to confusion.

**Comment by jonpas** [comment]
Doesn't fix the root issue, but improves translations by shortening them and keeping them on point (alganthe's words), I'd say merge.

**Pull request merged**
