### PR TITLE
Update spanish stringtables.xml

### PR DESCRIPTION
**Pull request by arv187**
**When merged this pull request will:**
-Update spanish stringtables.xml

### CODE REVIEW

**Comment by PabstMirror** [comment]
Looks like the base of this branch is outdated, so this pull request's diff is weird
but I think the commit https://github.com/acemod/ACE3/pull/8124/commits/6868fa5600841a3e929531367e6c500306a39c65 is valid

it should be possible to cherry pick that? we can try to fix this if you are not sure, let us know

**Comment by arv187** [comment]
> 
> 
> Looks like the base of this branch is outdated, so this pull request's diff is weird
> but I think the commit [6868fa5](https://github.com/acemod/ACE3/commit/6868fa5600841a3e929531367e6c500306a39c65) is valid
> 
> it should be possible to cherry pick that? we can try to fix this if you are not sure, let us know

Yes, of course.
I did this years ago:
fork repository and download with my github desktop app

Since then I pull request before modify anything (but I think that is made in my master branch, not ace3 master)
After that I edit with tabler app https://github.com/bux/tabler/
And push to my master branch
Create a push request in ACE3 web repository since my master branch repository

So, I need to find out how make a pull request from ACE3 master to my master branch  😔

**Comment by arv187** [comment]
Check if there are deletions of others languages

**Comment by arv187** [comment]
I will send again a pull request when all is right

**Pull request closed without merging**
