### PR TITLE
Explosive fix attach

### PR DESCRIPTION
**Pull request by PabstMirror**
Fix for #863

Attached the real explosive if the placeholder explosive was attached to something. (see fnc_placeExplosive.sqf)
Also added private variables

### CODE REVIEW

**Comment by CorruptedHeart** [comment]
Thanks @PabstMirror does it still allow defusing? There's some attachTo stuff with the defuse helper object. So just want to confirm that it still works.

**Comment by PabstMirror** [comment]
Just tested.  (Helper attachedTo Explosive attachedTo Vehicle) chain seems to work fine.

**Comment by ulteq** [comment]
> does it still allow defusing?

I test tested it both on master and this branch. The defusing issues are identical:

* I was not able to defuse explosives which were attached to a vehicle.
* I was able to defuse explosives which were placed on the ground.

On master branch, I was able to defuse the (not properly attached) explosive after I moved the vehicle away.

**Comment by CorruptedHeart** [comment]
> This branch introduces a weird flickering effect of the interaction menu, when you hover over icons in the "Select a Trigger" submenu.
I don't think this branch introduces it. I think it was already there. It was fixed https://github.com/acemod/ACE3/commit/d7d43ce3b1c922b647f9eaa4cd0fe53f8b2911bb which might have been after this branch was created.

**Comment by ulteq** [comment]
> It was fixed d7d43ce

You are right. I just tested it with the latest changes on master. Problem gone.

**Comment by ulteq** [comment]
detonateExplosive deletes the vehicle which the explosive was attached to.

**Comment by bux578** [comment]
> detonateExplosive deletes the vehicle which the explosive was attached to.

That's a mean bomb it even removes the vehicle from existence. IIRC i've seen such a bomb in Star Trek called a time bomb.

**Comment by alganthe** [comment]
it's a a truly scary piece of time wiggling weaponry.

**Pull request closed without merging**
