### PR TITLE
load things into vehicles

### PR DESCRIPTION
**Pull request by commy2**
- [ ] req. https://github.com/KoffeinFlummi/ACE3/pull/186

vanilla inventory menory point:
getText (configfile >> "CfgVehicles" >> typeOf cursorTarget >> "memoryPointSupply")

### CODE REVIEW

**Comment by WastedMike** [comment]
I cant wait for this to be in ACE.

**Comment by SzwedzikPL** [comment]
> I cant wait for this to be in ACE.

:+1:

**Comment by Glowbal** [comment]
Added an intial load in cargo module.

Works for all ammo crates and static weapons.

**Comment by jonpas** [comment]
Great work @Glowbal !

I'd say better interaction menu names would simply be `Load` and `Cargo`.

**Comment by Glowbal** [comment]
Good suggestion @jonpas :+1:

**Pull request merged**
