### PR TITLE
[medical] remove collision of bandage litter

### PR DESCRIPTION
**Pull request by dedmen**
I've just observed a car crashing into a floating bandage litter and loosing it's front wheels.
All other litter items don't have collision. Just these.

### CODE REVIEW

**Comment by TheMagnetar** [comment]
Why? Is this not a realistic behaviour?

**Comment by JonBons** [comment]
@dedmen I'm not sure if I'm testing this properly but it looks like littergeneric.p3d still has collision.

https://i.imgur.com/XgJdw8p.png
https://i.imgur.com/zetUxTu.jpg

**Comment by dedmen** [comment]
Oh yeah. Must've overlooked that one.

**Comment by dedmen** [comment]
Also removed shadow/collision from normal items as they are too small anyway and performance.
funFact. bodyBagItem's shadowLOD was 90° rotated versus res lod.

**Pull request merged**
