### PR TITLE
workflow - fix hemtt lint, drop sqflint, fix ext clippy warnings

### PR DESCRIPTION
**Pull request by PabstMirror**
(Will only apply after merge)

- Fix hemtt lint I think
ref https://github.com/acemod/ACE3/actions/runs/10434328035/job/28897068966?pr=10144
switch to `xcopy /y` use this to overwrite files

- Disable sqflint, hasn't been updated in years (it doesn't understand `#`), 
I don't think anyone looks at it's output?
it does have the ability to catch some things like undefined/shadowed vars
but it has too many false positives to be useful imho

- Fix extension lint
ref https://github.com/acemod/ACE3/actions/runs/10434327964/job/28897069005
```
  thread 'main' panicked at extension/build.rs:2:46:
  Open git repo: Error { code: -36, klass: 7, message: "repository path '/__w/ACE3/ACE3' is not owned by current user" }
```
possibly related to https://github.com/libgit2/libgit2/issues/6279
but I don't really understand as checkout is doing
```
Adding repository directory to the temporary git global config as a safe directory
/usr/bin/git config --global --add safe.directory /__w/ACE3/ACE3
```
in any case it shouldn't hurt to make it buildable without git?

### CODE REVIEW

**Comment by PabstMirror** [comment]
failing when building on linux
`if cfg!(feature = "clipboard")` doesn't seem to be working?
```
error[E0433]: failed to resolve: use of undeclared crate or module `clipboard`
  --> extension/src/lib.rs:26:17
   |
26 |                 clipboard::group()
   |                 ^^^^^^^^^ use of undeclared crate or module `clipboard`
```

**Comment by PabstMirror** [comment]
ugly but should work?
```
#[cfg(feature = "clipboard")]
#[arma]
fn init() -> Extension {
    Extension::build()
        .version(env!("GIT_HASH").to_string())
        .group("artillery", artillery::group())
        .group("ballistics", ballistics::group())
        .group("clipboard", clipboard::group())
        .command("break_line", break_line::break_line)
        .command("fcs", fcs::get_solution)
        .command("version", || env!("GIT_HASH"))
        .finish()
}

#[cfg(not(feature = "clipboard"))]
#[arma]
fn init() -> Extension {
    Extension::build()
        .version(env!("GIT_HASH").to_string())
        .group("artillery", artillery::group())
        .group("ballistics", ballistics::group())
        .command("break_line", break_line::break_line)
        .command("fcs", fcs::get_solution)
        .command("version", || env!("GIT_HASH"))
        .finish()
}
```

**Comment by BrettMayson** [comment]
I can't remember why I added that feature, potentially it's not needed?

**Comment by PabstMirror** [comment]
hemtt check fails, but should work after merge

**Review by BrettMayson — APPROVED** [review]

**Pull request merged**
