### PR TITLE
Arsenal - Remove unused VRTraining class from Arsenal config

### PR DESCRIPTION
**Pull request by dedmen**
Ref: https://forums.bohemia.net/forums/topic/193161-ace3-a-collaborative-merger-between-agm-cse-and-ace/?do=findComment&comment=3387061

apparently doesn't exist with contact loaded, and we don't use it anyway.

### CODE REVIEW

**Comment by commy2** [comment]
Can you still Tab key through the controls in the right order?

**Comment by dedmen** [comment]
> Can you still Tab key through the controls in the right order?
It was just a unused reference, and a one causing a error at that.
A proper config binarizer like Mikeros should even remove that useless reference 🤔

**Comment by commy2** [comment]
That doesn't answer my question. Also, learn to quote on Github, you're a prefessional computer person.

**Comment by jonpas** [comment]
> A proper config binarizer like Mikeros should even remove that useless reference

Hide the error instead of telling the user to fix it? Doesn't sound like Mikero to me.

**Pull request merged**
