### PR TITLE
Fastroping - Add user setting to confirm cutting ropes

### PR DESCRIPTION
**Pull request by PabstMirror**
When you are in queue to fast rope the "Fast rope" action fades in and out as other people are using it and it is possible to accidentally select the "cut ropes". This adds a user setting to move the action to a 2nd level.

Could also just make this default and drop the setting.

### CODE REVIEW

**Comment by Drofseh** [comment]
I think this should be the default as well.

**Comment by bux** [comment]
Default... and needs an icon ;)

**Comment by alganthe** [comment]
agreed, it should be default.

imho confirm shouldn't have an icon, but fastrope and cut ropes definitely should, it would help people differentiate the two at a quick glance.

**Comment by bux** [comment]
We should have an icon for cutting the primary parachute, iirc

**Pull request merged**
