### PR TITLE
Add goggle overlay support for Contact update Blindfolds

### PR DESCRIPTION
**Pull request by veteran29**
**When merged this pull request will:**
- Title

Texture by @BaerMitUmlaut 
<details>
  <summary>Images</summary>
  
image

</details>

### CODE REVIEW

**Comment by commy2** [comment]
Should name the file _ca before converting with img2paa.

**Comment by veteran29** [comment]
I have done that. Then renamed to `Blindfold.paa`. Conversion was done with TexView 2

**Comment by jonpas** [comment]
> Then renamed to `Blindfold.paa`.

Why though?

**Comment by veteran29** [comment]
> Why though?
Because all other textures in the component are named like that.

**Comment by commy2** [comment]
They shouldn't.

**Comment by veteran29** [comment]
Should I fix all of them then?

**Comment by commy2** [comment]
Make sure to convert them when named _ca, so
- paa → png
- rename _ca.png
- png → paa

**Comment by jones140** [comment]
Overlay for new respirator gear as well?

**Comment by jonpas** [comment]
> just a reminder that goggles effects are now client settable, so you would need to enforce the setting if you need the effect for a mission

This should have an override then.

**Comment by veteran29** [comment]
Merge? Goggles can be forced via setting. Option to force googles per goggle class should be separate PR anyway imho.

**Comment by commy2** [comment]
Agreed. Goggles component needs a rewrite anyway. Once I find my life again, I will do it.

**Pull request merged**
