### PR TITLE
Medical - Move GUI and Feedback settings to separate category

### PR DESCRIPTION
**Pull request by amsteadrayle**
**When merged this pull request will:**
- Move the settings in the GUI and Feedback modules to a separate category

### IMPORTANT

- If the contribution affects [the documentation](https://github.com/acemod/ACE3/tree/master/docs), please include your changes in this pull request so the documentation will appear on the [website](https://ace3.acemod.org/).
- [Development Guidelines](https://ace3.acemod.org/wiki/development/) are read, understood and applied.
- Title of this PR uses our standard template `Component - Add|Fix|Improve|Change|Make|Remove {changes}`.

### CODE REVIEW

**Comment by amsteadrayle** [comment]
This splits the medical settings into two categories: The settings for admins and the settings for players. Now (almost) every setting in the "ACE Medical" category is global and only admins care about them. Most of the settings in the "ACE Medical Interface" category are local and players might care about them.

arma3_x64_GPhYtShh3C

**Comment by jonpas** [comment]
I like it.

**Comment by LinkIsGrim** [comment]
I like it.

**Review by LinkIsGrim — APPROVED** [review]

**Review by PabstMirror — APPROVED** [review]

**Comment by veteran29** [comment]
I like it.

**Pull request merged**
