### PR TITLE
Execute take nozzle actions only on progress bar success

### LINKED ISSUE #3739: Cancelling Refuel Nozzle Taking results in inability to take it again
**Arma 3 Version:** `1.58` (stable)
**CBA Version:** `2.3.1+` (dev https://github.com/CBATeam/CBA_A3/commit/85b0b95cb80775da4f13f561bb6a5de115ace0cd)
**ACE3 Version:** `3.5.1+` (dev ab09e0989bb3789defeff2ccbdf2c54eb5a77ce5)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- Taking a nozzle, cancelling the progress results in inability to take the nozzle again. It also moves you into position like you would be holding it and sometimes forces you to walk.

**Steps to reproduce:**
- Take Nozzle
- Cancel action
- Observe

**Where did the issue occur?**
- Editor (Singleplayer)

**Placed Modules:**
- None

**RPT log file:**
- N/A

### PR DESCRIPTION
**Pull request by jonpas**
**When merged this pull request will:**
- Moves part of "Take Nozzle" action execution into progress bar on success (set force walk, holster weapon and 2 variables) - fixes #3739 
- Prettifies `params` usage in take nozzle function.

Tagging @GitHawk for review

### CODE REVIEW

**Comment by GitHawk** [comment]
Please leave the `REFUEL_HOLSTER_WEAPON` at its original place.

**Comment by jonpas** [comment]
But that will effectively put the weapon on the back even if taking fails. That might be wanted behaviour though. If it is, then I suggest we add unholster to progress bar on failure.

**Comment by GitHawk** [comment]
It is wanted behaviour. So add unholster to fail.

**Comment by jonpas** [comment]
It doesn't really unholster it due to the progress bar being too fast, but I think it's not bad, player simply takes the weapon out manually.

I also added lowered animation fix, which makes holstering a bit nicer.

**Comment by GitHawk** [comment]
I timed the progress bar to the animation speed.
Either manual unholster or a delayed execute is required.

**Comment by jonpas** [comment]
Yeah, I think manual unholster is the best, I will remove the on failure to make sure it won't cause undesired issues.

**Comment by GitHawk** [comment]
:+1:

**Pull request merged**
