### PR TITLE
Count the commander camera as a 3rd person camera

### PR DESCRIPTION
**Pull request by Tenga**

### CODE REVIEW

**Comment by commy2** [comment]
Related: https://github.com/acemod/ACE3/issues/422

>`isNull (missionNamespace getVariable ["BIS_DEBUG_CAM",objNull])`
>
>returns false if the camera is opened.

Also I think
`cameraView in ["EXTERNAL", "GROUP"]`
is slightly faster

**Comment by commy2** [comment]
We might want to also add the VA cam to that condition. Dunno it's script handle though.

**Comment by Tenga** [comment]
Splendid camera cam object:
`missionNamespace getVariable ["BIS_fnc_camera_cam", objNull]`

Arsenal cam object:
`uiNamespace getVariable ["BIS_fnc_arsenal_cam", objNull]`

**Comment by commy2** [comment]
Excellent stuff. This maybe warrants a function in common to check if any of their cams are enabled.

**Comment by Tenga** [comment]
Since these are a bit lengthy and not always descriptive enough, would you consider this to be against coding guidelines?
```SQF
(
    cameraView in ["EXTERNAL", "GROUP"] || // 3rd person camera and Commanders camera
    !isNull (missionNamespace getVariable ["BIS_DEBUG_CAM", objNull]) || // bis_fnc_cameraOld camera
    !isNull (missionNamespace getVariable ["BIS_fnc_camera_cam", objNull]) || // Splendid camera
    !isNull (uiNamespace getVariable ["BIS_fnc_arsenal_cam", objnull]) // Arsenal camera
)
```

**Comment by commy2** [comment]
No thats perfect. Could make use of lazy evaluation though. (Curly brackets)

(
    cameraView in ["EXTERNAL", "GROUP"] || // 3rd person camera and Commanders camera
    {!isNull (missionNamespace getVariable ["BIS_DEBUG_CAM", objNull])} || // bis_fnc_cameraOld camera
    {!isNull (missionNamespace getVariable ["BIS_fnc_camera_cam", objNull])} || // Splendid camera
    {!isNull (uiNamespace getVariable ["BIS_fnc_arsenal_cam", objnull])} // Arsenal camera
)

**Comment by Tenga** [comment]
Ok, since you suggested and I've added more BI "Feature cameras", like the ones for the animation viewer, establishing shot, I've gone ahead and added a new function to the ace_common.

As naming is always the hard part, I've gone ahead and named it fnc_isFeatureCameraActive.

The function detects the following feature cameras:
- Classic camera (BIS_fnc_cameraOld)
- Splendid camera (BIS_fnc_camera)
- Arsenal camera (BIS_fnc_arsenal)
- Animation viewer (BIS_fnc_animViewer)
- Establishing shot (BIS_fnc_establishingShot)

**Comment by commy2** [comment]
Good stuff :+1:

**Pull request merged**
