### PR TITLE
Fix grenade impact sounds

### LINKED ISSUE #7073: Missing grenade impact sounds
**Arma 3 Version:** `1.92` (stable)
**CBA Version:** `3.11.2` (stable)
**ACE3 Version:** `3.12.6` (stable)

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
With ACE running, you get grenade pin pull sounds, but no grenade impact sounds (when grenade hits the floor or wall for example). 
With no mods loaded, you get grenade impact sounds, but no pull pin sounds (since ACE adds that).

**Steps to reproduce:**
https://www.youtube.com/watch?v=vbAb25obxCM&feature=youtu.be
Comparison with, and without ACE

**Where did the issue occur?**
Everywhere

### PR DESCRIPTION
**Pull request by jonpas**
**When merged this pull request will:**
- Fix #7073 

Were removed in #3923 "ridiculous clinking sound", but it also removes impact sounds - this commit reverts that change.

### CODE REVIEW

**Comment by jonpas** [comment]
This does not appear to be impact sounds at all!

It is just a priming when you pull the pin, there is still no impact sound. :thinking:

**Comment by jonpas** [comment]
Never mind, it does fix impact sounds, there are just none if you throw it on the floor at your feet.

However, the sound played next to pin sound is pretty bad, I suggest you have a look @commy2 and see if you notice it now.

**Comment by jonpas** [comment]
I would close this, neither solution is perfect, but the one in `master` is preferably I think.

**Comment by commy2** [comment]
See: https://github.com/acemod/ACE3/issues/7073#issuecomment-544237582

**Pull request closed without merging**
