### PR TITLE
Medical performance improvements

### PR DESCRIPTION
**Pull request by Glowbal**
Reduced performance issues when a lot of units (15+) are taking damage within a few frames from each other.

Should reduce/eliminate the game freeze with basic medical and improve advanced medical performance by ~30% on average.

### CODE REVIEW

**Comment by esteldunedain** [comment]
:+1: Excellent. Now go for basic medical!

**Comment by commy2** [comment]
All the frames

**Comment by esteldunedain** [comment]
> Now go for basic medical!
Oh, you already included that fix! Great

**Comment by Glowbal** [comment]
### Basic

Original:
```ace_medical_handleDamage_basic_counter: Average: 0.628418s / 3207 = 0.195952ms```

New:
```ace_medical_handleDamage_basic_counter: Average: 0.332031s / 2947 = 0.112668ms```

The major difference is however not having a massive amount of new public frame handlers being added, which is what caused the freezing for basic.

### Advanced

Original:
```ace_medical_handleDamage_caching_counter: Average: 0.286995s / 3343 = 0.0858495ms```

New:
```ace_medical_handleDamage_caching_counter: Average: 0.287354s / 4283 = 0.0670916ms```

**Comment by esteldunedain** [comment]
Obviously is would be great to bring basic at least inline with advanced. Anyway, GJ glowbal!

**Comment by CamoSteve** [comment]
:+1:

**Pull request merged**
