### PR TITLE
overhaul movable markers

### LINKED ISSUE #5921: Make movable markers work on briefing map
This #5397 don't work.

### LINKED ISSUE #5980: after move a marker marking on map is toggled on
**Arma 3 Version:** stable
**CBA Version:** stable
**ACE3 Version:** stable

**Mods:**
```
- CBA_A3
- ace
```

**Description:**
after move a marker with ALT+mouseclick... marking on map is toggled on you need to mouseclick to turn off again

**Steps to reproduce:**
- Place marker
- move the marker with ALT+mouse
- the yellow map marking is active after moving
- need to click on map to disable

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

### PR DESCRIPTION
**Pull request by commy2**
**When merged this pull request will:**
- close #5921
- [x] cut back on the global use, objectively better variable / function names
- [x] fix ended event not resetting correct alpha etc.
- [x] cba_settings_fnc_init
- [x] work in briefing
- close #5980
- [x] map gestures interferes

### CODE REVIEW

**Comment by chris579** [comment]
There should be an extra options for enabling/disabling moving in briefing.

**Comment by commy2** [comment]
Why?

**Comment by chris579** [comment]
In big missions this could end up in a clusterfuck.

**Comment by commy2** [comment]
Then only allow it for group leaders? The setting can be changed mid mission too.

**Comment by chris579** [comment]
Ok, you are right.

**Pull request merged**
