### PR TITLE
remove weapon select in favor of the new controls from bi

### PR DESCRIPTION
**Pull request by commy2**
Keeps grenade select and engine on/off

### CODE REVIEW

**Comment by gienkov** [comment]
I liked to have it in one place. In what way bi-way is better at this?

**Comment by commy2** [comment]
Changing weapons while moving ha nothing to do with this.

The commands from BI are limited, in that the primary weapon key toggles through the GL attachmnt, while our system had a seperate key for that.

It's just weird to have the same thing twice I guess.

**Comment by esteldunedain** [comment]
My vote goes toward opinion keeping this in ACE, with most keybinds unbinded by default. I still like our system better than that of vanilla.

**Comment by commy2** [comment]
Another related question is , what new controls should be used for selecting grenades / selecting throw modes. I feel like if we remove the weapn select (1-5) , then we might aswell move the rest to clear up for the AI command menu.

**Comment by esteldunedain** [comment]
> then we might aswell move the rest to clear up for the AI command menu.

Makes sense, but I think the exact opposite. I feel the AI command menu is a niche thing for ACE players, as we have a strong focus on MP, and most players don't ever use it (some devs use them for testing, but that's also very niche ;) )

But again, I'd really love keeping those binds as we do now so I'm definitely biased.

**Comment by BryanBoru** [comment]
I found Dyslexi's suggestion for making High Command controls be 'ALT+x' was a great way to free up keybinds, I just wish BI had thought of that first. 
At this point, it would have to be a Mod Supplied recommendation that people go in and rebind all their Command keybinds to include ALT+ in all of the number keys and Function keys. I imagine most people won't be happy with that task. (I, however, think it's worth the freedom of having both available.

Come to think of it, is there a way to add something to edit or override the user configs to add those keybind alterations to the Command controls through the mod?

**Comment by commy2** [comment]
>Come to think of it, is there a way to add something to edit or override the user configs to add those keybind alterations to the Command controls through the mod?

I think a .dll could do that, but nothing in Arma. They are stored in a .Arma3Profile file in the documents folder I believe.

**Comment by Legolasindar** [comment]
I not understand the topic. What new controls from BIS? I not found new controls for select weapons in BIS.
I like the AGM style, 1-4 for select the weapons, and others for grenades is very very usefull. The selection with this is very ease and fast, my vote is for the AGM style.

**Comment by esteldunedain** [comment]
> I like the AGM style, 1-4 for select the weapons, and others for grenades is very very usefull. The selection with this is very easy and fast, my vote is for the AGM style.

Arma 3 now offers keybinds  for weapon switching (pistol, rifle, launcher, etc), which are unbinded by default.Using those you can set it up very closely to how AGM did it. However, we decided not to remove that feature from ACE yet, but leave our keys unbinded too.

**Pull request merged**
