### PR TITLE
Vehicle Damage - Add API to prevent AI from dismounting from immobile vehicles

### PR DESCRIPTION
**Pull request by johnb432**
**When merged this pull request will:**
- Title.

### IMPORTANT

- If the contribution affects [the documentation](https://github.com/acemod/ACE3/tree/master/docs), please include your changes in this pull request so the documentation will appear on the [website](https://ace3.acemod.org/).
- [Development Guidelines](https://ace3.acemod.org/wiki/development/) are read, understood and applied.
- Title of this PR uses our standard template `Component - Add|Fix|Improve|Change|Make|Remove {changes}`.

### CODE REVIEW

**Review by jonpas — APPROVED** [review]

**Review by BrettMayson — APPROVED** [review]

**Review by veteran29 — CHANGES_REQUESTED** [review]
Why not simply use engine command?

https://community.bistudio.com/wiki/isAllowedCrewInImmobile

**Comment by johnb432** [comment]
> Why not simply use engine command?
> 
> https://community.bistudio.com/wiki/isAllowedCrewInImmobile

I'm trying to find a good reason why not to use `isAllowedCrewInImmobile`, but I honestly can't. It would make it compatible with mods using the vanilla command, which would be my exact use case.

For context:

ACE sets it when a vehicle is spawned, see https://github.com/acemod/ACE3/blob/9d168756df555cdc71db40343bc9d4c9bfd196b2/addons/vehicle_damage/functions/fnc_addEventHandler.sqf#L99

ACE unsets it here
https://github.com/acemod/ACE3/blob/9d168756df555cdc71db40343bc9d4c9bfd196b2/addons/vehicle_damage/functions/fnc_abandon.sqf#L23

Since you have already reviewed - @jonpas and @BrettMayson, do you have any objection to the vet's proposal?

**Comment by BrettMayson** [comment]
No objections from me

**Comment by johnb432** [comment]
>but I honestly can't

@veteran29 I was too tired to see that using `isAllowedCrewInImmobile` won't work, unless we change more stuff (which I don't think it possible).

As said previously, https://github.com/acemod/ACE3/blob/9d168756df555cdc71db40343bc9d4c9bfd196b2/addons/vehicle_damage/functions/fnc_addEventHandler.sqf#L99
sets it to true. How are we supposed to distinguish us vs. other sources setting that? Using status effects would imo not solve the problem.

I was going to add a `if (isAllowedCrewInImmobile _vehicle) exitWith {};` check inside `FUNC(abandon)`, but that won't work since that is always going to be `true` - and if it isn't, they would bail. I'm fairly certain that `allowCrewInImmobile` is set to true so that we can handle bailout ourselves.

**Pull request merged**
