### PR TITLE
Italian translation (Add & Fix)

### PR DESCRIPTION
**Pull request by AtixNeon**
Added Italian translation for:
-advanced fatigue
-advanced throwing
-cook off
-dogtags
-gunbag
-ui-scopes and much more...

Fixed a lot of grammatical errors

### CODE REVIEW

**Comment by bux** [comment]
Thank you @AtixNeon 
Grazie!

**Comment by AtixNeon** [comment]
Please, tell me if there will be new lines to translate, I'm glad to help you ! Amazing Team !

**Comment by bux** [comment]
@AtixNeon Thank you for the kind words.
You can check https://github.com/acemod/ACE3/issues/367 from time to time, to see if there's something missing. The first post is always up to date.

**Comment by AtixNeon** [comment]
Got it, thank you !

**Pull request merged**
