### PR TITLE
Overheating - Add Bolt Type stat to arsenal

### PR DESCRIPTION
**Pull request by Drofseh**
**When merged this pull request will:**
- Adds an arsenal stat to show if the weapon is open or closed bolt.
- Adds an arsenal stat to show if the weapon's barrel can be swapped.

### IMPORTANT

- If the contribution affects [the documentation](https://github.com/acemod/ACE3/tree/master/docs), please include your changes in this pull request so the documentation will appear on the [website](https://ace3.acemod.org/).
- [Development Guidelines](https://ace3.acemod.org/wiki/development/) are read, understood and applied.
- Title of this PR uses our standard template `Component - Add|Fix|Improve|Change|Make|Remove {changes}`.

### CODE REVIEW

**Comment by Drofseh** [comment]
Would it be width adding a stat for barrel changeability as well?

Something like Barrel Type: Changeable/Fixed

**Comment by PabstMirror** [comment]
Should we combine into a single stat?
```
open
closed
open [QR Barrel]
```

**Comment by Drofseh** [comment]
I'd rather they be separate

**Comment by LinkIsGrim** [comment]
Fine with two stats, but decrease priority IMO. Should be one of the last stars shown.

**Comment by Drofseh** [comment]
> Fine with two stats, but decrease priority IMO. Should be one of the last stats shown.

I set it to 0 initially but then it ended up between two stats from ballistics

**Comment by LinkIsGrim** [comment]
priority can be negative

**Comment by Drofseh** [comment]
renaming the branch closed this PR, new PR is #9719

**Pull request closed without merging**
