### PR TITLE
Get In - Get In Actions for interactMenu

### PR DESCRIPTION
**Pull request by PabstMirror**
Rough WIP
Adds Get In Actions to the interaction menu. (inspired by commy's thing from AGM)

Scans the configFile and adds the action to the correct memory point for each seat location.

concept

Problems:
- [ ] Get in is often mirrored across, the y axis, 
e.g. You can get in on a car's backseats the same from either side, but there's only a single mem point
Still need to figure out how to read this from config.

- [ ] It does add clutter to a vehicles actions.  But could be toggled off by a user setting.

- [ ] Mem points sometimes look like their floating in midair.  Tough to find a reliable way to put the action on the hull of the vehicle and at a consistent height.

### CODE REVIEW

**Comment by SzwedzikPL** [comment]
Really cool feature. Any chance for 3.3.0 ?

**Comment by PabstMirror** [comment]
Many vehicles have multiple doors that have the same mem point name.
E.G.: 4 door car, 1 driver door and 3 cargo doors
`selectionPosition` only returns the one point, not all.

Right now there isn't much I can do.  `selectionPosition` is getting updated in 1.49, but right now it doesn't look like it will have what I need (the "allpoints" from VBS).
Alternelty, we may have a way to read these directly from the .p3d file, but that is still a little ways out.

**Comment by jonpas** [comment]
You could group together same type using subactions until better solution.

**Comment by SzwedzikPL** [comment]
> You could group together same type using subactions until better solution.

:+1:

**Pull request closed without merging**
