### PR TITLE
Add Error Checking to Settings + MapGesture Settings

### PR DESCRIPTION
**Pull request by PabstMirror**
This fixes an issue with nametags and hearing where there are settings that are clientSettable, but could be forced via a module. Modules run after GVAR(settings) is publicVariabled, so the force wasn't applied to clients.

* This moves the PV until after modules have run on the server.
* Adds a exclusive `isSingular = 1` to setting configs. A duplicate setting module would normaly have no effect, this just adds a warning.
* Adds warnings to `setSetting` for bad setting names, data types or other reasons it fails.
* @MikeMatrix - I cleaned up some map gesture stringtables, added exit code if the old pbo is already running and changed the logic on the color settings to be be optionally forced to clients.

### CODE REVIEW

**Comment by MikeMatrix** [comment]
:+1:

**Comment by PabstMirror** [comment]
Merged PR  #2826 into this branch - Read settings from paramsArray (params in description.ext)

**Comment by esteldunedain** [comment]
:+1: Nice, I like #2826 and the singular flag.

**Comment by Glowbal** [comment]
:+1:

**Comment by captainblaffer** [comment]
Is this feature added in the nightvision pbo? I personally find it very annoying gameplay wise and would like to disable it.

**Pull request merged**
