### PR TITLE
use 'getUnitLoadout' instead of 'FUNC(getAllGear)' and deprecate it

### PR DESCRIPTION
**Pull request by commy2**
**When merged this pull request will:**
- title
- massive performance improvement every frame

```
B_Soldier_F

getUnitLoadout player
0.0251 ms
10000/10000

player call ACE_common_fnc_getAllGear
0.535412 ms
1892/10000
```

### CODE REVIEW

**Comment by SilentSpike** [comment]
:+1: Man that `switch` block was ugly. All looks good to me - assuming that `FUNC(inventoryCheck)` in scopes defaults to `ACE_Player` anyway.

**Comment by Glowbal** [comment]
Perfect :+1:

**Comment by commy2** [comment]
>Man that switch block was ugly.
Yeah. It really sucked that `assignedItems` reports them in a undefined order. Now with `getUnitLoadout` you always know what map/watch/gps the unit actually has or if it's `""`.

**Comment by esteldunedain** [comment]
Yay!!

**Comment by PabstMirror** [comment]
Just to be aware: `getUnitLoadout` includes magazines ammo, so it changes with each bullet fired

Which means we throw the `playerInventoryChanged` event each round fired:
`ace_common_playerInventoryChanged_counter: Average: 0.121994s / 256 = 0.476539ms`

It is a change in behaviour from before, and the event is expensive.

So we save ~0.07ms speedup in the common case, but get a ~0.5ms slowdown when firing.

**Comment by esteldunedain** [comment]
@PabstMirror, do you think there's a quick way to exclude the current ammo of the loaded magazine from the `isEqual` test? Maybe overwriting it in the array before comparing it?

I think that should probably be good enough, because we'd still detect reloads, as in those the content of the inventory also changes.

**Comment by esteldunedain** [comment]
Oh, btw. According to @commy2's number, this PR saves 0.47ms each frame, so if those are right then the impact when firing should compensate.

**Comment by commy2** [comment]
We could add another step to the PFH that somehow filters out all the numbers from the array and only  do the event when something else changes.

**Comment by esteldunedain** [comment]
I was thinking of just clearing out the current magazines in the array before comparing them

**Comment by PabstMirror** [comment]
From same source for comparison:

0.0904 ms `ACE_common_fnc_getAllGear`
0.011 ms `getUnitLoadout`
0.47 ms playerChanged event

It might be fine as is:

600rnds/sec = ~5ms per second when full auto wasted on playerChanged event
(0.8*50 fps) = ~4ms per second saved on loadout checking (faster no matter if firing or not!)

**Comment by esteldunedain** [comment]
Sure, but if we could filter out the inventory event from firing it would be even better.

**Comment by PabstMirror** [comment]
Something like this would filter out currently loaded mag:
```
_data = getUnitLoadout ACE_player; 
if (!((_data select 0) isEqualTo [])) then { 
    (_data select 0) set [4, -1];
    (_data select 0) set [5, -1];
}; 
if (!((_data select 1) isEqualTo [])) then { 
    (_data select 1) set [4, -1]; 
    (_data select 1) set [5, -1];
}; 
if (!((_data select 2) isEqualTo [])) then { 
    (_data select 2) set [4, -1];
    (_data select 2) set [5, -1];
};
```

**Comment by esteldunedain** [comment]
I bet that should take way less than 05 ms

**Comment by commy2** [comment]
I already have made that. PR incoming.

**Pull request merged**
