### PR TITLE
Make attach/detach hint look uniform

### PR DESCRIPTION
**Pull request by mharis001**
**When merged this pull request will:**
- Add space at the bottom of hint to make it look nicer
- Before: 
attach_before
- After:
attach_after

### CODE REVIEW

**Comment by jonpas** [comment]
What if the item name is longer or shorter?

**Comment by mharis001** [comment]
The `STR_ACE_Attach_Item_Attached` string always places the attached/detached text on the second line and the item name on the first.
The items that are able to be attached/detached is when they have `ACE_Attachable != ""` defined.
Tested it with all items and even the longest names have some padding on the sides.

**Comment by bux** [comment]
IMO, It would be better to add a general inner padding to the box instead of adding a blank line as a spacer.

**Comment by jonpas** [comment]
@bux I am not sure how that works in Arma UI, but it is no CSS. 😆

**Pull request merged**
