### PR TITLE
Translations - Improve Russian

### PR DESCRIPTION
**Pull request by V1nsyara**
Update:
- medical_treatment
- hearing
- hitreactions

### CODE REVIEW

**Comment by johnb432** [comment]
@V1nsyara Can you double check that I didn't mess the translations up when merging master into this PR?

**Comment by V1nsyara** [comment]
@johnb432 as I understand it, a new line has been added and some lines have been changed?
image

**Comment by V1nsyara** [comment]
However, everything went well

**Comment by johnb432** [comment]
> @johnb432 as I understand it, a new line has been added and some lines have been changed? image

A lot has changed, all stringtables files have been sorted. Since it's good, I'll merge.

**Review by johnb432 — APPROVED** [review]

**Pull request merged**
