### PR TITLE
ATragMX and RangeCard - Fixed incorrect MRAD conversions

### PR DESCRIPTION
**Pull request by ulteq**
- This greatly improves the accuracy of the MRAD output in both modules
- Old and incorrect conversion factor: 3.38 [(360 * 60) / 6400]
- New and correct conversion factor: 3.44 [54 / (5 * PI)]

### CODE REVIEW

**Comment by jonpas** [comment]
Merging into master is fine. I will pull master in for another build today evening.

Or at least `release-3.11.0`, not `release`.

**Comment by QuickDagger** [comment]
Source | Circle [MIL] | 1 MOA = | 1 MIL =
Russians | 6000.00 | 0.27777778 MIL | 3.60000000 MOA
NATO | 6400.00 | 0.29629630 MIL | 3.37500000 MOA
USMC | 6283.00 | 0.29087963 MIL | 3.43784816 MOA
Swedish | 6300.00 | 0.29166667 MIL | 3.42857143 MOA
Trigonometry | 6283.19 | 0.29088821 MIL | 3.43774677 MOA

**Comment by QuickDagger** [comment]
Source | Circle [MIL] | 1 MOA = | 1 MIL =
Russians | 6000.00 | 0.27777778 MIL | 3.60000000 MOA
NATO | 6400.00 | 0.29629630 MIL | 3.37500000 MOA
USMC | 6283.00 | 0.29087963 MIL | 3.43784816 MOA
Swedish | 6300.00 | 0.29166667 MIL | 3.42857143 MOA
Trigonometry | 6283.19 | 0.29088821 MIL | 3.43774677 MOA

**Comment by ulteq** [comment]
JBM Ballistics and Strelok both seem to be using `3.43774677`, which is what we now use, to avoid further confusion.

**Pull request merged**
