### PR TITLE
Remove: pain diagnosis on dead patients

### PR DESCRIPTION
**Pull request by alef**

### CODE REVIEW

**Comment by SilentSpike** [comment]
I'd probably just stick this into the `alive _target` check further up in the function. Unless they have to appear in a specific order.

**Comment by alef** [comment]
I've thought that the information of finding someone bleed to death to be useful, so I've removed only the _pain_ message.

**Comment by SilentSpike** [comment]
I mean I'd move lines 39-43 to below line 24 :smile:

**Comment by alef** [comment]
I would prefer to keep the order of messages.

**Pull request merged**
