### PR TITLE
Try to handle -1 from eden modules

### PR DESCRIPTION
**Pull request by PabstMirror**
Help with  #3339

Bandaid for the bad mission modules in 3den.

E.G. a setting like:
```
    class GVAR(medicSetting) {
        category = CSTRING(Category_Medical);
        value = 1;
        typeName = "SCALAR";
        values[] = {"Disabled", "Normal", "Advanced"};
    };
```

It should be safe to assume that as the setting has a "values" array, which are strings shown for the server setting exporter, then a value of -1 wouldn't make any sense.

I've tried looking for cases were this might not be safe to assume, I can't find any so far.

### CODE REVIEW

**Comment by esteldunedain** [comment]
Wouldn't stuff like this fail:

https://github.com/acemod/ACE3/blob/master/addons/nametags/CfgVehicles.hpp#L13-L44

**Comment by PabstMirror** [comment]
They are handled before this func is called. - https://github.com/acemod/ACE3/blob/master/addons/nametags/functions/fnc_moduleNameTags.sqf#L26-L28

A module set to 0 (disabled) will be saved as -1, which means `FUNC(moduleNameTags)` will never make the call to `EFUNC(common,readSettingFromModule)` and the setting won't be forced off.

Because -1 and 0 are both valid options from the module; I don't see any good way to fix.
But this PR won't make those cases any worse.

**Comment by esteldunedain** [comment]
Perfect :+1: for merging this and making a warning on release

**Comment by commy2** [comment]
`missionVersion`
What about missions made with 3den and then converted to 2D? I know this is a common practice to avoid bugs with the HC, but the 3den values would still be wrong. I think this check should be removed for maximum compatibility.

**Comment by PabstMirror** [comment]
Good point commy, the check should be safe on any mission version

**Pull request merged**
