### PR TITLE
added the addons folder to gitignore

### PR DESCRIPTION
**Pull request by alganthe**
**THIS IS FOR gh-pages ONLY**
Removes the need to delete the folder every time you checkout from master (or any branch tracking it)

### CODE REVIEW

**Comment by bux578** [comment]
image

^ that's the way I'm doing it

**Comment by alganthe** [comment]
would be simpler to just add the proper gitignores no ?

**Comment by bux578** [comment]
simpler when changing, but that is just way faster for me. And "node_modules" (that is when you start to tweak the css/js files and build them) with its file name  lengths > 250 chars won't let you easily switch branches (git can't delete those files, because the names are too long).

**Comment by alganthe** [comment]
Make sense, closing.

**Pull request closed without merging**
