### PR TITLE
MicroDAGR - Add mode switching keybinds

### PR DESCRIPTION
**Pull request by JoramD0**
**When merged this pull request will:**
- Add 2 keybinds to cylce through the MicroDAGR modes/pages.
- Changed ERROR to LOG in fnc_saveCurrentAndSetNewMode to stop it from spamming the RPT, internal function anyway.

### CODE REVIEW

**Comment by commy2** [comment]
"Spamming the log"?

**Comment by bux** [comment]
Why is it spamming the log? Better to find the issue for that than to silence a probably valid log.

**Comment by JoramD0** [comment]
Poor choice of words, the line I changed is a check to see if there is a display, which used to write an error to the RPT if there wasn't any. I can't imagine it would be beneficial to do the same check twice so I changed it to LOG so it would still error with full debug mode enabled.

**Review by jonpas — APPROVED** [review]
That error is rather pointless there. Condition is now used to stop execution on keybinds if MicroDAGR is not opened, rather than duplicating it.

Simple and short.

**Review by mharis001 — COMMENTED** [review]
Works well. 

Can we get this to keep cycling between modes once the "end" for the keybind's direction is reached? For example, for the next mode keybind, after mode 6, it goes back to mode 0 (and the opposite for previous mode keybind). Essentially, mimic the behaviour of ALT-TABing and ALT-SHIFT-TABing.

**Comment by jonpas** [comment]
We could, I believe that was a design decision by @JoramD0. And I kind of like it, but I also see the point now that you could only use one button to cycle between all pages and wouldn't need to bind both. :thinking:

**Comment by JoramD0** [comment]
It was indeed a design choice, I could do either but I honestly like the way it is currently.

Could also go all out and somewhat overcomplicate it and add a setting

**Review by mharis001 — APPROVED** [review]

**Comment by bux** [comment]
Where does the magic number for the mode come from? A variable/constant/define would make sense for it.

**Comment by JoramD0** [comment]
@bux Do you mean these? https://github.com/acemod/ACE3/blob/master/addons/microdagr/script_component.hpp#L26-L33

**Comment by commy2** [comment]
Yes, although that could be considered out of scope for this PR. Up to you.

**Comment by JoramD0** [comment]
Okay, I forgot to use the defines which was my last commit.

I am still confused as to what you guys want me to do.

**Comment by bux** [comment]
Way better, thank you.

Having a seemingly random number appear in code makes the next person to work on it wonder, why someone used this number in particular.

**Review by PabstMirror — APPROVED** [review]

**Pull request merged**
