### PR TITLE
Merge pull request #2 from acemod/master

### PR DESCRIPTION
**Pull request by Jastreb**
Merge ACE3/Master with my fork

### CODE REVIEW

**Comment by Jastreb** [comment]
I fucked up. Again. Closing.

**Comment by PabstMirror** [comment]
I think you're going the wrong way, from command line you can do:

```
git fetch upstream
git checkout master
git merge upstream/master
```

**Comment by Jastreb** [comment]
I'm an idiot trying to use a freaking windows github client...sorry...

**Comment by PabstMirror** [comment]
In the windows github client, you can right click on the repo's name on the left side, and "Open in Git Shell" to do these commands.

**Pull request closed without merging**
