### PR TITLE
Dragging - Add setting for Max Weight Coefficient

### PR DESCRIPTION
**Pull request by LinkIsGrim**
**When merged this pull request will:**
- Add a setting to skip weight calculations entirely.

### IMPORTANT

- If the contribution affects [the documentation](https://github.com/acemod/ACE3/tree/master/docs), please include your changes in this pull request so the documentation will appear on the [website](https://ace3.acemod.org/).
- [Development Guidelines](https://ace3.acemod.org/wiki/development/) are read, understood and applied.
- Title of this PR uses our standard template `Component - Add|Fix|Improve|Change|Make|Remove {changes}`.

### CODE REVIEW

**Comment by jonpas** [comment]
A better name would be "Ignore Weight".

**Comment by LinkIsGrim** [comment]
Fucking hell I forgot to switch branches

**Comment by PabstMirror** [comment]
I wonder if this would work better as a scalar?
something like
```
        <Key ID="STR_ACE_Dragging_arcadeMode_DisplayName">
            <English>Weight Limit Coefficent</English>
        </Key>
        <Key ID="STR_ACE_Dragging_arcadeMode_Description">
            <English>Modifies weight limit calculations. Set to 0 to ignore all.</English>
        </Key>
```

**Review by PabstMirror — APPROVED** [review]

**Comment by LinkIsGrim** [comment]
I don't like "Weight Limit", leads to me think lower means you can carry less.

**Comment by Drofseh** [comment]
> I don't like "Weight Limit", leads to me think lower means you can carry less.

"Max Weight Coef" maybe?

**Pull request merged**
