### PR TITLE
Add reload mutex as canInteractWith condition

### LINKED ISSUE #3938: Finger, AdvancedThrowing and Wipe Goggles ignore the reload mutex causing animation issues
**Arma 3 Version:** `1.60` (stable)
**CBA Version:** `2.4.1` (stable)
**ACE3 Version:** `3.5.1` (eedb406ae5605c2dd5663fd0b2de2bb9bf501b6b with advancedThrowing branch)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
- If you do any action mid-reloading that will trigger an animation, it will freeze the weapon animation and will not return a mag that animation took from the gun at the start of the reloading. Addons that do not check if unit is reloading so far I found advanced throwing and finger pointing. Weapon switching actually has the same problem as vanilla arma, weapon animation freezes, but the unit animation continues and it returns the mag in the end so it's not a huge deal.
Video.
https://www.youtube.com/watch?v=WwmbtaGV05I
First reload, without interupting.
Second, pointing. Interrupts reload animation, doesn't return the mag reload took at the start.
Third, grenade throw. Same.

**Steps to reproduce:**
- Pick something with a long reload animation.
- Point forward mid-reloading.
- Throw a grenade mid-reloading.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Placed Modules:**
- Pointing Module.

**RPT log file:**
- N/A.

### PR DESCRIPTION
**Pull request by commy2**
**When merged this pull request will:**
- adds !GVAR(isReloading) as condition for canInteract
- fixes #3938

### CODE REVIEW

**Comment by esteldunedain** [comment]
Hey, hold on. `GVAR(isReloading)` doesn't exist yet. It's currently called `GVAR(ReloadMutex)` and it is defined only on the `gestures` module. IMO it should be moved to common and renamed.

Also I wonder if it would be possible to set the variable from an `AnimChanged` EH instead of `actionKeys` for better reliability and joystick support.

**Comment by commy2** [comment]
`AnimChanged` or any other anim event handler don't trigger for gestures like the reload animations.

**Comment by esteldunedain** [comment]
> AnimChanged or any other anim event handler don't trigger for gestures like the reload animations.

Too bad; I was half expecting that reply though.

**Comment by commy2** [comment]
^ this is my version of at least supporting the modifier keys. Not finished, because:

```
_a = -1207959552; (_a + 1) in [_a]
-> true
```
FML

**Comment by jonpas** [comment]
Note: still needs additional canInteract checks on keybinds in all affected components.

**Comment by commy2** [comment]
No, it's a canInteractWith condition.

**Comment by jonpas** [comment]
Yes, whatever it's named. :P

**Comment by esteldunedain** [comment]
> Yes, whatever it's named. :P

Nah, @jonpas . @commy2 means that this works automatically, without having to add any extra checks

**Comment by commy2** [comment]
I think it's impossible to work with these offsets:
`(-1207959552 + 32) + 1207959552`
`0`

**Comment by esteldunedain** [comment]
It's a precision issue; the numbers are being treated as floating point

**Comment by commy2** [comment]
Yeah, but that means that actionKeys cannot be used for this - at least not when we want to support modifier keys.

**Comment by esteldunedain** [comment]
>  at least not when we want to support modifier keys.

Let's not support it. I doubt anyone uses one for reloading

**Comment by jonpas** [comment]
> Nah, @jonpas . @commy2 means that this works automatically, without having to add any extra checks

Ah, in that case - awesome!

**Comment by commy2** [comment]
I don't like how easy it is to trick the reload mutex.

Pressing R in a reloading incompatible stance starts the timer and when then actually doing the reloading, the isReloading value is reset mid reload.

**Comment by esteldunedain** [comment]
Yeah, it's pretty unreliable stuff. 

> incompatible stance

Those can be detected from config I guess, right?

**Comment by PabstMirror** [comment]
Current interaction conditions take args `[_player, _target]`,
so you could do something like check if another player can interact with you.

This new condition would only be valid for ACE_player, 
but I really don't think this is a problem just wanted to mention it.

**Comment by commy2** [comment]
Same with the old one. In the end it's just a hacky work around. : /

**Comment by CorruptedHeart** [comment]
I assume this event is fired too late? (https://community.bistudio.com/wiki/Arma_3:_Event_Handlers#Reloaded)[Reloaded] and can't be used in any way?

**Comment by commy2** [comment]
Reloaded is fired when the animation ended. too late...

I even thought about SoundPlayed event handler, but the only noise the player makes that it can't pick up is reloading it seems ...

**Comment by commy2** [comment]
Should be good now.

Question: Do we want this as general canInteractWith condition, or would we be better of by if we add it to Finger / Advanced Throwing / Wipe Goggles directly?

**Comment by jonpas** [comment]
I'd say general is fine.

**Comment by esteldunedain** [comment]
@commy2, does this trigger when reloading vehicles?

**Comment by commy2** [comment]
It triggers whenever you press the reload key while being in the mission display.

**Comment by jonpas** [comment]
Merge @commy2 ?

**Pull request merged**
