### PR TITLE
Medical - Add Painkillers

### PR DESCRIPTION
**Pull request by LinkIsGrim**
**When merged this pull request will:**
- Add painkillers. Finally.

Implementation based on https://github.com/Theseus-Aegis/Mods/tree/master/addons/medical, with increased timeTillMaxEffect.

I've always wanted to see painkillers added as a magazine, though (I feel like that's interesting as API and example), but this is simpler and shouldn't break things for communities with their own implementations too much.

### IMPORTANT

- If the contribution affects [the documentation](https://github.com/acemod/ACE3/tree/master/docs), please include your changes in this pull request so the documentation will appear on the [website](https://ace3.acemod.org/).
- [Development Guidelines](https://ace3.acemod.org/wiki/development/) are read, understood and applied.
- Title of this PR uses our standard template `Component - Add|Fix|Improve|Change|Make|Remove {changes}`.

### CODE REVIEW

**Comment by LinkIsGrim** [comment]
It works (as it should), but could probably use a better model for litter/item, as they're currently shared and are not the best:


Something based off the inventory icon (orange-ish tube) would be ideal.

**Comment by Drofseh** [comment]
What painkiller are we trying to simulate here?
A previous unit I was in implemented painkillers in their house mod, and these are the values that were used to simulate something like ibuprofen or acetaminophen/paracetamol
```c++
class PainKillers {
    painReduce = 0.1;
    timeInSystem = 1200;
    timeTillMaxEffect = 60;
    maxDose = 25;
    incompatibleMedication[] = {};
    viscosityChange = 5;
};
```
we were actually considering reducing `painReduce` below 0.1 as we felt it was a bit too strong for that type of analgesic

**Review by jonpas — APPROVED** [review]
Neat!

**Comment by jonpas** [comment]
@Drofseh Our values just come from what we wanted in gameplay. Something that reduces pain for a short period of time, not a longer-term solution.

**Comment by LinkIsGrim** [comment]
Missing CfgPatches entries still

**Comment by johnb432** [comment]
> Missing CfgPatches entries still

Done.

**Review by johnb432 — CHANGES_REQUESTED** [review]
Syringe sound is played when painkillers are administered.

Either we remove the sound entirely or replace it with something else.

**Comment by Zman6258** [comment]
> Either we remove the sound entirely or replace it with something else.

[pills.zip](https://github.com/acemod/ACE3/files/13981746/pills.zip)

Recorded and edited myself so there's no chance of any rights issues, if y'all wanna use it. Five-second audio file in .ogg format of a bottle of pills opening, getting shaken a little to represent actually taking one, then closing again.

**Review by johnb432 — APPROVED** [review]
LGTM

**Pull request merged**
