### PR TITLE
Grenades - Add grenade rolling

### PR DESCRIPTION
**Pull request by johnb432**
**When merged this pull request will:**
- Title.
- Some grenades roll further than others, range is between 3-10 m depending on shape.
- Tested with Vanilla fragmentation and smoke grenades, as well as ACE flashbangs.
- Tested with 3CB BAF and RHS grenades, an overwhelming majority of grenades work well, some even better than others (e.g. stick hand grenades).
  ~~Grenades such as `rhs_mag_nspd` and `rhs_mag_rdg2_black` are not set on their side properly and tumble instead of roll.~~ Added a config entry for `setVectorDirAndUp`.
  ~~`rhsgref_mag_rkg3em` just isn't meant for this type of thing and fails horribly.~~ Don't allow grenades to be rolled which have fuse times under 1 second.
  ~~I was thinking of adding a config entry for the rotation of the grenade (default would be 90°) for the first issue, but I'm not sure what to do about the second issue. Thoughts on both?~~

### IMPORTANT

- If the contribution affects [the documentation](https://github.com/acemod/ACE3/tree/master/docs), please include your changes in this pull request so the documentation will appear on the [website](https://ace3.acemod.org/).
- [Development Guidelines](https://ace3.acemod.org/wiki/development/) are read, understood and applied.
- Title of this PR uses our standard template `Component - Add|Fix|Improve|Change|Make|Remove {changes}`.

### CODE REVIEW

**Comment by johnb432** [comment]
`vn_t67_grenade_mag` and `vn_chicom_grenade_mag` are causing issues, because they can't simply be rotated like most other cylindrical grenades (they are thrown like an arrow, meaning they would need to be rotated along a different axis than is currently possible).
I was thinking of adding a config entry compatible with `setVectorDirAndUp`, but honestly I'm not looking forward to the math that needs to be done. It would be the most flexible solution however, so probably worth it. Thoughts?

**Comment by johnb432** [comment]
> `vn_t67_grenade_mag` and `vn_chicom_grenade_mag` are causing issues, because they can't simply be rotated like most other cylindrical grenades (they are thrown like an arrow, meaning they would need to be rotated along a different axis than is currently possible). I was thinking of adding a config entry compatible with `setVectorDirAndUp`, but honestly I'm not looking forward to the math that needs to be done. It would be the most flexible solution however, so probably worth it. Thoughts?

Solved easier than anticipated with `setVectorDirAndUp`.

**Review by Mike-MF — APPROVED** [review]
Tested this (without RHS/SOG) and it works quite nicely, tested rolling in and out of buildings, up and down hills etc. Nicely done.

**Comment by johnb432** [comment]
Made some minor changes
- added optimisation done by Pabst
- prevented players from rolling grenades when in FFV
- only force switch grenade modes when throwables are usable (= on foot or in FFV)

**Review by Mike-MF — APPROVED** [review]
Tested FFV and same stuff I tested last time, all good.

**Review by PabstMirror — APPROVED** [review]

**Pull request merged**
