### PR TITLE
10 Digit grids for GPS

### PR DESCRIPTION
**Pull request by VKing6**
#514
There weren't any functions for this in SA_M109 like I thought, so I wrote one.
Currently backend only. I want to change the number of displayed digits in the MicroDAGR and any other position display eventually, but I'll probably need help with that.

Backend:
- [x] Return correct grid for maps with reversed Y-axis
- [x] Return correct grid for maps that don't start in 000000
- [x] Return correct grid for positions with negative x/y 
- [X] Add option to return single string instead of Array
- [X] Add option to return MGRS zone and 100km square
- [ ] Decrement 100km grid at negative x/y
- [ ] Change Latitude correction to common system once it's moved out of ace_weather

Frontend:
- [X] Change MicroDAGR position readout to 10-digit grid
- [X] Change MicroDAGR target (laser) position readout to 10-digit grid
- [ ] Allow entry of 10-digit waypoints
- [ ] Commanche gunner's display

### CODE REVIEW

**Comment by kavinsky** [comment]
Are you gonna make the inverse of `fnc_getMapGridFromPos`?

**Comment by PabstMirror** [comment]
CBA_fnc_mapGridToPos:

```
x1 = getPos player;
x2 = [x1, true] call compile preprocessFileLineNumbers "vgrid.sqf";  
x3 = x2 call CBA_fnc_mapGridToPos;
x4 = x1 distance x3;
```
x4 is ~100m on sarhani.  
The issue is the stupid maps that have northing lines going the wrong way.
also for the CBA team: https://dev.withsix.com/issues/76198 (although you're manual setting `cba_common_mapReversed ` seems to fix this)

image

**Comment by VKing6** [comment]
Yea the reversed northing lines are annoying. I've compensated for it in the GridFromPos function, but the only good way to fix it is to change the grid direction in the config.
At UO we have our own override config to fix it for all the maps we're using, but I don't know how feasable it would be for us to do that in ACE.

**Comment by jaynus** [comment]
That's fine leaving it on the map maker to fix their shit. (Looking at you AIA)

**Comment by VKing6** [comment]
@jaynus: Do you know where the grid readout in the Comanche gunner's view is defined?

**Comment by austinjames314** [comment]
When are the currently implemented changes likely to be released? This is the number one issue with ACE3 for me right now, and the stuff you've already got ticked off would be good enough for me.
 I guess it's a matter of waiting for 3.1.0 to come out? but I have no idea how to find out when that might be.
 Keep it up! This is super important, awesome work you're doing!

**Comment by austinjames314** [comment]
As #514 was part of the 3.1.0 milestone but has been closed, is this still going to be in the next release?

**Comment by esteldunedain** [comment]
No, we closed the issue because we'll track progress on this PR instead.

**Comment by austinjames314** [comment]
Um OK. So is this still planned for the 3.1 release? (I'm hoping so).

**Comment by ulteq** [comment]
This won't go into 3.1.0, but the new DAGR has a 8 digit output (10m grids).

**Comment by austinjames314** [comment]
Woohoo!

**Comment by BryanBoru** [comment]
10 digit is kind of rediculous and unrealistic. demand is demand but i dont
see the use above 8

**Comment by austinjames314** [comment]
Actually anything less that 10 figures is unrealistic, you've clearly never used an actual GPS before:
Dagr display
Dagr in use
Civilian GPS display with 10 figure grid

As for the use, when I'm using the Mk6 mortar with my mortar fire calculator, I can get rounds within 10m of the target... As long as I have a 10 figure grid to work off. This is usually given to me by an FO working off a reference point that's visible on the map.
 If I have to use 8 figure grids, that 10m accuracy goes to 20 meters. Still pretty good, but not as good as it could be. Plus it's unrealistic to only get 8 figure grids.

That all said, I'm loving that it's been improved. :smile: Looking forward to trying it out.

**Comment by VKing6** [comment]
Heh show me a GPS device that _doesn't_ give you 10 digits.

I'll hopefully be able to do some more work on this in the next couple of weeks.

**Comment by BryanBoru** [comment]
I am referring to usefulness in this computer sim, not usefulness in real life. I am not going to complain about the lack of flushing toilets either, because that is a simulation we just don't need to waste time on.

**Comment by VKing6** [comment]
With GPS guided artillery rounds, it *is* a question of usefulness in game.

**Comment by bux578** [comment]
I totally agree with @VKing6

**Comment by austinjames314** [comment]
Yep. Even just with the unguided Mk6 Mortar it makes a huge difference. It's totally a matter of in-game usefulness.

**Pull request merged**
