### PR TITLE
Possible fix medical unload patient

### PR DESCRIPTION
**Pull request by ViperMaul**
Fixes - Unload patient does not work #1375

### CODE REVIEW

**Comment by ViperMaul** [comment]
@gienkov, @Desty84: 
If you have the ability give this PR a test in Dedicated MP with more than one player as I have and confirm the fix with multiple vehicles.

**Comment by Desty84** [comment]
If you can tell me how to get the latest master with this PR?
I can only download the lastest master, but not with this PR

(I didn´t use git very much in the past, so i have no idea how to do this)

**Comment by gienkov** [comment]
Will test this tomorrow morning and report back.

**Comment by jonpas** [comment]
> If you can tell me how to get the latest master with this PR?
I can only download the lastest master, but not with this PR

> (I didn´t use git very much in the past, so i have no idea how to do this)


`git checkout possibleFixMedicalUnloadPatient`

**Comment by ViperMaul** [comment]
@Desty84 
It depends on which git client you are using but the key is exactly what jonpas said. You need to checkout the branch. Then after you are done you need to check out the master branch to get back to main branch.

**Comment by Glowbal** [comment]
Once it has been confirmed this fixes it, this can go in. :+1: Thanks @ViperMaul

**Comment by gienkov** [comment]
Starting testing of this on our dedicated, will report asap.

**Comment by gienkov** [comment]
Confirmed working on dedicated!

**Comment by Glowbal** [comment]
Thanks @ViperMaul and @gienkov

**Pull request merged**
