### PR TITLE
Add handheld maglite ML300L flashlight, clean up flashlight addon

### PR DESCRIPTION
**Pull request by bux**
**When merged this pull request will:**
- Add a maglite flashlight model
    - Will use pistol slot
- Cleanup of flashlight addon folder

- [x] Holding animation
- [x] ~Different Light modes?! 2 intensity levels, 1 strobe level~
- [x] Remove weapon attachment options
- [x] Allow to be used as map light

### CODE REVIEW

**Comment by commy2** [comment]
Done. Only issue I found is `Warnings in z\ace\addons\flashlights\data\maglite_ml300l.p3d:shadow(1000)`, but idk how to fix that.

**Comment by bux** [comment]
Left clicking (shooting) throws following message in a popup and in rpt
`16:53:06 Warning Message: Size: 'bin\config.bin/CfgRecoils/recoil_default/' not an array`

**Comment by bux** [comment]
Should we keep the binarized rtm or the unbinarized one?

**Comment by commy2** [comment]
I'd say both. One to keep this component functional in dev builds, one to make further changes to the animation file possible. Ideally the build would handle animations and binarize them, but this is out of scope for this PR, and a minor issue overall due to the low number of RTM files in ACE.

**Comment by bux** [comment]
the unbinarized rtm can't be used to edit the animation afaik. There's nothing in Alwarran's tool for blender to "import" an rtm. Which - to me - means that an rtm has to be exported from the blender rig source file each time one wants to change the animation

**Comment by commy2** [comment]
Should probably get the project files then and put them into the component or into a dev folder.

**Comment by bux** [comment]
Done.

**Comment by commy2** [comment]
Merge?

**Pull request merged**
