### PR TITLE
Sandbags surfaces update

### PR DESCRIPTION
**Pull request by jonpas**
**When merged this pull request will:**
- Add Tanoa surfaces support to Sandbags
- Check height above terrain, if more than 0.05 disallow sandbags (when on buildings and similar)
- Check if in water (ATL is negative during shallow swimmable water for some reason)
- Use private keyword

### CODE REVIEW

**Comment by PabstMirror** [comment]
Should we update the list in ace_trenches as well?
https://github.com/acemod/ACE3/blob/master/addons/trenches/functions/fnc_canDigTrench.sqf

**Comment by jonpas** [comment]
Oh, didn't even realize there is a function that's exactly the same. I'll move it to common even.

**Comment by PabstMirror** [comment]
Can build trench on stratis runway
surfaceType = "#GdtStratisConcrete";   CfgSurface -> `concrete` has dust of 0.15

Maybe we should keep the blacklist and just use the dust as a backup for external maps?
Or tweak dust cutoff?

**Comment by nateberkopec** [comment]
I have a crapton of mods/terrains loaded, noticing lots of concrete surfaces use 0.15 for `dust`. XCam-Taunus appears to use 0.15 for many of their road surfaces as well.

**Comment by jonpas** [comment]
Will look at it and possibly just keep dust as fall-back if higher value will cause other problems.

**Comment by jonpas** [comment]
Changed to fall-back for dust, as it does not work as expected for some cases.

**Pull request merged**
