### PR TITLE
Load in cargo

### PR DESCRIPTION
**Pull request by esteldunedain**
AGM logistics port by @MarcBook.

@commy2 said he wanted to do a full rewrite, so leaving up to him to review this and see how in line it is what he was planning on doing. Maybe it can serve as a base for that.

EDIT: It contains the ventral backpack commits too, that should be reverted in this branch.

### CODE REVIEW

**Comment by MarcBook** [comment]
Maybe something like this. I hope everybody knows what I mean.

**Comment by alganthe** [comment]
yep I do, didn't saw the code but do you plan on using setmass for realism ?

**Comment by MarcBook** [comment]
If it is possible: YES. I also will lock the passenger seats

**Comment by alganthe** [comment]
you may want to add an other one big enough to block the whole back of the vehicle to fit a MRAP or a container up there.

**Comment by MarcBook** [comment]
I think, I'll do with a packing-algorithm.

**Comment by jaynus** [comment]
vehicledamage model information seems applicable to this.

**Comment by NemesisRE** [comment]
So sad that this is not in 3.2.0 it's still a functionality which which is missing in ACE

**Comment by Glowbal** [comment]
Closed in favour of #275

**Comment by NemesisRE** [comment]
This means we will not have a visible cargo system?

**Pull request closed without merging**
