### PR TITLE
Increase "load in bodybag" action time to 15s

### PR DESCRIPTION
**Pull request by gienkov**
Around 15 seconds seems optimal (for dead bodies that are left in **one** piece).

### CODE REVIEW

**Comment by jokoho48** [comment]
:+1:

**Comment by MikeMatrix** [comment]
:+1:

**Comment by gienkov** [comment]
I still think this should take longer, maybe 30 seconds? Should be done in calm situations anyway.

**Comment by SzwedzikPL** [comment]
@gienkov dont forget that is only the game.

**Comment by bux578** [comment]
@SzwedzikPL Than ace3 might be wrong for you :stuck_out_tongue_winking_eye:

**Comment by SzwedzikPL** [comment]
@bux578 xD

**Pull request merged**
