### PR TITLE
Explosive reflection

### PR DESCRIPTION
**Pull request by NouberNou**
This is built into frag (which already is a misnomer for the system since it does spalling too, but that is disabled).

Works on any explosive, but usually only applies to large ones (IDH value > 10)

### CODE REVIEW

**Comment by jaynus** [comment]
Will we need to MP/battle test this first before merging @NouberNou ? 

I assume this is all local only Explosion magic, so it shouldn't have a network perf element, but can you just verify that for me? 

Also, we probably need to test this in conjunction with some interesting rapid-explosion scenarios, like shooting HE 30mm/20mm into a window? or a MK19 shooting into windows, even.

I was thinking about implementing frag on the 20mm, but not sure if its worth it.

**Comment by ViperMaul** [comment]
Checking status...

**Comment by jaynus** [comment]
This needs to be conflict resolved, I'll merge tonight

**Comment by Glowbal** [comment]
This could do with a setting to enable/disable reflections. 

Might also be good to do this PR for next milestone instead of 3.0.0.

**Comment by ViperMaul** [comment]
Moved to the next milestone. More time for testing.

**Pull request closed without merging**
