### PR TITLE
ASDG- Fail gracefully if attachments not compatible

### PR DESCRIPTION
**Pull request by PabstMirror**
To reproduce: run @ASDG without the ace_asdg_comp - hit ctrl-L, laser pointer is gone.

ASDG messes with `PointerSlot` and compatible items.
If a user has ASDG installed without our compatibilty patch, then it seems like none of our ACE_x attachements will work on weapons.

With laser pointers, on switch we delete the current and then add the new laser.  If that new laser isn't compatible then it won't get added and the user will have nothing.

This dumps several error messages in the RPT and if the `ACE_nextModeClass` doesn't get added then it reverts back to the current so nothing is lost.

### CODE REVIEW

**Comment by jaynus** [comment]
Should we be adding exceptions for addons in the core code? Shouldn't this be handled more gracefully with them? 

I don't want to get into the habit of having to hard-code 50 exceptions into our core code all over the place like this. I don't like it at all. We should probably request ASDG to handle this aspect of it for us, no?

**Comment by PabstMirror** [comment]
ASDG is fairly unique as a mods goes, we really only have 1 rail compatibility mod to worry about.

I don't think ASDG can't really do anything about this.  They have to change PointerSlot/compatibleItems on vanilla weapons to use their system.

**Comment by esteldunedain** [comment]
:+1:

**Comment by jonpas** [comment]
When ASDG JR is in CBA, this will have to be changed afaik (unless the class will stay the same).

**Pull request merged**
