### PR TITLE
Add CanInteractWith checks for repair

### PR DESCRIPTION
**Pull request by PabstMirror**
#2525

There is no canInterctWith check for repair actions, so right now you can remove wheels when underwater or handcuffed.

Does it make sense to do repairs underwater, if so we will want to add an exception for that??

### CODE REVIEW

**Comment by commy2** [comment]
>Does it make sense to do repairs underwater, if so we will want to add an exception for that??

I'd say no.

**Comment by SilentSpike** [comment]
Agreed :+1:

**Comment by Glowbal** [comment]
Isn't this handled by the interaction actions?

**Comment by PabstMirror** [comment]
createAction/addActionToXXX just takes a raw conditional

**Comment by commy2** [comment]
^ This is true. Asked esterldunedain about this, but iirc it was done to leave flexibility or something.

**Pull request merged**
