### PR TITLE
don't default to polish on the switch units module description, fix #2469

### LINKED ISSUE #2469: SwitchUnits: Missing english translation
STR_ACE_SwitchUnits_Module_Description defaults to polish right now.

### PR DESCRIPTION
**Pull request by commy2**

### CODE REVIEW

**Comment by jokoho48** [comment]
@gienkov @Tourorist @ToasterBR @alganthe could some of you translate it to english?

**Comment by commy2** [comment]
I don't even know what the translators wrote there.

**Comment by alganthe** [comment]
I can probably find back the proper strings, give me a sec.

**Comment by SilentSpike** [comment]
Google translation of all strings there:
```
This module allows you to change the page during the game.
This module allows for switching the lubricant available to the parties.
This module allows you to change the side available to players.
This module allows players to switch between the available units.
This module allows the change of faction players
```

Take the average and use that :laughing:

**Comment by SzwedzikPL** [comment]
`<Polish>Moduł ten pozwala na zmianę strony w trakcie gry.</Polish>`
Module allows to switch side during the game.

**Comment by gienkov** [comment]
Module allows you to switch side during the game.

**Comment by commy2** [comment]
Done.

**Pull request merged**
