### PR TITLE
Collision lights keybind

### PR DESCRIPTION
**Pull request by tbeswick96**
**When merged this pull request will:**
- Add collision lights keybind
- Unbound by default (any suggestions for good default?)

### CODE REVIEW

**Comment by jonpas** [comment]
I don't think a default keybind is necessary for this. But if we want it, some modifier on top of the vanilla "Lights" action.

**Comment by tbeswick96** [comment]
Only issue with a modifier on top of L I found is that they are already bound to other things, or aren't great for vehicles.
Ctrl+L is something already (Change sight mode in CBA I think)
Shift+L not sure if it's something, however this will start the engine unwanted if Shift is bound as throttle
Alt+L seems to turn normal lights on as well (could be CBA bug?)

**Comment by PabstMirror** [comment]
> Note that the vehicle has to be local, for global variant use Arma 3 Actions "CollisionLightOn"/"CollisionLightOff"

Could use the `action` version, but vehicle should always be local to driver.

**Comment by jonpas** [comment]
Can finally bind that to my joystick!
_Next step is BI giving us joystick API so I don't have to use 3rd party software._

**Pull request merged**
