### PR TITLE
nozzle additonal check condition

### PR DESCRIPTION
**Pull request by gienkov**
Have you ever did refuel at gas station with **engine on**?

### CODE REVIEW

**Comment by commy2** [comment]
Yes, I have. : - )

**Comment by jokoho48** [comment]
@commy2 bad idea :D i like the idea :+1:

**Comment by VKing6** [comment]
Not sure that idea applies to tanks.
They wouldn't drive up to the refuel bowser and turn their engines off just for the few minutes it takes to refuel.

**Comment by gienkov** [comment]
@VKing6 you can still start up tank engine within seconds in Arma so...

**Comment by SilentSpike** [comment]
Isn't this invalid syntax?

**Comment by gienkov** [comment]
I'm gonna test but I used wiki https://community.bistudio.com/wiki/isEngineOn

**Comment by SilentSpike** [comment]
I mean because the condition is using lazy evaluation and you've added a non-lazy condition onto the end

**Comment by gienkov** [comment]
Um... tell me how to fix? :)

**Comment by SilentSpike** [comment]
I'd add a line under 24 with:

`{isEngineOn _target} ||`

**Comment by esteldunedain** [comment]
In any case the lazy evaluation thing should be fixed @gienkov

**Comment by gienkov** [comment]
Fixed!

**Comment by bux578** [comment]
:+1:

**Pull request merged**
