### PR TITLE
Jpn translation to v371

### PR DESCRIPTION
**Pull request by classicarma**
this is japanese translation to v3.7.1.

### CODE REVIEW

**Comment by KoffeinFlummi** [comment]
Thanks!

**Comment by commy2** [comment]
🎌

**Comment by jonpas** [comment]
@classicarma Sitting has been removed so those translations are not in ACE3. It has been moved to [ACEX](https://github.com/acemod/ACEX), feel free to pull request it there.

**Comment by classicarma** [comment]
@jonpas Ok. I got it.

**Pull request merged**
