### PR TITLE
Add Traditional & Simplified Chinese Localization to stringtable.xml

### PR DESCRIPTION
**Pull request by GodofMonkeys**
I add whole translate of Chinese (Traditional  and Simplified) to stringtable.xml.

I also translate Arma3 main game language, I find some new string when I update 1.70 game's translation.
These new string is **Chinese Trad.** and **Chinese Simp.** in languagecore_f file.
So I guess BI might will add official Chinese support in-game in future.

So my friend and I decide to upload our ACE3 Chinese mod's content to here, hope every Chinese user can share our work.
Our work on Stem:
1.[ACE3 Chinese (Traditional )](http://steamcommunity.com/sharedfiles/filedetails/?id=665878645&searchtext=ace+3+)
2.[ACE3 Chinese (Simplified)](http://steamcommunity.com/sharedfiles/filedetails/?id=666949696&searchtext=ace+3+ )

We will keep update this mod version and also keep push new pull request if you add or edit any new content to ACE, until we finally get official Chinese support, then we will focus only on Github to help you translate Chinese.

👍

### CODE REVIEW

**Comment by jonpas** [comment]
Placing on Backlog until BI adds official support.

You can keep committing to this pull request as we add new features as well, simply update `master` on your forke and merge it into the `Chinese` branch.

Amazing work!

**Comment by GodofMonkeys** [comment]
Thanks :)

**Comment by jonpas** [comment]
@GodofMonkeys We have decided to merge that to prevent merge conflicts as that would require constant maintenance of this branch (which would be a nightmare for all of us). We don't lose anything with having those strings, if anything we'll be ready if BI ever adds official support! At most, we'll have to just edit the actual string tag name, but that's a lot easier than keeping a branch up to date all the time. Feel free to keep opening new PRs based on latest `master` and we'll be merging them as they come in.

BTW, you should totally contact BI about your main game translations, that's A LOT of work there that could easily be in the main game. ;)

**Comment by GodofMonkeys** [comment]
@jonpas 
Thanks a lot :)
I already told BI long before, and still WIP.

**Comment by GodofMonkeys** [comment]
@jonpas
I find out the BI's new game Argo already have in-game Chinese.
[Imgur](http://i.imgur.com/aN5pOgz.jpg)

And this is their pbo.
[Imgur](http://i.imgur.com/ijNsW2x.png)

The TChinese they write in <Chinese>, and SChinese they write in <Chinesesimp>.
Next time I will update ACE Chinese into this format.

**Comment by jonpas** [comment]
This just got released: https://dev.arma3.com/post/spotrep-00071 as a hotfix. The names are different though, `Chinese` and `Chinesesimp`. I'll prepare a PR to change those.

**Pull request merged**
