### PR TITLE
Interaction - Allow pulling bodies out of wrecks

### LINKED ISSUE #8699: SOGPF - Cannot pull players from burning helicopter wrecks.
ARMA 3 Stable
ACE3 Stable
CBA Stable
SOGPF Public Stable

**Description:**
Cannot ACE interact on burning wrecks of SOGPF vehicles, specifically Helicopters, and pull players out.

**Steps to reproduce:**
Put player in SOGPF Helicopter such as the UH-1. Destroy it. Ace interact, notice there is no ace interact available and the player cannot be pulled out.

**Expected behavior:**
As on Vanilla and other modded vehicles, the wreck should have an Ace interact point allowing the player to be removed with an interact.

**Where did the issue occur?**
Multiplayer

### PR DESCRIPTION
**Pull request by johnb432**
**When merged this pull request will:**
- Fixes #8699.
- Unsure of unintended side effects, but I did try with a larger modset and no negative side effects were noticed.

### IMPORTANT

- If the contribution affects [the documentation](https://github.com/acemod/ACE3/tree/master/docs), please include your changes in this pull request so the documentation will appear on the [website](https://ace3.acemod.org/).
- [Development Guidelines](https://ace3.acemod.org/wiki/development/) are read, understood and applied.
- Title of this PR uses our standard template `Component - Add|Fix|Improve|Change|Make|Remove {changes}`.

### CODE REVIEW

**Comment by Dystopian** [comment]
If vehicle is burned then body is burned too, isn't it? That was initial point of `alive` check.

**Comment by LinkIsGrim** [comment]
> If vehicle is burned then body is burned too, isn't it? That was initial point of alive check.
Not necessarily? Players can be unconscious and alive inside wrecks. Happens a lot with helicopter crashes.

**Review by LinkIsGrim — APPROVED** [review]
IMO this is a subjective change, though.

**Comment by Dystopian** [comment]
> Players can be unconscious and alive inside wrecks

I think if mission allows alive players inside wreck, it should eject them when vehicle becomes destroyed. Or in-mission way to pull out (e.g. useraction). But not ACE pull-out.

**Comment by johnb432** [comment]
> If vehicle is burned then body is burned too, isn't it? That was initial point of alive check.
> Not necessarily? Players can be unconscious and alive inside wrecks. Happens a lot with helicopter crashes.

That's was the intention - to make it possible to remove players from (burning) wrecks. Otherwise they could slowly bleed out, which isn't a particularly fun experience.

> I think if mission allows alive players inside wreck, it should eject them when vehicle becomes destroyed. Or in-mission way to pull out (e.g. useraction). But not ACE pull-out.

I'm not a fan of vanilla useractions, so imo that is out of the question. As for the automatic ejecting, it doesn't feel very realistic, although to be honest pulling an unconscious person out of a raging fire/cook-off isn't too realistic either... but in terms of game play it's a decent solution.

I think more opinions are needed.

**Comment by rautamiekka** [comment]
> > If vehicle is burned then body is burned too, isn't it? That was initial point of alive check.
> > Not necessarily? Players can be unconscious and alive inside wrecks. Happens a lot with helicopter crashes.
> 
> That's was the intention - to make it possible to remove players from (burning) wrecks. Otherwise they could slowly bleed out, which isn't a particularly fun experience.

Anyone who's played will say it feels unfair that there's absolutely nothing you can do if someone doesn't wake up after the wreck catches on fire, which adds undue stress on the Players and Zeuses/mission devs alike to do things absolutely precisely.

> I'm not a fan of vanilla useractions, so imo that is out of the question.

Eh, better than the above.

> [...] although to be honest pulling an unconscious person out of a raging fire/cook-off isn't too realistic either... but in terms of game play it's a decent solution.

Completely realistic and being done wherever possible, just very dangerous in the latter case. Raging fire is very hot but not hot enough to melt or otherwise kill by being close, they ain't the Sun after all.

**Comment by johnb432** [comment]
@jonpas @BaerMitUmlaut @PabstMirror What do you guys think?

**Review by PabstMirror — APPROVED** [review]

**Comment by BaerMitUmlaut** [comment]
Does this allow pulling unconscious enemy units out of a tank?

**Comment by johnb432** [comment]
> Does this allow pulling unconscious enemy units out of a tank?

Sort of, but not really.

Directly it does not, but it's possible to pull unconscious enemies out of vehicles generally speaking - should be addressed in another PR.

This PR gives the ability to pull out unconscious enemies from wrecks.

**Pull request merged**
