### PR TITLE
Extension - Disable call context

### PR DESCRIPTION
**Pull request by PabstMirror**
Coming in 2.18 (and in profiling now)

10x `"ace" callExtension ["break_line", ["alpha bravo charlie"]];`

2.16: 0.251 ms
Profiling 2.16: 0.281 ms // call-context = true
Profiling 2.16: 0.221 ms // call-context = false
RC 2.18: 0.253 ms // call-context = true
RC 2.18: 0.215 ms // call-context = false

### CODE REVIEW

**Comment by BrettMayson** [comment]
This won't do anything? That change to arma-rs would, but I have also started on an alternative PR for this

**Comment by PabstMirror** [comment]
There is a measurable performance increase with this on 2.18 RC
You can see the `RVExtensionFeatureFlags` Export in the dll - https://www.virustotal.com/gui/file/2d138fc9012fe2eac385e798ac0538d3e344c69887db35f8ca1451f684149e12/details

**Comment by BrettMayson** [comment]
Yes I know about that, but this PR won't do that

**Comment by PabstMirror** [comment]
no change to cargo.toml, it's using `1.10.5`

**Comment by BrettMayson** [comment]
Ok yeah that's fine, TIL

This seems to be something that won't yell at you until you actually build a DLL. `cargo check` is fine with this conflicting, `cargo build` is not

**Pull request closed without merging**
