### PR TITLE
Only go for healing an unit if you are ready to move

### LINKED ISSUE #4805: Medic gets "stuck" after ordering "Stop" or "Find cover"
**Arma 3 Version:** `1.66.139586` (stable)
**CBA Version:** `3.1.2` (stable)
**ACE3 Version:** `3.8.3` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
When ordered to "Stop" or "Find cover" and someone requests the medic, it'll be unable to execute its `doMove`. This will result in `QGVAR(movingToInjured)` being set to `true` while the medic is not moving (nor going to move) to the injured.

**Workaround:**
Order the medic to move to the injured yourself. (This however will not work if you are down.)

**Steps to reproduce:**
1. Make a squad with at least 1 Combat Life Saver and a Rifleman.
2. Order the medic to "Stop".
3. Shoot the Rifleman in the foot.
4. Order the medic to move to another location (*not* the Rifleman).
5. Medic is now "stuck".
6. Shoot the Rifleman in the foot again to observe the bug.

**Where did the issue occur?**
- [ ] Dedicated
- [ ] Self-Hosted Multiplayer
- [ ] Singleplayer
- [x] Editor (Singleplayer)
- [x] Editor (Multiplayer)
- [ ] Virtual Arsenal

**Placed Modules:**
- None

**RPT log file:**
Let me know if you need anything from it. :)

### PR DESCRIPTION
**Pull request by Skully71**
**When merged this pull request will:**
- fixes #4805

### CODE REVIEW

**Comment by jonpas** [comment]
Wouldn't checking `unitReady` mean if a unit is issued a move order, they'd instead do that first and then come back to heal? Not sure if this is wanted.

**Comment by SilentSpike** [comment]
It would, I'm also not sure how this really fixes the issue as surely they'd still remain stopped until told to move again?

**Comment by ace3mod** [comment]
Hello @Skully71! There has been no activity on this ticket for over a period of 57 days. I am automatically replying to let you know we will close this ticket within 1 week due to inactivity and consider this resolved.

If you believe this is in error, please reply with the requested information.

Thank you. :robot:

**Comment by ace3mod** [comment]
Hello @Skully71! There has been no activity on this ticket for over a period of 30 days. I am automatically replying to let you know we will close this ticket within 1 week due to inactivity and consider this resolved.

If you believe this is in error, please reply with the requested information.

Thank you. :robot:

**Comment by ace3mod** [comment]
Hello @Skully71! We have detected no activity for 7 days on this ticket. We therefore assume that the original reporter has lost interest or the issue has been resolved.

Since we have marked this ticket for deletion, we will be closing it.

If this has been closed in error, please create a comment below and we can reopen this issue. Note that you may need to provide additional information that was requested.

Thank you. :robot:

**Comment by ace3mod** [comment]
Hello @Skully71! There has been no activity on this ticket for over a period of 30 days. I am automatically replying to let you know we will close this ticket within 1 week due to inactivity and consider this resolved.

If you believe this is in error, please reply with the requested information.

Thank you. :robot:

**Comment by ace3mod** [comment]
Hello @Skully71! We have detected no activity for 7 days on this ticket. We therefore assume that the original reporter has lost interest or the issue has been resolved.

Since we have marked this ticket for deletion, we will be closing it.

If this has been closed in error, please create a comment below and we can reopen this issue. Note that you may need to provide additional information that was requested.

Thank you. :robot:

**Comment by jokoho48** [comment]
@PabstMirror the Bot don't like it that you want this PR to be open

**Comment by thojkooi** [comment]
Has someone been able to test this?

**Comment by PabstMirror** [comment]
Handled in #6902

**Comment by PabstMirror** [comment]
Should be mostly fixed by 

- prefer to use medics that can actually move:
https://github.com/acemod/ACE3/pull/6902/files#diff-6ae76b9a0d49442ea7263ea1cdc22478R27

- reissue the move order over time, instead of only giving it once
https://github.com/acemod/ACE3/pull/6902/files#diff-0d4a504b953f1acad1661cb887f1b11dR49

But i still don't know a good way to unload a AI that has been issued a stop order by the command bar
```
[z2] joinSilent grpNull;  
[z2] joinSilent group player
```
will work, but group switching is a big mess I really don't want to have to use

**Comment by BaerMitUmlaut** [comment]
>But i still don't know a good way to unlock a AI that has been issued a stop order by the command bar
```sqf
z2 doFollow leader z2;
```

**Comment by PabstMirror** [comment]
no effect

**Pull request closed without merging**
