### PR TITLE
Cleanup heli pod actions

### LINKED ISSUE #4783: Taru pods bugs and missing features
**Arma 3 Version:** `1.66` (stable)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ACE3 Version:** `3.x.x` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
Some bugs and feature misses:
1. Taru pod (Refuel) have no visible hose
2. Taru pod (Ammo) can't rearm vehicles
3. All Taru pods can be loaded in to vehicle with visible internal space smaller than the pod. Like fuel pod can be put in to Mora or Kamysh

**Where did the issue occur?**
Self-Hosted Multiplayer

### PR DESCRIPTION
**Pull request by PabstMirror**
Close #4783
- Make taru pods non loadable
- Make taru pods non draggable
- Increase interaction range for huron pods

### CODE REVIEW

**Comment by SilentSpike** [comment]
I know the visible hose thing should be fixed by #5151. However, has the rearm issue mentioned in #4783 been addressed elsewhere too?

Everything else here looks good 👍

**Comment by PabstMirror** [comment]
Rearm works: https://github.com/acemod/ACE3/blob/master/addons/rearm/CfgVehicles.hpp#L140

**Comment by jonpas** [comment]
Let's wait for merging until 3.10.0 has the additional fixes merged.

**Comment by jonpas** [comment]
Can be merged, I merged the last 3.10 fix directly.

**Pull request merged**
