### PR TITLE
Fix for Comanche zoom levels

### PR DESCRIPTION
**Pull request by VKing6**
Bit of a hack, but fixes the order to
Unstab Wide
Wide
Medium
Narrow
Narrower

### CODE REVIEW

**Comment by VKing6** [comment]
Pabst came up with a better solution: https://gist.github.com/PabstMirror/96afea46c4617725bbf1
If that works as intended it should replace this.

**Comment by jaynus** [comment]
Should we close this then?

**Comment by VKing6** [comment]
Let's just change it in this PR/branch.

**Comment by commy2** [comment]
Uhm. Wtf are you guys trying to do? Can someone explain? Because I'm almost certain there is a better way.

**Comment by VKing6** [comment]
Fixing the order the optics modes appear in in game.

**Pull request merged**
