### PR TITLE
porting sounds

### PR DESCRIPTION
**Pull request by commy2**
Sounds. Nothing implemented yet.

### CODE REVIEW

**Comment by Tachii** [comment]
wow thats alot of screams

**Comment by jaynus** [comment]
Variety @Tachii, variety!

**Comment by Tachii** [comment]
I wonder who was recording all those screams :|

**Comment by bux578** [comment]
Left 4 dead pain and death screems:
https://www.youtube.com/watch?v=O8IJepb-hlQ

**Comment by cych** [comment]
what about the ACE 2 ACE_SM   soundpack ?  will you port it to ACE 3 ?  because it had the best sound ever made for arma series concerning grenade, GAU-8 30mm, missile, ....etc

**Comment by esteldunedain** [comment]
@cych, https://github.com/acemod/ACE3/issues/371

**Pull request closed without merging**
