### PR TITLE
Attempt to fix #1465 and #1354

### LINKED ISSUE #1465: Bug report about ACE medical system
ACE3 Version: 3.0.1

**Mods:**
* @cba_a3
* @ace3

**Placed ACE3 Modules:**
hearing
explosive system
blue force tracking
respawn system
weather
advanced ballistics
mk6 settings
wind deflection
micro dagr map fill
medical settings
revive settings
advanced medical settings
set medic class
set medical vehicle
set medical facility

**Description:**
I'm not sure is it bug or not

1. sometimes when i get shot i have no injuries in ACE interaction and can see visually that my body is injured but can't run, you can run after apply PAK but if you being hit again you will walk again
i highly assume that it's happening because falling damage, i can rapdly seeing this symptom when people get falling damage.

2. and sometimes i can't revive my team mate, his pulse and blood pressure is on stable no bleeding but can't revive him he just lie down there, we can make him with PAK but we should wake him with out PAK.

3.  i can hear medical treatment sound that keep over looping, the only solution about this is respawn and come back

**Steps to reproduce:**
being shot and watch the symptom 

**Where did the issue occur?**
"Multiplay", host by in multiplay session not like TADST or other dedicated server tool 
but it's also happening in dedicated server too. 

**RPT log file:**
none

### PR DESCRIPTION
**Pull request by ulteq**
@gienkov, @Dobakjang, does that fix your issues?

### CODE REVIEW

**Comment by gienkov** [comment]
Sadly, no :(.
Best way to repro now - jump from 1 floor of a building.

**Comment by ulteq** [comment]
@gienkov, please test again.

**Comment by gienkov** [comment]
Falling damage is now fixed and causes abrasions only which can be bandaged now by field dressing. Vehicle damage still needs fixing tho but "acupuncture" works now. By "acupuncture" I mean shooting patient once to cause any kind of damage and immediately bandaging it, thus causing to reset "vanilla damage" to 0.

**Comment by gienkov** [comment]
Repro - drive onto wall few times, it will cause vanilla damage which cannot be fixed.

**Pull request merged**
