### PR TITLE
Fix missing zeroing UI on vehicles without FCS

### LINKED ISSUE #4176: No zeroing for statiс weapons
**Arma 3 Version:** 1.62 (stable)
**CBA Version:** 3.0.0 (stable)
**ACE3 Version:** 3.6.2 (stable)

**Mods:**
- `@CBA_A3`
- `@ace`
- `@rhs` (optional)

**Description:**
- Since 3.6.0 zeroing for some statiс weapons (HMG and GMG) is gone.

I.e. Mk19 by RHS (look at the weapon info in the top right corner):
- Vanilla http://i.imgur.com/3ScOndy.jpg
- ACE 3.6.2 http://i.imgur.com/wK8a2jt.jpg
- ACE 3.5.1 http://i.imgur.com/7xiYO3G.jpg

It's the same with the vanilla static MG and GMG

**Steps to reproduce:**
- It should be noted that instead of changing zeroing (PgUp/PgDwn) began to work automatic setup of range button (T or Tab).

**Where did the issue occur?**
- Everywhere

**Placed Modules:**
- None

**RPT log file:**
- Not relevant

### PR DESCRIPTION
**Pull request by jonpas**
**When merged this pull request will:**
- Fixes #4176

### CODE REVIEW

**Comment by jonpas** [comment]
If @lolkij or anyone with RHS can test this it would be great!
[ace_fcs_fixMissingUI.zip](https://github.com/acemod/ACE3/files/414169/ace_fcs_fixMissingUI.zip)

**Comment by PabstMirror** [comment]
This seems to be working great

**Comment by lolkij** [comment]
Yes, now it works fine. Thank you, jonpas!

**Comment by Glowbal** [comment]
How often is that condition called?

**Comment by jonpas** [comment]
On every `infoDisplayChanged` and `settingChanged` event.

**Pull request merged**
