### PR TITLE
General - Convert vehicle to objectParent

### PR DESCRIPTION
**Pull request by Mike-MF**
**When merged this pull request will:**
- Converts `vehicle _unit == unit` into `isNull objectParent _unit`, it's better and already used in some areas.

### CODE REVIEW

**Comment by BaerMitUmlaut** [comment]
What do you mean with it's better? It decreases readability which is why we didn't do this in the past. Performance gains are negligible.

**Comment by veteran29** [comment]
There's also `_unit in _unit` which is of similar performance and still quite readable IMO.

**Comment by BrettMayson** [comment]
imo they're all not that unreadable. I remember `vehicle _unit == _unit` being confusing as I was just getting into arma.

imo `_unit in _unit` is the least clear. `vehicle _unit == _unit` at least has the vehicle command to make its purpose a bit clearer. I am fairly indifferent between `vehicle` and `objectParent`, but if I had to pick I'd go with `objectParent`, more explicit in its return and for someone less familiar, they'll be more likely to google it and get an actual idea of what's going on. `vehicle _unit` returning `_unit` on foot instead of objNull is not clear

> Use objectParent instead of [vehicle](https://community.bistudio.com/wiki/vehicle) to get a soldier's vehicle. Apart from being faster it is also more reliable, as when used on dead [crew](https://community.bistudio.com/wiki/crew), [vehicle](https://community.bistudio.com/wiki/vehicle) command may surprisingly return the unit itself.

I don't think that's relevant

**Comment by LinkIsGrim** [comment]
I prefer `objectParent` for reasons above.

**Comment by johnb432** [comment]
> I prefer `objectParent` for reasons above.

Same.

**Review by jonpas — APPROVED** [review]

**Review by johnb432 — APPROVED** [review]

**Review by LinkIsGrim — APPROVED** [review]
Merge conflicts!

**Pull request merged**
