### PR TITLE
Make ACE_moduleEquipFRIES compatible with zeus

### LINKED ISSUE #3523: Question: FRIES in zeus/FRIES var?
Hello,
My question is: Is it possible to make a helicopter use the fastrope system if you put it down trough zeus?

And is there a var you can add to helicopters to enable FRIES?

### PR DESCRIPTION
**Pull request by PabstMirror**
Tag @BaerMitUmlaut
Close #3523

### CODE REVIEW

**Comment by esteldunedain** [comment]
:+1:

**Comment by BaerMitUmlaut** [comment]
I never worked with Zeus modules, will this get executed serverside?

**Comment by PabstMirror** [comment]
`isGlobal = 0;`
Same as before, so it will only run on server.

**Comment by BaerMitUmlaut** [comment]
:+1:

**Comment by Glowbal** [comment]
Any reason we are not adding this to the other zeus component we have?

**Comment by PabstMirror** [comment]
Replaced by #4597

**Pull request closed without merging**
