### PR TITLE
Fixed typos, added missing translations (Russian translation)

### PR DESCRIPTION
**Pull request by Bla1337**
Fixed some typos (capitalizing, е => ё), added some missing translations (AP, HPBT, API ammunition).

### CODE REVIEW

**Comment by alganthe** [comment]
oh god 1 of the three of us will have to enjoy editing his files two times.

**Comment by Bla1337** [comment]
I will look into it, I'm not really experienced with the Github so excuse my ignorance.

**Comment by alganthe** [comment]
Don't worry, just check if you don't have duplicates. 
I had the same issue because of a previous stringtable update ;)

**Comment by ulteq** [comment]
Please add yourself to the AUTHORS.txt

**Comment by alganthe** [comment]
your mk6mortar stringtable is outdated.

**Comment by Bla1337** [comment]
Not sure if I should update all of the files that have changed since my original submission or just the Tabler editing line that was messing up the mk6mortar/stringtable.xml, can anyone clarify?

**Comment by Bla1337** [comment]
As I'm still figuring out all of the quirks of Github, I had to resubmit the pull request here: https://github.com/acemod/ACE3/pull/911
Should be mergeable now.

**Pull request closed without merging**
