### PR TITLE
PL translation

### PR DESCRIPTION
**Pull request by gienkov**
Sneaky empty strings in spectator...

### CODE REVIEW

**Comment by esteldunedain** [comment]
Thanks

**Comment by bux578** [comment]
Could add that as a function to tabler: To remove empty translations.

**Comment by esteldunedain** [comment]
> Could add that as a function to tabler: To remove empty translations.

That'd be very usefull

**Comment by bux578** [comment]
> That'd be very usefull

https://github.com/bux578/tabler/commit/97b33ae6962fa97ee9c9be428bde007f432a877e

**Pull request merged**
