### PR TITLE
Don't display injectors on arms

### PR DESCRIPTION
**Pull request by KoffeinFlummi**

### CODE REVIEW

**Comment by Glowbal** [comment]
I thought this was going to be IVs, not auto-injectors?

**Comment by headedhorseman101** [comment]
If your going for realism, injectors should only be used on the upper leg. Since ACE can't get that specific without over complicating things or reworking the whole med system, interaction should be limited to legs.

**Comment by ViperMaul** [comment]
Status?

**Comment by Glowbal** [comment]
I don't like this. I don't think reducing the amount of clutter justifies not having these actions available on the arms. Especially taking into account that some models still have their selection positions for legs f'd.

**Pull request closed without merging**
