### PR TITLE
Add Actions to buildings (UserActions - Ladders)

### PR DESCRIPTION
**Pull request by PabstMirror**
WIP - Still debug stuff inside

Adds UserActions (which includes all door stuff) / Ladder mount points to buildings

Because buildings can be very large (building center could be far away, but door right infront of player), I have to add the points to dummy objects that get generated when the interact key is pressed (just like wirecutter).  There's an extension to pull the image name from the action's config strucutredText. It pulls the raw condition/statement from the config, so this should be fully compatible with any kind of action.

I could make this an optional userSetting.

Solves the "guess which door will actually open" problem:
whichdoor

Edit: video: https://www.youtube.com/watch?v=1DtwMyfCiyc

### CODE REVIEW

**Comment by esteldunedain** [comment]
Pretty much perfect @PabstMirror, gj! The action points can be moved now on a frame by frame basis, so maybe it would be possible to make the AP follow the door as it opens, providing we can get the animation for that. I'm not sure how difficult it is (may not make sense to go full p3d extension for that)

**Comment by esteldunedain** [comment]
Quick question: is it too annoying to remove those actions from the action wheel?

**Comment by PabstMirror** [comment]
Here's an example config thats parsed:
```
class OpenDoor_1 {
    displayNameDefault = "<img image='\A3\Ui_f\data\IGUI\Cfg\Actions\open_door_ca.paa' size='2.5' />";
    displayName = "Open door";
    priority = 0.4;
    position = "Door_1_trigger";
    radius = 1;
    onlyForPlayer = 0;
    condition = "((this animationPhase 'Door_1_rot') < 0.5) && ((this getVariable ['bis_disabled_Door_1',0]) != 1) && (cameraOn isKindOf 'CAManBase')";
    statement = "([this, 'Door_1_rot'] execVM ""\A3\Structures_F\scripts\DoorNoHandle_open.sqf"")";
};
```
The action could be anything, I don't actually know if it's a door or a merry go round
untitled

I could probably match "door_x_trigger", and "_rot" animationPhase, but I don't know how to tell which way the door moves.

We can mod the ladder actions (either turn off show3d or hide completly), but can't really do anything about the userActions because vehicles and I think addAction use the same system.

**Comment by esteldunedain** [comment]
I mean: does the `Door_1_trigger` position moves with the animation or not? If it does then we are all set (you create the dummy object in a fixed position and move the actual AP frame by frame). If it doesn't then tough luck.

**Comment by PabstMirror** [comment]
`Door_1_trigger` doesn't move with the animation.

I played around with finding the animated door position:
```
zzz = 63 * (cursorTarget animationPhase "Door_1_rot");
x1 = cursorTarget modelToWorld (cursorTarget selectionPosition "Door_1_trigger");  
x2 = cursorTarget modelToWorld (cursorTarget selectionPosition "Door_1_axis");    
x3 = x1 vectorDiff x2;  
x4 = [((cos (zzz)) * (x3 select 0)) + ((sin (zzz)) * (x3 select 1)), ((sin (zzz)) * (x3 select 0)) + ((cos (zzz)) * (x3 select 1)), (x3 select 2)];
helperObject1 setPosAtl x1;
helperObject2 setPosAtl x2;
helperObject3 setPosAtl (x2 vectorAdd x4);
```
But, doors open different angles, and this won't work on AiA buildings, I'm not even sure if all a3 buildings have a x_axis mem point.  I really don't think this would be reliable.

untitled

**Comment by esteldunedain** [comment]
> But, doors open at different angles, and this won't work on AiA buildings, I'm not even sure if all a3 buildings have a x_axis mem point. I really don't think this would be reliable.

**Comment by ViperMaul** [comment]
@PabstMirror
Yeah let's make this a user setting. On by default for now. 
I think this is a great feature.

**Comment by Khaosmatic** [comment]
Having an option to disable stuff like opening doors from the scroll wheel would probably be one of the best features ever.

**Comment by jonpas** [comment]
> Would it be possible to apply the same system to vehicles for getting in at correct positions? (I guess APC's and stuff would be harder but simply being at a certain side and seeing visually what seats and positions are available would be brilliant!

IIRC this will be available with the p3d (model) parser extension, same system vehicle damage is/will be using. It's not possible to get correct positions of everything with SQF purely.

**Comment by esteldunedain** [comment]
Hey @PabstMirror, can we merge this already?. If it still has any quirks people will find them in no time (so we can fix them), and it's really a great feature

**Comment by bux578** [comment]
yes please

**Comment by PabstMirror** [comment]
In towns, there still is a a performance hit when opening interaction menu (it's worse the first time as buildings aren't cached).
BIS's action menu works ok for doors 95% of the time, so this isn't a critical feature.

Should be good to merge, hopefully get some feedback on any issues prior to 3.2

**Comment by esteldunedain** [comment]
I imagine that performance cost I'm merging this. I think there's couple of tweaks that can still be made to make this more efficient and activate it by default later on.

**Pull request merged**
