### PR TITLE
German translations

### PR DESCRIPTION
**Pull request by simon84**
Some german translations:
- ballistics
- interact menu
- medical
- missileguidance
- mk6mortar
- optionsmenu
- realisticnames

### CODE REVIEW

**Comment by bux578** [comment]
@ulteq did you proof read the translations? @simon84 can't decide if he's using `,` or `.` as a decimal seperator :)

**Comment by bux578** [comment]
or if there's a space between the numbers and `mm`

**Comment by simon84** [comment]
Oh, checked it, but it was late, yesterday! Will change it this evening.

**Comment by bux578** [comment]
:+1:

**Pull request merged**
