### PR TITLE
german translations

### PR DESCRIPTION
**Pull request by simon84**
Some german translations and corrections

### CODE REVIEW

**Comment by KoffeinFlummi** [comment]
Thanks for your contribution! Please add a valid email address to your entry in the AUTHORS.txt file before we merge this.

**Comment by licht-im-Norden87** [comment]
Check your translation for some typos, have found some.

**Comment by simon84** [comment]
yeah, i will check some translations. Is it necessary to add an email address? I thought this is optional.

**Comment by simon84** [comment]
Ok, I have updated my pull-request. Should be easy to merge now.

**Comment by simon84** [comment]
Oh, wanted to make a new pull-request for minor changes on the FCS. Now its commited on this pull-request. Can I change this? Do I need a new branch?

**Comment by bux578** [comment]
Yes. This pull request will contain all changes you make on your master branch. You should revert your last commit and switch to a new branch.

**Comment by simon84** [comment]
Thx, I reverted the commit and make an extra branch out of it. Now, this "translation-branch" should be complete! Sorry, its my first time with git. I used SVN before.

**Comment by bux578** [comment]
Kein Problem, alles gut! We appreciate it!

**Comment by KoffeinFlummi** [comment]
@simon84 We still need that email address ;)

**Comment by simon84** [comment]
Ok! I have updated the AUTHORS.TXT.

**Comment by KoffeinFlummi** [comment]
Thanks!

**Pull request merged**
