### PR TITLE
strobe light more bearable

### PR DESCRIPTION
**Pull request by alganthe**
changed the intensity of the strobe light, it's still VERY visible on a
very long distance, (around 1.6k maybe more)

Before  http://steamcommunity.com/sharedfiles/filedetails/?id=455041609

after http://steamcommunity.com/sharedfiles/filedetails/?id=455048548

RL :

### CODE REVIEW

**Comment by esteldunedain** [comment]
I'm pretty sure those things in the picture are NOT strobes.

Btw, how the current strobe looks is VERY dependant on light conditions (moon, clouds, etc). Be sure to test the modification under various conditions to ensure it is still visible from the AIR (which is the whole point of this)

**Comment by alganthe** [comment]
I could see this from 1.6k away, I'll do some tests in forest with a huge tempest going on.

**Comment by esteldunedain** [comment]
> I could see this from 1.6k away, I'll do some tests in forest with a huge tempest going on.

I think visibility goes way down when there's some ambient light, like bright moon conditions. Check those.

**Comment by alganthe** [comment]
Tested with full moon, there's barely any difference between the previous and the new brightness, for some reason at a distance the effect is the same

**Comment by esteldunedain** [comment]
OK, thanks

**Pull request merged**
