### PR TITLE
Don't show mine detector in holster

### PR DESCRIPTION
**Pull request by Grey-Soldierman**
Removed Valon from any vest properly configured to use a holster

### CODE REVIEW

**Comment by PabstMirror** [comment]
Without this PR, it looks like this in a holster:
image

**Comment by commy2** [comment]
Wait, I'm confused. This doesn't add a mine detector, but sets the holser scale to 0, so the mine detector isn't rendered at the holster.

**Comment by Glowbal** [comment]
This has some issues that I will fix in the mine detector PR

**Comment by Glowbal** [comment]
Thanks @Grey-Soldierman

**Pull request merged**
