### PR TITLE
Medical - Adjustable times for many treatment actions

### PR DESCRIPTION
**Pull request by diwako**
**When merged this pull request will:**
- Add CBA settings for most constant treatment times
  - Default values are the original values
- Add variable time needed to stitch one wound

Currently changed treatments:
- Tourniquet (apply and remove)
- Splint
- Autoinjectors
- IV bags
- CPR
- Stitching

### CODE REVIEW

**Comment by Elgin675** [comment]
It's not the same ?
https://github.com/acemod/ACE3/pull/7900

**Comment by diwako** [comment]
Yeah that does look the same. only difference is i am including cpr and stitching time, Could edit this PR and kick out the ones that are duplicate.

**Comment by GlutenFreeVapes** [comment]
Can you please also make a slider to increase bandage power?

**Comment by dgibso29** [comment]
If I'm not mistaken, there are already Addon Options controlling CPR & Stich time. That's why they weren't included in my PR.

**Comment by diwako** [comment]
As far as I see (at least on master branch). I do not see any adjustable settings for those two. Stitching is controlled by a constant pre processor instruction and CPR is constantly defined in config at the moment.

Might be best if you add those two in your PR, then I will close this one as it has become fully redundant.

**Comment by dgibso29** [comment]
> As far as I see (at least on master branch). I do not see any adjustable settings for those two. Stitching is controlled by a constant pre processor instruction and CPR is constantly defined in config at the moment.
> 
> Might be best if you add those two in your PR, then I will close this one as it has become fully redundant.

Ah, my mistake. I was thinking of the PAK coefficient.

Sure, will do when I have a moment.

**Comment by PabstMirror** [comment]
Combined with changes from #7900 
now just changing cpr and stitch

**Review by PabstMirror — APPROVED** [review]

**Review by jonpas — APPROVED** [review]

**Pull request merged**
