### PR TITLE
Fix UAV and Interaction Compile Inheritance

### PR DESCRIPTION
**Pull request by PabstMirror**
#1269 

I had logistics_uavbattery's config all wrong, fixed it and now compileMenu.sqf is only compiling that action, not the ~9 other actions (I don't care about them on the UAV, but it's going to be a problem for other things)

`count (configfile >> "CfgVehicles" >> "B_UAV_01_F" >> "ACE_Actions" >> "ACE_MainActions")` = 1

`count (configProperties [configFile >> "CfgVehicles" >> "B_UAV_01_F" >> "ACE_Actions" >> "ACE_MainActions", "isClass _x", true])` = 9

`configProperties` seems to work whereas `count`/`select` doesn't.

### CODE REVIEW

**Comment by esteldunedain** [comment]
@PabstMirror, would this method allow deleting on a child actions added to it's father? Overriding them with other actions named equaly?

**Comment by PabstMirror** [comment]
In interaction I test added
```
                class test2 {
                    displayName = "2";
                    condition = "true";
                    statement = "hint '2'";
                };       
                class test3 {
                    displayName = "3";
                    condition = "true";
                    statement = "hint '3'";
                };
```

in UAV I do:
```
                delete test2;
                class test3 {
                    displayName = "3 new";
                    condition = "true";
                    statement = "hint '3 new'";
                };
```

The delete doesn't work not sure why,  But "3 new" does.

**Comment by esteldunedain** [comment]
Well, I guess that instead of deleting test2 we coud replace the condition "false" if absolutely necessary

**Comment by PabstMirror** [comment]
I wondered why this worked back in AGM, but not here:

AGM: 
`configfile >> "CfgVehicles" >> "I_Truck_02_fuel_F" >> "AGM_Actions"` = 2 (should be ~12)

The difference is we did a call to
`_parents = [configFile >> "CfgVehicles" >> typeOf _object, true] call BIS_fnc_returnParents;`

And then went though all of it's parents and added their actions.  As far as I can tell `configProperties` with inherit=true should do all of that (probably faster as well).

* AGM_Interaction/fn_showMenu.sqf - fn_GetActions.sqf

**Comment by xPride** [comment]
Em, https://github.com/acemod/ACE3/pull/1172 ? Cool "fresh" idea, guys.

**Comment by esteldunedain** [comment]
> Em, #1172 ? Cool "fresh" idea, guys.

@xPride, did you read my comment on that issue?

**Pull request merged**
