### PR TITLE
enable gunbag for all non-machinegun primary weapons

### LINKED ISSUE #4042: Gunbag Only able to store DMR's
**Arma 3 Version:** `1.60`
**CBA Version:** `2.4.1` (stable / dev + commit hash)
**ACE3 Version:** `3.6.0` (stable / dev + commit hash)

**Mods:**
- `@CBA_A3`
- `@ace`

**Description:**
The gunbags mechanism is only able to store DMR's. When trying to run a DMR + SMG/Rifle without the gunbag you could store the SMG/Rifle in a big bag and would be forced to dump the DMR. The current gunbag setup simply reverses this issue. As a gunbag owner IRL straps are setup so you could fit anything in there within its size constraints.

Allowing all primary weapons to be stored in a gun bag would also allow a switch weapon feature. this effectively being the same as the double weapon feature of ACE2.

**Steps to reproduce:**
N/A

**Where did the issue occur?**
N/A

**Placed Modules:**
N/A

**RPT log file:**
N/A

### PR DESCRIPTION
**Pull request by commy2**
**When merged this pull request will:**
- Removes `GVAR(allowGunbag)` config entry, which means that all rifles should work out of the box now
- Instead treats machine guns as incompaitble only (launchers are not primary weapons anyway)
- closes #4042

I'm not a huge fan of using the cursor to define what a machine gun is, but the 3den inventory menu uses this too, as well as `BIS_fnc_itemType`, so it is official.

```
"configName _x call ace_gunbag_fnc_isMachineGun" configClasses (configFile >> "CfgWeapons") apply {configName _x}
["MGun","M2","LMG_RCWS","LMG_65mm_body","LMG_M200","LMG_M200_body","LMG_Minigun","LMG_Minigun_heli","HMG_127","HMG_127_APC","HMG_127_UGV","HMG_01","HMG_static","HMG_M2","HMG_NSVT","SmokeLauncher","FlareLauncher","CMFlareLauncher","M134_minigun","gatling_20mm","gatling_30mm","LMG_Minigun2","LMG_Minigun_Transport","LMG_Minigun_Transport2","gatling_25mm","autocannon_35mm","LMG_coax","Twin_Cannon_20mm","Gatling_30mm_Plane_CAS_01_F","Cannon_30mm_Plane_CAS_02_F","HMG_127_MBT","LMG_Mk200_F","LMG_Mk200_MRCO_F","LMG_Mk200_pointer_F","LMG_Zafir_F","LMG_Zafir_pointer_F","LMG_Zafir_ARCO_F","arifle_MX_SW_F","arifle_MX_SW_pointer_F","arifle_MX_SW_Hamr_pointer_F","arifle_MX_SW_Black_F","arifle_MX_SW_Black_Hamr_pointer_F","FakeWeapon_moduleTracers_F","MMG_01_base_F","MMG_02_base_F","LMG_Mk200_LP_BI_F","LMG_Mk200_BI_F","MMG_01_hex_F","MMG_01_tan_F","MMG_01_hex_ARCO_LP_F","MMG_02_camo_F","MMG_02_black_F","MMG_02_sand_F","MMG_02_sand_RCO_LP_F","MMG_02_black_RCO_BI_F","ACE_LMG_coax_MAG58_mem2","ACE_LMG_coax_MAG58_mem3","ACE_LMG_coax_L94A1_mem3","ACE_LMG_coax_PKT_mem2","ACE_gatling_20mm_Comanche"]
```

### CODE REVIEW

**Comment by esteldunedain** [comment]
> I'm not a huge fan of using the cursor to define what a machine gun is, but the 3den inventory menu uses this too, as well as BIS_fnc_itemType, so it is official.

That's so fucked up it's not even funny.

**Comment by jonpas** [comment]
I think that's the best way to go, mods most of the time just inherit that anyways. Merge?

**Comment by DLEGION** [comment]
hi guys....i noticed this only now (never used gunbag until now).
can someone explain how this works exactly ? 
how disable the artificial (and unrealistic) limitation "of the caliber bigger than 6.5mm will not fit into backpack" ?
thanks for any info !

**Comment by commy2** [comment]
Has nothing to do with this. This PR is about the gunbag not regular backpacks. You cannot make more weapons fit into bagpacks without having to make a whole bunch of configs for many addon weapons out there.

**Pull request merged**
