### PR TITLE
ceil number of wounds

### PR DESCRIPTION
**Pull request by gienkov**
This fixes not round number of wounds, see image below (1.7x wound). This happens when you use wrong type of bandage on wound. Thing below that is just my experiment that failed, sadly.
img

### CODE REVIEW

**Comment by Glowbal** [comment]
Why is showing 1.7x a bad thing?

**Comment by VKing6** [comment]
Because it doesn't make sense to have fractions of a wound?
If you have a partially bandaged or treated wound it should say "Partially bandaged wound" not "0.7 wounds".

**Comment by gienkov** [comment]
Let me explain, back before 3.4.0 all bandages were not correctly defined, and all of them had effectiveness of 1. Because of that you could use any bandage type and it would still heal that one wound completely. Right now bandages are defined properly and they have different effectiveness, so for example bandaging velocity wounds with basic bandage will use 4 of them because they have effectiveness of 0.3. That number is substracted from openWounds array and displayed as number of wounds after that. But I think you still want to count them as before and this PR does that:
2x wounds of same type are displayed as 2x wounds
1.7x wounds are displayed as 1x wound and partially open wound and so on.

**Comment by Glowbal** [comment]
I have added this to the 3.5.0 milestone, but I might consider adding it to 3.4.2. I'd like to double check the effects before I decide to merge this (and for what version).

**Comment by TheGrandVizier** [comment]
Player Input, if you care:
WE LOVE THE "0.7" WOUND SYSTEM!

Very clear to untrained personnel what is going on and why.
We like the indications. Please retain.

**Pull request merged**
