### PR TITLE
Generalizing interact_menu compilation

### PR DESCRIPTION
**Pull request by SilentSpike**
Generalization for the interact menu compilation functions as discussed in slack.

### CODE REVIEW

**Comment by PabstMirror** [comment]
ace_interaction: fnc_addPassengerActions.sqf has:
`_varName = format [QEGVAR(interact_menu,Act_%1), typeOf _unit];`
should be switched as well.

Minor thing, but we really don't need the ACE prefix on GVARs:
`QGVAR(ACE_Actions_%1)` will expand to` "ace_interact_menu_ACE_Actions_%1"`

**Comment by SilentSpike** [comment]
On your second point, it's the class name currently being used for actions and the simplest way of keeping the variable names unique in the generalized function. I'm not a fan of it either but this PR is just the general functionality.

@esteldunedain said he's likely to change the implementation in future so I expect it won't stay that way forever.

I'll take a look at passangerActions

**Comment by SilentSpike** [comment]
@esteldunedain I'm thinking of just closing this PR, can probably be handled better, besides we probably want to wait until after the zeus menu stuff is integrated.

**Comment by esteldunedain** [comment]
I agree.

**Pull request closed without merging**
