### PR TITLE
Fixes to medical handleDamage

### PR DESCRIPTION
**Pull request by Glowbal**
fix for #1155

### CODE REVIEW

**Comment by esteldunedain** [comment]
:+1:

**Comment by jaynus** [comment]
:thumbup: :clap:

**Comment by Jester814** [comment]
Yay! Is there a way we can get the fixed medical pbo to put in our mod pack as a hotfix until 3.1.0 releases? <3

**Comment by jonpas** [comment]
@Jester814 build it yourself.

**Comment by esteldunedain** [comment]
@Jester814, there'sa hotfixed version incoming after the weekend.

**Pull request merged**
