### PR TITLE
Captives - rewrite findEmptyNonFFVCargoSeat

### LINKED ISSUE #4339: Can't put a prisoner on a boat
**Arma 3 Version:** `1.62` stable 
**CBA Version:** `3.0.0` 
**ACE3 Version:** `3.6.2` 

**Mods:**
- `@CBA_A3`
- `@ace`
- @ RHS
- @ TFR

**Description:**
When you tie a prisoner, you can force him to get on board of a car/truck, helicopter, or even in submarine. But when you ask him to go on a boat, he remains foots on the ground. He really hates boats.

**Steps to reproduce:**
- On the editor, place on map a player unit; add ACE_CableTie to his inventory or place a box with ACE_CableTie inside.
- Place a boat.
- Place a IA.
- Start the mission, as you wish
- Use ACE_CableTie to tie the IA unit.
- Escort/move this prisoner/IA near a boat (RHS or vanilla, doesn't matter) and try to make him get on board.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Editor (Singleplayer) 

**Placed Modules:**
- None OR various module like ACE medicals, ACE explosive, TFR modules.

### PR DESCRIPTION
**Pull request by PabstMirror**
Simplify func using `fullCrew`
Fix #4339
also switch hard `ERROR(` macro to `WARNING(`

### CODE REVIEW

**Comment by commy2** [comment]
how exactly does this fix the boats? and what is the issue with them anyway?

**Comment by PabstMirror** [comment]
It was a mess of code to find empty cargo seats (prioitizing non-ffv first).
I was relying on `getInProxyOrder` config, which doesn't seem to work on boats.

Using the newer "includeEmpty" syntax of `fullCrew` made this trivial compared to the mess of code before.

**Comment by commy2** [comment]
Ok.
`fullCrew` is one of those nice commands with a horrible naming / syntax. Always have to visit the wiki.

**Comment by commy2** [comment]
:+1: wub lgtm

**Comment by SilentSpike** [comment]
:+1:

**Pull request merged**
