### PR TITLE
Common - Fix retrieving the version of an addon when searching for mismatches

### PR DESCRIPTION
**Pull request by Timi007**
**When merged this pull request will:**
- Fix retrieving the version of an addon when searching for version mismatches.
- Keep the current logic of handling versions as floating point numbers.

### IMPORTANT

- If the contribution affects [the documentation](https://github.com/acemod/ACE3/tree/master/docs), please include your changes in this pull request so the documentation will appear on the [website](https://ace3.acemod.org/).
- [Development Guidelines](https://ace3.acemod.org/wiki/development/) are read, understood and applied.
- Title of this PR uses our standard template `Component - Add|Fix|Improve|Change|Make|Remove {changes}`.

### CODE REVIEW

**Comment by PabstMirror** [comment]
Does this match 3.17.1 behavior?

**Comment by johnb432** [comment]
> Does this match 3.17.1 behavior?

No, it adds onto it. #9266 just moved that part of the code without modifying it.

**Comment by Timi007** [comment]
Mh, I noticed that my first case of just getting the number as a float is wrong compared to the other cases. 

Example: 
Client: `version = 1.9`  
Server: `version = 1.10`  
results in: Client (newer) > Server

Should this be fixed so that Client version is treated as `version = 1.09` instead?

**Comment by Timi007** [comment]
> Does this match 3.17.1 behavior?

I don't know if BI changed the behavior of `getText` but getting the version now in `A3 2.18` with this command results in nothing when a floating point number is assigned to `version` (typical with CBA/ACE structured addons). The default value of `0` applies on parsing errors. Therefore, all float versions are 0 and no mismatch is detected.

**Comment by PabstMirror** [comment]
iirc they mentioned using a newer compiler that might have changed float->string conversions?

**Comment by johnb432** [comment]
> Example: Client: `version = 1.9` Server: `version = 1.10` -> A3 gets `1.1` results in: Client (newer) > Server
That's indeed less than ideal. I'm trying to come up with a better solution.

**Review by johnb432 — APPROVED** [review]

**Review by PabstMirror — APPROVED** [review]

**Pull request merged**
