### PR TITLE
Stringtable macros

### PR DESCRIPTION
**Pull request by jonpas**
#1380 

Adds 4 new macros for use in stringtables and converts entire ACE3 to use it.

Script Strings:
- `#define LSTRING(var1) QUOTE(TRIPLES(STR,ADDON,var1))`  
Example: `LSTRING(banana) == "STR_ACE_Module_banana"`
- `#define ELSTRING(var1,var2) QUOTE(TRIPLES(STR,DOUBLES(PREFIX,var1),var2))`  (like EFUNC)  
Example: `ELSTRING(balls,banana) == "STR_ACE_balls_banana"`

Config Strings (require `$` as first character):
- `#define CSTRING(var1) QUOTE(TRIPLES($STR,ADDON,var1))`  
Example: `CSTRING(banana) == "$STR_ACE_Module_banana"`
- `#define ECSTRING(var1,var2) QUOTE(TRIPLES($STR,DOUBLES(PREFIX,var1),var2))` (like EFUNC)  
Example:`ECSTRING(balls,banana) == "$STR_ACE_balls_banana"`

Also fixed a bunch of wrong naming in package names of `stringtable.xml`s and all that. I also had to change a lot of stringtable keys to use proper module prefix, but those could be reverted and use external variation of the macros.

I probably missed some or there might be bugs/wrong strings used as I was using regex for almost everything. Report and I can fix, this PR will get majorly broken anyways due to it's size. :grin: 

Thanks @SilentSpike for regex help!

### CODE REVIEW

**Comment by bux578** [comment]
IMO, `STRING` is a poor name for this.

**Comment by PabstMirror** [comment]
I agree with buxMaybe switch to:
LSTRING for `localize`
CSTRING for configFile

**Comment by jonpas** [comment]
Gosh people, where were you when I asked that in the issue! :grin:

LSTRING, would it be better in that case to add 'localize' command to it as well?

**Comment by jonpas** [comment]
There, STRING changed to LSTRING.

**Comment by ViperMaul** [comment]
We can add it to CBA once it gets approved here. 
The good thing about CBA is it is a set up functions and macros that people can decide to use or not use.

**Comment by jonpas** [comment]
Sounds good to me, it would basically just require a copy/paste of the definition anyways. Thanks for the answer!

**Comment by jonpas** [comment]
Merge conflicts resolved.

**Comment by jonpas** [comment]
Resolved conflicts, went through a check, everything works fine on my side.

**Pull request merged**
