### PR TITLE
make.py - update for new mikros tools

### PR DESCRIPTION
**Pull request by PabstMirror**

### CODE REVIEW

**Comment by jonpas** [comment]
Copy of the changes recently introduced in CBA's make.py?

**Comment by PabstMirror** [comment]
yup, same as https://github.com/CBATeam/CBA_A3/pull/193

**Comment by jonpas** [comment]
:+1:

**Comment by PabstMirror** [comment]
For reference, people will need to update their mikero tools if they are still using an older version:

https://dev.withsix.com/projects/mikero-pbodll/files

**Pull request merged**
