### PR TITLE
Hearing: Fix firedNear not working in vehicles

### LINKED ISSUE #463: Hearing damage module affects external listener, not shooter
When hearing a 50cal technical shooting, hearing damage is audible. When firing from that same 50cal technical yourself, no hearing damage occurs.

Possibly more vehicles/weapons are affected, wasn't tested yet.

### PR DESCRIPTION
**Pull request by PabstMirror**
Fix #463 

A player sitting on a 50cal, would never trigger the firedNear because the event seems to only trigger on dismounted men.  Attaching it to AllVehicles seems to fix.

Also adds a updatePlayerVehicleAttunation (run when switching vehicles/turrets), that adjusts how much you can hear the outside from a vehicle (1 in a hmg, 0.1 in a tank)

### CODE REVIEW

**Comment by commy2** [comment]
FYI there is a coeficient for muffling sounds already in the game.

configfile >> "CfgVehicles" >> "B_MBT_01_base_F" >> "insideSoundCoef"

Seems to be 1.0 for cars and 0.9 for enclosed vehicles.

Also note that wheeled apcs are cars, but are armored more like apcs/tanks.

**Comment by PabstMirror** [comment]
I can't find any logic behind `insideSoundCoef` values
Car/Tank/Quadbike are all 0.9
Littlebird is 0.0316228
HMG Boat is 0
BIS says it's for "How much is the volume of the vehicle engine/movement changed when sitting inside that vehicle."

**Comment by jaynus** [comment]
It is how much you hear external sounds, and its a linear inverse coefficient. We utilize it in ACRE. 

There is not much logic to it besides how much it muffles the external world.

0 = no change
1 = cant hear outside.

**Comment by PabstMirror** [comment]
So the Quadbike (0.9) has more sound insulation than an opforTank (0.5)? :wink:

The `attenuationEffectType` on a vehicle and the corresponding `AttenuationsEffects` seem to match up much nicer (and I think have the actual gain values the game uses)

E.G. Static weapon and quadbike are both `OpenCarAttenuation`.  Tanks are `TankAttenuation`.  Plus it has some turret specific Attenuation values.

**Comment by PabstMirror** [comment]
The real advantage this has over just using a a vehicle's `insideSoundCoef` is that we can get per-turret levels, for example the FFV slots on the outside of a BTR.

The native `isTurnedOut` is false for these.

image

Same thing with a HMMWV, people inside get "car" protection, but the turret gunner is exposed.

**Pull request merged**
