### PR TITLE
Arsenal - Use forceUnicode for search functions

### PR DESCRIPTION
**Pull request by LinkIsGrim**
**When merged this pull request will:**
- Title.

```
"Песочный" regexMatch "Песочный"; // true
"Песочный" regexMatch (toLower "Песочный"); // false
forceUnicode 1;
"Песочный" regexMatch (toLower "Песочный"); // true
```

### IMPORTANT

- If the contribution affects [the documentation](https://github.com/acemod/ACE3/tree/master/docs), please include your changes in this pull request so the documentation will appear on the [website](https://ace3.acemod.org/).
- [Development Guidelines](https://ace3.acemod.org/wiki/development/) are read, understood and applied.
- Title of this PR uses our standard template `Component - Add|Fix|Improve|Change|Make|Remove {changes}`.

### CODE REVIEW

**Comment by johnb432** [comment]
I'm a bit worried that `forceUnicode` will affect parent scopes in an unintended way.

This is the trick I used for CBA: https://github.com/CBATeam/CBA_A3/pull/1592/files#diff-e68ad6c2c836c9c0eb4ec723632e2856d5745ea87be0ebdd03788d5b29e1998aR32-R34

**Comment by LinkIsGrim** [comment]
Not a fan of that solution. Would rather use `forceUnicode 1` before each command then

**Comment by LinkIsGrim** [comment]
Maybe `forceUnicode -1` at the end of the function?

**Comment by johnb432** [comment]
> Maybe `forceUnicode -1` at the end of the function?

It does not restore the previous context, which is what I am worried about. If you decide to call either functions when nested within other functions, it might produce unexpected behavior.

I took the wiki example and adapted it a bit just to illustrate:

```sqf
forceUnicode 0;

private _output = call {
    private _results = [];
    private _string = "привет"; // a string that uses Unicode characters
    _results pushBack (count _string); // 6 - outer scope is affected by forceUnicode as well, because the command mode is 0	
    
    forceUnicode -1;
    
    _results pushBack (count _string); // 12 - the character count is wrong without forceUnicode
    
    _results
};

_output pushBack (count "привет"); // 12 - the character count is wrong because it was reset

_output // [6,12,12]
```
---

I just want to be sure that it won't cause any weird edge-case problems in future. However, given the fact that currently no other functions in `arsenal` call `forceUnicode`, it should be fine.

**Comment by LinkIsGrim** [comment]
Oh, *that's* what you meant?

Function ain't public and its context is limited. Any changes in the codebase to use it will have to go through review, and I think the only such thing in the pipeline is the Filters PR.

It'll be fine.

**Review by johnb432 — APPROVED** [review]

**Pull request merged**
