### PR TITLE
Recoil overhaul

### PR DESCRIPTION
**Pull request by commy2**
Nothing changed. Just made the files to work with.

### CODE REVIEW

**Comment by commy2** [comment]
Official doc: http://forums.bistudio.com/showthread.php?188999-Recoil-Overhaul-Feedback&s=dba8590ec07adb5ffa87f72d38dde6fc&p=2886744&viewfull=1#post2886744

**Comment by NouberNou** [comment]
Is this something that we want as part of the 3.0.0 milestone or can we push it back to 3.0.1?

**Comment by commy2** [comment]
I think this can be implemented in a few hours. (It's just some config entires) I'd personally like to have it in 3.0.0.

**Comment by licht-im-Norden87** [comment]
In which way are you going to tweak it? More or less?

**Comment by commy2** [comment]
Different

**Comment by ulteq** [comment]
I like it. :+1:

**Pull request merged**
