### PR TITLE
Remove enhancement request issue template

### PR DESCRIPTION
**Pull request by bux**
**When merged this pull request will:**
- remove enhancement request issue template

### CODE REVIEW

**Comment by jonpas** [comment]
Reason?

**Comment by bux** [comment]
Not needed. And doesn't have disclaimer

**Comment by jonpas** [comment]
It seems it's fairly in use, although I don't know how many of currently tagged "kind/enhancement" issues are actually that. Where do enhancement ideas/requests go if this is removed?

**Comment by bux** [comment]
When getting into the role of a user and trying to answer what the difference is between an enhancement and a feature request, I really can't answer this properly. An "improvement" is also a feature that is being requested.
image

Imho it's safe enough to try.

**Review by jonpas — APPROVED** [review]
Sure. I guess enhancements are either "feature requests" or "go open a PR". :P

**Pull request merged**
