### PR TITLE
Scaled wind arrow for color blind players.

### PR DESCRIPTION
**Pull request by ulteq**
Scaled wind arrow for color blind players. For reference: https://github.com/acemod/ACE3/issues/1272

It works, but it's not very pretty.

### CODE REVIEW

**Comment by esteldunedain** [comment]
I think the scaled wind arrow should still have it's color. Probably make GVAR(coloredWindArrow) a client setting?

**Comment by ulteq** [comment]
Probably rename it to GVAR(scaleWindArrow) and make it a client setting.

**Comment by gienkov** [comment]
No numbered modern Beaufort scale then?

**Comment by VKing6** [comment]
Instead of changing the arrow shape or adding a wind gauge, you could add a visual representation of the same info the colour gives you. 

For example a system with dots or a filling bar under the arrow. 
White arrow - no dots/empty bar 
Green arrow - one dot/slightly filled bar
and so on. 

Or something to that effect.

**Comment by ulteq** [comment]
Yeah, good idea. The arrow scaling is just too ugly.

**Comment by esteldunedain** [comment]
Closing in favor of #3126

**Pull request closed without merging**
