### PR TITLE
Update Japanese Translation

### PR DESCRIPTION
**Pull request by EtoileRei**
* improved JP readability of addons/advanced_ballistics/stringtable.xml

### CODE REVIEW

**Comment by EtoileRei** [comment]
-switched indentation to spaces from tabs
-fixed unintended string shift

**Comment by EtoileRei** [comment]
-improved JP readability of addons/advanced_fatigue/stringtable.xml

**Comment by EtoileRei** [comment]
* improved JP readability of addons/advanced_throwing/stringtable.xml

**Comment by EtoileRei** [comment]
Just now I noticed there was a similar action

#6340 

May I close this pull request?

**Comment by dedmen** [comment]
What you linked was merged 15 days ago. So if you changed stuff here you probably weren't happy with what @classicarma did?

**Pull request closed without merging**
