### PR TITLE
Only play repetitive sounds when game is focused

### PR DESCRIPTION
**Pull request by PabstMirror**

### CODE REVIEW

**Comment by jonpas** [comment]
Wouldn't `isGamePaused` make more sense here? That would then mimic vanilla behaviour.

There are 3 states: normal running, unfocused and paused. Unfocused can still have simulation running (and thus sounds), paused has simulation stopped. `-noPause` startup parameter controls this.

**Comment by synixebrett** [comment]
Vanilla audio is still muted when unfocused while using `-noPause`

**Comment by PabstMirror** [comment]
The problem only really happens in development when alt-tabbing a lot (I use -noPause)
it seems to queue up sounds like heartbeats and then when I tab back in it plays 100x heartbeats at once and is extremely loud

**Comment by jonpas** [comment]
Well that's just silly, such consistency in the game! /s

The this makes sense.

**Pull request merged**
