### PR TITLE
Fix cached call events

### PR DESCRIPTION
**Pull request by PabstMirror**
Noticed big arrays:
```
ace_common_clearcache_interactmenuclosed - ARRAY SIZE: 67
ace_common_clearcache_clearconditioncaches - ARRAY SIZE: 863
```

### CODE REVIEW

**Comment by esteldunedain** [comment]
Wow, great catch @PabstMirror!

**Comment by esteldunedain** [comment]
:+1: for merging this ASAP. For some reason github isn't allowing me to do so.

"This pull request can be automatically merged by project collaborators
Only those with write access to this repository can merge pull requests.
You're not authorized to merge this pull request."

**Comment by commy2** [comment]
^ Same

**Comment by jonpas** [comment]
@esteldunedain @commy2 only owners can merge into `release`.

**Comment by esteldunedain** [comment]
"This pull request can be automatically merged by project **collaborators**
Only those with write access to this repository can merge pull requests.
You're not authorized to merge this pull request."

Great job on explaining this github.

**Comment by bux578** [comment]
needs to be added to the changelog

**Pull request merged**
