### PR TITLE
QuickMount - Use correct cargo index

### PR DESCRIPTION
**Pull request by PabstMirror**
ref @Dystopian / https://github.com/acemod/ACE3/pull/5630#discussion_r149043888

### CODE REVIEW

**Comment by commy2** [comment]
Pretty sure you can just subtract the amount of person turrets from the command cargo index to get the action cargo index.

**Comment by PabstMirror** [comment]
Maybe, might break if they're in a weird order like `[FFV,Cargo,FFV,Cargo]`

**Comment by Dystopian** [comment]
I wanted to fix it :(

As for PR, I wouldn't use another `forEach fullCrew` inside the same cycle. External cycle is enough to count cargo action index.

**Comment by jonpas** [comment]
@Dystopian If you would like to, feel free to PR the improvement, merged that as it fixes things.

**Pull request merged**
