### PR TITLE
Hungarian translation update

### PR DESCRIPTION
**Pull request by Harakhti**
If you keep adding strings, we'll be doing this forever. :stuck_out_tongue:

### CODE REVIEW

**Comment by bux578** [comment]
Think of it as a long term relationship. Like a marriage ... only without sex. Oh wait, that's what marriage already implies.

**Comment by esteldunedain** [comment]
Too many stringtables? Yeah, just hold on until we introduce ace_rpg, including a full set of soldier followers/companions, each with their own sidequests and optional romantic options.

**Comment by Harakhti** [comment]
@esteldunedain ACE_effect_3.pbo, DLCs not included?

**Comment by KoffeinFlummi** [comment]
Thanks!

**Pull request merged**
