### PR TITLE
Remove redundant rotation boundaries in Sitting

### PR DESCRIPTION
**Pull request by jonpas**
The PFH is only there to automatically stand up the player if a chair moves/falls, rotating is now disabled via `CfgMoves` thanks to @commy2

### CODE REVIEW

**Comment by SilentSpike** [comment]
Seems pretty trivial, I notice the auto stand up thing doesn't account for if their chair is deleted though (it also seems kinda wasteful to have an entire function just to check if the position has changed, wouldn't `isEqualTo` suffice?).

**Comment by jonpas** [comment]
It does account for deletion actually, doing `getPosASL` on an inexisting object returns `[0, 0, 0]`, just tested.

I'll look into `isEqualTo` replacement now.

**Comment by SilentSpike** [comment]
What if the chair was at position [0,0,0] :wink:

Gotta be explicit

**Comment by SilentSpike** [comment]
Also, it might make more sense to check the vectorDir of the chair rather than the position. I know it's probably very edge case, but there could be uses for a moving chair.

**Comment by jonpas** [comment]
> What if the chair was at position [0,0,0]

That's such an edge case it can't happen in theory, there will always be some decimal numbers, if someone puts it at `[0,0,0]` explicitly... I don't think it's warrants a check really.

> Also, it might make more sense to check the vectorDir of the chair rather than the position. I know it's probably very edge case, but there could be uses for a moving chair.

Well yes and no, from my experimentation a chair can get moved in such ways that it doesn't change direction (weird Arma if you ask me), I managed to do that by throwing a grenade next to it.

**Comment by SilentSpike** [comment]
>Well yes and no, from my experimentation a chair can get moved in such ways that it doesn't even change direction (weird Arma if you ask me), I managed to do that by throwing a grenade next to it.

lol, that's pretty halarious

I still think there should be an `isNull` check, again, explicit > implicit

**Comment by jonpas** [comment]
Trust me, I was shocked, couldn't even think about laughing...

There, added isNull check.

**Comment by SilentSpike** [comment]
:+1: the isEqualTo change doesn't cause any issues does it?

I've never actually ran a getPos command on an object that is stationary to check for changes

**Comment by jonpas** [comment]
It works perfectly fine, since I want even the slightest move to get recorded. Surprisingly even 0.0000001 changes don't matter which is Arma's real-time simulation weirdness.

**Comment by SilentSpike** [comment]
Cool, merging

**Comment by jonpas** [comment]
This was like live PR support. :grin:

**Pull request merged**
