### PR TITLE
Add and Update Some 3D Object and Textures

### PR DESCRIPTION
**Pull request by jokoho48**
Add IRStrobe 3D Object to attach (Made by Me)
Add M57 Clacker to explosives (Made by Me)
Add New LowPoly Earplug to Hearing (Made by Me)
Add WireCutter to logistics_wirecutter (Made by Me)
Reduce UAVBattery Texture Size in logistics_uavbattery (Made by Me)
Add MapTools to maptools (Made by Me)
Add 3D Object IVBag Blood, Plasma and Saline with 1000ml, 500ml, 250ml (Made by PaxJaromeMalues)
Add DAGR (by Blackpixxel)
Add QuikClot to Medical (by Blackpixxel)
Add QuikClot Litter (by Blackpixxel)

### CODE REVIEW

**Comment by jokoho48** [comment]
Add IVBags from PaxJaromeMalues

**Comment by jokoho48** [comment]
Add Content form Blackpixxel

**Comment by bux578** [comment]
Thank you and the others for that.

**Comment by Glowbal** [comment]
Thank you. I will take a look asap.

**Comment by Glowbal** [comment]
Thank you for your contributions!

**Pull request merged**
