### PR TITLE
Fix stop gesture keybind

### PR DESCRIPTION
**Pull request by PabstMirror**
This matches the interaction menu

stop -> gesutreFreze
freeze -> freeze

### CODE REVIEW

**Comment by jonpas** [comment]
I am confused, [this](https://github.com/acemod/ACE3/blob/702fc75e627f899a2c2f855a3116d540d01b6545/addons/gestures/XEH_postInit.sqf#L10-L11) should handle that.

**Comment by PabstMirror** [comment]
This should now match the interaction menu.
```
class GVAR(Stop) {
    displayName = CSTRING(Stop);
    statement = QUOTE([ARR_2(_target,'gestureFreeze')] call EFUNC(common,doGesture);); // BI animation - is actualls "stop" in all stances but prone

class GVAR(Freeze) {
    displayName = CSTRING(Freeze);
    statement = QUOTE(QUOTE(QGVAR(freeze)) call FUNC(playSignal));
```

**Comment by jonpas** [comment]
Ahh, so when doing it with keybind it was actually calling `BIgestureStop`, therefore not doing any gesture because that doesn't exist?

**Comment by Glowbal** [comment]
:+1:

**Pull request merged**
