### PR TITLE
Fastroping: post-release enhancements

### PR DESCRIPTION
**Pull request by BaerMitUmlaut**
**When merged this pull request will:**
- Use the `preStart` XEH in fastroping
- Fix a major bug with multiple people fastroping simultaneously
- Add a hiding animation for either of the gantrys from the gantry type FRIES (#3475)
- Force ramps from vanilla helicopters open when fastroping
- Improve rope twitching and glitchyness *a lot*, additionally ropes no more break when flying too fast
- Fix a config change which broke all fastroping interactions

For some reason, the FRIES on the Wildcat is now completly misaligned on my machine. I didn't change anything in the model and have a feeling this is a problem on my side.

Also needs testing, please mark as WIP.

### CODE REVIEW

**Comment by olanguedoc** [comment]
will this have an effect on the "AI PILOT" just going up towards space?

**Comment by BaerMitUmlaut** [comment]
No, that should already be fixed with #3508.

**Comment by olanguedoc** [comment]
So in the next update?

Olivier Languedoc
Réalisateur @ La Cavalerie
514.991.5052

**Comment by BaerMitUmlaut** [comment]
Yes.

**Comment by esteldunedain** [comment]
@BaerMitUmlaut, when are you planning on finishing this? Do you think it could be finished sometime this week?

**Comment by BaerMitUmlaut** [comment]
There's one more commit coming, and then I'll test it today if possible.

**Comment by esteldunedain** [comment]
Ok, perfect

**Pull request merged**
