### PR TITLE
pl translation

### PR DESCRIPTION
**Pull request by gienkov**

### CODE REVIEW

**Comment by bux578** [comment]
> 4,730 additions and 4,677 deletions.
uh, there's too much going on in this PR

**Comment by gienkov** [comment]
It's Tabler again... haven't used it in a while.

**Comment by bux578** [comment]
It kinda looks like a line ending problem.

**Comment by gienkov** [comment]
Indeed, Tabler keeps changing it from Unix to Windows format, thus all those changes.

**Comment by gienkov** [comment]
Better?

**Comment by bux578** [comment]
>Tabler keeps changing it from Unix to Windows format, thus all those changes.

Totally valid. Git handles line endings if you configure it correctly.

You should set `autocrlf = true`
https://help.github.com/articles/dealing-with-line-endings/#platform-windows

**Comment by gienkov** [comment]
Neat!

**Comment by esteldunedain** [comment]
:+1: For merging this while it still doesn't have conflicts

**Comment by bux578** [comment]
Looks good. Thanks @gienkov

**Pull request merged**
