### PR TITLE
[medical_status] Only set unconscious upon entering Cardiac Arrest

### PR DESCRIPTION
**Pull request by Whigital**
**When merged this pull request will:**
- Set unconsciousness only when entering Cardiac Arrest.

Addresses https://github.com/acemod/ACE3/issues/7448

### CODE REVIEW

**Comment by Whigital** [comment]
There's a check for unconsciousness in `ace_medical_status_fnc_setUnconsciousState`,
https://github.com/acemod/ACE3/blob/2feeec0d7f252209c48a79760d2dc129e5e80655/addons/medical_status/functions/fnc_setUnconsciousState.sqf#L24

so adding something like `&& {_unit getVariable [VAR_UNCON, false]}` feels redundant, or ?

**Comment by commy2** [comment]
Does it feel redundant or is it actually redundant? :)

**Comment by SilentSpike** [comment]
Would be redundant yeah 👍

**Comment by SilentSpike** [comment]
Have you tested that this is the cause of #7448?

The change should be included either way since it's an unnecessary call, just good to confirm

**Comment by Whigital** [comment]
Didn't manage to reproduce with this fix in. Then again, i didn't try to reproduce with released code either so, inconclusive :confused:

**Comment by commy2** [comment]
Would be nice to have confirmation that after this merged, the issue will be gone as well. Then I can tag this PR as "bug fix" and close the issue.

**Pull request merged**
