### PR TITLE
add 'name' to components

### PR DESCRIPTION
**Pull request by commy2**
**When merged this pull request will:**
- adds 'name' to all components by macros
- fixes some indentation issues and uses ADDON macro in parachute

### CODE REVIEW

**Comment by Glowbal** [comment]
What is the purpose of the name attribute in CfgPatches? Is this a new BI thing?

**Comment by SzwedzikPL** [comment]
> What is the purpose of the name attribute in CfgPatches? Is this a new BI thing?

Yes. Name from CfgPatches is displayed in required addons list in eden

**Comment by commy2** [comment]
And this patch will change "ace_gforces" to "Advanced Combat Environment 3 - gforces"

**Comment by bux578** [comment]
I don't like the long name. ACE3 is sufficient. And name should contain the file name of the pbo.

**Comment by commy2** [comment]
There is enough space for that name. Vanilla Arma has even longer ones.

>And name should contain the file name of the pbo.
You already get the name of pbo if you select the "advanced" tab. This screen is for end users.

**Comment by commy2** [comment]
`Arma 3 Marksmen (Multiplayer) - Mission Texts and Translations`
vs.
`Advanced Combat Environment 3 - spottingscope`

**Comment by bux578** [comment]
> This screen is for end users.

Exactly.

"ACE3" is more common. And it's the end user that deletes random pbo's. So giving them the info what pbo they require would be helpful.

**Comment by commy2** [comment]
Yeah.
I wouldn't use the raw pbo name though. That's what you get in the "advanced" tab already. It would defeat the purpose of this system.

**Comment by jonpas** [comment]
I vote `ACE3 - component` as well.

Would be great if we could prettify components but that's some work I guess. :D

**Comment by commy2** [comment]
Thanks for the help, guys. :+1:

**Comment by commy2** [comment]
merging, sue me

**Comment by bux578** [comment]
_sues commy_

**Pull request merged**
