### PR TITLE
Less fictional weapon names

### PR DESCRIPTION
**Pull request by Brisse89**
ACP-C2 -> Custom Covert II
KT2002 Katiba -> KH2002 Khaybar

### CODE REVIEW

**Comment by ulteq** [comment]
Is anyone against it?

**Comment by alganthe** [comment]
is it confirmed that they are the real counterpart ?

**Comment by Harakhti** [comment]
I agree with what @alganthe says, it looks more like the improved 2009 "Sama" model, not the original Khaybar.

**Comment by Brisse89** [comment]
DIO is intentionally left out since it is manufacturer name. "Sama" is interesting. Googling it yields very few results, but there seems there might be a real world upgraded Khaybar called Sama. 

Best info I could find was on the bottom of this page: http://defense-arabia.blogspot.se/2009/02/irans-small-arms-assault-rifles.html

**Comment by alganthe** [comment]
according to that link the older model is called the Khaybar and the newest the Sama.
So I would say "KH2002 Sama" would be more accurate.

**Comment by Harakhti** [comment]
The Sama in theory is KH-2009, but not sure. If anyone can get a verification on that...

**Comment by alganthe** [comment]
Not sure either but saw some websites indicating KH2009 Sama indeed

**Comment by Brisse89** [comment]
Googling KH2009 yields very little results related to this weapon. Does anyone have a good source that confirms it's name should be KH2009?

**Comment by alganthe** [comment]
Go for KH2002 Sama since we can't find results about the 2009 version.

**Comment by ulteq** [comment]
Maybe `1911 Custom Covert II` instead of just `Custom Covert II`?

**Pull request merged**
