### PR TITLE
Update how weight is displayed in ACE arsenal

### PR DESCRIPTION
**Pull request by alganthe**
**When merged this pull request will:**
- Weight is now indicated as follows: "kilos (lbs)".

new weight

### CODE REVIEW

**Comment by PabstMirror** [comment]
Why not just show a single weight that matches the user setting for inventory display?

**Comment by alganthe** [comment]
Because that way you can tell your squadmates using the other system how much you weight without having to go on a google search.

**Comment by Cuel** [comment]
If merged the change should be reflected in inventory aswell imo

**Comment by Dystopian** [comment]
I know how make it suitable for everyone: make the option not just `kg` and `lb`, but also `Show both (kg first)` and `Show both (lb first)`

**Comment by alganthe** [comment]
The order literally doesn't matter., for inventory this is out of the scope of this PR

**Comment by commy2** [comment]
Done in #5918.

**Comment by jonpas** [comment]
The PRs work hand-in-hand right @commy2 ? As in merging them both it should already work.

**Comment by commy2** [comment]
Yes.

**Pull request merged**
