### PR TITLE
Interact menu settings after init

### LINKED ISSUE #1171: The land of the mysteriously missing interact menus
RPT: http://pastebin.com/VvhUzYUj
Another RPT: http://pastebin.com/1NiZ57dE

Symptoms:
- This is consistently happening across all players @ UO with the modpack. It may/may not be mod pack related, but the conflict seems common enough to warrant investigation. 
- It is random, reconnects and/or reslots fix it. This means a preinit/postinit re-run fixes it.
- Units in tests are RHS units
- It cannot be file corruption or CBA issues, as the server is signed/modpacked/verified 

Thoughts on possible causes (checkbox is ruled out):
- [x] mods using the old CBA method are corrupting the keybinds (unlikely, ACRE still works)
- [] I tested excessive XEH times; that is *not* the cuplrit.
- [ ] XEH Initialization order
- [x] Somehow the objects are not tracking their interactions correctly
- [x] Interaction cache is getting corrupted or deleted 
- [x] RHS unit related issue for XEH initializers for the actions
- [ ] ????????? @esteldunedain  help me out here bud

### LINKED ISSUE #2486: Settings (size, colour) of menu interaction, cannot be saved.
ACE3 Version: 3.3.1
Stable

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed ACE3 Modules:**
None

**Description:**
Modify the text size and colors of interaction menu, always and always return to the standard indicators (default size and default colours).

**Steps to reproduce:**
Try to modify the interaction menu with yourself(color and size) via ACE Settings in the left upper corner. First you will see that the changes came into force, but later(after small time), the interaction menu will return to its default size and colour.

**Where did the issue occur?**
Editor

**RPT log file:**
Not needed

### PR DESCRIPTION
**Pull request by PabstMirror**
fix #2486 (might fix #1171 as well???)

* setupTextColors now runs after SettingsInitialized and only then do we install render
* settingsChanged uses count to handle possible capitalization differences
* minor optimization in fnc_render - (save 0.015ms wow !!!!!!!!)

### CODE REVIEW

**Comment by commy2** [comment]
I take from this that all postInit are guaranteed to execute before SettingsInitialied ?
Pls merge soon, so I can get done with #2150 without ze merge conflicts.

**Comment by PabstMirror** [comment]
I think it goes like this
```
run all preInit
run all postInit
...possibly some frames later...
run all ace_modules (server finishes before clients start)
read client saved settings
run "SettingsInitialized" event
run all runAtSettingsInitialized functions
```
#2150 should be fine, this is for interact_menu vs interaction

**Comment by commy2** [comment]
Oh, right. Derp.

**Comment by Glowbal** [comment]
@PabstMirror I think it goes more like this:

Server side:
```
- run preInit (server side collection of config settings)
- run init
- ACE module init
- postInit (settings initalized event is called somewhere during postInit)
```

Client side:
```
- run preInit
- run init
- ACE module init (settings are server only, so won't do much)
- postInit
- Sometime after or during post init, settings arrive. This depends on the moment of joining by the client. At start: After postInit. JIP: either after or during postInit.
```

**Comment by PabstMirror** [comment]
modules get added to collection in their init
but don't get run until event `InitSettingsFromModules` which is after all other postInit

**Comment by Glowbal** [comment]
Oh right, that got changed from the first implementation. I forgot about that. :+1:

**Pull request merged**
