### PR TITLE
Use AGL for sitting setPos

### PR DESCRIPTION
**Pull request by PabstMirror**
#2391

Tag @jonpas

### CODE REVIEW

**Comment by jonpas** [comment]
What's the actual difference? Are there problems with how it was? Is the new not slower (not like it matters, just personal interest)?

**Comment by PabstMirror** [comment]
https://community.bistudio.com/wiki/Position
modelToWorld returns AGL (which is the same as ASLW over water)

So on the carrier on utes, it's something like `[x,y,16.5]`
Doing `player setPos [x,y,16.5]` on the carrier, sticks you 16 meters up in the air.

I'm not entirely sure what format `setPos` uses? biki says AGL but I dont think that's right.
This explicitly converts AGL into ASL and then uses the setPosASL.

**Comment by SilentSpike** [comment]
I think `setPos` is a kind of AGL, but if there's a building or something at the position it might not necessarily detect it, hence ATL.

**Comment by jonpas** [comment]
Perfect. :grinning:

**Pull request merged**
