### PR TITLE
Disposable - switch NLAW to CBA disposable system and remove ace_disposable functionality

### PR DESCRIPTION
**Pull request by commy2**
**When merged this pull request will:**
- title
- see: https://github.com/CBATeam/CBA_A3/pull/1116

### CODE REVIEW

**Comment by PabstMirror** [comment]
to maintain compatibility with CUP, we probably want to go in stages
- move nlaw over to cba
- then remove code after next cupdate

**Comment by jonpas** [comment]
Standard 2 version deprecation sounds the best to me.

**Comment by commy2** [comment]
I don't understand why we need to put the NLAW into CBA.

**Comment by PabstMirror** [comment]
I mean make it compatible with cba_disposable (like how the configs are changed in this PR)
but leave the ace_disposable code for other addons to use

**Comment by commy2** [comment]
All we have to do is to update CBA first, then CUP and at a later point ACE.

**Comment by commy2** [comment]
Merge?

**Comment by PabstMirror** [comment]
this needs to be after cup

**Pull request merged**
