### PR TITLE
Comment out 3den Attributes for 3.5.0

### LINKED ISSUE #3339: Module has wrong values when placed with 3D Editor
**ACE3 Version:**
3.4.2.0

**Mods:**
@CBA_A3 (tested with v2.2.0 and v2.3.0, same results)
@ACE

**Description:**
There is some odd behavior with the module values in the 2D editor versus the 3D editor, specifically with the ACE Medical -> Medical Settings Module. 

[2D Editor Default Module Settings](http://puu.sh/ncLG2/d7078ddf02.png)
[3D Editor Default Module Settings](http://puu.sh/ncLbJ/65875a418d.png)

The 2D editor modules are fine and won't cause any issues, the 3D editor-placed ones, however, seem to give the wrong values for some of the settings, regardless if you make changes to the setting or not.

Looking at the mission.sqm - a 2D editor-placed [module with AI unconsciousness turned off has a value of 0](http://puu.sh/ncMa0/c8e199d486.png). A 3D editor-placed [module with AI unconsciousness turned off has a value of -1.](http://puu.sh/ncMxR/fb59a31aec.png)

Also causes some .RPT outputs listed below.

**Steps to reproduce:**
- Make a fresh mission in 3D editor
- Place player
- Place medical module (set AI unconsciousness to disabled)
- Place enemy group
- Preview
- Shoot enemies and they will still go unconscious
- Check RPT for errors below

**Where did the issue occur?**
3D Editor

**.RPT:**
http://pastebin.com/2MCdtRiY

**Excerpt from RPT:**
19:42:33 [ACE] (common) WARNING: Setting [ace_medical_medicSetting] out of bounds -1 (values[] count is 3)(
19:42:33 [ACE] (common) WARNING: Setting [ace_medical_enableUnconsciousnessAI] out of bounds -1 (values[] count is 3)(

### PR DESCRIPTION
**Pull request by esteldunedain**
### When merged this pull request will:

1. Remove ACE 3den attributes temporarily until BIS solves the problem which changes entries from 0. 

2. Close #3339

As explained by @PabstMirror here: https://github.com/acemod/ACE3/issues/3339#issuecomment-186967305.

### CODE REVIEW

**Comment by PabstMirror** [comment]
Might be able to hold off on this, playing with rewriting the combo box with something else 
image

But needs testing  ed96307f2f16d689dc2218bbe5de5e0a0b945675
(Plus it's easier to use than the awkward drop down thing)

**Comment by esteldunedain** [comment]
> Might be able to hold off on this, playing with rewriting the combo box with something else 

Looks good.

**Comment by gienkov** [comment]
Comment captives too then since you cannot set both handcuffed and
surrender (doesn't make sense).
22.02.2016 2:45 PM "Nicolás Badano" <notifications@github.com> napisał(a):

**Comment by commy2** [comment]
These drop down boxes aren't working for me anyway. I can't select anything on an expanded box, except by typing it with the keyboard.
They also are cut off at the botton most of the time.
I saw another issue about this on the feedbacks before it was shot down.

**Comment by esteldunedain** [comment]
Closed in favor of #3393

**Pull request closed without merging**
