### PR TITLE
Explosive fix attach delete vehicle fix

### PR DESCRIPTION
**Pull request by ulteq**

### CODE REVIEW

**Comment by CorruptedHeart** [comment]
I'm not sure simply removing the delete will result in the correct actions taking place.

However, If you add an `Explosion` event to the helper object, that removes itself when its explosive ammo object is no longer around. It would have the desired effect. As well as taking care of cleaning up defuse objects when the explosive is trigger through another means.

Could also allow certain explosives to be set off by nearby explosions if Arma doesn't correctly handle that at the moment.

**Comment by ulteq** [comment]
`_helper = (attachedTo (_item select 0));`

_helper was either `<null>` or `<vehicle it was attached to>`.
In both cases nothing needs to be deleted.

> Could also allow certain explosives to be set off by nearby explosions if Arma doesn't correctly handle that at the moment.

I will test that.

**Comment by alganthe** [comment]
someone pushed the wrong pull request -_- reverting the one from past and pushing this one is much needed now.

**Comment by PabstMirror** [comment]
I just closed #909, thanks really testing it and fixing the bug.

**Comment by alganthe** [comment]
it's working as intended on my end on this branch.

**Comment by ulteq** [comment]
@CorruptedHeart, I think the new code is the way it was originally planned.

**Pull request merged**
