### PR TITLE
Push SDV sub, cleanup push

### PR DESCRIPTION
**Pull request by PabstMirror**
#2045
Note: sub couldn't be pushed because it's `mass` is 2600 and we had a limit of 1000.
2600 is more than twice a hatchback, mass is kinda wonky in this game.
I just upped it to 2600.  The big big assault boat is 9600, so it still cannot be pushed.

Also switched to use event system.

### CODE REVIEW

**Comment by Glowbal** [comment]
A cleaner solution would be to use a different mass limit if the object is floating in water.

**Comment by bux578** [comment]
^ you can push very heavy stuff that's floating

**Comment by SilentSpike** [comment]
Do configs have some sort of buoyancy value?

**Comment by jonpas** [comment]
Recently BI added buoyancy values IIRC.

**Comment by cptnnick** [comment]
There have been for a while, just the Buoy object didm't have a config value for buoyancy, which they fixed.

**Comment by SilentSpike** [comment]
Then perhaps we could use that value and the mass value to calculate a representation of how hard it is to push

**Comment by jonpas** [comment]
Well, if the object is entirely in the water, then you can really push around insanely heavy objects (just difference in speed), what this function must do is make sure yiu can't push something insanely heavy when it's eg. only halway in the water.

**Pull request merged**
