### PR TITLE
[WIP] Fix script errors reporting wrong line numbers

### PR DESCRIPTION
**Pull request by dedmen**
analogue to https://github.com/CBATeam/CBA_A3/pull/937

Todo:
- [ ] check if documentation generator can handle this

Shouldn't need to worry about merge conflicts. unless someone edited the first line of some script.

Doing all commits for automated replacement first. Then manual commits that need closer review later.
Automatic updates use notepad++ replace in files
`\s*(/\*[\s\S]+?\*/)\s*#include\s*"script_component\.hpp"`
-> `#include "script_component.hpp"\n$1`

### CODE REVIEW

**Comment by dedmen** [comment]
All automatic changes are done to this point. Now to the manual ones... Which a quick search tells me will be 28!

**Comment by dedmen** [comment]
>check if documentation generator can handle this

We don't even have a documentation generator as far as I can see :D 
I'd like to add a check to the SQF validator that there are no #include's after block comments. Which is just a simple regex. But for some files like https://github.com/acemod/ACE3/blob/master/addons/zeus/functions/fnc_zeusAttributes.sqf#L23
That would always throw errors.

**Comment by SilentSpike** [comment]
@dedmen Exclude `.sqf` extension from the filter?

**Comment by dedmen** [comment]
@SilentSpike We only want to check sqf files though. ^^

**Comment by dedmen** [comment]
need someone to test the sqf_validator.py change

**Comment by Dystopian** [comment]
> need someone to test the sqf_validator.py change

tested, works

**Comment by dedmen** [comment]
@Dystopian Working means it should throw an error about https://github.com/acemod/ACE3/blob/master/addons/zeus/functions/fnc_zeusAttributes.sqf#L23 currently. 
Does it do that? Or does it work in the sense that it isn't completely broken?

**Comment by Dystopian** [comment]
It really triggers if `#include` is not before `/*comment*/` but right after it.
It doesn't throw error if **anything except whitespace**  is before `/*comment*/` and I don't know why :disappointed:.
Slack for more.

**Comment by dedmen** [comment]
>check if documentation generator can handle this

🤔 Which documentation generator even? Does ACE have one?

**Comment by Dystopian** [comment]
#5253?

**Comment by jonpas** [comment]
Ah, @SilentSpike !

I think we should merge this, documentation script can easily be changed in order afterwards.

**Comment by dedmen** [comment]
Somehow I thought we already had a documentation generator merged :thinking:

**Pull request merged**
