### PR TITLE
Fix empty flashlightProxy model + Delete map glow lights from disconnecting players

### LINKED ISSUE #2828: No shape RPT errors for Map Flashlights
ACE3 Version: 3.3.2 (stable)

**Mods:**
* `@cba_a3`
* `@ace3`

**Placed ACE3 Modules:**
N/A

**Description:**
Use the map flashlight and check RPT, `No shape for ammo type ACE_FlashlightProxy_White` shows up.

**Steps to reproduce:**
* Use map flashlight
* Check RPT

**Where did the issue occur?**
Multiplayer - Dedicated

**RPT log file:**
N/A

### PR DESCRIPTION
**Pull request by PabstMirror**
Fix #2828
@voiperr - this should be fine, just wanted to check with you

### CODE REVIEW

**Comment by jonpas** [comment]
That was fast!

**Comment by jokoho48** [comment]
:+1:

**Comment by PabstMirror** [comment]
Added fix for #2810

**Comment by voiperr** [comment]
The secret that I don't know much about ammo configs is out. :sweat_smile:
:+1:

**Pull request merged**
