### PR TITLE
Add seperate setting for NVG noise intensity

### PR DESCRIPTION
**Pull request by BaerMitUmlaut**
**When merged this pull request will:**
- Add a seperate setting for NVG noise intensity

A seperate setting for this makes sense as it can cause headaches with long time use. The other effects do not cause this issue. Was also requested in #3594 by @ghost.

### CODE REVIEW

**Comment by jonpas** [comment]
Should it not be a client setting in that case?

Should also be added via CBA Settings directly.

**Comment by BaerMitUmlaut** [comment]
No, because it's also a difficulty option.
I don't think it's a good idea to have half CBA, half ACE settings. Either convert all or none.

**Comment by jonpas** [comment]
> Either convert all or none.

All, and use `movedToSQF` like in markers.

**Comment by BaerMitUmlaut** [comment]
That's not the point of this PR and should be done in a seperate one. Small, granular changes.

**Comment by jonpas** [comment]
Sure, but before next release then. Less `movedToSQF` the better. Doesn't matter during development as we obviously don't provide backwards compatibility that time.

**Pull request merged**
