### PR TITLE
Vanilla Mortars - Rangetables/Tweaks

### PR DESCRIPTION
**Pull request by PabstMirror**
Adds rangetable #115 and makes the MK6 Mortar less awful.
I had a more advanced version for AGM, but it was a new vehicle whereas this is mostly done via scripts.  So it will have no effect unless activated and you don't have to change missions/loadouts.

- [x] - User toggle to show MILS/Degrees on Mortar Hud
- [x] - Shows shell charge (upper right) (I have no idea how they expect people to do indirect fire without showing this)
- [x] - control showing rangefinder/compass/artillery computer
- [x] - Rangetable (and backend to generate)
- [x] - Air/Wind Effects

Todo: 
- [x] - Rangetable data for no air resistance (same item, just change what's showed based on world setting)
- [ ] - Maybe add some more ammo types (different smoke colors, airburst)

### CODE REVIEW

**Comment by jaynus** [comment]
I'd recommend merging this so we can get some sort of functional mortars in at this time. This is a good stop gap solution, which we can also update, as we go along.

Do the range tables apply to all mortars?

**Comment by commy2** [comment]
:+1: MergeMergeMerge

**Comment by NouberNou** [comment]
Only thing I can say about the tables is that they need to make sure to account for things like cargo rounds and time fuzes. Usually there is a field for adjusting the time fuze in seconds based on increments of elevation.

That being said, most cargo rounds are for howitzers and in that case the BCS (or similar system will be used to calculate firing solution).

**Comment by austinjames314** [comment]
Are tables going to be added for the smoke rounds? After lots of testing, the smoke rounds consistently go well past the expected point of impact using the existing tables for the HE rounds. I'm hoping we'll get a table for the smoke rounds as well soon? 
I'm not sure about the illumination rounds, as I haven't had a good chance to test them as so often other players can't see them.

**Comment by Giorox** [comment]
Been having the same problems with smoke rounds as @austinjames314 , would like to know about that aswell.

Other thing that would be nice is having artillery tables for the RHS artillery, since they add the Arma 2 Vanilla artillery (81mm and 105mm) as well as some self-propelled ones.

PS: That 60mm from ACE2 was amazing....

**Comment by austinjames314** [comment]
@Giorox I've been using the 3CB BAF mortars the last couple of years, and they are the best out there. Smoke rounds work perfectly, it includes a much better ammo handling system, and it also has a 60mm mortar system. Runs off the back of the ACE3 mortar system. I recommend you try that out.
As for RHS mortars, that's not an ACE issue. If they (RHS) had left the ballistics alone, then you could use the ACE3 mortar tables, but because they've changed the ballistics, and (last I checked) not published what exactly they've done to it, it's impossible to aim them. (unless you cheat and use the artillery computer I guess)

**Pull request merged**
