### PR TITLE
Self blood infusion for SP

### PR DESCRIPTION
**Pull request by eagleye100**
Hi Guys,

I know you all guys are working around the clock but i dont think if anyone has come up with this request before, but i would be so delighted to have self blood infusion ability in single player modes same as in Arma 2 ACE. Without self infusion i have to disable ace or agm and this way i mess up with control keys all the time.

Thanks

### CODE REVIEW

**Comment by PabstMirror** [comment]
you need to double check your head and base when making a PR.

I can't actualy see your repo of ace (https://github.com/eagleye100) ?

Did you mean to make a feature request (#414)?

**Comment by eagleye100** [comment]
yes. how you receive pr?

**Comment by PabstMirror** [comment]
Pull Requests are for when you have code written that you want to contribute to ACE.
If you just want to request a feature, put it in the feature request issue (#414).

**Comment by eagleye100** [comment]
thank you and apology for any inconvenience

**Pull request closed without merging**
