### PR TITLE
CUP compat no longer needed: CUP makes their own

### PR DESCRIPTION
**Pull request by PabstMirror**
ref
https://forums.bistudio.com/topic/179326-community-upgrade-project-cup/

CUP has been making their own ACE compat PBO for some time now (last updated 2015-12-25)
Looks like they did a great job on it, so kudos to the CUP team!

### CODE REVIEW

**Comment by jonpas** [comment]
:+1: for CUP Team!

**Comment by Glowbal** [comment]
:+1:

**Comment by bux578** [comment]
:+1:

**Comment by esteldunedain** [comment]
:+1: Glad to hear this!

**Pull request merged**
