### PR TITLE
Added compatability addon for RKSL LDS (2D animated optics and PiP optics) under optionals

### PR DESCRIPTION
**Pull request by da12thMonkey**

### CODE REVIEW

**Comment by da12thMonkey** [comment]
Ulteq comitted 819b7af42617795cddf1d7dafeb93bbd8a11908e a compatibility addon for the RKSL PM II scope I made, so I thought I'd push the one I did for the LDS.

One concern I have is whether adding such compatibility addons that contain textures for the animated 2D and PiP optics system will cause too much bloat to the overall file size of the mod

**Comment by ulteq** [comment]
This seems to convert the standard LDS into a 2D version of it. Is this correct? The area outside of the scope is very dark:

**Comment by da12thMonkey** [comment]
The 2D image was created by rendering the 3D model in Marmoset Toolbag and applying some depth of field effects, so yes it more or less converts the standard model into a 2D format.

The area outside the scope is darkened by modeloptics = \z\ace\addons\optics\models\ace_optics_reticle90.p3d made by the ACE team, not the 2D texture I made that is overlayed on top.

Other optics in the mod use ace_optics_reticle90.p3d, so the outside is no darker than the ARCO or RCO. AFAIK "reticle90" implies that the black area surrounding the scope is 90% opaque, so other models in the folder provide different opacities.

I did try ace_optics_reticle80.p3d (80% opacity) but there's a visible seam in the area around the scope when using wide-screen monitors, so I thought it best to use the 90% standard used by other optics in the mod.

**Comment by esteldunedain** [comment]
@ulteq, @da12thMonkey, sorry if you already talked about this privately (you probably have). The ideal solution is to include all this ace entries **along with the original mod config as long as they don't clash with the vanilla game**. If they do, then the recommended solution would be to **have a compatibility pbo distributed with RKSL LDS**.

The ACE compat pbos are only meant to be a temporary solution, in order to:

- provide a sample of what config entries are needed for compatibility and how to write them as 
optional

- kickstart compatibility work on sone very high profile mods

The ultimate goal however is to deprecate them, moving all the compat configs into the source mods.

**Comment by ulteq** [comment]
@da12thMonkey, I would like to have 3 different versions then.
1. LDS
2. LDS (2d)
3. LDS (PiP)

And @esteldunedain is right. The compat PBOs are only an interim solution.

**Comment by Glowbal** [comment]
It appears this is already part of the RKSL optional pack. Also, inactivity & merge conflicts.

**Pull request closed without merging**
