### PR TITLE
Added 'parachute' and 'camera' hitpoints to the HuntIR model:

### PR DESCRIPTION
**Pull request by ulteq**
* You can now shoot the parachute to make it fall faster
* And you can shoot the camera to kill the video feed

### CODE REVIEW

**Comment by esteldunedain** [comment]
:+1:

**Comment by whiztler** [comment]
Can this be added to the 3.1.0 milestone?

**Comment by esteldunedain** [comment]
> Can this be added to the 3.1.0 milestone?

No

**Comment by Glowbal** [comment]
Is this ready?

**Pull request merged**
