### PR TITLE
Arsenal - Sort by protection (helm, uniform, vest)

### PR DESCRIPTION
**Pull request by PabstMirror**
Idea From @Elgin675 - https://github.com/acemod/ACE3/issues/3594#issuecomment-698439972

### CODE REVIEW

**Comment by Elgin675** [comment]
Thank you very much @PabstMirror !
After a quick test, it works well !
But in the case of some vests with a higher explosive resistance than bullet resistance (V_PlateCarrierGL_xxx), the order is not good.

Is it due to the fact that the filter takes into account the highest resistance, without distinction between ballistic and explosion ?

Tri

**Comment by PabstMirror** [comment]
The formula is roughly `ballistic * 2 + explosive`; we could change coefficient to 10x to make explosive less important.

**Comment by Elgin675** [comment]
I think it's a good idea ;) !
Or separate the sorting by ballistic protection and the sorting by explosive protection, but it seems a bit extreme :D ^^ !

**Comment by BrettMayson** [comment]
Personally I was going to split this into two

**Comment by Elgin675** [comment]
Work's fine, thank you :) !

**Review by jonpas — APPROVED** [review]

**Pull request merged**
