### PR TITLE
WIP: Support # command in SQF Validator (quick, will miss missing semi-col…

### PR DESCRIPTION
**Pull request by thojkooi**
…ons on actual # command)

### CODE REVIEW

**Comment by jonpas** [comment]
Very WIP, breaks builds, see https://github.com/CBATeam/CBA_A3/pull/920#issuecomment-388635843

**Comment by dedmen** [comment]
the column typo is still not fixed :D

**Comment by jonpas** [comment]
Whoever knows more about this linter, please fix it!

**Comment by jonpas** [comment]
Replaced by #6768.

**Pull request closed without merging**
