### PR TITLE
Added a real nozzle

### PR DESCRIPTION
**Pull request by GitHawk**
Added code for nozzle object
Params and private update

Special thanks to @jokoho48 for the modell

nozzle in action

### CODE REVIEW

**Comment by esteldunedain** [comment]
That looks perfect. Congrats to both of you

**Comment by licht-im-Norden87** [comment]
Wow, astonishing work! Really like it. But maybe the texture does not look "used" and could need some improvement.

**Comment by Glowbal** [comment]
I am happy with this. If we want to change the model, we can do that at a later stage. What @licht-im-Norden87 is suggesting does make sense. What are your thoughts on that @GitHawk and @jokoho48 ?

**Comment by GitHawk** [comment]
i'm no graphics guy. Everybody with some skills can now improve the nozzle further

**Comment by jokoho48** [comment]
@Glowbal there are some issues with the model import @GitHawk done i will fix that in a PR in some min

**Comment by GitHawk** [comment]
Possible, was the first time I used the Object Builder.

**Pull request merged**
