### PR TITLE
common code cleanup part 7

### PR DESCRIPTION
**Pull request by commy2**

### CODE REVIEW

**Comment by commy2** [comment]
Do we need setProne?
There is a goKneeling that is functional.

**Comment by commy2** [comment]
done otherwise

**Comment by PabstMirror** [comment]
@commy2 - it's no worse than before, we can deal with it later, just merge if you want to keep going

**Comment by commy2** [comment]
There is another nifty error with it that I had in similar scripts already. If you put you weapon on back or have no weapon then `currentWeapon player == primaryWeapon player == ""`

**Pull request merged**
