### PR TITLE
Laser guidance for all designators

### PR DESCRIPTION
**Pull request by esteldunedain**
Tasks:
- [x] Enable ace_laser to interact with vanilla lasers.
- [x] Make laser dispersion optional, default off.
- [x] Rewrite `fnc_shootRay` using `lineIntersectsSurfaces`.
- [x] Deprecate laser_selfdesignate in favor of the laser_designate?

### CODE REVIEW

**Comment by PabstMirror** [comment]
@esteldunedain did some work on this and I think we can grab it for 3.8

Fix #4420 (someone else is trying to use the framework, so I'd like to get this merged even if we don't have some of the other stuff done)
Fix #1959
Fix #967

I merged laser_designate into laser
lase_selfDesignate really isn't nessacary so was dropped
rewrote big chunk of laser
using `lineIntersetsSurfaces` was much faster for shootRay

If anyone wants to test it out, there is a hidden vehicle that you can spawn in `ACE_Comanche_Test`

**Comment by esteldunedain** [comment]
:+1: @PabstMirror, I'm glad to see this being rescued from oblivion.

**Comment by PabstMirror** [comment]
This seems to be working in mp
Moved some of the laser todos to #380

We still don't have any vehicles that are using this right now besides the `ACE_Comanche_Test`
I'm not sure if we want to re-add laser/dagr weapons to the main comanche, we could make it optional (3den attribute?)

**Comment by esteldunedain** [comment]
> I'm not sure if we want to re-add laser/dagr weapons to the main comanche, we could make it optional 

If it's possible to add them to the main Comanche as optional, then :+1: for that. But if not, I think we could keep it sepparate for now.

**Comment by PabstMirror** [comment]
I'm thinking it would work similar to #3043
Using something like `removeWeaponTurret` and `addWeaponTurret` to just swap launchers/ ammo.

**Comment by esteldunedain** [comment]
> Using something like removeWeaponTurret and addWeaponTurret to just swap launchers/ ammo.

@PabstMirror, great idea; that sounds perfect.

**Pull request merged**
