### PR TITLE
Increase interaction distance with explosives from 1m to 1.5m. 

### LINKED ISSUE #3379: Explosives are cumbersome to interact with while standing
**Arma 3 Version:** `1.56`

**ACE3 Version:** `3.4.2`

**Mods:**
* `@CBA_A3`
* `@ace`

**Placed Modules:**
None

**Description:**
It looks like the ability to interact with something depends on proximity of player's head (or upper body) to object you're trying to interact with. With default ace interaction (show cursor disabled) it causes problems, since your entire body moves while interacting (left - right / up and down). Which causes you to appear out of range, and interaction gets aborted. Even though you're close enough to original interaction point. 

Check the video below to understand better what I'm trying to say.

**Steps to reproduce:**
https://www.youtube.com/watch?v=-5PyrVKUA_Q&feature=youtu.be

**Where did the issue occur?**
Everywhere

### PR DESCRIPTION
**Pull request by esteldunedain**
**When merged this pull request will:**
- Increase interaction distance with explosives from 1m to 1.5m. 
- Fix #3379

It's a nice usability enhancement, that makes placing explosives quicker and more streamlined.

### CODE REVIEW

**Comment by jonpas** [comment]
:+1:

**Comment by esteldunedain** [comment]
Normal eyepos in arma is 1.52m, so the new distance prevents the issue that @Gwynblade described from happening at all and should allow confortable interaction.

**Comment by esteldunedain** [comment]
Interaction distance for defusing was reduced again to 1m by @bux578 's request

**Comment by bux578** [comment]
:kissing:

**Pull request merged**
