### PR TITLE
Map Gestures - reduce the size of the procedural texture and don't generate mipmaps

### PR DESCRIPTION
**Pull request by jokoho48**
**When merged this pull request will:**
- Title

### CODE REVIEW

**Comment by dedmen** [comment]
And why? generating 8x8 procedural texture instead of loading a 32x32 from disk is better on memory usage and doesn't need disk access to load.

**Comment by jokoho48** [comment]
after my tests, it was marginally faster to use the static texture instead of procedural textures but if you say its worse than I trust you

**Comment by dedmen** [comment]
How did you test and how much faster?

**Comment by jokoho48** [comment]
when I use a 1,1,1 texture it is the fastest so I am gonna switch that to that.
I draw 100x100 "icons" and average the values of 1000 frames
8x8,3 - 7ms
texture - 6ms
1x1,1 - 5ms

**Pull request merged**
