### PR TITLE
realisticnames 1.50 Updating Base Class Changes

### PR DESCRIPTION
**Pull request by PabstMirror**
- [ ] protection (FixUniforms.hpp)
- [ ] medical
- [x] realisticnames

New Hitpoints have some really messy inheritance

### CODE REVIEW

**Comment by Glowbal** [comment]
I guess we will need to fix all of these this week.

**Comment by PabstMirror** [comment]
protections has a lot of commented out stuff, I'm not sure how much of it is necessary

**Comment by jonpas** [comment]
Just ran the game with 5ea98143e237114a2b5d850b2209037c2cba5a7a and Arma 3 1.50. The following base class errors showed up. Also note the first line (`Cannot delete class EventHandlers`), this is pure `@CBA_A3` and `@ace`.

```
Cannot delete class EventHandlers, it is referenced somewhere (used as a base class probably).
Updating base class HitPoints->, by z\ace\addons\medical\config.cpp/CfgVehicles/CAManBase/HitPoints/
Updating base class HitArms->, by z\ace\addons\medical\config.cpp/CfgVehicles/CAManBase/HitPoints/HitHands/
Updating base class HitLegs->, by z\ace\addons\medical\config.cpp/CfgVehicles/CAManBase/HitPoints/HitLegs/
Updating base class HitNeck->HitHead, by z\ace\addons\medical\config.cpp/CfgVehicles/B_Soldier_04_f/HitPoints/HitHead/
Updating base class HitChest->HitBody, by z\ace\addons\medical\config.cpp/CfgVehicles/B_Soldier_04_f/HitPoints/HitBody/
Updating base class HitArms->HitHands, by z\ace\addons\medical\config.cpp/CfgVehicles/B_Soldier_04_f/HitPoints/HitHands/
Updating base class HitNeck->HitHead, by z\ace\addons\medical\config.cpp/CfgVehicles/B_Soldier_05_f/HitPoints/HitHead/
Updating base class HitChest->HitBody, by z\ace\addons\medical\config.cpp/CfgVehicles/B_Soldier_05_f/HitPoints/HitBody/
Updating base class HitArms->HitHands, by z\ace\addons\medical\config.cpp/CfgVehicles/B_Soldier_05_f/HitPoints/HitHands/
Updating base class HitNeck->HitHead, by z\ace\addons\medical\config.cpp/CfgVehicles/I_Soldier_03_F/HitPoints/HitHead/
Updating base class HitChest->HitBody, by z\ace\addons\medical\config.cpp/CfgVehicles/I_Soldier_03_F/HitPoints/HitBody/
Updating base class HitArms->HitHands, by z\ace\addons\medical\config.cpp/CfgVehicles/I_Soldier_03_F/HitPoints/HitHands/
Updating base class HitNeck->HitHead, by z\ace\addons\medical\config.cpp/CfgVehicles/I_Soldier_04_F/HitPoints/HitHead/
Updating base class HitChest->HitBody, by z\ace\addons\medical\config.cpp/CfgVehicles/I_Soldier_04_F/HitPoints/HitBody/
Updating base class HitArms->HitHands, by z\ace\addons\medical\config.cpp/CfgVehicles/I_Soldier_04_F/HitPoints/HitHands/
Updating base class HitNeck->HitHead, by z\ace\addons\medical\config.cpp/CfgVehicles/O_Soldier_base_F/HitPoints/HitHead/
Updating base class HitChest->HitBody, by z\ace\addons\medical\config.cpp/CfgVehicles/O_Soldier_base_F/HitPoints/HitBody/
Updating base class HitArms->HitHands, by z\ace\addons\medical\config.cpp/CfgVehicles/O_Soldier_base_F/HitPoints/HitHands/
Updating base class HitNeck->HitHead, by z\ace\addons\medical\config.cpp/CfgVehicles/O_Soldier_02_F/HitPoints/HitHead/
Updating base class HitChest->HitBody, by z\ace\addons\medical\config.cpp/CfgVehicles/O_Soldier_02_F/HitPoints/HitBody/
Updating base class HitArms->HitHands, by z\ace\addons\medical\config.cpp/CfgVehicles/O_Soldier_02_F/HitPoints/HitHands/
Updating base class HitNeck->, by z\ace\addons\protection\config.cpp/CfgVehicles/CAManBase/HitPoints/HitHead/
Updating base class HitChest->, by z\ace\addons\protection\config.cpp/CfgVehicles/CAManBase/HitPoints/HitBody/
Updating base class HitNeck->HitHead, by z\ace\addons\protection\config.cpp/CfgVehicles/O_officer_F/HitPoints/HitHead/
Updating base class HitChest->HitBody, by z\ace\addons\protection\config.cpp/CfgVehicles/O_officer_F/HitPoints/HitBody/
Updating base class HitArms->HitHands, by z\ace\addons\protection\config.cpp/CfgVehicles/O_officer_F/HitPoints/HitHands/
Updating base class CannonCore->cannon_120mm, by z\ace\addons\realisticnames\config.cpp/CfgWeapons/cannon_105mm/
Updating base class Mode_SemiAuto->player, by z\ace\addons\realisticnames\config.cpp/CfgWeapons/cannon_105mm/player/
Updating base class CannonCore->cannon_120mm, by z\ace\addons\realisticnames\config.cpp/CfgWeapons/cannon_125mm/
Updating base class MainTurret->MainTurret, by z\ace\addons\aircraft\config.cpp/CfgVehicles/Heli_Transport_01_base_F/Turrets/M
```

**Comment by PabstMirror** [comment]
Going to merge the realisticnames changes, looks like we can fix others in different prs

**Pull request merged**
