### PR TITLE
Fixed small UAV carrying allot of cargo.

### PR DESCRIPTION
**Pull request by ColdEvul**
I've fixed small UAV carrying allot of cargo.

The following parameters were active:
```ace_cargo_hasCargo = 1;```
```ace_cargo_space = 8;```

This is due to the fact that the UAV inheritance the class ```Helicopter```

### CODE REVIEW

**Comment by jonpas** [comment]
Can you also check UAVs which inherit from `Plane`, the following:
```
Plane
    UAV
        UAV_02_base_F
            B_UAV_02_F
            I_UAV_02_F
            O_UAV_02_F
            UAV_02_CAS_base_F
                B_UAV_02_CAS_F
                I_UAV_02_CAS_F
                O_UAV_02_CAS_F
```

**Comment by ColdEvul** [comment]
Already did that they check out and are both on
```ace_cargo_hasCargo = 0;```
```ace_cargo_space = 0;```

**Comment by jonpas** [comment]
Awesome :+1: 

Good to merge IMO.

**Comment by commy2** [comment]
Thanks for the contribution!

**Comment by bux578** [comment]
Could you please add yourself to the "Authors.txt". Thanks :)

**Pull request merged**
