### PR TITLE
Fix reload mutex with binocs or mounted

### LINKED ISSUE #4088: Vector 21 rangefinder issue
**Arma 3 Version:** `1.62.137494` (stable)
**CBA Version:** `2.4.1` (stable)
**ACE3 Version:** `3.6.1` (stable)

**Mods:**
- `@CBA_A3`
- `@ace`
- `@aceX`

**Description:**
Vector 21 range finder and azimuth no longer work after apex update. 

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.

**Where did the issue occur?**
- Editor (Singleplayer) 

**Placed Modules:**
- None

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
- If possible at the time the bug is encountered, go to ACE Options and select "Debug To Clipboard", this will print extensive debug information to the RPT file.

https://gist.github.com/Hailstorm12/63d348910b6acae25c2980b11af3cc3c#file-gistfile1-txt

### PR DESCRIPTION
**Pull request by PabstMirror**
Fix #4088

### CODE REVIEW

**Comment by Glowbal** [comment]
This is probably something we want to release with a new patch.

**Comment by commy2** [comment]
not done. I'll be doing further improvements.

What branch should this target?

**Comment by Glowbal** [comment]
Release. But we can cherry pick this over if need be.

**Comment by bux578** [comment]
@commy2 release would make sense

(master and release are in sync as of now!)

**Comment by Glowbal** [comment]
They are not. Master contains a few things such as dog tags.

**Comment by bux578** [comment]
ah yeah, i forget. we don't recreate release ... wrong workflow in my head

**Comment by bux578** [comment]
> (master and release are in sync as of now!)
now, they are

**Comment by commy2** [comment]
ref: https://github.com/acemod/ACE3/pull/4096

**Pull request closed without merging**
