### PR TITLE
Code cleanup Markers

### PR DESCRIPTION
**Pull request by commy2**
- disabled channels are no longer selectable
- the currently selected channel is auto selected
- changing the channel a marker should be set in also changes the current channel

closes: #2914

### CODE REVIEW

**Comment by PabstMirror** [comment]
`x3 = radioChannelCreate [[0.96, 0.34, 0.13, 0.8], "Q-dance Radio", "%UNIT_NAME", [player]];`
Switch to channel with `,`/`.`and try placing marker:
```
Error in expression <el lbText _j];
if ((_channel lbText _j) == _currentChannelName) then {
_channel >
Error position: <== _currentChannelName) then {
_channel >
Error Generic error in expression
File z\ace\addons\markers\functions\fnc_initInsertMarker.sqf, line 153
```
I think `currentChannel` is 6 so out of bounds for `CHANNEL_NAMES`.

Also:
`disableChannels[]={0,1,2,3,4,5,6};` in description.ext and was still able to select group channel on client and group or global for admin.

**Comment by commy2** [comment]
> disableChannels[]={0,1,2,3,4,5,6}; in description.ext and was still able to select group channel on client and group or global for admin.

Yes. You cannot disable the group channel or the global channel in case of the admin.
`disableChannels[]` and even `3 enableChannel false;` does not work. Same happens with the next channel and prev channel keybinds, so I think this is fine.

I'll try to fix the error with custom channels.

**Comment by commy2** [comment]
I must say it's funny how the menu flies off to the right when using the custom channel, haha.

**Comment by commy2** [comment]
>I think currentChannel is 6 so out of bounds for CHANNEL_NAMES.

The default value of a `param` I specifically placed for this reason was a number and not a string. Derp.

**Comment by commy2** [comment]
Now supports custom radio channels as good as possible. Unfortunately there is no way to auto select these channels as there is no command to retrieve the displayed name of a channel and I have to use lbText to identify them in the first place.

**Pull request closed without merging**
