### PR TITLE
NightVision adjustment - use CSE's gamma

### PR DESCRIPTION
**Pull request by PabstMirror**
#1374

Shots taken at -5, 0 and +5 adjustment:
Current:
old
New:
new

### CODE REVIEW

**Comment by jonpas** [comment]
That's pretty nice! :+1:

**Comment by alganthe** [comment]
For 3 lines of code that's a pretty big improvement, this looks much nicer than before.

**Comment by esteldunedain** [comment]
:+1: It's definitely better

**Comment by jaynus** [comment]
Thats super easy to see :/ Was this from a ticket saying our NVG's were too hard to see with at the moment?

**Comment by PabstMirror** [comment]
from issue #1374

From what I understand we where just adding and subtracting a static offset.  
Which doesn't really help increase visibility at all.

CSE's way was to adjust contrast (some place called it gamma)

**Comment by jaynus** [comment]
well IRL increasing/decreasing gamma is supposed to lower the image quality - your processing and mofiying the image and as a result, it looks worse. That's literally the way it is supposed to be and how it is in real life.

The NVG's in arma have always been way too horribly photorealistic.

**Comment by Legolasindar** [comment]
+100

**Comment by jaynus** [comment]
:thumbsup:

**Pull request merged**
