### PR TITLE
Correct typos ("enginer" to "engineer")

### PR DESCRIPTION
**Pull request by Wakbub**
**When merged this pull request will:**
- Correct typos ("enginer" to "engineer").

### CODE REVIEW

**Comment by bux** [comment]
literally unplayable

**Comment by Wakbub** [comment]
Forsooth, literally unplayable for non-engineers in missions which depend on repairing vehicles and use properly spelled Key IDs from the string tables of ACE in its mission parameters, without incredible guesswork what the missing parameter names really represent.

**Comment by jonpas** [comment]
And you have a white GitHub avatar, this is the second time I opened this PR from notifications and wondered what the heck is wrong.

**Comment by commy2** [comment]
Stole my Steam avatar.

**Pull request merged**
