### PR TITLE
Fix CPR params

### PR DESCRIPTION
**Pull request by PabstMirror**
#2491

### CODE REVIEW

**Comment by commy2** [comment]
`param` is a ugly trap for everyone using autocomplete with the scripting commands. Noticed that too.

**Comment by SilentSpike** [comment]
Since this is targeted at master I'd go ahead and merge it, will probably want to hotfix into release too

**Comment by SilentSpike** [comment]
I have no idea what happened, but that works :laughing: :+1:

Was that a cherry pick?

**Comment by PabstMirror** [comment]
just branched off of release, so merge is easy to both branches

**Pull request merged**
