### PR TITLE
Disabled pain effect while unconscious

### PR DESCRIPTION
**Pull request by GitHawk**
Limited _strength of painEffect to 0.1 so a player does not have to watch a flashing screen while he can't do anything about it.
Otherwise we need to include a serious epilepsy warning! See http://en.wikipedia.org/wiki/Photosensitive_epilepsy

### CODE REVIEW

**Comment by Glowbal** [comment]
It might be better to not play any pain effects while unconscious.

**Comment by jonpas** [comment]
> It might be better to not play any pain effects while unconscious.

It does sound way better, you can't see anything anyways... (practically).

**Comment by ulteq** [comment]
> It might be better to not play any pain effects while unconscious.

Yes, please.

**Comment by GitHawk** [comment]
Ok, will change it.

**Comment by GitHawk** [comment]
@Glowbal Now the effect is disabled.

**Comment by ulteq** [comment]
> The code alignment in diffview looks wierd.
You should use 4 spaces instead of tabs.

**Comment by GitHawk** [comment]
> You should use 4 spaces instead of tabs.

I am using spaces but the diffview matches the wrong lines. Old line 167 is now at 174

**Comment by esteldunedain** [comment]
> I am using spaces but the diffview matches the wrong lines. Old line 167 is now at 174

Yeah, don't worry about it. This is just github being weird, and happens often. Unfortunately it makes code much harder to review, but tough luck.

**Comment by Glowbal** [comment]
I will take a look at this today.

**Comment by GitHawk** [comment]
@Glowbal Can you merge, so I can work on other stuff?

**Comment by jonpas** [comment]
@GitHawk that's the point of GitHub, make branches and you can work on infinite stuff without waiting for merges. In fact, you should really make all your pull requests on a separate (non-master) branch, do that for each feature/fix/whatever you are working on and pull request from that.

**Comment by Glowbal** [comment]
Thank you @GitHawk

**Pull request merged**
