### PR TITLE
Virtual explosives place

### PR DESCRIPTION
**Pull request by PabstMirror**
Just like the virtual attach, except now doing per-frame placement scanning so the user can see roughly what it will look like when attached (I should backport that to attach at some point).

https://www.youtube.com/watch?v=np4135sOsso

Should solve
Glitching items into the player moves them over the map #1234
Explosive Attachment failure in MP #1243
Explosives can be activated before even being placed #1777
Placing explosives inside walls is possible #1734

### CODE REVIEW

**Comment by alganthe** [comment]
Did some tests with a buddy on a dedicated:
- This fixes the placement issues (the explosives stick to surfaces and vehicles)
- New issues:
 - Explosives can ragdoll and kill you now (very rare, extremely hard to reproduce) if you try to place them inside vehicles
 - Explosives stay "straight" when attaching them to vehicles, see here -> http://steamcommunity.com/sharedfiles/filedetails/?id=490214873

**Comment by PabstMirror** [comment]
Fixed #2018 (unconc - deadman)

The big physics problem was the satchel, which had a mass of 15.  It could kill a player if it collided with them at all.  Limiting mass to 5 seems to fix, and shouldn't really cause any problems.

**Comment by alganthe** [comment]
:+1:

**Comment by SilentSpike** [comment]
@PabstMirror Is #1991 still an issue in this PR?

**Comment by PabstMirror** [comment]
It is, I will see if I can't fix it in this pr

**Pull request merged**
