### PR TITLE
Categorize Overheating

### PR DESCRIPTION
**Pull request by ulteq**
Should we call the category `ACE - Weapon Overheating`?

### CODE REVIEW

**Comment by PabstMirror** [comment]
Right now the converter will add the `ACE - ` if it doesn't exist.
For final settings I think we'll want it in a single string for simplicity;
so might as well add it now

**Comment by ulteq** [comment]
> Right now the converter will add the ACE - if it doesn't exist.

Yes. But the module is currently called `Overheating`. `ACE - Overheating` is very ambiguous in my opinion.

**Comment by jonpas** [comment]
Wouldn't that generally fit under `ACE - Weapons`?

**Comment by ulteq** [comment]
And what else would you put under `ACE - Weapons`?

**Comment by jonpas** [comment]
Anything to do with a weapon? 😆 
I'd have to check what settings there are, I think we're fine with whatever you do, that can always be tweaked later.

**Comment by ulteq** [comment]
> I think we're fine with whatever you do, that can always be tweaked later.

I'd merge it as is.

**Pull request closed without merging**
