### PR TITLE
ACE_Chemlight_Shield not public

### PR DESCRIPTION
**Pull request by ColdEvul**
**When merged this pull request will:**
Changed `ACE_Chemlight_Shield` to `public` from `protected`

### CODE REVIEW

**Comment by jonpas** [comment]
Tagging @voiperr

**Comment by commy2** [comment]
Same for `ACE_Chemlight_Shield_Green` which all the colored ones inherit from.

**Comment by ColdEvul** [comment]
That I thought was intentional.

**Comment by commy2** [comment]
Why though?

**Comment by ColdEvul** [comment]
Cause I thought the `in use` one was supposed to be protected while the `in used` one was not to be protected.  To avoid people grabbing a ready one from the arsenal (or similar systems).

**Comment by commy2** [comment]
So `ACE_Chemlight_Shield` is basically the empty one? I had to google what a chemlight shield is.

**Comment by ColdEvul** [comment]
Hehe, yes the `ACE_Chemlight_Shield` is the empty one.

**Comment by Glowbal** [comment]
Added to 3.8.2 branch

**Pull request merged**
