### PR TITLE
showMouseHint - Allow adding additional icon/text lines

### PR DESCRIPTION
**Pull request by PabstMirror**
Want this for https://github.com/acemod/ACEX/pull/76

image

Not really thrilled with how the icons look, 
and they might have problems with localization (eg german "STUG")
Might drop them for a wider text bar and just use `localize "str_dik_shift"`

### CODE REVIEW

**Comment by Dystopian** [comment]
vote for simple rectangles with text inside. I think Shift should be the widest, then Ctrl, and Alt is the narrowest.

**Comment by 654wak654** [comment]
Could do what BIS does and add color too.

**Comment by commy2** [comment]
>STUG

Sturmgeschütz?
I think you meant "Strg".

**Comment by commy2** [comment]
```
localize "str_dik_control"
localize "str_dik_shift"
localize "str_dik_alt"
```

**Comment by jonpas** [comment]
I'd personally add some spacing between icon and text as well, even for mouse buttons.

**Comment by PabstMirror** [comment]
image

**Comment by jonpas** [comment]
Could use a key-shape background? Like on the image in OP, just no text on them.

**Comment by PabstMirror** [comment]
It has very limited use for now, I'd rather keep it simple for now
we can make it pretty later if it gets used more

**Pull request merged**
