### PR TITLE
Update spectator doc with new information

### PR DESCRIPTION
**Pull request by SilentSpike**

### CODE REVIEW

**Comment by SilentSpike** [comment]
@bux @alganthe Could use a quick review for typos/phrasing etc. if you've got the chance :smiley:

**Comment by bux578** [comment]
@SilentSpike You're the native speaker here ... :smile:

**Comment by bux578** [comment]
In 1.6: `at ay point` -> `at any point`

**Comment by SilentSpike** [comment]
> You're the native speaker here

All the more reason to make sure non-native speakers can understand it :wink:

**Pull request merged**
