### PR TITLE
Added - Portuguese translation to Attach Failed

### PR DESCRIPTION
**Pull request by VyMajoris**
I would also change the translation of "Attach" to "Anexar" instead of "Acoplar". But either way is works fine.

### CODE REVIEW

**Comment by esteldunedain** [comment]
@VyMajoris: if possible keep adding translations in this branch: 

https://github.com/VyMajoris/ACE3/tree/patch-3

Whatever you modify there will appear on this thread. We'll merge this once you get enough translations in.

**Comment by VyMajoris** [comment]
Roger that.

**Comment by VyMajoris** [comment]
Sorry about me closing this. I wanted to close the #407. 
Should I close #411 and #410 aswell?

**Comment by esteldunedain** [comment]
No, you don't have to close any of the PRs; we'll merge them eventually. Anyway, it would be great if you could create all your following commits on one of the already existing branches. Try going to this branch and edit from there:

https://github.com/VyMajoris/ACE3/tree/patch-3

**Comment by VyMajoris** [comment]
So you want me to re-open #407 too?
Ok I'll do that. The most recent patch on my fork is patch-5, but I'll copy the stuff to patch-3.

**Comment by esteldunedain** [comment]
> Ok I'll do that. The most recent patch on my fork is patch-5, but I'll copy the stuff to patch-3.

Just pick one of the branches and keep working with it. If you already created a PR for that branch the new commits will automatically be added. If not, just create a PR when the branch is ready.

Thank you very much

**Comment by VyMajoris** [comment]
Yeah, It will be patch-3.

**Comment by KoffeinFlummi** [comment]
Is this ready for merging?

**Comment by bux578** [comment]
@VyMajoris 

> please add yourself to the AUTHORS.txt file with a valid email address.

**Comment by VyMajoris** [comment]
Sorry for the absence... I was busy with other stuff. 
No, this is not ready as I need to use the Tabler tool.

**Comment by VyMajoris** [comment]
Alright, that should be everything. But be advised that this fork is not the latest version, thus some keys will be missing. Also I won't be able to work on the translations again for a couple of days. I'll make another fork with a another clean pull request when I am able again.

**Comment by KoffeinFlummi** [comment]
Thanks!

**Pull request merged**
