### PR TITLE
Blur background while interaction menu is open

### PR DESCRIPTION
**Pull request by Glowbal**
Added blur background client setting

### CODE REVIEW

**Comment by esteldunedain** [comment]
:+1:

**Comment by Glowbal** [comment]
That was fast. :p

**Comment by Glowbal** [comment]
https://www.youtube.com/watch?v=cg6ePRLXa9Q youtube video for those who want to quickly view this. 

Note: It may look better in game.

**Comment by esteldunedain** [comment]
Yay, looks fantastic. I still intend to try something else, but options are good anyway. 

btw, I really liked that the implementation is so concise

**Pull request merged**
