### PR TITLE
Fix M84 lods

### LINKED ISSUE #6851: M84 looks gash in advanced throwing
look, it's awful

dedmen and jonpas suggest it might be an LOD issue.

this is less bad

Opening it in Oxygen seems to confirm it - it seems to be using LOD 7:

oh god why

### PR DESCRIPTION
**Pull request by dedmen**
Fixes #6851

### CODE REVIEW

**Comment by bux** [comment]
how does it look now?

**Comment by PabstMirror** [comment]
PR on the left,
I don't think those lod names are right?
image

**Comment by commy2** [comment]
Pabst, you have to delete the distance lods, otherwise the farhest LOD is displayed for grenades, because the game is bugged. This was acknowledged by reyhard on the discord.

Dedmen kept them as Edit LODs, in case they ever fix this, or if this model will get recycled in another game.

**Comment by dedmen** [comment]
>I don't think those lod names are right?

They are

**Comment by dedmen** [comment]
>how does it look now?

arma3_x64_2019-03-09_19-37-26

**Pull request merged**
