### PR TITLE
Dragon model fixed, basic config and script work done

### PR DESCRIPTION
**Pull request by zumorc**
**When merged this pull request will:**
Add the M47 Dragon Anti-Tank Guided Missile

The Dragon Sight Unit or "Tracker" is carried in the Binocular slot, the M222 HEAT round is carried in the launcher slot. To deploy the weapon system the Gunner carries the round and self-interacts to start deployment under equipment. Normal static weapon functionality applies.

M47 Dragon - Fixed Model p3d (memory points)
M47 Dragon - Basic Weapons and Vehicle configs prepared
M47 Dragon - Basic Scripting prepared

Guidance script could use some brushing up.

### CODE REVIEW

**Comment by NouberNou** [comment]
Waiting on more finalization for potential ACEX package for ATGMs before merging from Zumorc's fork.

**Comment by jonpas** [comment]
There are tabs mixed in.

**Comment by sargken** [comment]
ACEX? Its coming back sweet.

**Comment by zumorc** [comment]
Everything I added/changed should be using spaces, I'll make sure there is no more tabs.

**Comment by PabstMirror** [comment]
Worked on in #6773

**Pull request closed without merging**
