### PR TITLE
Fix mouse getting repositioned when opening medical menu

### PR DESCRIPTION
**Pull request by thojkooi**
Change from @mharis001 in PR #6403, done for the rewrite branch

Needs testing.

### CODE REVIEW

**Comment by thojkooi** [comment]
Original issue is still present;

- open menu, observe position of the mouse
- close menu, open again. See position of the mouse changed to some random spot.

**Comment by mharis001** [comment]
I am not sure what is going on. When the menu re-opens automatically after treatment the issue doesn't occur. But when closing and re-opening manually, it does.

**Comment by thojkooi** [comment]
Ok I understand now. Yes I agree, that should be fixed. Need to figure out how to detect the reopen bit. Maybe pass a flag for centralizing the mouse?

**Comment by mharis001** [comment]
That should work, will fix half of the problem at least.

**Pull request closed without merging**
