### PR TITLE
Add CBA 2.3.1 to versioning check

### PR DESCRIPTION
**Pull request by PabstMirror**
Will require https://github.com/CBATeam/CBA_A3/pull/290/

### CODE REVIEW

**Comment by esteldunedain** [comment]
:+1:

**Comment by Glowbal** [comment]
What will this do if someone loads an incorrect CBA version?

Are those minimum versions or does it have to match the exact version?

**Comment by PabstMirror** [comment]
Just the min version, so 2.3.2 or 3.0.0 would be fine.
It just puts a little systemChat warning.
Do we want a stronger warning, like closeDisplay on a ace version mismatch?

**Comment by bux578** [comment]
CheckPBO outputs a nice red box in the center of the screen.

**Comment by jonpas** [comment]
What @bux578 said.

**Comment by PabstMirror** [comment]
Now a hard stop if using an older version of CBA.
If we're counting on new stuff like `cba_missionTime`, there is no point trying to run on old versions of cba.

**Comment by commy2** [comment]
:+1: 
This is brilliant. Old glory of A2 is coming back.

**Comment by Glowbal** [comment]
Perfect, thanks @PabstMirror :+1:

**Pull request merged**
