### PR TITLE
use a function to do gestures

### PR DESCRIPTION
**Pull request by commy2**
**When merged this pull request will:**
- creates `doGesture` so we can apply the reload mutex to every gesture
- removes the `canInteractWith` condition for `!isReloading`

### CODE REVIEW

**Comment by commy2** [comment]
Should fix:
https://github.com/acemod/ACE3/issues/4088
https://github.com/acemod/ACE3/issues/4094

**Comment by esteldunedain** [comment]
How is #4094 related to this?

**Comment by commy2** [comment]
Shortcut for `R` blocks the actions of these. I think that is why he can't check the ammo.

**Comment by esteldunedain** [comment]
> Shortcut for R blocks the actions of these. I think that is why he can't check the ammo.

Nope, those actions are done via the Interaction menu.

**Comment by jonpas** [comment]
@esteldunedain Check ammo is also a keybind. Not sure about link belts.

**Comment by esteldunedain** [comment]
The ticket is about checking the ammo of the AR, not your own. I dont think
we have a keybind for that

**Comment by commy2** [comment]
I striked it off. Was misreading.

**Comment by commy2** [comment]
will fix #4101

**Comment by commy2** [comment]
^
I made a function to read vanilla keybinds

```
actionKeysNamesArray "ReloadMagazine"
["Alt links+R","Shift rechts+R","Strg rechts+R","R++","R","++R","+"]

"ReloadMagazine" call ace_common_fnc_actionKeysNamesConverted
[[19,false,false,true],[19,true,false,false],[19,false,true,false],[27,false,false,false],[19,false,false,false],[19,false,false,false],[27,false,false,false]]
```
(Note that for double keybinds, e.g. "C+R" only the last key is used - those can't be displayed with the keyDown format)

**Comment by commy2** [comment]
^ CheckAmmo and UnjamWeapon use this parameter to not require `!isReloading`
The parameter should only be used for keybinds which overwrite vanilla actions via returning `true`

**Pull request merged**
