### PR TITLE
Force lf line endings for docker entrypoint file

### PR DESCRIPTION
**Pull request by bux**
Docker Container won't start, because the linux image can't execute the entrypoint file with crlf line endings

### CODE REVIEW

**Comment by bux** [comment]
On windows default git setting is `autocrlf = true` by forcing it to be `lf` we can circumvent such settings.

**Comment by jonpas** [comment]
`autocrlf = true` just auto-converts to CRLF when pulling and back to LF when pushing. There should be no way in having CRLF upstream with `* text = auto`.

But I see what you are saying, I'd blame the user though. :P

**Comment by bux** [comment]
It's not about having `lf` upstream, but having ``lf` locally too. Because docker needs it.

**Comment by jonpas** [comment]
Yeah I get it.

**Pull request merged**
