### PR TITLE
Fix lead calculation for vehicle FCS

### PR DESCRIPTION
**Pull request by VKing6**
Fix lead calculation aspect of #2126

### CODE REVIEW

**Comment by jokoho48** [comment]
there is the issue with regex :D

**Comment by commy2** [comment]
Why next milestone? Should be merged right now.

**Comment by VKing6** [comment]
Sure.

**Comment by SilentSpike** [comment]
>there is the issue with regex :D

Nah, this is where regex could have prevented these edge cases :wink:

**Comment by jokoho48** [comment]
yeah i am not so known how regex work but i think we now have 3 or 4 times the time issue :D

**Comment by VKing6** [comment]
https://xkcd.com/208/

**Pull request merged**
