### PR TITLE
Synced weapon heating, deterministic bullet dispersion

### PR DESCRIPTION
**Pull request by esteldunedain**
*WIP*

Continuing the ongoing effort to get bullet trajectories to behave as identical as possible on all clients. 

- Weapon temperatures are synced regularly for clients.
- Bullet dispersion changed from random to pseudo-random, to allow deterministic computing on each client.
- The pseudo-randomness is based on a synced list of random values and uses the remaining ammo count to lookup on that table. The index could be also salted using other deterministic things like the rounded bullet coordinates.

Based on https://github.com/KoffeinFlummi/ACE3/pull/143, hence the commits to common

### CODE REVIEW

**Comment by commy2** [comment]
- [ ] adjust FX (smoke, heat distortion) to actual temperatures
- [ ] adjust Check temperature display to better reflect temperatures (currently 350°C is green!)

**Comment by ulteq** [comment]
- [X] Allow permanent weapon damage

**Comment by Glowbal** [comment]
What is the status on this?

**Comment by ulteq** [comment]
Ready to merge, but esteldunedain still wanted to add something.

**Comment by Glowbal** [comment]
Closing (#3082)

**Pull request closed without merging**
