### PR TITLE
Add manual reload for vehicle weapons

### PR DESCRIPTION
**Pull request by PabstMirror**
Adds ability to reload vehicle weapons (swapping to a fuller magazine)
I'm not sure why this isn't in the base game

Example:
HMG gunner on car, have 10 rounds left;
before you would have to mag dump to do a tactical reload

### CODE REVIEW

**Comment by jonpas** [comment]
> mag dump to do a tactical reload

Very "tactical". 😆

**Comment by jonpas** [comment]
@PabstMirror Is this still up to date?

**Comment by PabstMirror** [comment]
look into how the ` I_C_Offroad_02_LMG_F` can reload

**Comment by Mike-MF** [comment]
Closing due to age and/or inactivity, unlikely to be finished or has to be reworked due to other changes over the years. May be re-opened if someone finds it useful, even better just open a new up-to-date PR.

**Comment by jonpas** [comment]
> look into how the ` I_C_Offroad_02_LMG_F` can reload

Depends what this was about?

**Pull request closed without merging**
