### PR TITLE
Remove particles component

### PR DESCRIPTION
**Pull request by BaerMitUmlaut**
**When merged this pull request will:**
- Remove the particles component for the 3.7 release

Due to a relatively new Arma bug particles will randomly vanish. Because this is more visible with larger particles and since this component is creating larger particles than vanilla, it is likely that this bug will be blamed on ACE or at least is more apparent with ACE.

BI feedback tracker issue:
https://feedback.bistudio.com/T120030

Reference videos (vanilla!):
https://my.mixtape.moe/flftdv.webm
https://my.mixtape.moe/wwdjmp.webm

### CODE REVIEW

**Comment by jonpas** [comment]
Add the issue to [our list](https://github.com/acemod/ACE3/blob/master/docs/wiki/development/arma-3-issues.md).

**Comment by SilentSpike** [comment]
:+1:

**Comment by ElTyranos** [comment]
Does this mean no more smoke grenades overhaul ? :crying_cat_face:

**Comment by jonpas** [comment]
Most likely not for 3.7.0.

**Comment by Glowbal** [comment]
Discussed on Slack: instead of removing, move to optionals for 3.7.0. Add release note in change log.

**Pull request closed without merging**
