### PR TITLE
Interaction - Check `canInteractWith` before taking dropped weapons

### PR DESCRIPTION
**Pull request by PabstMirror**

### CODE REVIEW

**Comment by LinkIsGrim** [comment]
:(

**Comment by johnb432** [comment]
Do we also want to lock the inventory while carrying?
It would mean that we would also need to handle edge cases liking players dying/disconnecting etc.

**Comment by PabstMirror** [comment]
I guess this is desired behavior
but we should still check `canInteractWith` to prevent handcuffed or otherwise locked players from using this
(this checks canInteractWith with objNull as target so it won't check if claimed)

**Review by johnb432 — APPROVED** [review]
LGTM

**Review by LinkIsGrim — APPROVED** [review]

**Pull request merged**
