### PR TITLE
Trivial variable name fix for moduleAssignMedicalVehicle function

### PR DESCRIPTION
**Pull request by SilentSpike**
The rest of the medical vehicle functions are using variable `ace_medical_isMedic` rather than `ace_medical_medicClass` so I changed this one to match.

Probably just an oversight in copy-pasting as the function is very similar to the `moduleAssignMedicRoles` function.

### CODE REVIEW

**Comment by Glowbal** [comment]
Actually they should be the otherway around. All should be `ace_medical_medicClass`. Nice find. Could you please adjust them all to be medicClass?

**Comment by SilentSpike** [comment]
Sure thing

**Comment by SilentSpike** [comment]
Should be all (all instances that my sublime text file search turned up anyway)

**Comment by SilentSpike** [comment]
I actually also noticed that on line 40 of `moduleAssignMedicalVehicle` you have this:

```
    _setting = _logic getvariable ["enabled", false];
```

The value seems to usually be either 1 or 0 (whereas this uses false by default), however I'm not sure if that matters or if the rest of the medical code can accept a boolean in either form.

**Comment by Glowbal** [comment]
That false should be a 0. Again nice find! Thanks.

**Comment by SilentSpike** [comment]
Done

**Comment by Glowbal** [comment]
:+1: Thank you

**Pull request merged**
