### PR TITLE
Fix magazines not listed in arsenal due to case-sensitive check and replace  code with cba functions

### PR DESCRIPTION
**Pull request by brainslush**
**When merged this pull request will:**
- Fix: Magazines on the virtual item list of the ace arsenal which are written in different cases than in the config wouldn't be listed in the arsenal.
- Replaced code with cba functions to streamline code.

### CODE REVIEW

**Comment by brainslush** [comment]
Don't merge. There is more to sort out.

**Comment by dedmen** [comment]
The bug was because we were using configCase instead of everything toLower.
Didn't we at some point move arsenal to using configCase, to not have to toLower everything on every iteration or smth?

**Comment by alganthe** [comment]
That was indeed the case dedmen.

**Comment by brainslush** [comment]
We could do it the other way around and get the configCase names for the items added via addvirtualItems by doing a config lookup. Since addvirtualItems shouldn't be called that often I think the performance impact can be ignored.

**Comment by dedmen** [comment]
> and get the configCase names for the items added via addvirtualItems by doing a config lookup
I thought we were already doing that 🤔

**Comment by brainslush** [comment]
I'll create soon a new PR as I need to tackle the problem from a different angle. I'm closing this PR for now.

**Pull request closed without merging**
