### PR TITLE
Allow explosives to be placed on buildings

### PR DESCRIPTION
**Pull request by tbeswick96**
**When merged this pull request will:**
- Title

### CODE REVIEW

**Comment by PabstMirror** [comment]
I just tried this an the explosive doesn't stick to walls, it's just spawned nearby on the ground.
I don't think `attachTo` works on buildings.

**Comment by tbeswick96** [comment]
I actually only tested with a MGB killhouse spawned in zeus, perhaps it does not work with map buildings

**Comment by PabstMirror** [comment]
It probably works with mission placed objects, but terrain buildings won't work.
Besides, attachTo is needed for vehicles because they move, most buildings have a low max speed.

**Comment by tbeswick96** [comment]
In that case scrap this. I'll keep it on my custom branch for use with a breaching charge on the MGB Kill houses doors, but otherwise it doesn't work.
Shoulda tested it more lol

**Comment by 654wak654** [comment]
Could still place the explosive in the right relative location and freeze it in the air.

**Comment by tbeswick96** [comment]
Yeah I might revisit it and reopen if I get anywhere

**Pull request closed without merging**
