### PR TITLE
disable auto weather - bugging out ACE weather

### PR DESCRIPTION
**Pull request by commy2**
**When merged this pull request will:**
- Disable the auto weather settings
- Which makes sure the weather SQF commands don't bug out

### CODE REVIEW

**Comment by PabstMirror** [comment]
Some of ace_weather can be disabld via settings, so we might want to sill allow vanilla auto-weather.

Could we just keep the `onMissionNew` part, so new missions will default to good settings, but still allow people to re-enable?

**Comment by commy2** [comment]
Yes, we could.

**Comment by jonpas** [comment]
Neat fix! :+1:

**Comment by esteldunedain** [comment]
Should we print a warning and disable ace weather simulation if the commands are bugged?

**Comment by commy2** [comment]
Probably yes. I'm not sure which places are to check.

**Comment by commy2** [comment]
Check would be:
```
if (["Intel" get3DENMissionAttribute "IntelRainIsForced"] param [0, true]) then {
    // warning
};
```
for each of these weather attributes

**Comment by commy2** [comment]
oops, I was wrong. That only works in the editor and the previews.
Apparently it's this verbose monstrum:


`[getMissionConfigValue ["IntelRainIsForced", "intel" get3DENMissionAttribute "IntelRainIsForced"]] param [0, true]`

**Pull request closed without merging**
