### PR TITLE
Send directly to extension instead of splitting it

### PR DESCRIPTION
**Pull request by Glowbal**
Proposed fix for #1158

### CODE REVIEW

**Comment by PabstMirror** [comment]
config export works and the data gets copied to clipboard with perfect formatting, and then the game crashes

only crashes if I include the client settings (~13k output)
nothing in my RPT (usually there would be a crash report and .bidump files)

**Comment by Glowbal** [comment]
That is with this solution? Maybe something else is going on? Does the extension return something?

**Comment by PabstMirror** [comment]
I'm not getting anything returned by the call.
It will sometimes finish the entire config dump (all calls to extension return) and then crash a few seconds later.  

If someone else wants to test this branch, it could be something just with me.

**Comment by PabstMirror** [comment]
@Glowbal - Just tried this again and I can't reproduce the crash at all.  
It may have just been something with my local system at the time.

So I would say this is fine to merge.

**Pull request merged**
