### PR TITLE
Medical GUI - Reformat injury list to clarify global vs. limb-specific information

### PR DESCRIPTION
**Pull request by amsteadrayle**
**When merged this pull request will:**
- Change the layout of the injury list to separate global and limb-specific information
- Add new non-issue text to positively indicate lack of conditions
- Deemphasize non-issues with darkened text color

### IMPORTANT

- [ ] If the contribution affects [the documentation](https://github.com/acemod/ACE3/tree/master/docs), please include your changes in this pull request so the documentation will appear on the [website](https://ace3.acemod.org/).
- [x] [Development Guidelines](https://ace3.acemod.org/wiki/development/) are read, understood and applied.
- [x] Title of this PR uses our standard template `Component - Add|Fix|Improve|Change|Make|Remove {changes}`.

### CODE REVIEW

**Comment by amsteadrayle** [comment]
This will improve the readability of the overview/injury list in multiple ways:

- Visually separating information that applies to the whole body and to the selected body part
- Positively confirming the lack of certain conditions
- Keeping certain information in the same location regardless of the presence or absence of other conditions

image

https://github.com/acemod/ACE3/assets/2516219/ecb2ea87-567f-4726-9fac-24f2b44ac3b8

**Comment by mharis001** [comment]
This is nice UX improvement. 👍

**Comment by LinkIsGrim** [comment]
Should be some indication of which limb the IV is attached to, due to tourniquets. Looks good.

**Review by LinkIsGrim — APPROVED** [review]

**Comment by amsteadrayle** [comment]
> ~Should be some indication of which limb the IV is attached to, due to tourniquets.~ I misremembered how we display IVs in that menu.

That would be nice and not too much work. But yeah, it's a separate thing. I might give it a try now thinking about it.

And I agree with putting bleeding above blood loss. 👍

**Pull request merged**
