### PR TITLE
Spanish strings Updated

### PR DESCRIPTION
**Pull request by arv187**
11 changed files with 139 additions and 1 deletion.
+11 −0 
addons/medical_statemachine/stringtable.xml
+80 −1
addons/medical_treatment/stringtable.xml
+5 −0
addons/microdagr/stringtable.xml
+1 −0
addons/mk6mortar/stringtable.xml
+3 −0
addons/nlaw/stringtable.xml
+2 −0
addons/noradio/stringtable.xml
+13 −0
addons/quickmount/stringtable.xml
+2 −0
addons/realisticnames/stringtable.xml
+15 −0
addons/rearm/stringtable.xml
+5 −0
addons/refuel/stringtable.xml
+2 −0
addons/reload/stringtable.xml

### CODE REVIEW

**Comment by PabstMirror** [comment]
The git diff is still weird on this PR
I cherry picked the main commit here: https://github.com/acemod/ACE3/compare/elFixoCommito?expand=1
(may have dropped some translations that were already present)
if that diff looks ok we can merge that into here

**Comment by arv187** [comment]
> 
> 
> The git diff is still weird on this PR
> I cherry picked the main commit here: https://github.com/acemod/ACE3/compare/elFixoCommito?expand=1
> (may have dropped some translations that were already present)
> if that diff looks ok we can merge that into here

Hi @PabstMirror
 I have to do something?
 In the future, how I can avoid this diff issues?

**Comment by PabstMirror** [comment]
The normal git workflow 
- Update your master to origin/master
- Make a new branch off of master
- commit into that and make a PR for that branch

Your master branch seems to have some weird merge commits, I think this is due to our use of "squash" merging.
To fix your branch you can run
```
git fetch --all
git reset --hard origin/master
```
Warning: this will erase all commits on that branch, so don't do this until after we get this merged!

A simpler way that doesn't invovle the command line would be to just delete your fork and create a new one.

**Comment by PabstMirror** [comment]
this PR was (mostly) merged by #8139
you should now be able to reset your fork (either command line or delete and re-create)

then in the future you can keep your master up to date by hitting the "current branch" dropdown in gitDesktop
and all the way at the bottom is "choose a branch to merge into"
then look for `origin/master`

thanks for your contribution

**Comment by arv187** [comment]
You're welcome, thanks to you.

**Pull request closed without merging**
