### PR TITLE
Trenches - Improve trenches textures

### PR DESCRIPTION
**Pull request by Mysteryjuju**
**When merged this pull request will:**
- Change trenches textures with "dirt texture" like if we just dig the ground
- For winter maps, set snow/dirt texture for trenches

Trenches on Livonia, default at the bottom, PKL textures if loaded above: 

Trenches on Altis, default at the bottom, PKL textures if loaded above: 

Trenches on Chernarus Winter, default texture on the right, snow textures on the left:

### CODE REVIEW

**Comment by Vdauphin** [comment]
Hello,
Don't know if you are aware but you could take a look to this https://github.com/acemod/ACE3/pull/6712

**Comment by Mysteryjuju** [comment]
Hello, 
I know, I follow this PR from month, but it seems abandonned. :(
So, I updated ACE trenches module for my team to include new features and I propose evolutions here for official ACE. It's a different approach to manage trench textures.
And don't worry, I will understand if this PR is refused to prefer the other one, it was proposed first. ;)

**Comment by dedmen** [comment]
https://community.bistudio.com/wiki/surfaceTexture is a thing btw. Made specifically for trenches.

**Comment by jonpas** [comment]
What's the status of this?

**Comment by Mysteryjuju** [comment]
> What's the status of this?

Ready to merge ? ;)
More seriously, like when I posted this PR in august. No comments in the code, but the feature is operational. As I said, I already use it in my community since 6 months. Now, I see two possibilities: 
- the code is so perfect that nobody found a comment to do (but I really doubt of this)
- nobody take care about this, and no one review the code (more probable)

I am mostly waiting feedback about the code if this approach can be added to ACE with this form or if this is not possible.

**Comment by jonpas** [comment]
`surfaceTexture` command is now available, so this feel redundant. If #6712 would get finished, it would be preferable (in case you want to take that on, just leave a comment in the other PR).

**Comment by kymckay** [comment]
Thank you for the work and time spent creating this, with the addition of `surfaceTexture` I believe this is now obsolete with #8935 merged. Only took us 2 years to get something like this in!

**Pull request closed without merging**
