### PR TITLE
Medical - Change - Pain level affects stability

### PR DESCRIPTION
**Pull request by Bummeri**
**When merged this pull request will:**
- Make it so that units are not stable unless their pain level is managed

Stability is a prerequisite for becoming conscious

### CODE REVIEW

**Review by jonpas — CHANGES_REQUESTED** [review]
This does slightly more than you wanted to I bet.

**Comment by Bummeri** [comment]
Yes, its likely.

Here :
https://github.com/acemod/ACE3/blob/8e7f9b6db53a279432a2372c04be311807d1193b/addons/medical_treatment/functions/fnc_fullHealLocal.sqf

Here (setting uncon by script):
https://github.com/acemod/ACE3/blob/8e7f9b6db53a279432a2372c04be311807d1193b/addons/medical/functions/fnc_setUnconscious.sqf

Here (PAK treatment):
https://github.com/acemod/ACE3/blob/171fbf1e9ec3ee593ee0fc9e5c04b1270db4d01f/addons/medical_treatment/ACE_Medical_Treatment_Actions.hpp

**Comment by Bummeri** [comment]
I think FullHealLocal is not an issue since pain is set to 0 in it.

https://github.com/acemod/ACE3/blob/8e7f9b6db53a279432a2372c04be311807d1193b/addons/medical_treatment/functions/fnc_fullHealLocal.sqf#L35

**Comment by Bummeri** [comment]
https://github.com/acemod/ACE3/blob/8e7f9b6db53a279432a2372c04be311807d1193b/addons/medical_vitals/functions/fnc_updatePainSuppress.sqf

And pain supression should be considered in some way...

**Comment by jonpas** [comment]
No, I meant you included commits from another PR. :P

**Comment by Bummeri** [comment]
> No, I meant you included commits from another PR. :P

ahh, ok. I dont know how I did that. Can I remove them?

**Comment by jonpas** [comment]
You can rebase your latest commit on master. Ask around on Slack.

**Pull request closed without merging**
