### PR TITLE
README: Shields back up

### PR DESCRIPTION
**Pull request by Tourorist**
Also, changed the download  link from source code to the official compiled version.

### CODE REVIEW

**Comment by Tourorist** [comment]
BTW, which of the two BIF links is correct:
* [Original post by NouberNou](http://forums.bistudio.com/showthread.php?190433-ACE3-A-collaborative-merger-between-AGM-CSE-and-ACE&p=2910796&viewfull=1#post2910796), or
* [The one authored from ACEMod account](http://forums.bistudio.com/showthread.php?191716-ACE3-A-collaborative-merger-between-AGM-CSE-and-ACE&p=2935435&viewfull=1#post2935435)?

**Comment by Tourorist** [comment]
Don't push it yet, seems the shields are still off. I'll ask the authors for help.

**Comment by PabstMirror** [comment]
The 2nd one is the current one, the first was the pre-release announcement and is now closed.

**Comment by Tourorist** [comment]
@PabstMirror, thanks, I'll use that from now on.

@bux578 was correct in his assesment, shields is currently experiencing technical problems ([shields/issues/445](https://github.com/badges/shields/issues/445)). I'll follow this issue and let you know when it's resolved.

**Comment by Tourorist** [comment]
@bux578, you tricked me, or to be more precise my eyes are playing tricks on me. Somehow I didn't notice those text links that you manually added as placeholders and assumed it the actually shields that was doing some kind of rendering fallback.

The problem still persists though, where right now the Issues badge fails to load from time to time.

**Comment by Tourorist** [comment]
Has been stable now for almost a week, even prio to the [server switch](/badges/shields/issues/459).

@PabstMirror, push it maybe?

**Comment by bux578** [comment]
I like the title of the PR. :+1:

**Comment by Tourorist** [comment]
@PabstMirror, do you want me here to modify something?

**Comment by PabstMirror** [comment]
Sorry for the delay, this looks good.

**Pull request merged**
