### PR TITLE
Fix typo in ACE_hearing config

### LINKED ISSUE #3194: ace_hearing-CfgWeapons has _0 instead of _O
In https://github.com/acemod/ACE3/blob/master/addons/hearing/CfgWeapons.hpp in line 21 there's an error:
class H_HelmetCrew_0: H_HelmetCrew_B {};
Should be
class H_HelmetCrew_O: H_HelmetCrew_B {};

### PR DESCRIPTION
**Pull request by esteldunedain**
Fix #3194

### CODE REVIEW

**Comment by bux578** [comment]
:+1:

**Comment by PabstMirror** [comment]
```
    class H_HelmetCrew_O: H_HelmetCrew_B {};
    class H_HelmetCrew_I: H_HelmetCrew_B {};
```
These lines do nothing anyways, and could just be removed

**Comment by esteldunedain** [comment]
I'll do

**Comment by PabstMirror** [comment]
opps

**Comment by esteldunedain** [comment]
np

**Pull request merged**
