### PR TITLE
Interaction coding guidelines

### PR DESCRIPTION
**Pull request by jonpas**
Because I was too lazy to do something more productive and because function headers are nice.

I don't know what all the functions do exactly so I did my best, let me know if anything looks wrong (or what the questions marks are).

I was also thinking of going through it again and changing argument variable definitions to CBA macros (`EXPLODE_N_PVT` or `PARAMS_N`), but I don't know if that's supposed to be used everywhere or whatever, also not sure which I should use of the two (or something entirely else?).

### CODE REVIEW

**Comment by PabstMirror** [comment]
Nice job, some things in interaction are deprecated and needs cleaning, but it's nice to have good headers on everything.

EXPLODE_N_PVT(_this,xxx) PARAMS_N(xxx) both do the same thing. They add private defines and more importantly they help with debuging (you can quickly add #define DEBUG_MODE_FULL and see param's in rpt).  I like PARAMS_N but some people seem to prefer the :bomb:

**Comment by jonpas** [comment]
What is the reason there are both though? I see `EXPLODE_N_PVT` has the first parameter of `_this` in most cases, I don't see why exactly.

**Comment by esteldunedain** [comment]
`PARAMS_N(xxx) = EXPLODE_N_PVT(_this,xxx)`

**Comment by jaynus** [comment]
Explode can be applied to any array. Like PFH arts are _this select 0 so PARAMS doesn't apply

**Comment by esteldunedain** [comment]
Check this out: https://github.com/acemod/ACE3/blob/master/addons/interact_menu/functions/fnc_renderMenu.sqf#L20-L22

**Comment by jonpas** [comment]
Ahh, I see, you can basically "explode" any array. PARAMS only takes the passed array into function (the argument) while with EXPLODE you can practically do it mid-script as well.

I'll do that for interaction and probably other modules as well in a separate branch. If changes in this branch look good to you I think it's ready to merge (except that question marks, because I have no idea what logic modules pass, just like bux didn't).

**Comment by esteldunedain** [comment]
> The whole list interaction menu for explosives as it was in AGM is not used anymore either

Yeah, I think that can be deleted.

> I'll do that for interaction and probably other modules as well in a separate branch. 

If you want it's probably easier to do it in this branch

**Comment by jonpas** [comment]
> If you want it's probably easier to do it in this branch

Will do it here then.

**Comment by PabstMirror** [comment]
frisk still uses it I belive

**Comment by jonpas** [comment]
I did a search on GitHub for many of the functions and they didn't turn up anything but `PREP(funcName)`, so I guess those are the ones not used? Is there any other word I should search for next to the function name?

**Comment by esteldunedain** [comment]
I think there's an issue to remove Frisk altogether, as we have Check inventory now.

**Comment by bux578** [comment]
> I think there's an issue to remove Frisk altogether, as we have Check inventory now.

#1018

**Comment by jonpas** [comment]
So the entire Frisk module should be deleted? Or is the Open Inventory inside Captives module (where Frisk is as well)?

**Comment by jonpas** [comment]
CBA PARAM/EXPLODE Macros implemented where possible, Tabs converted to Spaces. Privates added. Unused variables and class removed

Still needs testing, but if it looks good to all of you I guess it's fine. Build went fine.

**Comment by jonpas** [comment]
Tested, all looks good from my side, ready for merge.

**Pull request merged**
