### PR TITLE
Cargoload

### PR DESCRIPTION
**Pull request by MarcBook**
PLEASE CLOSE

LOOK AT THIS:
https://github.com/MarcBook/ACE3/tree/loadInCargo/addons/cargo

[ ] add Loadpoints
[ ] Test MP
[ ] remove TABS
[ ] add comments
[ ] remove some commits

### CODE REVIEW

**Comment by esteldunedain** [comment]
https://github.com/MarcBook/ACE3/tree/loadInCargo/addons/cargo

Is that the logistics system from AGM ported? The idea was to completely rewritte that. 

@commy2 should take a look if it's worth basing the rewritte on this code or not.

**Comment by MarcBook** [comment]
I ported it from AGM, but I think I'll nearly rewrite it complete.

**Comment by esteldunedain** [comment]
Can you make a separate PR for that branch (called  `loadInCargo`). This PR is for another branch (`cargoLoad`), which contains the backpack stuff instead

**Comment by MarcBook** [comment]
Maybe something like this.

@esteldunedain Sry, but I don't know how to do this. :(

**Comment by esteldunedain** [comment]
Ok @MarcBook, I'll try to do it myself. I'll close this issue now.

**Comment by MarcBook** [comment]
Ok, making a "good" PR?

**Pull request closed without merging**
