### PR TITLE
Store Interact Menus on CBA Namespaces

### PR DESCRIPTION
**Pull request by commy2**
**When merged this pull request will:**
- Store action menues in CBA pseudo namespaces instead of `format`ed mission namespace variables
- I can't reproduce the save game crash with this anymore
- I don't know why though, so don't close the issue for now (requires feedback)

ref #3397, #1098

### CODE REVIEW

**Comment by PabstMirror** [comment]
Should we do the zeus actions as well?

**Comment by commy2** [comment]
Zeus actions? Probably yes.

**Comment by commy2** [comment]
>Should we do the zeus actions as well?
I don't think that's necessary as that one is one level less deep. There only is one zeus actions mission namespace array, while there was one for each unit type.

**Comment by esteldunedain** [comment]
:+1: for merging this @commy2. I checked to see if you might have missed replacing it somewhere, but I couldn't find anything wrong.

**Comment by commy2** [comment]
Yay. Let's see if that fixes the save game problem. Can't wait for testing results from the mob.

**Comment by esteldunedain** [comment]
>  Can't wait for testing results from the mob.

Lol @bux578,** calling our user-base "the mob" could trigger a great PR mess.

**Comment by JoeSchr** [comment]
I tried it with Campaign Mission: `The East Wind -> Win -> Resurgent West`.


I saved ~2min in, exited and couldn't load or resume the misson after. 

When disabling ACE3, restarting the mission, saving, loading it works. 

If I try to load a "naked" save game with ACE3 activated, I get 
`The instruction at 0xetc referenced memory at 0x000000. The memory could not be read`

Sadly it seems, save games are **not working**. Or do I need to disable/enable anything? 
Tested with ACE 3.5.1

**Comment by commy2** [comment]
Has nothing to do with this. Please open a new issue. Keep in mind that the campaign is not supported.

**Pull request merged**
