### PR TITLE
Standardize logging format through ACE_LOG macros

### PR DESCRIPTION
**Pull request by MikeMatrix**
This covers most of the uses of `diag_log` to output logs manually.

This PR relies on #2052.

EDIT: #2052 has been merged.

### CODE REVIEW

**Comment by jokoho48** [comment]
you cant use a format ["%1", _var] with out a ARR_N in MACROS

**Comment by MikeMatrix** [comment]
Just realized that myself >_<

**Comment by MikeMatrix** [comment]
Alright, should be good now.

**Comment by jokoho48** [comment]
this PR have merge conflicts

**Comment by MikeMatrix** [comment]
@jokoho48 should be mergable now

**Comment by Glowbal** [comment]
I understood we were replacing this in favor of a new CBA logging system?

**Comment by MikeMatrix** [comment]
Yes. Doesn't mean we can't merge this and standardize it beforehand, since this is already written. 
The logging system is probably gonna take at least until the next version of CBA comes out.
We'll also be able to just use the CBA functionality in our macros themselves if we want to.
Either way, merging this should do no harm, since it's already done.

**Comment by Glowbal** [comment]
#2429

**Pull request closed without merging**
